### PR TITLE
LPS-136536 Add className and style to Numeric inputMask when the language is Arabic

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-136536

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@danvb112, besides request Milton's review, can you please also assign the pull to him? More details how to do it, please visit https://liferay.atlassian.net/wiki/spaces/ENGFORMS/pages/1579288217/Developers+allocation+and+code+review+process#Code-review.

This is important because the `liferay-forms` user receives many pulls and setting an assignee to the pulls make easier for reviewers filter the pulls assigned to them. :wink: 

Thanks in advance

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Review by miltonmc — APPROVED** [review]
Good job!

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@danvb112, to solve the reported failure, please see this [comment](https://github.com/liferay-forms/liferay-portal/pull/790#issuecomment-896814646).

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by danvb112** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
