### PR TITLE
LPS-143760

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related ticket:
https://issues.liferay.com/browse/LPS-143760

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:reevaluate:1367401_133

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @rodrigopaulino, can you please check if these failures are related to your changes? Thanks

**Comment by rodrigopaulino** [comment]
ci:forward

**Pull request closed without merging**
