### PR TITLE
LPS-168955: Allow ddmStructure Key update

### PR DESCRIPTION
**Pull request by kristofloneck**
Related issue: https://issues.liferay.com/browse/LPS-168955

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
Just started reviewing :)

**Comment by marcelabc** [comment]
Hi @kristofloneck, how are you doing?
Thank you for collaborating! :tada: 
I made a minor change in your PR, resending: https://github.com/liferay-forms/liferay-portal/pull/2086
Let me know if you have questions :+1:

**Comment by kristofloneck** [comment]
Okey thank you

**Pull request closed without merging**
