### PR TITLE
LPS-178864 Fix Multiple selection value with _getValue method

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi Team,

could you pleae review this fix?

The case:
In Custom Facet the ddm aggregation filed value shows the field references instead of the labels in case of Multiple Selection structure.

The fix:
Handle the ddmFormFieldOptions in a separate _getValue method.

https://issues.liferay.com/browse/LPS-178864
https://issues.liferay.com/browse/PTR-3803

cc @carolmariaabb

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:forms

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
