### PR TITLE
LPS-191691

### PR DESCRIPTION
**Pull request by jonathanmccann**
Resending this based on the changes requested here - https://github.com/brianchandotcom/liferay-portal/pull/138904#issuecomment-1668265903

Previous pull request - https://github.com/liferay-forms/liferay-portal/pull/2290

### CODE REVIEW

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
