### PR TITLE
LPS-131824 Fix alert message container sizing

### PR DESCRIPTION
**Pull request by miltonmc**
**Ticket**: [LPS-131824](https://issues.liferay.com/browse/LPS-131824)
#### Before
Screenshot from 2021-05-14 10-19-24
#### After
Screenshot from 2021-05-14 10-20-51

#### Before
Screenshot from 2021-05-14 10-04-53
#### After
Screenshot from 2021-05-14 09-59-06

### Notes
Since I was not able to identify any CSS class naming pattern for the Form's code, I thought would be good to starting adopt the [BEM — Block Element Modifier methodology](http://getbem.com/introduction/) to the project.

E.g.: `block-name__element-name--modifier-name`

Note that `alert-container` can be implemented by any module, causing class name collision and enforcing the use of class nesting  to avoid that (it makes the class precedence harder to understand, leading developer to errors manipulating the CSS). In other hand, by using  the prefix `ddm-form-web__` we can consistently identify the module this class belongs, drastically reducing the chance of a class collision and the need of nesting classes. If a collision happen will be an  internal module's issue with no impact to the other modules.

A proper naming would be `ddm-form-web__alert-container--collapsed`. Where:
- `ddm-form-web` is the block (or module)
- `alert-container` is the element
- `collapsed` is the modifier (state of the element)

This methodology is already been used in the [Commerce's CSS](https://github.com/liferay-forms/liferay-portal/blob/2b3674ff72353a861931a2597469ef6d93c8ff9e/modules/apps/commerce/commerce-theme-minium/commerce-theme-minium/src/css/_custom.scss#L19-L99).

### CODE REVIEW

**Comment by miltonmc** [comment]
ci:test:sf

**Review by interaminense — APPROVED** [review]
LGTM!

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:forward

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:forward

**Pull request closed without merging**
