### PR TITLE
LPS-176243 dynamic-data-lists-uad: adds marker file

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

I'm adding the marker file to the now module so it will be included in the builds.

Thank you and best regards,
István

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:reevaluate:1397401_3314

**Comment by marcelabc** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
