### PR TITLE
LPS-194017 Also search for nested fields when propagating fieldSet changes

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://liferay.atlassian.net/browse/LPS-194017

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
just started reviewing :cherry_blossom:

**Review by rebsilva — APPROVED** [review]
LGTM! :tada: great work @carolmariaabb! :cherry_blossom:

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:data-engine

**Comment by carolmariaabb** [comment]
ci:test:data-engine

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
