### PR TITLE
LPS-146262 Fix settingsContext tests

### PR DESCRIPTION
**Pull request by miltonmc**
Related Issue: https://issues.liferay.com/browse/LPS-146262

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @miltonmc, can you please check if these failures are related to your changes? Thanks

**Comment by miltonmc** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @miltonmc, can you please check if these failures are related to your changes? Thanks

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @miltonmc, can you please check if these failures are related to your changes? Thanks

**Comment by pyoo47** [comment]
ci:test:relevant:8328d769f081fe7b11a2a16956b9601e4260840a

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:forward

**Pull request closed without merging**
