### PR TITLE
LPS-148748 Decimal value is being round when viewing Form entry with more than 20 decimal places

### PR DESCRIPTION
**Pull request by quanhuynhces**
Hi @liferay-forms team!
This PR is for fixing the [LPS-148748](https://issues.liferay.com/browse/LPS-148748)
I've found out that the problem may come from this [line of code](https://github.com/liferay/liferay-portal/blob/93720ccdbebdeb15eaa62d4d0241ab6909147ede/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/internal/util/DDMFormValuesMergerImpl.java#L156). When you call getDouble() method, it will go to NumberFormat, and parse the value. Then the value will be rounded if the decimal places is long (more than 16 places) by the Java library standard. So that why the issue occur.
So I think that we no need to format the number because in 7.4 form, I see that we can not change the language of submitted form.
Please review and hope to get your comment.
Thanks,
Quan

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Review by carolmariaabb — CHANGES_REQUESTED** [review]
Hi @quanhuynhces,

Can you check if it is possible to reproduce the issue described in [LPS-87353](https://issues.liferay.com/browse/LPS-87353)? 
This ticket was responsible for adding the code you removed in this PR ([commit](https://github.com/liferay/liferay-portal/commit/6a2fa6bf38f4bead6abcd10d3ddae7cba8a62f5c)).

Thanks!

**Comment by quanhuynhces** [comment]
Hi @carolmariaabb,
I've checked that and it is NOT possible to reproduce the issue described in [LPS-87353](https://issues.liferay.com/browse/LPS-87353)
Please feel free to tell me if you have any concern.
Cheers!

**Pull request closed without merging**
