### PR TITLE
LPS-194047 - fix testDDLDisplayPortletPreferences test case to work with recordSetKey instead of recordSetId

### PR DESCRIPTION
**Pull request by DaniSzimko**
[LPS-194047](https://liferay.atlassian.net/browse/LPS-194047)

Regression : [LPS-167450](https://liferay.atlassian.net/browse/LPS-167450l)

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:sf

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
