### PR TITLE
LPS-145204-master

### PR DESCRIPTION
**Pull request by manuelRives**
Related Issue: https://issues.liferay.com/browse/LPS-145204

Related Issue: https://issues.liferay.com/browse/LPS-145204

When you try to apply a field filter to an Asset Publisher, if the page is on a language different from the default locale the validation fails.

Hey @natocesarrego @carolmariaabb @liferay-forms

This pull is the rebase of the pull https://github.com/liferay-forms/liferay-portal/pull/1375.

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @manuelRives, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @manuelRives, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
Last try, @manuelRives. If it doesn't succeed, please feel free to close this pull and send it directly to Brian. :slightly_smiling_face: 

Thanks

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
