### PR TITLE
Forms Automated Test - LPS-134390 | master

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by DiegoDOC** [comment]
Hey @JoMaAlves your PR looks good to go.

Keep up the good work!

**Comment by DiegoDOC** [comment]
ci:forward

**Comment by DiegoDOC** [comment]
Hey @JoMaAlves, it seems you forgot to run the source format command before sending the PR, could you fix that and re-send it?

Thanks in advance!

**Comment by JoMaAlves** [comment]
@DiegoDOC Fixed!

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
@JoMaAlves, can you please rebase your code against to the latest branch master of Brian Chan's repo to solve the reported conflicts?

@DiegoDOC, is there anything else pending on this pull regarding you review?

Thanks.

**Comment by JoMaAlves** [comment]
@natocesarrego Done!

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by DiegoDOC** [comment]
ci:forward

**Pull request closed without merging**
