### PR TITLE
LPS-140212 Error message does not show when auth error occurs in Search Location field

### PR DESCRIPTION
**Pull request by DiegoDOC**
Related Issue: https://issues.liferay.com/browse/LPS-140212

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @DiegoDOC, can you please check if these failures are related to your changes? Thanks

**Comment by DiegoDOC** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @DiegoDOC, can you please check if these failures are related to your changes? Thanks

**Comment by DiegoDOC** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @DiegoDOC, can you please check if these failures are related to your changes? Thanks

**Comment by pyoo47** [comment]
ci:test:relevant

**Pull request closed without merging**
