### PR TITLE
LPS-169630 include validations before dataDefinition deletion

### PR DESCRIPTION
**Pull request by devpedrotavares**
[LPS-169630](https://issues.liferay.com/browse/LPS-169630)
The bug is happening because the dataLayout of the dataDefinition is being deleted before the verification for template references is done. As this verification was only being done in the "deleteStructure" method of DDMStructureLocalService. 
So I moved the validations up from this method to the DataDefinitionResource "deleteDataDefinition" method that calls it.

### CODE REVIEW

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:reevaluate:1367401_2531

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Pull request closed without merging**
