### PR TITLE
LPS-144718

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related ticket: https://issues.liferay.com/browse/LPS-144718

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Review by carolmariaabb — APPROVED** [review]
@rodrigopaulino amazing job refactoring the test

**Comment by carolmariaabb** [comment]
ci:reevaluate:1327401_1909

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
I believe it got stuck because of merge conflicts.

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
ci:forward

**Pull request closed without merging**
