### PR TITLE
[TECHNICAL SUPPORT] LPS-116665 Regen snapshots

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related Issue: https://issues.liferay.com/browse/LPS-116665

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hey @rodrigopaulino, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Clearly, the commit 03c0297 message should start with "Unrelates". Missed a character there. Let me know if you want me to resend it.

Thanks.

**Comment by liferay-forms** [comment]
Hey @rodrigopaulino, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
@rodrigopaulino, can you please update the commit message you're mentioned?

Thanks.

**Comment by natocesarrego** [comment]
@antonio-ortega, do you have any concern about this pull?

You and @rodrigopaulino worked simultaneously to address Forms' Accessibility issues and I'd like to make sure you guys are on the same page about these changes and avoid reword from each side.

Thanks.

**Comment by antonio-ortega** [comment]
Hi guys,

I haven't tested but at a first glance it looks good to me, because I can see we solved twice the same issue in the past to meet WCAG's 3.3.2 success criterion.

Thanks.

Regards.

**Comment by rodrigopaulino** [comment]
If you guys need more context on why I chose to remove these changes, you can check my latest comment back in the LPS where I linked the PTR that documents the Product Team's decision on which approach to take when dealing with these accessibility issues. If you need more info from my end, I'll be happy to help.

Thanks, guys.

**Comment by natocesarrego** [comment]
Thank you very much,@antonio-ortega and @rodrigopaulino ! 😄 I'll move on with this pull.

**Comment by natocesarrego** [comment]
ci:forward

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @rodrigopaulino, can you please check if these failures are related to your changes? Thanks

**Pull request closed without merging**
