### PR TITLE
LPS-151773 Create toggle with tooltip component

### PR DESCRIPTION
**Pull request by miltonmc**
Related: https://issues.liferay.com/browse/LPS-151773

### CODE REVIEW

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:reevaluate:1387401_1470

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:reevaluate:1357401_1787

**Comment by miltonmc** [comment]
ci:forward

**Pull request closed without merging**
