### PR TITLE
LPS-152504

### PR DESCRIPTION
**Pull request by alinedoleron**
Related issue: https://issues.liferay.com/browse/LPS-152504

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @alinedoleron, can you please check if these failures are related to your changes? Thanks

**Comment by alinedoleron** [comment]
ci:stop

**Comment by liferay-forms** [comment]
Hey @alinedoleron, can you please check if these failures are related to your changes? Thanks

**Comment by alinedoleron** [comment]
ci:forward

**Pull request closed without merging**
