### PR TITLE
LPD-34375 WIP

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey Team,

I implemented the missing functionality of `Undo/Redo `for the `repeatable fields` the same way you described it in the [Spike](https://liferay.atlassian.net/browse/LPD-34562), but in the end I discovered 2 major issues that blocks the whole story.

1. The `HistoryReducer` is called twice when receiving the `journal:storeState` event from `input_localized.js` For example when we edit the title. The event is fired once from `input_localized.js`, it received once in `Layout.es.js`  and it is dispatched one time from there. Still the Action is received two times in the `HistoryReducer` creating a duplicate step.

2. The second issue is with the repeatable fields. Once a field is repeated, The `Layout` is rerendered as many times as many fields we have in the `Layout`. This in return creates multiple `Layout`s what creates multiple event handlers that ends up creating multiple steps in the `HistoryReducer`. Essentially creating so many steps that the functionality seems to not work at all with the repeatable fields. But in reality it works, just we have too many steps in the state to make it work.

I created this PR with the tmp commit so we can start collaborating on these issues more easily. It implements the step creating for repeating, removing and moving a repeatable field. It changes how we reset the History so it does not cause issues when the Layout is rerenderd. It also provides console.log statements to every relevant part of the codeBase where the code of Undo/Redo story runs, so we can all see what is happening in what order and the two issues described above is easier to see.

Reproduction steps to follow:

1. Go to Web content => structures => Create a structure with a repeatable text field and a non repeatable text field
2. Create a web content from this structure
3. Add a title
(Notice the first issue, HistoryReducer's `ADD` action runs twice)
5. Add text for the repeated field
6. Add text for the non repeated field
7. Click the history button and select 'Undo-all'
(Notice that the fields are reseted correctly as stepping back to the first History step works well in every case. Restoring the state works for repeatable fields as well)
8. Repeat the repeated field
(Notice the `'Layout is rendered and events are registered'` console log appears 3 times)
9. Add a text to the newly repeated field and click outside of it

Expected: `dispatching storeState from layout` appears one time in the console and we dispatch the storeState event one time
Actual: It appears multiple times and the Action is dispatched multiple times

After a field is repeated all the fields produce the same behaviour, meaning we don't have to edit one of the repeated fields to have multiple Action dispatched from the Layout

These issues are blockers for our story and we would appreciate the help as this seem to be a bug in data-engine.

Thank you in advance!

### CODE REVIEW

**Comment by rebsilva** [comment]
i will start to take a look at this tomorrow, thanks!

**Comment by rebsilva** [comment]
hello @NemethNorbert, the bpm team will schedule a meeting to discuss about this task/epic so we can have a better context about what is being developed and the criteria behind it, so we can help you out the best way we can.

for the time being the PR review/help will be on hold, thanks for your understanding!

**Comment by NemethNorbert** [comment]
> hello @NemethNorbert, the bpm team will schedule a meeting to discuss about this task/epic so we can have a better context about what is being developed and the criteria behind it, so we can help you out the best way we can.
> 
> for the time being the PR review/help will be on hold, thanks for your understanding!

Sure thing, could you also look into the issue of multiple Layout creation when repeating a field for that meeting?
Thanks

**Comment by rebsilva** [comment]
sure @NemethNorbert, we will talk about both of them there, thanks!

**Pull request closed without merging**
