### PR TITLE
LPS-182981 Single selection and Multiple selection interferes with one another

### PR DESCRIPTION
**Pull request by icgsbr**
## LPS Associated
[LPS-182981](https://issues.liferay.com/browse/LPS-182981)

### CODE REVIEW

**Review by rebsilva — APPROVED** [review]
LGTM! :tada: :cherry_blossom:

**Comment by rebsilva** [comment]
the tests doesn't seem related, but i will try again since the stable didn't pass as well.

**Comment by rebsilva** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
@icgsbr The reported failures seem to be related to your changes. It looks like some FE unit tests from Workflow are failing. Could you please ask some FE developer for help to fix it? Thanks!

**Comment by icgsbr** [comment]
> @icgsbr The reported failures seem to be related to your changes. It looks like some FE unit tests from Workflow are failing. Could you please ask some FE developer for help to fix it? Thanks!

Hi @carolmariaabb! I'll take a look on that. Thanks!

**Comment by rebsilva** [comment]
Thank you so much for seeing that @carolmariaabb! :pray: I didn't realize that they were related, you are a lifesaver :cherry_blossom:

**Comment by icgsbr** [comment]
ci:test:relevant

**Comment by icgsbr** [comment]
ci:stop

**Comment by icgsbr** [comment]
ci:test:sf

**Comment by icgsbr** [comment]
ci:test:relevant

**Comment by icgsbr** [comment]
ci:test:forms

**Review by rebsilva — APPROVED** [review]
Since the it's the same code only rebased, it still LGTM :cherry_blossom:

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
