### PR TITLE
LPS-133385 update leaflet to 1.7.1

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
LPS-133385 Upgrade leaflet library from 1.2.0 to the latest version 1.7.1 because there are major fixes related to accessibility that our client needs, please check link https://github.com/Leaflet/Leaflet/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility

While testing, I discover https://issues.liferay.com/browse/LPS-133544 is happening with the actual version leaflet 1.2.0 on master only

Not sure if this is for Forms team or should go to Data Engine or Echo

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
@liferay-echo Not sure if this is a @liferay-forms or is this PR related to any of your component?

Regards.

**Comment by natocesarrego** [comment]
Hey @georgel-pop-lr,

You did correctly to send this pull to Forms Team. :slightly_smiling_face: After all, the Form Fields code is inside Forms Team modules. Even though, I think that it's important to let @liferay-echo and @liferay-data-engine know about this change.

Echo Team and Data Engine Team, would you like to trigger any test suite before we move on with this pull?

Thanks.

**Comment by rodrigopaulino** [comment]
Hi, @natocesarrego. Thanks for reaching out.

Currently, Data Engine doesn't have automated tests that use this package or something related to it. It's good to go from our end.

Kind regards.

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
