### PR TITLE
LPS-189715

### PR DESCRIPTION
**Pull request by alinedoleron**
Ticket: https://liferay.atlassian.net/browse/LPS-189715

### CODE REVIEW

**Comment by alinedoleron** [comment]
Hi @marcelabc , I know this is a Front end fix, but I'm not confident on sending it without your look. The case is: 
if initially the default language is **English**, and then I change it to **Spanish**, the localizableValue is: 
`{'en_US': '' , ' es_Es': ' '}`. So when I was setting a value to Spanish, and then back to English, it was checking only if the `localizableValue[en_US]` was _null_ or _undefined_, so it would never change the content, because it is an empty string. So I included this check into the conditional. Do you know if this change can negatively impact something ?

**Comment by alinedoleron** [comment]
Current behavior:

[Untitled_ Sep 18, 2023 3_15 PM.webm](https://github.com/liferay-forms/liferay-portal/assets/26491796/235f0087-9d1a-40ad-b903-ab9540dd0d1e)

**Comment by georgel-pop-lr** [comment]
> Hi @marcelabc , I know this is a Front end fix, but I'm not confident in sending it without your look. The case is: if initially the default language is **English**, and then I change it to **Spanish**, the localizableValue is: `{'en_US': '' , ' es_Es': ' '}`. So when I was setting a value to Spanish, and then back to English, it was checking only if the `localizableValue[en_US]` was _null_ or _undefined_, so it would never change the content, because it is an empty string. So I included this check into the conditional. Do you know if this change can negatively impact something ?

Hi all,

I need to make one remark regarding this fix, I haven't tested but is important that after this change the client still can add an empty translation if he wants to in any other language, but this shouldn't happen automatically if he changes the default language.

Regards.

**Comment by alinedoleron** [comment]
Hi @georgel-pop-lr! Thank you so much for mentioning this point. I need to handle this case.

**Comment by alinedoleron** [comment]
Hi guys, I've made some changes. Please, check the video below.
 
[Untitled_ Sep 19 2023 10_56 AM.webm](https://github.com/liferay-forms/liferay-portal/assets/26491796/79f8285e-cf63-4f26-8a97-8ded2e798e1a)

**Comment by georgel-pop-lr** [comment]
> Hi guys, I've made some changes. Please, check the video below.
> 
>  Untitled_.Sep.19.2023.10_56.AM.webm

Looks good to me.

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:reevaluate:1397401_7414

**Comment by marcelabc** [comment]
Just started reviewing :)

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:forward:force

**Pull request closed without merging**
