### PR TITLE
LPS-174943 Check if tab key is pressed before adding another option

### PR DESCRIPTION
**Pull request by naraandrade**
Related issue: https://issues.liferay.com/browse/LPS-174943.

### CODE REVIEW

**Review by rebsilva — APPROVED** [review]
LGTM! :cherry_blossom:

**Comment by rebsilva** [comment]
Hello @naraandrade! This PR has now some conflicts with the main branch, could you please make the rebase and send it again? Thanks!

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
@rebsilva I just fixed the conflicts :)

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
