### PR TITLE
LPS-124206  Remove unnecessary variables

### PR DESCRIPTION
**Pull request by miltonmc**
Changes requested on PR https://github.com/brianchandotcom/liferay-portal/pull/98973

Original PR https://github.com/liferay-forms/liferay-portal/pull/128

### CODE REVIEW

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:forward

**Pull request closed without merging**
