### PR TITLE
LPS-139245 Refactor FieldSupport.addField()

### PR DESCRIPTION
**Pull request by miltonmc**
Related Issue: https://issues.liferay.com/browse/LPS-139245

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @miltonmc, can you please check if these failures are related to your changes? Thanks

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
This PR is must be rebased after #923 is merge to [liferay/liferay-portal](https://github.com/liferay/liferay-portal)

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:forward

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:stop

**Pull request closed without merging**
