### PR TITLE
Forms Automated Test - LPS-130996 | master

### PR DESCRIPTION
**Pull request by leticiachiu**

### CODE REVIEW

**Comment by brittneyq** [comment]
Hi @leticiachiu , could you please add step 7 on the ticket? `Assert the default text "Drag fields from the sidebar to compose your form." on Page 2`

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
@leticiachiu, according to @brittneyq review your pull looks good to go, can you please just rebase it according to the latest branch master to solve the conflicts reported below?

Thanks in advance.

Note: I apologize to you for the delay to move on with this pull, but I was out of office all last week and I wasn't aware that this specific pull was assigned to me. Thanks for your understanding. :slightly_smiling_face:

**Comment by leticiachiu** [comment]
No problem! Rebased :)

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
