### PR TITLE
LPD-27315 REST Data Provider ignores nonProxyHosts 

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://liferay.atlassian.net/browse/LPD-27315

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
@vngoliveira could you please check if the following failure is related:

1. [LocalFile.FormsSelectFromListField#CanSaveFormFieldEntryWithRestDataProvider](https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/841830/)

**Comment by vngoliveira** [comment]
@carolmariaabb I ran locally the test and it passed. Probably it is a flaky, not related

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
The test is now passing, as you can see [here](https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/396829/testReport/com.liferay.poshi.runner/PoshiRunner/)

image

**Comment by carolmariaabb** [comment]
Manully forwarded https://github.com/brianchandotcom/liferay-portal/pull/150966

**Pull request closed without merging**
