### PR TITLE
LPS-201461

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related Issue: https://liferay.atlassian.net/browse/LPS-201461

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:forms

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by alinedoleron** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:test:stable

**Comment by carolmariaabb** [comment]
ci:test:stable

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
