### PR TITLE
LPS-169459 Update number validation for null input

### PR DESCRIPTION
**Pull request by titokenzo**
https://issues.liferay.com/browse/LPS-169459

### CODE REVIEW

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:forward

**Review by carolmariaabb — CHANGES_REQUESTED** [review]
@titokenzo Please fix the SF error. Thanks!

**Comment by titokenzo** [comment]
Source updated. Push force.

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
