### PR TITLE
Forms Automated Test - LPS-131078 | master

### PR DESCRIPTION
**Pull request by leticiachiu**

### CODE REVIEW

**Comment by brittneyq** [comment]
Hi @leticiachiu, could you please assert the other fields in this step? `10. Under the Summary tab, assert there is 1 entry for each of the Text field, Color field, and Date field and that the field inputs are correct.` Looks like your test is missing asserting for color field and date field entries.

**Comment by leticiachiu** [comment]
Fixed @brittneyq

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
ci:forward

**Pull request closed without merging**
