### PR TITLE
LPD-18623 LocalFile.FormsTranslations#CanBeCreatedInMultipleLanguages

### PR DESCRIPTION
**Pull request by diogomelo09**
Hi Team,

This is for [LPD-18623](https://liferay.atlassian.net/browse/LPD-18623)
Our current java locale provider is JRE (jdk8 default)
In preparation to make the change to jdk21, we noticed that jdk21 default is CLDR. This made many functional tests fail because display name for timezone, country, format are slightly different.

This works both with JRE and CLDR

Testing here:
[CLDR](https://github.com/p-albuquerque/liferay-portal/pull/121)
[JRE](https://github.com/p-albuquerque/liferay-portal/pull/122)

### CODE REVIEW

**Comment by diogomelo09** [comment]
@carolmariaabb I've sent this new PR with the changes and the tests carried out

**Comment by diogomelo09** [comment]
changes requested in: [liferay-portal/pull/2480](https://github.com/liferay-forms/liferay-portal/pull/2480)

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
