### PR TITLE
LPS-153685

### PR DESCRIPTION
**Pull request by icgsbr**
## Related LPS
- [LPS-153685](https://issues.liferay.com/browse/LPS-153685)

### CODE REVIEW

**Comment by icgsbr** [comment]
ci:reevaluate:1377401_12408

**Comment by alinedoleron** [comment]
Hi @icgsbr! I tested here but I didn´t get the correct behavior yet. I ran the script but I'm not sure I had to wait some time to test it. Did I miss some step to configure? 
I'm getting this result when I type user1.

image

**Review by alinedoleron — COMMENTED** [review]
Hi @icgsbr! I have a question related to the setup. Please, check my comment above. Thanks!

**Comment by icgsbr** [comment]
Hi @alinedoleron I'll check again. I'll came back to you once I've checked it.

**Comment by icgsbr** [comment]
Hi @alinedoleron, somehow the solution stopped working. I'll move the LPS back to progress.

**Comment by carolmariaabb** [comment]
@icgsbr Since the ticket is In Progress, I will close this PR for now. Please feel free to reopen it or even open a new one if needed.

Thanks!

**Pull request closed without merging**
