### PR TITLE
LPS-144584 Allowing Field search in Forms show an unique field

### PR DESCRIPTION
**Pull request by rijema**
Related Issue: https://issues.liferay.com/browse/LPS-144584

Hi Team,

In this [ticket](https://issues.liferay.com/browse/LPS-144584) I changed the value that is checked to render the component containing a list of fields or an empty component. The previous value was one, with that, if only one field fits the condition, it would not be shown to users. I kept the evaluation of a value but I decrease the verification to a value greater than 0.

Let me know if you have any question.

Thanks,
Richard.

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @rijema, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
ci:reevaluate:1327401_1769

**Comment by liferay-forms** [comment]
Hey @rijema, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @rijema, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @rijema, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @rijema, can you please check if these failures are related to your changes? Thanks

**Comment by rijema** [comment]
Hi @carolmariaabb, is there anything I could help with this PR?

**Comment by carolmariaabb** [comment]
> Hi @carolmariaabb, is there anything I could help with this PR?

No 😔 Unfortunately, the reported failure is not related to your changes.

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
