### PR TITLE
LPS-200278 Draft DDMFormInstanceVersion and DDMStructureVersion cannot be approved

### PR DESCRIPTION
**Pull request by pei-jung**
Hi team, can you please review these changes? Thank you!

### Motivation
https://liferay.atlassian.net/browse/LPS-200278

In publications, we don't allow publishing a publication with draft changes. While doing testing, we noticed that with every form update, it creates a new DDMFormInstanceVersion and DDMStructureVersion. When a form rule is added, the form is saved as draft with the version objects' status set to `draft`. However, when the form is published, the draft versions are not updated, and new ones are created instead.

### Proposed Solution
Version control is handled differently in forms. Usually, we only create a new version if the current version is published/approved. We keep updating the draft until it's published/approved. Can we apply the same behavior to DDMFormInstanceVersion and DDMStructureVersion so that we don't just keep draft versions in the db without being able to update them? 

### Steps to verify
1. Add a new form and add a rule. Don't save or publish the form yet
2. Verify in the database that DDMFormInstanceVersion and DDMStructureVersion are created with `draft` status = 2
3. Publish the form
4. The draft DDMFormInstanceVersion and DDMStructureVersion are still in the database, and new ones with approved status = 1 are created.

### CODE REVIEW

**Comment by samuelromeiro** [comment]
Hi @pei-jung, thanks for your contribution. 
Since your PR is chamging some older behavior in Forms, we are going to need to analyze it with carefull. For this reason, we might finish the review by the end of next week, ok? 

Thanks for understanding!

**Comment by pei-jung** [comment]
@samuelromeiro sure, thank you for taking the time to review!

**Comment by pei-jung** [comment]
@samuelromeiro actually, can you prioritize this? We need to create a hotfix for a customer and need to include this change.

**Comment by samuelromeiro** [comment]
Hi @pei-jung, 
Tomorrow is a local holiday in Brazil. We are going to try to finish sonner than end of next week. I will come back on Friday to give you en ETA. 

Thanks!

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
@pei-jung the following failures appear to be related to your changes:

1. [LocalFile.FormsRulesActions#CanBeEdited](https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/772220//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FormsRulesActions_CanBeEdited_)
2. [LocalFile.FormRules#ActionIsUpdatedWhenFieldLabelIsEdited](https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/308393//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FormRules_ActionIsUpdatedWhenFieldLabelIsEdited_)
3. [LocalFile.FormRules#ConditionIsUpdatedWhenFieldLabelIsEdited](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/815458//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FormRules_ConditionIsUpdatedWhenFieldLabelIsEdited_)

and the integratio test

4. [com.liferay.dynamic.data.mapping.service.test.DDMFormInstanceLocalServiceTest](https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/710056/testReport/com.liferay.dynamic.data.mapping.service.test/DDMFormInstanceLocalServiceTest)

Could you please check? 

Thanks!

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
Thanks, @pei-jung

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
