### PR TITLE
LPS-168955 Allow ddmStructureKey to be edited

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://issues.liferay.com/browse/LPS-168955

cc: @kristofloneck

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Hi @kristofloneck, how are you doing?
Sorry for the delay! I was on this branch, and I run locally and all tests failed in this class: [com.liferay.journal.service.test.JournalArticleDDMFormConverterTest](https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/168696/testReport/com.liferay.journal.service.test/JournalArticleDDMFormConverterTest)

Could you investigate the reason, please? Thank you :smile:

**Comment by kristofloneck** [comment]
Hi @marcelabc 
I start checking it.

**Comment by marcelabc** [comment]
Hi @kristofloneck,
Could you fix the rebase error please?

**Comment by kristofloneck** [comment]
@marcelabc 
I wrote a fix:
Add a null check for structure key before setting it to the structure:
You can find it on kristofloneck:LPS-168955_master

**Comment by kristofloneck** [comment]
I don't have right to solve the conflict in this branch (mine don't have any conflict)

**Comment by kristofloneck** [comment]
btw sorry being late other tickets cut in the line.

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Hi @kristofloneck, no problem!
I updated this branch with the new code that you sent me! Let's wait the CI results :smile: 
Thank you

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:reevaluate:1387401_5871

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/129173

**Pull request closed without merging**
