### PR TITLE
[TS] LPS-173034

### PR DESCRIPTION
**Pull request by crodriguezy**
Related issue: https://issues.liferay.com/browse/LPS-173034

### CODE REVIEW

**Comment by crodriguezy** [comment]
Hello @carolmariaabb , as requested in https://github.com/liferay-forms/liferay-portal/pull/2110, I included the proposed changes and I fixed the tests.

**Comment by crodriguezy** [comment]
Hi @carolmariaabb , @marcelabc , is there any problem with this? The customer is still testing the functionality

**Comment by crodriguezy** [comment]
Hello @carolmariaabb and @marcelabc , unfortunately this fix is not working correctly for some contents :(

This content in 7.0:
[lfr-70_complex.txt](https://github.com/liferay-forms/liferay-portal/files/10675561/lfr-70_complex.txt)

is not being correctly upgraded in 7.4:

[lfr-74_complex.txt](https://github.com/liferay-forms/liferay-portal/files/10675567/lfr-74_complex.txt)

Could you please advice?

Thanks

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by crodriguezy** [comment]
Hello @marcelabc and @carolmariaabb ,

I'm afraid the changes there can cause trouble with methods implemented in com.liferay.dynamic.data.mapping.util.DDMFormValuesConverterUtil


I'm testing in the customer scenario and I'm reproducing an issue related:

1. Use the structure attached in https://issues.liferay.com/browse/LPS-173034 in 7.0.
2. Create a content like the one I attach here (lfr-70_complex.txt)
3. Perform the upgrade (u51) without the fix. That's what they did and they cannot perform the upgrade again with the fix.
4. So, in order to try and fix their current data (its urgent for them), proceed as follows:
    4.1 "Import and replace" the structure (incorrectly upgraded without the fix) with the one attached 
      (Structure_7.4_migrada_ok.json)
    4.2 Open the upgraded content created in 2, so it renders with the updated data. Here you can see the data is incorrect 
    (attached result -> lfr-74_complex.txt)

[Structure_7.4_migrada_ok_json.txt](https://github.com/liferay-forms/
[lfr-70_complex.txt](https://github.com/liferay-forms/liferay-portal/files/10685941/lfr-70_complex.txt)
[lfr-74_complex.txt](https://github.com/liferay-forms/liferay-portal/files/10685942/lfr-74_complex.txt)
liferay-portal/files/10685938/Structure_7.4_migrada_ok_json.txt)

A lot of nested 2nd level fields (enlaceNieto) empty and with incorrect data have been added. I've been debugging and the problem seems to be in com.liferay.dynamic.data.mapping.util.DDMFormValuesConverterUtil, specifically in the recursive addMissingDDMFormFieldValues and _addMissingNestedDDMFormFieldValues

Please, let me know what you think. Any kind of help is welcome
Thanks

**Comment by marcelabc** [comment]
Hey @crodriguezy,
There were a lot of conversations and tickets that made me confused. Would you want this PR Review to continue the way it is?
Please, let us know!

**Comment by crodriguezy** [comment]
Hello @marcelabc ,

I think we can move forward with the current proposal

cc/ @carolmariaabb

**Review by marcelabc — APPROVED** [review]
Hi @crodriguezy, LGTM 🎉
Since these changes can impact upgrade, I will ask for our QA team to test locally before we send to Brian, okay?
Thank you!

**Comment by marcelabc** [comment]
Hi @crodriguezy,
Our QA team tested locally and we can move forward with this solution :smile: 
Thank you!

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
