### PR TITLE
LPD-39099 Unable to send email notification after form submission

### PR DESCRIPTION
**Pull request by izaera**
This is removing the `${nonceAttribute}` from the template and adding a SF exception so that SF doesn't complain.

Refer to slack conversation https://liferay.slack.com/archives/CNBG06JS3/p1728665719893339 for more context.

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:sf

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
Thanks a lot for your help, @izaera !

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:test:stable

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
