### PR TITLE
LPS-155021 Add conditions for fieldset and ddm-paragraph for translation

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-155021

When a field is nested inside a fieldset and the user changes the language, the field's translation will be set to the translation of the fieldset, rather than its original translation.
This is occurring since the setLabel looks for instance.getLabelNode();. This will result in getting the field information when the instance is the fieldset. The field will then be translated into the fieldset information.

In order to resolve this, I included a condition that will check if the type is a fieldset and correctly translate it. I also accounted for ddm-paragraph by adding a field-wrapper and condition for translation.

Let me know if there are any questions or comments about this.
Thank you!

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by rebsilva** [comment]
Hi @fortunatomaldonado! Could you take a look at the test failing? I think they are related to your changes since we added a new field (ddm-paragraph at ddm_form.js) and a new class in the paragraph as well. Please let us know if you have any questions about this!

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
Hello @rebsilva,
I will be working on a project all of next week so I will see if there will be anyone available to take a look at this. If not, I will try to make some time for it.

Thank you again for all your help!

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
Hi @fortunatomaldonado! Since the failing tests are recurrent, I'll close this PR; you can open another one when you have the time to fix the tests. Thanks a lot!

**Pull request closed without merging**
