### PR TITLE
LPS-140670 Cannot filter by Image field

### PR DESCRIPTION
**Pull request by IstvanD**
Related Issue: https://issues.liferay.com/browse/LPS-140670

Dear Team,

Could you please review this pull request?

Unfortunately, [LPS-136630](https://issues.liferay.com/browse/LPS-136630) caused a regression but I managed to find the root cause and fix it.

Thank you and best regards,
István

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Review by rodrigopaulino — CHANGES_REQUESTED** [review]
Hi, @IstvanD.

Will this regression be reproducible on 7.3.x once LPS-136630 is backported? If so, please remember to backport this regression bug fix along with the LPS-136630 in the same pull request.

Kind regards.

**Comment by IstvanD** [comment]
> Hi, @IstvanD.
> 
> Will this regression be reproducible on 7.3.x once LPS-136630 is backported? If so, please remember to backport this regression bug fix along with the LPS-136630 in the same pull request.
> 
> Kind regards.

Hi @rodrigopaulino, no, this issue affects only master. On 7.3.x, `ddmFormField.getType()` will be "ddm-image", not "image".

**Review by rodrigopaulino — APPROVED** [review]

**Comment by rodrigopaulino** [comment]
Hey, @IstvanD. I can see this failure is unrelated to your fix.
I already contacted the QA team so they can assist us to understand the root cause.

Please, let's wait their response. You can find the thread in the quality assurance Slack channel. 😉 
Thanks for understanding.

**Comment by nkkwon** [comment]
Analysis details:
Failing with
`delete-liferay-home:
     [exec] ERROR 1064 (42000) at line 5: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(6) null,
     [exec] 	modifiedDate datetime(6) null,
     [exec] 	classNameId bigint,
     [exec] 	classPK bigint,
     [exec] ' at line 9
[stopwatch] [run.batch.test.action: 13.915 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:365: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:434: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:11755: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-common.xml:521: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-common.xml:640: exec returned: 1`
It looks like a SQL syntax error and it doesn't look related to commits for this PR

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
