### PR TITLE
LPS-152426

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related Issue: https://issues.liferay.com/browse/LPS-152426

Some customers are complaining that the **Checkbox** field (boolean type) is missing from the **Data Engine** sidebar. This field exists in previous versions but has been removed in 7.4.x. An upgrade process was created in the past to convert the **Checkbox** field to **Checkbox Multiple**.

As not every **Checkbox Multiple** field is a **Checkbox** field, there is no way to recover the **Checkbox** field created in previous versions after performing the upgrade to 7.4.x. Unfortunately, the only solution is to change the existing upgrade process.

This PR aims to:
- Add the **Checkbox** field back to the **Documents and Media** and **Web Content** sidebar
- Change the existing upgrade process to prevent other customers from having the same issue when upgrading to 7.4.x

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hey @carolmariaabb, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @carolmariaabb, can you please check if these failures are related to your changes? Thanks

**Review by rodrigopaulino — APPROVED** [review]
LGTM! 🎉 
Thanks for working so fast on this, @carolmariaabb.

**Comment by rodrigopaulino** [comment]
@carolmariaabb, do you think it would be worth running D&M's and WC's tests too?

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @carolmariaabb, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:help

**Comment by carolmariaabb** [comment]
ci:test:echo

**Comment by carolmariaabb** [comment]
ci:test:documents

**Comment by carolmariaabb** [comment]
ci:test:lima

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @carolmariaabb, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:reevaluate:1307401_3170

**Comment by carolmariaabb** [comment]
ci:reevaluate:1307401_3170

**Comment by liferay-forms** [comment]
Hey @carolmariaabb, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @carolmariaabb, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @carolmariaabb, can you please check if these failures are related to your changes? Thanks

**Pull request closed without merging**
