### PR TITLE
LPS-136443

### PR DESCRIPTION
**Pull request by mlan0**

### CODE REVIEW

**Comment by mlan0** [comment]
ci:test:relevant

**Review by miltonmc — APPROVED** [review]
LGTM!

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@mlan0, can you please double check if the reported test failure isn't related to your pull? The same failure was reported twice.

**Comment by mlan0** [comment]
@natocesarrego , @miltonmc this poshi test is failing because of the Paragraph Field, as shown in the screenshots. This may be related to those CKEditor bugs, because I ran the test a few times locally and sometimes it pass. 

screenshot-1629750415

screenshot-1629750847

**Comment by natocesarrego** [comment]
Thanks for your clarification, @mlan0. :slightly_smiling_face: 

So, we should fix the CKEditor issues, before move on with this pull, did I understand you correctly?

**Comment by rodrigopaulino** [comment]
Hey, guys! With this fix, we can get rid of the entire solution for this [bug](https://issues.liferay.com/browse/LPS-135432). That one was only intended to workaround the problem @mlan0 is fixing here. I've tested this fix and it seems to work for that case too, but you're free to test it yourselves. 😄 

Good job!

**Comment by mlan0** [comment]
@natocesarrego , We can add this Poshi test to the list of tests affected by those ckeditor bugs, because I suppose that it will pass only when the CKEditor bugs are fixed, and then forward this pull as it solves these 2 bugs.

**Pull request closed without merging**
