### PR TITLE
[TS] LPS-160234

### PR DESCRIPTION
**Pull request by tototrinh**
Hi guys,
Please help review this PR and leave your comments.
Tickets:
https://issues.liferay.com/browse/LPP-46182
https://issues.liferay.com/browse/LPS-160234
cc: @hongvo2308

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
Hi, @hongvo2308. Thanks a lot for your contribution.
I ran some quick tests on your solution and I'll let you know more details in the comment's section of the ticket.
Kind regards.

**Comment by rodrigopaulino** [comment]
ci:close

**Comment by rodrigopaulino** [comment]
ci:reopen

**Review by rodrigopaulino — APPROVED** [review]
LGTM! Thanks for your contributions, @tototrinh and @hongvo2308. 😄

**Comment by rodrigopaulino** [comment]
ci:forward

**Review by rodrigopaulino — CHANGES_REQUESTED** [review]
Hi, @tototrinh. Thanks a lot for your contribution.
I have some questions regarding these changes that I will address in the ticket's comment section.
Kind regards.

**Comment by michaelhashimoto** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
ci:stop

**Comment by rodrigopaulino** [comment]
ci:close

**Comment by rodrigopaulino** [comment]
Resent https://github.com/liferay-forms/liferay-portal/pull/1913

**Pull request closed without merging**
