### PR TITLE
LPS-130069 It's not possible to scroll a structure when the mouse is on the left side of the builder

### PR DESCRIPTION
**Pull request by mateusgomes01**
Related Issue: https://issues.liferay.com/browse/LPS-130069

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @mateusgomes01, can you please check if these failures are related to your changes? Thanks

**Comment by mateusgomes01** [comment]
ci:reevaluate:1187401_6177

**Comment by mateusgomes01** [comment]
ci:reevaluate:1187401_6177

**Comment by miltonmc** [comment]
@mateusgomes01
Please, try to rebase on top of the `liferay/liferay-portal` `master` branch and then re execute `ci:test:sf`to restart the PR validation process

**Comment by mateusgomes01** [comment]
ci:test:sf

**Comment by mateusgomes01** [comment]
@miltonmc it passed. May I foward this PR?

**Comment by miltonmc** [comment]
@mateusgomes01 , maybe we should involve Journal's team, since this code is changing things inside their module.

@natocesarrego what do you think about it?

**Comment by natocesarrego** [comment]
Makes sense to me, @miltonmc. :slightly_smiling_face: Can you please forward the pull to the Echo Team?

Good job, @mateusgomes01! :clap: 

During your next investigations, if you realize that the issue's root cause is in other component which uses Data Engine, like Web Content, please assign it to the proper component / product team as you did recently to that bug related to `Liferay.Session.extend()`. :wink: 

Thanks guys!

**Comment by miltonmc** [comment]
@mateusgomes01 can you please forward the pull to the Echo Team?

**Comment by mateusgomes01** [comment]
fowarded to liferay-echo team at [#6011](https://github.com/liferay-echo/liferay-portal/pull/6011)

**Pull request closed without merging**
