### PR TITLE
LPS-135282 Navigation bar overlaps the user dropdown menu

### PR DESCRIPTION
**Pull request by mateusgomes01**

### CODE REVIEW

**Comment by mateusgomes01** [comment]
@miltonmc Milton, could you please review this PR? Thanks!

**Review by miltonmc — APPROVED** [review]
LGTM!

**Comment by mateusgomes01** [comment]
ci:test:sf
ci:test:relevant

**Comment by mateusgomes01** [comment]
ci:test:relevant

**Comment by mateusgomes01** [comment]
ci:test:relevant

**Comment by mateusgomes01** [comment]
ci:test:stop

**Comment by mateusgomes01** [comment]
ci:test:sf

**Comment by mateusgomes01** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:forward

**Pull request closed without merging**
