### PR TITLE
LPS-144108 Fix error message not displaying

### PR DESCRIPTION
**Pull request by miltonmc**
Related Issue: https://issues.liferay.com/browse/LPS-144108

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
closed in favor of https://github.com/brianchandotcom/liferay-portal/pull/111319

**Pull request closed without merging**
