### PR TITLE
[TECHNICAL SUPPORT] LPS-167775 Repeated DDM html field will associate with ddmPortlet instead of where ddm is consumed

### PR DESCRIPTION
**Pull request by NemethNorbert**
Previous PR: https://github.com/liferay-forms/liferay-portal-ee/pull/140

Hey,
[LPS-167775](https://issues.liferay.com/browse/LPS-167775)

The issue here is that repeated ddm fields will be associated with dynamic-data-mapping instead of the portlet where ddm is consumed. The solution was to override the portletId of the httpServletRequest when we create the renderingContext of the DDM fields. I did not find any downside of overwriting the attribute.

Please review the changes,

cc @marcelabc

### CODE REVIEW

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:reevaluate:1257401_5316

**Comment by carolmariaabb** [comment]
@NemethNorbert The failures are not related to your changes. Feel free to send this directly to Brian. Thanks!

**Comment by NemethNorbert** [comment]
Hey @marcelabc,

The PR automatically got closed due to it was sent manually and not forwaded by ci. 
I reopen this PR and please try to forward it

**Comment by marcelabc** [comment]
Hey @NemethNorbert,
It is normal to close automatically, but just need to comment "ci:reopen" and it will open :+1: 
https://github.com/brianchandotcom/liferay-portal/pull/126115
I reopened your PR and I'm closing this one, okay?

**Pull request closed without merging**
