### PR TITLE
LPS-144801 Display all fields rather than limiting it to 5

### PR DESCRIPTION
**Pull request by mbowerman**
Related Issue: https://issues.liferay.com/browse/LPS-144801

Hi Forms Team,

Please see [PTR-2815](https://issues.liferay.com/browse/PTR-2815) for the explanation about why this is being treated as a bug.

https://issues.liferay.com/browse/LPS-144801

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @mbowerman, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
