### PR TITLE
LPD-19090 Remove test from quarantine

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://liferay.atlassian.net/browse/LPD-19090

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Review by carolmariaabb — APPROVED** [review]

**Comment by marcelabc** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
Test is passing:
image

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
