### PR TITLE
LPS-153685 fetching users when field is edited

### PR DESCRIPTION
**Pull request by linolaoj**
Related issue: https://liferay.atlassian.net/browse/LPS-153685

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:forms

**Comment by linolaoj** [comment]
ci:relevant

**Comment by linolaoj** [comment]
ci:test:forms

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
i'll review this later today :cherry_blossom:

**Review by rebsilva — APPROVED** [review]
LGTM! :tada:

**Comment by davisaints** [comment]
Unrelated failures! This PR is good to go!

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by davisaints** [comment]
ci:stop

**Comment by davisaints** [comment]
ci:forward

**Comment by davisaints** [comment]
ci:stop

**Comment by davisaints** [comment]
@linolaoj, can you manually forward this pull request to BChan?

**Comment by linolaoj** [comment]
ci:forward:force

**Pull request closed without merging**
