### PR TITLE
Forms Automated Test - LPS-134386 | master 

### PR DESCRIPTION
**Pull request by fmarcio**

### CODE REVIEW

**Comment by DiegoDOC** [comment]
Hey @fmarcio, your code seems good to go.

Keep up the good work!

**Comment by DiegoDOC** [comment]
ci:forward

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
@DiegoDOC PR issues fixed! I couldn't upload the new index on JIRA because it is facing some file uploads issues

**Comment by DiegoDOC** [comment]
ci:forward

**Pull request closed without merging**
