### PR TITLE
LPD-23306 Predefined value disappears from Form text field if Rule is applied

### PR DESCRIPTION
**Pull request by vngoliveira**
[LPP-53623](https://liferay.atlassian.net/browse/LPP-53623)
[LPD-23306](https://liferay.atlassian.net/browse/LPD-23306)

### CODE REVIEW

**Review by devpedrotavares — APPROVED** [review]
LGTM!

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:test:stable

**Comment by vngoliveira** [comment]
ci:foward

**Comment by vngoliveira** [comment]
ci:test:sf

**Comment by vngoliveira** [comment]
ci:test:relevant

**Comment by vngoliveira** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
