### PR TITLE
LPS-125821 Fixes error of breaking the rules page when trying to save the form with broken rule

### PR DESCRIPTION
**Pull request by matuzalemsteles**
Ticket: https://issues.liferay.com/browse/LPS-125821

@natocesarrego I realized that when trying to save a form with a broken rule in the case of use of the ticket the rule that comes back from the backend is the rule saved previously. I think, should go back to the rules that was sent to the backend because otherwise, we cannot say if the rule is broken.

Simplifying, when deleting the field that was used in the rule, we show that the rule is broken by removing the field from the rule but when trying to save the form it should return without the field in the rule in the same way that the form returns without the field.

### CODE REVIEW

**Comment by natocesarrego** [comment]
Hey @matuzalemsteles, your suggestions makes sense to me and I remember to discuss this matter with @carolmariaabb and @alinedoleron, right girls?

Do you remember about this discussion and what we've concluded/decided?

Thanks.

**Comment by carolmariaabb** [comment]
Hi @natocesarrego, I remember that the `MustSetValidFormRuleExpression` exception is the reason why the backend sends the rule with the deleted field. This exception does not allow the Form to be saved, therefore, the rules are not updated.

So, we chose to [format the rules](https://github.com/gabrielwas/liferay-portal/blob/8b65f6f1b16ed6cfb617d63c861ae9a3963ae6d6/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-builder/src/main/resources/META-INF/resources/js/components/RuleBuilder/RulesSupport.es.js#L59) in the [RuleList](https://github.com/liferay/liferay-portal/blob/8b65f6f1b16ed6cfb617d63c861ae9a3963ae6d6/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-builder/src/main/resources/META-INF/resources/js/components/RuleList/RuleList.es.js#L56) in order to find out if a rule is broken or not.

**Comment by natocesarrego** [comment]
Great, @carolmariaabb! Thanks for your clarification. 😉 

Let's move on with this pull, @matuzalemsteles. 🙂

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
