### PR TITLE
[TS] LPP-46306 > LPS-161353 Accept Root Relative URL in Form redirect url on success

### PR DESCRIPTION
**Pull request by hongvo2308**
Hi @rodrigopaulino 
This is the PR for the ticket https://issues.liferay.com/browse/LPS-161353. I have updated this to use the new validation for FormInstance only. Could you please help me to review this one?
Thank you.

### CODE REVIEW

**Comment by hongvo2308** [comment]
ci:test:bundle

**Review by rodrigopaulino — CHANGES_REQUESTED** [review]
Hi, @hongvo2308. Thanks for your contribution.
That's good. It addresses the issue I mentioned in your last pull request, but I think there's a better way of doing it.
You can actually give a DDMExpressionFunction more than one signature if you implement more than one DDMExpressionFunction.FunctionX in the isURL existing one. You can implement a 2 parameters function which will accept a boolean as last parameter called "acceptsRootRelative".
I'm closing this one so you can send a new PR with the proposed changes.
Kind regards.

**Comment by rodrigopaulino** [comment]
ci:close

**Comment by hongvo2308** [comment]
@rodrigopaulino Thank you for your suggestion. I will update the implement and send another PR.

**Pull request closed without merging**
