### PR TITLE
LPS-171482 getting picklist options from object

### PR DESCRIPTION
**Pull request by linolaoj**
Related issue: https://issues.liferay.com/browse/LPS-171482

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Just started reviewing :)

**Comment by marcelabc** [comment]
Hi @linolaoj , how are you doing?
I did minor changes in this PR and I resent https://github.com/liferay-forms/liferay-portal/pull/2084
Let me know if you have questions!

**Pull request closed without merging**
