### PR TITLE
LPS-149701 Can't order templates alphabetically

### PR DESCRIPTION
**Pull request by lfbesada**
Related Issue: https://issues.liferay.com/browse/LPS-149701

Hi Team,

I'm sending this PR to you in order to review the first two commits since @bakayattila added a new comparator (TemplateNameComparator) on the dynamic data mapping API module. The purpose is to allow ordering template names by locale, also he added some tests to check the behavior match with expected.

I've already reviewed the code from Echo modules and added a few SF commits.

Could you please take a look at it and forward it to Brian if everything looks good to you?

For more information see: https://issues.liferay.com/browse/PTR-2856 and https://issues.liferay.com/browse/LPS-149701

Thanks!!

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hey @lfbesada, can you please check if these failures are related to your changes? Thanks

**Comment by lfbesada** [comment]
Hi @carolmariaabb 
Thanks for reviewing it! ❤️ 
I have pushed the asked renames.
The failed test doesn't seem to be related to these changes. 
Thanks!
cc: @bakayattila

**Review by carolmariaabb — APPROVED** [review]
Hi @lfbesada,

LGTM 😄 🥳

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @lfbesada, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
