### PR TITLE
LPS-198968 Normalize fieldName/fieldReference of duplicated fieldSets

### PR DESCRIPTION
**Pull request by carolmariaabb**
**Related Issues**: 
https://liferay.atlassian.net/browse/LPS-199088
https://liferay.atlassian.net/browse/LPS-198968

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:data-engine

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:stable

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
LGTM :) Thx a lot, @carolmariaabb

**Comment by carolmariaabb** [comment]
ci:test:stable

**Comment by brianchandotcom** [comment]
@carolmariaabb I just merged this to master.

**Comment by rijema** [comment]
Thanks, @carolmariaabb !!

**Pull request closed without merging**
