### PR TITLE
LPS-144911 fieldName may be longer than 255 characters

### PR DESCRIPTION
**Pull request by IstvanD**
Related issue: https://issues.liferay.com/browse/LPS-144911

Dear Team,

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by natocesarrego** [comment]
Hi @IstvanD,

Have a field label with more than 255 characters is really a valid test case for the customer?

Maybe, we should set a max limit of 255 characters for the field label and the field name in the UI, what do you think?

Thanks in advance for your answers. :slightly_smiling_face:

**Comment by IstvanD** [comment]
Hi @natocesarrego 

Yes, this may happen.
Some Forms (in DDMStructure) may contain fields whose names exceed 255 chars
This can happen (at least) when someone creates a form with selectable answers as radio boxes. If the author enters a text long enough, liferay will default radio field name to a technical name based on that text (but not shortened).

An alternative solution may be during the upgrade, to truncate the field name before it [gets inserted](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/internal/upgrade/v4_1_0/DDMFieldUpgradeProcess.java#L477-L478).

What do you think?

Best regards,
István

**Comment by natocesarrego** [comment]
It makes sense to me, @IstvanD. :slightly_smiling_face: 

In order to address this issue, I understand we should perform the following steps:

1. Add a validation in the front-end to limit the number of characters to 255 maximum of field labels and field names
2. During the upgrade, truncate the existing field labels and field names bigger than 255 characters, as suggested by you. Even though, I understand it's worth we log that the info was truncated during the upgrade to let the users know about it.

I'll discuss this idea with the team, but do the steps above make sense to you?

Thanks

**Comment by IstvanD** [comment]
Hi @natocesarrego 

This makes sense to me, however, as I surmise from the customer use case, the field labels are generated dynamically, which a front-end validation could not catch. Also, it would be hard to backport as in this particular use case, the upgrade is made from 7.0 to master (7.4) and the validation logic would have to be implemented differently.
However, the truncation to 255 chars during the upgrade wouldn't be that problematic.

What do you think?

Best regards,
István

**Comment by natocesarrego** [comment]
Great job, @IstvanD!

I also discussed with Forms Team about this pull and another problematic use case raised during our discussion is related to custom code, therefore let's move on with your initial fix proposal. :slightly_smiling_face:

Do you mind to split your pull into 2 separated commits? I mean, can you please add a dedicated commit to the `build service` output?

Thanks!

**Comment by IstvanD** [comment]
Hi @natocesarrego 

Sure, I'll do that.
May I ask just for a little bit more clarification :)

By initial fix proposal, do you mean the changes in this commit (turning fieldName in the schema from VARCHAR(255) to TEXT)?
Or the truncation during the upgrade process?

By build service output do you mean the logging that you mentioned earlier?

> it's worth we log that the info was truncated during the upgrade to let the users know about it.

Thank you and best regards,
István

**Comment by natocesarrego** [comment]
Oh, sorry for the confusion, @IstvanD. Please move on with changing the database column type from `VARCHAR(255)` to `TEXT`.

In regards to the commits, please create two separated commits, like below:
- https://github.com/liferay-forms/liferay-portal/pull/1264/commits/5d99607e83cea61cdcd9270282f43daaab7bfcdb
- https://github.com/liferay-forms/liferay-portal/pull/1264/commits/6646c534ef38029161753a9159b724483c41966e

The idea is use both commits above as an inspiration. :slightly_smiling_face:

Is it clearer now?

Thanks

**Comment by IstvanD** [comment]
Hi @natocesarrego 

Thank you, it's all clear now. :)
Actually, I'm going to break it into 3 commits.

1. changing the type of fieldName in portlet-model-hints.xml
2. build service
3. changing the create table SQL command in DDMFieldUpgradeProcess

The 3rd one is not related to the building of the service.

**Comment by IstvanD** [comment]
New pull sent: https://github.com/liferay-forms/liferay-portal/pull/1339

**Pull request closed without merging**
