### PR TITLE
LPD-38566 Fix data engine poshi tests

### PR DESCRIPTION
**Pull request by igor-franca**
Related [Ticket](https://liferay.atlassian.net/browse/LPD-38566)

### CODE REVIEW

**Comment by igor-franca** [comment]
ci:test:data-engine

**Comment by igor-franca** [comment]
These tests failed due to the removal of a feature flag from the web content.

I noticed there is another web content update under the feature flag. Removing it would also break data engine testing again. I preferred to add their FF to our poshi tests and correct the tests considering this new feature.

**Comment by igor-franca** [comment]
ci:test:data-engine

**Comment by igor-franca** [comment]
ci:test:data-engine

**Comment by igor-franca** [comment]
TestRay results:

[LocalizedSimpleFieldsWebContent#CreateEditAndDeleteLocalizedWebContent](https://testray.liferay.com/#/project/35392/routines/45357/build/38470998/case-result/38475982) ✅ 
[LocalizedNestedFieldsWebContent#AddAndEditTranslatedFieldsWithOptions](https://testray.liferay.com/#/project/35392/routines/45357/build/38470998/case-result/38475970) ✅ 
[LocalizedSimpleFieldsWebContent#AddAndEditTranslatedFieldsWithOptions](https://testray.liferay.com/#/project/35392/routines/45357/build/38470998/case-result/38475978) ✅ 
[LocalizedFieldsetsWebContent#CreateEditAndDeleteLocalizedFieldset](https://testray.liferay.com/#/project/35392/routines/45357/build/38470998/case-result/38475966) ✅ 
[LocalizedSimpleFieldsWebContent#DuplicateAndEditTranslatedFieldsWithOptions](https://testray.liferay.com/#/project/35392/routines/45357/build/38470998/case-result/38475986) ✅

**Comment by igor-franca** [comment]
Changes to the web content path file are being reviewed [here](https://github.com/liferay-echo/liferay-portal/pull/16388)

**Review by larissacribeiro — APPROVED** [review]
LGTM!

**Comment by igor-franca** [comment]
The changes were approved in liferay-content-management, and sent forward there. Thanks!

**Comment by samuelromeiro** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/155107

**Pull request closed without merging**
