### PR TITLE
LPS-181656

### PR DESCRIPTION
**Pull request by mbowerman**
Ticket: [LPS-181656](https://issues.liferay.com/browse/LPS-181656)

Adding data via Spreadsheet View was not working. I applied a similar solution to [LPS-107858](https://issues.liferay.com/browse/LPS-107858) for updating data via Spreadsheet View (see https://github.com/liferay/liferay-portal/compare/4660a7c533...b1cf5e5713).

### CODE REVIEW

**Comment by mbowerman** [comment]
Hello @carolmariaabb,

Thank you very much for your thorough review! I've made all the requested changes and did a force-push, could you please check it again when you get a chance? Thanks!

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
