### PR TITLE
LPS-155626 Remove Feature Flag for LPS-152735

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://issues.liferay.com/browse/LPS-155626

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Review by rodrigopaulino — APPROVED** [review]
LGTM! 🎉

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
