### PR TITLE
Forms Automated Test - LPS-133469

### PR DESCRIPTION
**Pull request by wesleyroberts**

### CODE REVIEW

**Comment by wesleyroberts** [comment]
Sorry, I forgot to remove // TODO LPS-133469 PreserveTheRepeatableProperty pending implementation

**Comment by wesleyroberts** [comment]
ci:test:forms

**Comment by wesleyroberts** [comment]
ci:test:forms

**Comment by wesleyroberts** [comment]
ci:test:forms

**Comment by wesleyroberts** [comment]
ci:test:relevant
    ci:test:sf

**Comment by wesleyroberts** [comment]
ci:test:relevant

**Comment by wesleyroberts** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
@wesleyroberts, why did you decide to run the command `ci:test:forms`? Can you please clarify?

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
