### PR TITLE
LPS-139520 Change of locale does not update editor data and language direction

### PR DESCRIPTION
**Pull request by markocikos**
Fixes: https://issues.liferay.com/browse/LPS-139520

See steps to reproduce in the JIRA ticket.

@eli-rlima I started working on [the RTL bug in CKEditor](https://issues.liferay.com/browse/LPS-138142), but noticed locale change is not working at all. This is a partial revert of https://github.com/brianchandotcom/liferay-portal/pull/107250/commits/9fec8e05d395fd7d3162a6c99bdaf8909432996d, of the code related to data and language direction setting.

Before PR:
before

After PR
after

### CODE REVIEW

**Comment by eli-rlima** [comment]
ci:test:sf

**Comment by eli-rlima** [comment]
Thanks, @markocikos!

I noticed in last Friday that my changes wasn't working correctly. Thanks by your fix!

**Review by miltonmc — APPROVED** [review]
@markocikos, thanks for you contribution! :1st_place_medal:

**Comment by miltonmc** [comment]
ci:forward

**Pull request closed without merging**
