### PR TITLE
LRQA-69824 deleting polls

### PR DESCRIPTION
**Pull request by leticiachiu**
Related Issue: https://issues.liferay.com/browse/LRQA-69824

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@leticiachiu, I'll forward this pull, but please make sure that we won't hit other teams. I'm saying this considering the following search in VSCode:

image

Thanks :wink:

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
