### PR TITLE
LPS-146526 Revert "LPS-144712 Add feature flag"

### PR DESCRIPTION
**Pull request by rebsilva**
Related issue: https://issues.liferay.com/browse/LPS-146526

Hello Reviewer!

This PR has the removal of the FF related to the story:
**As a form admin, I want to be able to request datetime from my users** ([LPS-143050](https://issues.liferay.com/browse/LPS-143050))
If you have any questions feel free to ask, thank you for your time!

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:stop

**Comment by liferay-forms** [comment]
Hey @rebsilva, can you please check if these failures are related to your changes? Thanks

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:forms

**Review by rodrigopaulino — APPROVED** [review]
Thanks, Beca! LGTM 🎉

**Comment by liferay-forms** [comment]
Hey @rebsilva, can you please check if these failures are related to your changes? Thanks

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @rebsilva, can you please check if these failures are related to your changes? Thanks

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @rebsilva, can you please check if these failures are related to your changes? Thanks

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @rebsilva, can you please check if these failures are related to your changes? Thanks

**Comment by rodrigopaulino** [comment]
Hey, @rebsilva. Could you please check if the JS tests from the `dynamic-data-mapping-form-web` module are passing locally before running relevant again? Thanks in advance.

**Comment by rebsilva** [comment]
Hi @rodrigopaulino! Just tested and everything is passing. Maybe I should do a rebase and open this PR again?

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Hey @rebsilva, I think you should also revert this [commit](https://github.com/liferay/liferay-portal/commit/9056c87cf4ada95ad60374f5bdc50f7ca69d0ffc#diff-517f0e37a6dab7df06fae30dda5a6f9682c4ca8c534f658fc40fe1443431c301).

**Comment by rebsilva** [comment]
ci:stop

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:forms

**Comment by rebsilva** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
> ### ❌ ci:test:forms - 8 out of 11 jobs passed in 1 hour 37 minutes
> Click here for more details.
> 

Unrelated failures

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
