### PR TITLE
LPS-153046,LPS-152377

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issues: 

- https://issues.liferay.com/browse/LPS-153046
-  https://issues.liferay.com/browse/LPS-152377

Hi Reviewer!

This PR is related to the 7.4 Polls Upgrade bugs, you can know more about them in the links above; I will leave here some advice that the PO said about these bugs:

_Attention: make sure we don't break anything in the customers that already are in 7.4 and are only using forms (for a missing flag for example)_

P.S: These are changes requested by Brian, the previous PR is here https://github.com/liferay-forms/liferay-portal/pull/1670

Thank you for your time!

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @rebsilva, can you please check if these failures are related to your changes? Thanks

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
@rebsilva related failure: `PollsToDDMUpgradeProcessTest.testGetSerializedSettingsDDMFormValues`

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
