### PR TITLE
LPS-166350 Corrected the width to 25% and added the truncate an tooltip in text and select area

### PR DESCRIPTION
**Pull request by Valmir-unicap**
Link: https://issues.liferay.com/browse/LPS-166350

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Hey @Valmir-unicap,
Just for curiosity, did you see the discussion in the ticket? Eric answered that he had worked with Daniel on a possible solution.
I want to know if you work alone or talk with the guys. :smile:

**Comment by Valmir-unicap** [comment]
Hello @marcelabc, yes I saw the discussion in the ticket, I worked with Eric to develop the solution.

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Review by alinedoleron — CHANGES_REQUESTED** [review]
Hi @Valmir-unicap. Sorry for the delay to review.
I've made some initial tests on the pr and I noticed some points that needs to be fixed. The main point is that, when we resize a field, the remaining space should be droppable. I didn't have time to search for something to help you in this case. So, when you have time to back to this ticket, please have a look on this video.
I also noticed some bugs related to the tooltips. 
[dnd_broken.webm](https://user-images.githubusercontent.com/26491796/203141115-1e2e4a48-806d-4772-8dfc-49c0cec9cf5f.webm)


Thanks!

**Comment by samuelromeiro** [comment]
Hey @Valmir-unicap, can you check the conflicts and resend the PR, please?

**Pull request closed without merging**
