### PR TITLE
LPS-140215 Change the close button to KeyValue from Options and some needed parameters

### PR DESCRIPTION
**Pull request by kiwm**
Related issue: https://issues.liferay.com/browse/LPS-140215

### CODE REVIEW

**Comment by kiwm** [comment]
ci:test:sf

**Comment by kiwm** [comment]
ci:test:relevant

**Comment by kiwm** [comment]
ci:test:relevant

**Comment by kiwm** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Hi @kiwm! how are you doing?
I just wanted to let you know that I edited the description to include the "Related Issue" (with the Jira ticket). Please always add this information in your following reviews if you can :smile:

**Comment by marcelabc** [comment]
Hey @alinedoleron,
Could you review this PR, please? Let me know if you need any help :smile:

**Comment by kiwm** [comment]
ci:stop

**Comment by alinedoleron** [comment]
Hello @kiwm. Please, could you run `yarn test` on `dynamic-data-mapping-form-field-type` module. There are some snapshot test failing.  After this, you can run `yarn test -u` to update those failing tests and make a push force on this branch. 
Please, if you have any question let me know.
Thanks!

**Review by alinedoleron — CHANGES_REQUESTED** [review]
Hello @kiwm. Please, could you run `yarn test` on `dynamic-data-mapping-form-field-type` module. There are some snapshot test failing.  After this, you can run `yarn test -u` to update those failing tests and make a push force on this branch. 
Please, if you have any question let me know.
Thanks!

**Pull request closed without merging**
