### PR TITLE
LPD-22634 Deleted form entries are shown in "Entries" tab

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://liferay.atlassian.net/browse/LPD-22634

### CODE REVIEW

**Review by marcelabc — APPROVED** [review]
LGTM 🎉
One question: I saw that you only edited the Text implementation. Do we need to worry about the other implementations?

**Comment by carolmariaabb** [comment]
@marcelabc I tested with the other fields too.

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
