### PR TITLE
LPS-130164 Create masks for decimal numeric type fields

### PR DESCRIPTION
**Pull request by alinedoleron**
Ticket: [LPS-134560](https://issues.liferay.com/browse/LPS-134560)

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:stop

**Comment by alinedoleron** [comment]
ci:test:relevant

**Review by miltonmc — APPROVED** [review]

**Comment by miltonmc** [comment]
ci:forward

**Pull request closed without merging**
