### PR TITLE
LPS-136526 Fix inputNumericMask application for predefinedValue and FormBuilder

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-136526

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Review by miltonmc — APPROVED** [review]
LGTM!

**Comment by miltonmc** [comment]
ci:reevaluate:1327401_221

**Comment by eli-rlima** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hey @danvb112, @marcelabc and @miltonmc,

The 2 Poshi tests reported as failures indeed can be failures because they were reported in the 3 executions of CI. @danvb112, can you please double check?

Thanks in advance.

**Comment by natocesarrego** [comment]
@danvb112, are there tests passing locally on your machine?

**Comment by danvb112** [comment]
@natocesarrego, yes i have tested them now and they 2 passed on my local machine.

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @danvb112, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:reevaluate:1287401_703

**Comment by liferay-forms** [comment]
Hey @danvb112, can you please check if these failures are related to your changes? Thanks

**Comment by miltonmc** [comment]
ci:reevaluate:1287401_703

**Comment by liferay-forms** [comment]
Hey @danvb112, can you please check if these failures are related to your changes? Thanks

**Comment by danvb112** [comment]
ci:reevaluate:1287401_703

**Comment by liferay-forms** [comment]
Hey @danvb112, can you please check if these failures are related to your changes? Thanks

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:forward

**Comment by liferay-forms** [comment]
ci:test:relevant

**Pull request closed without merging**
