### PR TITLE
LPS-156001 Date Field translation cannot be saved with empty value

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
Dear Team,

It appears the automated tests passed.
Please let me know if the review process can move forward.

Thank you and best regards,
István

**Review by rodrigopaulino — APPROVED** [review]
LGTM!

**Comment by rodrigopaulino** [comment]
ci:forward

**Pull request closed without merging**
