### PR TITLE
[TS] LPS-166896 In a webcontent numeric field, when using Spanish language, it is not possible to enter a negative decimal number that starts with -0,xxx

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-166896

In a webcontent numeric field, when using Spanish language, it is not possible to enter a negative decimal number that starts with -0,xxx

If you enter any negative number with that format, it will lose the negative sign. For example: -0,5 => 0,5
The error is not reproduced with negative decimal numbers that starts with -1,xxx or smaller

**Root cause:**

- The com.liferay.dynamic.data.mapping.storage.constants.FieldConstants.getSerializable method handles decimal numbers with the following decimal separators: ".", "," and "٫"
- In some situations this method splits the number in two: integer part and decimal part.
    Once it is split, the number is concatenated again with the correct decimal separator.
- But if the integer part of the number is zero, it loses the sign, as zero has no sign.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Hi @marcelabc 

Do you have any updates about this PR?

Thank you

**Comment by jorgediaz-lr** [comment]
Posted a message in slack https://liferay.slack.com/archives/C031U3B3EUW/p1667930740643129

**Comment by marcelabc** [comment]
Hi @jorgediaz-lr, my apologies for the delay!

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Thank you!

**Comment by marcelabc** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
