### PR TITLE
LPS-131826 The created Structure appears in its own Fieldset list

### PR DESCRIPTION
**Pull request by miltonmc**
**Ticket**: [LPS-131826](https://issues.liferay.com/browse/LPS-131826)

### CODE REVIEW

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:relevant

**Review by interaminense — APPROVED** [review]
LGTM!

**Comment by miltonmc** [comment]
ci:reevaluate:1167401_8329

**Comment by miltonmc** [comment]
ci:reevaluate:1167401_8329

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:forward

**Pull request closed without merging**
