### PR TITLE
LPS-123793 LPS-124147 LPS-123797 LPS-124146 LPS-124149 Adding the new Forms/Data Engine architecture and data flow foundation with removal of Metal.js from the Forms product

### PR DESCRIPTION
**Pull request by matuzalemsteles**
Well, this is a big change that still needs to be adjusted before going or starting to run the CI, so in draft. I will also clarify the main changes that were made in this PR and what it affects, probably working on it tomorrow with a more complete description. The vast majority of commits contain a description of the things that have been done and the reasons are a good start to understand the reason and the final objective that tells a story of the work done.

This PR also includes the main tickets that are part of the whole change and they are highly coupled that prevent I from sending the master alone without compromising the codebase or breaking something.

- LPS-123793
- LPS-124147
- LPS-123797
- LPS-124146
- LPS-124149 (From #140)

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:stop

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:stop

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
Adding a follow-up status for this PR related to CI failures. More than 17 commits (473ccafc2fa5492dbe4f283738a805899332e3c7...00668a63de604e0c7da0e51f63ce4f3b5036b2df) were also added that corrected other problems that the CI can detect and others were manual tests.

Some flaws are always persisting in the same **Form#PUBLISH_FORM_PUBLIC_URL** selector and pass locally, so let's take a closer look to find out what's going on.

- ⚠️ LocalFile.Forms#SubmitFormWithUploadFieldAsNewUser
- ⚠️ LocalFile.FormRules#ViewPredefinedValueCanBeUsedToRequireAnotherField
- ⚠️ LocalFile.FormRules#UseIsNotEmptyRuleToShowField
- ⚠️ LocalFile.Forms#UploadFileWithInvalidSizeAsGuestUser

The other flaws probably need correction in the code, looking at them.

- [ ] ⚠️ LocalFile.Forms#AddElementSetsWithTranslation (Considered a little flaky, in the CI it breaks in one step but local it passes)
- [ ] 🚨 LocalFile.Forms#ChangeFieldType
- [ ] 🚨 LocalFile.Forms#ViewFieldValidationIsNotBypassedWhenNextButtonIsHitTwice
- [ ] 🚨 LocalFile.Forms#EditTranslatedGridField

There are still some bugs that we discovered by testing manually because there are no poshi tests for them, which are more related to Field Group and Drag Preview.

- [ ] 🚨 Drag Preview looks like CSS is not being applied correctly after rebase
- [ ] 🚨 When saving a Field Group, the data returns `rows` as an object containing `JSONArray: []`
- [ ] 🚨 When moving a Field over another field to create a Field Group it does not seem to allow it but it is possible to do this when adding a new field, this in Forms.

I'm also going to rebase with today's master, there seem to be new things coming in that are giving rise to conflicts.

**Comment by diegonvs** [comment]
* LocalFile.Forms#ViewSaveNotification :white_check_mark: Fixed

* LocalFile.Forms#EditAllFormFieldsTypesUsedBySystemSettings :warning: :white_check_mark: (When running the tests locally I didn't identify any errors) Taking a look on the local generated POSHI report the test didn't fail.

* LocalFile.Forms#SubmitFormWithCustomTextContainingValidation :white_check_mark: Fixed

* LocalFile.Forms#SelectAndRemoveMultipleOptionsInSelectFromListField :warning: :white_check_mark: (When running the tests locally I didn't identify any errors) Taking a look on the local generated POSHI report the test didn't fail.

* LocalFile.Forms#SubmitFormWithRequiredImageField :white_check_mark: :warning:  Flaky

* LocalFile.Forms#SubmitFormWithRequiredRepeatingTextField  :white_check_mark: :warning: Flaky

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
Adding a follow-up status for this PR related to CI failures. Previous round https://github.com/liferay-forms/liferay-portal/pull/142#issuecomment-795725130

Some flaws are always persisting in the same **Form#PUBLISH_FORM_PUBLIC_URL** selector and pass locally, so let's take a closer look to find out what's going on.

- ⚠️ LocalFile.FormsJumpToPage#ViewPagesAfterJump
- ⚠️ LocalFile.FormRules#ConfigureAutofillRule
- ⚠️ LocalFile.Forms#ViewDefaultFieldNamesWithPunctuationCharacters 
- ⚠️ LocalFile.Forms#SubmitFormWithUploadFieldAsNewUser

Some tests that need to be analyzed are possible bugs.

- [ ]  🚨 LocalFile.Forms#ChangeFieldType
- [ ]  🚨 LocalFile.Forms#EditTranslatedGridField

Some exploratory bugs that we found and must be fixed before sending.

- [ ]  🚨 When saving a Field Group, the data returns rows as an object containing `JSONArray: []`
- [ ]  🚨 We will have to revert the change from https://github.com/liferay/liferay-portal/commit/c37d885f93c2a4d0ddd4eae81c4f869fd72e6498, the best for that has to be done in EditorVariant. Reducers or events must be pure functions and must not contain edge cases or more than one responsibility.

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
- Round 1 https://github.com/liferay-forms/liferay-portal/pull/142#issuecomment-795725130
- Round 2 https://github.com/liferay-forms/liferay-portal/pull/142#issuecomment-795725130

Adding a follow-up status for this PR related to CI failures. Previous round

Some flaws are always persisting in the same **Form#PUBLISH_FORM_PUBLIC_URL** selector and pass locally, so let's take a closer look to find out what's going on.

- ⚠️ LocalFile.Forms#SelectAndRemoveMultipleOptionsInSelectFromListField
- ⚠️ LocalFile.FormRules#ViewPredefinedValueCanBeUsedToRequireAnotherField

Some tests that need to be analyzed are possible bugs.

- [x]  🚨 LocalFile.Forms#ChangeFieldType
- [x]  🚨 LocalFile.Forms#EditTranslatedGridField

Some exploratory bugs that we found and must be fixed before sending.

- [ ]  🚨 We will have to revert the change from https://github.com/liferay/liferay-portal/commit/c37d885f93c2a4d0ddd4eae81c4f869fd72e6498, the best for that has to be done in EditorVariant. Reducers or events must be pure functions and must not contain edge cases or more than one responsibility. (Maybe send in another follow-up PR)

💆‍♂️ Some conflicts to resolve. 

- [x] 7edbf54a963172eb35388c01b0fc2bd8081cf277...4dcaed5e9bac70ac92687f1d6fc735c2ed4d2b31

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
- Round 1 https://github.com/liferay-forms/liferay-portal/pull/142#issuecomment-795725130
- Round 2 https://github.com/liferay-forms/liferay-portal/pull/142#issuecomment-795725130
- Round 3 https://github.com/liferay-forms/liferay-portal/pull/142#issuecomment-799877519

Adding a follow-up status for this PR related to CI failures. 

Some flaws are always persisting in the same **Form#PUBLISH_FORM_PUBLIC_URL** selector and pass locally, so let's take a closer look to find out what's going on.

- ⚠️ LocalFile.Forms#SubmitFormWithUploadField
- ⚠️ LocalFile.Forms#SelectAndRemoveMultipleOptionsInSelectFromListField
- ⚠️ LocalFile.FormRules#ConfigureAutofillRule
- ⚠️ LocalFile.Forms#PreviewAndPublishForm

Other flaky or unrelated tests.

- LocalFile.Forms#SubmitFormAfterEditingFields
- LocalFile.Forms#EditAllFormFieldNames

**Submit in another follow-up PR...**

- 🚨 We will have to revert the change from https://github.com/liferay/liferay-portal/commit/c37d885f93c2a4d0ddd4eae81c4f869fd72e6498, the best for that has to be done in EditorVariant. Reducers or events must be pure functions and must not contain edge cases or more than one responsibility.

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
I'm on 

LocalFile.Forms#SubmitFormAfterEditingFields
LocalFile.Forms#SubmitFormWithAllFieldTypesAndThreePages

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
When running locally,

* LocalFile.Forms#SubmitFormAfterEditingFields
* LocalFile.Forms#SubmitFormWithAllFieldTypesAndThreePages

It seems very flaky because I got an "Out of memory" error intermittently or suddenly stops on the new Site creation and I got only an error that can be helpful when setting a predefined value for the paragraph field but I can't reproduce it anymore during the tests or running exploratory

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:forward

**Pull request closed without merging**
