### PR TITLE
[TECHNICAL SUPPORT] LPS-188749 DDM's repeatable field loses localized data when created on non default locale

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,

[LPS-188749](https://liferay.atlassian.net/browse/LPS-188749)

We can have empty transaltions and we can repeat a field on a non default locale. Currently the updateLocalizationMap method did not take this into account, so I had to update it.
This issue is reproducible on master due to dynamic data list that still uses DDM under the hood.

Please review my changes

Thanks,

### CODE REVIEW

**Comment by NemethNorbert** [comment]
Hey @liferay-forms ,

Can you follow up with the review on this PR?

Thanks,

**Review by rebsilva — APPROVED** [review]
Hi @NemethNorbert, LGTM! 

I've tested on master (the DDL part, because the web content uses data engine now) that is the focus of this PR, but when sending this no 7.2 and 7.3 I suggest testing it a lot to make sure everything is working as expected. Thanks!

**Comment by rebsilva** [comment]
Waiting for the QA team to check the tests failing to forward.

**Comment by rebsilva** [comment]
ci:forward

**Pull request closed without merging**
