### PR TITLE
LPS-176140 Forms input accessibility improvements

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Read https://issues.liferay.com/browse/LPS-176140 for steps and more details

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:forms

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:forms

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
