### PR TITLE
LPS-124039 | LPS-124042 Small tweaks on Calculator

### PR DESCRIPTION
**Pull request by diegonvs**
Related Issues:

* https://issues.liferay.com/browse/LPS-124042
* https://issues.liferay.com/browse/LPS-124039

/cc @cvanut

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
I'm not sure if this PR will fix

* https://issues.liferay.com/browse/LPS-124279
* https://issues.liferay.com/browse/LPS-124273

@cvanut, could you validate if those bugs still being reproduced when this PR got merged?

**Comment by diegonvs** [comment]
ci:forward

**Pull request closed without merging**
