### PR TITLE
LPS-150392

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related Issue: https://issues.liferay.com/browse/LPS-150392

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Review by rodrigopaulino — APPROVED** [review]

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by felix3508** [comment]
@carolmariaabb Looks like this issue also happened on 7.3. See [here](https://liferay.atlassian.net/browse/LPS-150392?focusedCommentId=2185065). Could you please backport it to 7.3.x? Thank you!

**Pull request closed without merging**
