### PR TITLE
LPS-136519 Split Numeric into input and append

### PR DESCRIPTION
**Pull request by miltonmc**
### Related Tickets
- [LPS-136519](https://issues.liferay.com/browse/LPS-136519) Letters on keyboard are inputting wrong values when using an input mask with a suffix in a decimal number field
- [LPS-136523](https://issues.liferay.com/browse/LPS-136523) When using an number as prefix of the input mask on decimal the prefix is being saved with the input value
- [LPS-136524](https://issues.liferay.com/browse/LPS-136524) The input mask on decimal is not updating on the form builder when the user is editing
- [LPS-136534](https://issues.liferay.com/browse/LPS-136534) The input mask on decimal is not working correctly when the admin is setting a dot or comma as a prefix or suffix

### CODE REVIEW

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:reevaluate:1287401_600

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:stop

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:forward

**Pull request closed without merging**
