### PR TITLE
LPS-90833 fixed the bug by creating a new class for the label tag and adding a css rule

### PR DESCRIPTION
**Pull request by devpedrotavares**
[LPS](https://issues.liferay.com/browse/LPS-90833) - The solution was to add padding to the field’s label when the field is marked as repeatable. For that, I created a className “repeatable” that is assigned to the ‘label’ tag only when the ‘repeatable’ argument is true. In addition, I added a css rule that targets the label only when it has that className.

### CODE REVIEW

**Comment by devpedrotavares** [comment]
ci:test:sf

**Comment by devpedrotavares** [comment]
ci:test:sf

**Comment by devpedrotavares** [comment]
ci:test:sf

**Comment by devpedrotavares** [comment]
ci:test:sf

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:reevaluate:1377401_5841

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by alinedoleron** [comment]
ci:forward

**Comment by alinedoleron** [comment]
Hi @devpedrotavares! Please, could you update the commit message to be in the correct format?
`LPS-xxxxxx Type the message`

Thanks!

**Comment by devpedrotavares** [comment]
> Hi @devpedrotavares! Please, could you update the commit message to be in the correct format? `LPS-xxxxxx Type the message`
> 
> Thanks!

Done!

**Comment by alinedoleron** [comment]
ci:forward

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
