### PR TITLE
LPS-202852 Update field when storageTypes field changes

### PR DESCRIPTION
**Pull request by alinedoleron**
Ticket: https://liferay.atlassian.net/browse/LPS-202852

[storagetype.webm](https://github.com/liferay-forms/liferay-portal/assets/26491796/48bb25d4-7736-4079-982f-426fe3b91c30)

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:reevaluate:1327401_2970

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
