### PR TITLE
[TS] LPS-154203 The first day of week in the Datepicker must follow the locale configuration

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-154203

Set the firstDayOfWeek parameter of ClayDatePicker using the locale information

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:stop

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:reevaluate:1337401_1871

**Comment by carolmariaabb** [comment]
ci:foward

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by jorgediaz-lr** [comment]
ci:forward

**Comment by jorgediaz-lr** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:reevaluate:1317401_3539

**Comment by jorgediaz-lr** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:reevaluate:1317401_3539

**Comment by carolmariaabb** [comment]
ci:reevaluate:1257401_2899

**Comment by carolmariaabb** [comment]
ci:reevaluate:1387401_629

**Comment by jorgediaz-lr** [comment]
ci:reevaluate:1387401_629

**Comment by carolmariaabb** [comment]
ci:reevaluate:1257401_2899

**Comment by jorgediaz-lr** [comment]
Hi @carolmariaabb 

The CI test error `org.junit.ComparisonFailure: expected:<\{life,content,osgi,[social,liferay],open\}> but was:<\{life,content,osgi,[liferay,social],open\}>` is unrelated to my changes, I have detected the same error in other unrelated PRs and my changes don't apply to the search functionality.

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
