### PR TITLE
LPD-15505 Take into account localizable fields in the translation label of the language selector

### PR DESCRIPTION
**Pull request by veroglez**
Hi guys!

According to this epic https://liferay.atlassian.net/browse/LPD-10755, when editing Web Content we must take into account the non-localized fields in the new language selector. 

Screen Shot 2024-01-26 at 4 04 56 PM

So from Echo we have made several improvments to achieve this goal. The commits to review in this PR are the following:

- [x] d555ae7952e63057a9dfc90fd890e1698c05acc9: the `data-field-name` and `data-languageid` attributes have been added to hidden inputs to be taken into account in the translation label of the language selector.
- [x] https://github.com/liferay-forms/liferay-portal/commit/27094877f62b89bba102a244a4286efd9e195a59. We need that the language that is being edited has a hidden input.
- [x] https://github.com/liferay-forms/liferay-portal/commit/f3e0d5233de1811abf3324cf7e5bd7a9705ab970.  The event `inputLocalized:updateTranslationStatus` is fired to know when the translation label has to be updated when the hidden inputs change
- [x] https://github.com/liferay-forms/liferay-portal/commit/4e36d1eb685db181fe0ba1b8a8227d4b195116d7. The attribute `data-ddm-localizable-field` is added to the field if the field is localizable.
- [x] https://github.com/liferay-forms/liferay-portal/commit/632ec1564d993cf27f942fe3d032a53c42564a39. Tests has been added to check the previous changes.

The Feature Flag to test it is `feature.flag.LPS-114700=true`

The rest of the commits are being reviewed by the corresponding teams. Let me know if you have any questions. Thanks in advance! :smile:

### CODE REVIEW

**Comment by veroglez** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
Hey @danvb112 
Could you review this PR, please? :smile:

**Review by danvb112 — CHANGES_REQUESTED** [review]
Hey @veroglez, great job on this PR, your code looks good to me! 

Just one question, should your logic consider repeatable fields? I found some bugs involving this, for example the number of fields not being updated when we add a repeatable, I wll not block your code because of it, but I want to know :

1. If this is a product decision or really a bug.

2. In case of a bug, if you fix that bug here or open a new ticket to work on later?

I will put the change request in the PR and wait for your response.

**Comment by veroglez** [comment]
> Hey @veroglez, great job on this PR, your code looks good to me!
> 
> Just one question, should your logic consider repeatable fields? I found some bugs involving this, for example the number of fields not being updated when we add a repeatable, I wll not block your code because of it, but I want to know :
> 
> 1. If this is a product decision or really a bug.
> 2. In case of a bug, if you fix that bug here or open a new ticket to work on later?
> 
> I will put the change request in the PR and wait for your response.

Hi @danvb112, thanks for you review and feedback! Yes, I totally agree with you, it's a bug, the repeteable fields should be cosidered. I have added a commit (2430d5c5a731c63cc6ff6e6e3e24a2df77829708) with the solution for this, could you take a look at it?

**Comment by marcelabc** [comment]
ci:test:sf

**Review by danvb112 — CHANGES_REQUESTED** [review]
Hey @veroglez, I'm afraid the bug is still happening, I'll send you a video on slack to send it in better quality

**Comment by veroglez** [comment]
> Hey @veroglez, I'm afraid the bug is still happening, I'll send you a video on slack to send it in better quality

Updated! I've just changed the way translations are calculated here cbd577c9a6f9ebd273d6e07b4b5b1b49d4fbfb0d

**Comment by marcelabc** [comment]
ci:test:sf

**Review by danvb112 — APPROVED** [review]
LGTM! Great job @veroglez :tada: 

I will run the `forms` and `data-engine` test suites to see if everything is ok

**Comment by danvb112** [comment]
ci:test:forms

**Comment by danvb112** [comment]
ci:test:data-engine

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:report:2534063098

**Comment by marcelabc** [comment]
Based on the CSV report generated by ci:test:data-engine, there are no unique failures.

**Comment by marcelabc** [comment]
ci:report:2534119891

**Comment by marcelabc** [comment]
Based on the CSV report generated by ci:test:forms, there are no unique failures.

**Comment by marcelabc** [comment]
ci:report:2534147213

**Comment by marcelabc** [comment]
Based on the CSV report generated by ci:test:relevant, there are 2 unique failures:
- com.liferay.dynamic.data.mapping.change.tracking.test.DDMTemplateLinkTableReferenceDefinitionTest
- com.liferay.dynamic.data.mapping.change.tracking.test.DDMStructureLinkTableReferenceDefinitionTest

However, I analyzed them manually and there is no unique failure.

**Comment by marcelabc** [comment]
ci:forward:force

**Comment by veroglez** [comment]
Resent here https://github.com/brianchandotcom/liferay-portal/pull/146973

**Pull request closed without merging**
