### PR TITLE
LPS-146105 check if the rawDate state is empty

### PR DESCRIPTION
**Pull request by larissacribeiro**
**Related Issue**: [LPS-146105](https://issues.liferay.com/browse/LPS-146105)

### CODE REVIEW

**Comment by larissacribeiro** [comment]
ci:test:sf

**Comment by larissacribeiro** [comment]
ci:test:relevant

**Comment by larissacribeiro** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Pull request closed without merging**
