### PR TITLE
LPS-179505 Unexpected "Description" subtitle when creating a web content

### PR DESCRIPTION
**Pull request by larissacribeiro**
Related Issue: [LPS-179505](https://issues.liferay.com/browse/LPS-179505)

### CODE REVIEW

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by larissacribeiro** [comment]
Hey @alinedoleron, I'm gonna have to rerun the tests because now I saw that the portletId of a published form is different from the page where it is created. In order for the solution to work I should use the web content portlet instead, as you also suggested! Now it's working fine

**Comment by larissacribeiro** [comment]
ci:test:relevant

**Comment by larissacribeiro** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by alinedoleron** [comment]
ci:forward

**Comment by alinedoleron** [comment]
> Hi @alinedoleron and @carolmariaabb, I'm gonna have to rerun the tests because I saw that the portletId of a published form is different from the page where it is created, so the second description wasn't appearing in the published page. In order for the solution to work I should use the web content portlet instead, as you also suggested! Now it's working fine

Thanks for the details and the fix, @larissacribeiro!

**Pull request closed without merging**
