### PR TITLE
LPS-202991 Remove double borders from fields panel

### PR DESCRIPTION
**Pull request by p2kmgcl**
Hi!

This PR has been discussed here: https://liferay.slack.com/archives/CL8R04Z7X/p1701341841111579

The general idea is to update the `liferay-data-engine:data-layout-renderer` so it allows optionally removing the outer clay:sheet.

### CODE REVIEW

**Comment by marcelabc** [comment]
Hey @p2kmgcl, how are you doing?
Did you run the command `gw buildTaglib` or do the changes manually?
When we want to add a new property to a taglib, we must add the property in the taglibFileName.xml and run the command `gw buildTaglib`. In this case, you should add this property in `liferay-data-engine.xml` and run the command.

If you did it manually, can you do the process by running the command, please?

**Comment by p2kmgcl** [comment]
Hi @marcelabc! Thanks so much for your help. I did update the taglib manually, didn't know about the buildTagLib command :sweat_smile: 

But I already did with the command and split the commits a bit more. Hope it is fine now :smile:

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:data-engine

**Comment by carolmariaabb** [comment]
@p2kmgcl could you please fix the semantic versioning?

1. [testSemanticVersioning[/apps/data-engine/data-engine-api]](https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/690630//testReport/com.liferay.semantic.versioning/SemanticVersioningTest/testSemanticVersioning__apps_data_engine_data_engine_api_)
2. [testSemanticVersioning[/apps/data-engine/data-engine-taglib]](https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/690630//testReport/com.liferay.semantic.versioning/SemanticVersioningTest/testSemanticVersioning__apps_data_engine_data_engine_taglib_)

**Comment by ealonso** [comment]
Hey @carolmariaabb,

Thanks you very much for taking care of it!!! ❤️

**Pull request closed without merging**
