### PR TITLE
LPS-154627 Improve Forms Accessibility

### PR DESCRIPTION
**Pull request by alinedoleron**
This PR just fixed the snapshot tested related to this https://github.com/liferay-forms/liferay-portal/pull/2054#issue-1482407801

Ticket: https://issues.liferay.com/browse/LPS-154627

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
QA team will update the broken paths.

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:forms

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
This PR is on hold, for now, because after QA analysis it was found that some paths outside Forms context need to be updated.

**Comment by carolmariaabb** [comment]
@alinedoleron I'll close this PR for now. Is there anything we can do on our side?

**Comment by carolmariaabb** [comment]
ci:close

**Pull request closed without merging**
