### PR TITLE
LPD-35285 Add verification to avoid security vulnerability

### PR DESCRIPTION
**Pull request by marcelabc**
## Jira Link
- https://liferay.atlassian.net/browse/LPD-35285

## Additional Information
- The related [LPP](https://liferay.atlassian.net/browse/LPP-55408) is marked as **SDH**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:forms

**Comment by icgsbr** [comment]
Hi @marcelabc !

It appears that the issues found on the upgrade suite aren't related to the changes contained in this PR. Since the ticket is an SDH, could I deliver it to the client? Furthermore, do you find that we can forward this to Bchan now?

Best regards.

**Comment by marcelabc** [comment]
ci:report:79319020

**Comment by marcelabc** [comment]
I manually analyzed the failures, and there is no unique failure.

**Pull request closed without merging**
