### PR TITLE
LPS-196935 Show deprecated warning

### PR DESCRIPTION
**Pull request by seltong**
Related: [LPS-196935](https://liferay.atlassian.net/browse/LPS-196935)

### CODE REVIEW

**Comment by seltong** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:forward

**Pull request closed without merging**
