### PR TITLE
LPS-171487 Unable to delete numeric field value in translations

### PR DESCRIPTION
**Pull request by Manda-vit**
related issue: https://issues.liferay.com/browse/LPS-171487

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]

**Comment by Manda-vit** [comment]
ci:test:stable

**Comment by Manda-vit** [comment]
ci:test:relevant

**Comment by Manda-vit** [comment]
ci:test:forms

**Comment by Manda-vit** [comment]
liferay/ci:test:relevant

**Comment by Manda-vit** [comment]
liferay/ci:test:forms

**Comment by Manda-vit** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:forward

**Pull request closed without merging**
