### PR TITLE
[TS] LPS-174138 | master

### PR DESCRIPTION
**Pull request by samanzanedo**
Hi team,

This is an additional commit for PR #2120

Customer data showed us that '_valuesJSONObject_' can be null when it is recovered from fields like radio buttons.

So I added a check of null object (and thus avoid, again, a NPE)

cc/ @carolmariaabb 

Reference: 
https://issues.liferay.com/browse/LPS-174138

### CODE REVIEW

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by carolmariaabb** [comment]
@samanzanedo could you please fix the SF erro?

> At least one commit message is missing a reference to a required JIRA project: BLADE, CLDSVCS, COMMERCE, FACES, IDE, ISSITES, LCD, LHC, LOOP, LPS, LRAC, LRCI, LRDOCS, LRIS, LRQA, OAUTH2, POSHI, RELEASE, SYNC, TR. Please verify that the JIRA project keys are specifiedin ci.properties in the liferay-portal repository.

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by samanzanedo** [comment]
@carolmariaabb 

I was trying to remove the commit 34a234727bd9942ac66b642912408bf6811cc0de but I do not how to do it.

I think the best option is to resend you the PR. Do you agree?

Thanks!

**Comment by carolmariaabb** [comment]
@samanzanedo no problem, feel free to resend

**Pull request closed without merging**
