### PR TITLE
LPS-150774 Remove Feature Flag for LPS-146889

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issue: https://issues.liferay.com/browse/LPS-150774

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
Hey @rebsilva, can you please fix the source formatter issues and resend? Thanks

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Review by rodrigopaulino — APPROVED** [review]
Awesome! Great work, @rebsilva! 🎉

**Comment by rodrigopaulino** [comment]
@rebsilva, do you need Milton's review on this? If no, feel free to add the "Good to Go" label on this PR. 😄

**Review by miltonmc — APPROVED** [review]
LGTM!

**Comment by liferay-forms** [comment]
Hey @rebsilva, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
Hey @rebsilva, can you please check if these failures are related to your changes? Thanks

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @rebsilva, can you please check if these failures are related to your changes? Thanks

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @rebsilva, can you please check if these failures are related to your changes? Thanks

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @rebsilva, can you please check if these failures are related to your changes? Thanks

**Comment by rodrigopaulino** [comment]
@rebsilva, let's hold off this PR until we get this [LPS-151024](https://issues.liferay.com/browse/LPS-151024) fixed. It's a very important fix for the new feature.

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hey @rebsilva, can you please fix the source formatter issues and resend? Thanks

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @rebsilva, can you please check if these failures are related to your changes? Thanks

**Comment by rodrigopaulino** [comment]
Hi, @rebsilva. As agreed, I'm closing this and we'll finish on this later. Please make sure to comment this WIP on the Jira ticket. Thanks for your work.

**Comment by rodrigopaulino** [comment]
ci:close

**Pull request closed without merging**
