### PR TITLE
LPS-167798 HR_160 The close button aren't being announced properly

### PR DESCRIPTION
**Pull request by larissacribeiro**
Related Issue: [LPS-167798](https://issues.liferay.com/browse/LPS-167798)

### CODE REVIEW

**Comment by larissacribeiro** [comment]
Hey @alinedoleron! I saw that there was a snapshot failing, so I took the liberty of updating it in advance. 😄

**Comment by larissacribeiro** [comment]
ci:test:relevant

**Comment by larissacribeiro** [comment]
ci:test:forms

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
