### PR TITLE
LPS-143113

### PR DESCRIPTION
**Pull request by rodrigopaulino**
I'm pushing this deletion so we can get rid of the blockers, but I'm currently working on a permanent solution that will come later.

Related Issue: https://issues.liferay.com/browse/LPS-143113

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
