### PR TITLE
LPD-25871 Add dir property on InputComponent to fix the input direction when the translation languague is right to left oriented

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issue: https://liferay.atlassian.net/browse/LPD-25871

### CODE REVIEW

**Review by igor-franca — CHANGES_REQUESTED** [review]
Everything is fine with the code, you just need to make an adjustment to the unit tests to deal with `Liferay.Language.direction`

**Review by igor-franca — APPROVED** [review]
Test results after push force:

screenshot-1717773110

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by cgmonte** [comment]
ci:test:forms

**Comment by cgmonte** [comment]
ci:test:data-engine

**Comment by cgmonte** [comment]
ci:test:relevant

**Comment by cgmonte** [comment]
ci:test:echo

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:forward

**Pull request closed without merging**
