### PR TITLE
LPS-157041 Change array for double numeric fields to Number type

### PR DESCRIPTION
**Pull request by mbowerman**
https://issues.liferay.com/browse/LPS-157041

/cc @javalosjr96

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Review by rodrigopaulino — APPROVED** [review]
LGTM!

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
ci:forward

**Pull request closed without merging**
