### PR TITLE
LPS-203465 Remove 'for' attribute on forms from fields with type select to respect accessibility rules

### PR DESCRIPTION
**Pull request by rebsilva**
related issue: https://liferay.atlassian.net/browse/LPS-203465

i had to remove the `for` attribute on forms from fields with type `select` to follow the recommendations of [this comment](https://liferay.atlassian.net/browse/LPS-203465?focusedCommentId=2542849). it was oriented to us that `select from list` fields should have the `aria-labelledby` approach instead, which was already implemented but it needed to remove the `for` property to be fully correct.

this solution is a follow-up of https://github.com/liferay/liferay-portal/commit/a157dff3138765785546865bdc22a56d31f95b8f

### CODE REVIEW

**Comment by igor-franca** [comment]
Starting the review

**Review by igor-franca — APPROVED** [review]

**Comment by igor-franca** [comment]
ci:test:relevant

**Comment by igor-franca** [comment]
ci:test:forms

**Comment by rebsilva** [comment]
the tests failing seem related, i'm taking a look

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:forms

**Comment by rebsilva** [comment]
ci:test:data-engine

**Comment by rebsilva** [comment]
ci:forward:force

**Pull request closed without merging**
