### PR TITLE
[Technical Support] MASTER - LPS-122339

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related Issue: https://issues.liferay.com/browse/LPS-122339

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Amazing pull, @rodrigopaulino! 😄 👏 Great SF. 😉 

leonardo di caprio

**Comment by natocesarrego** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
Thanks, @natocesarrego. Thanks also to @rijema for his contributions. :D

**Comment by rijema** [comment]
Thank you, @rodrigopaulino!

**Pull request closed without merging**
