### PR TITLE
LPS-142133 Remove feature flag to enable/disable the decimal places for Numeric fields

### PR DESCRIPTION
**Pull request by alinedoleron**
Related Issue: https://issues.liferay.com/browse/LPS-142133

- LPS-142133 Revert "LPS-141791 Create feature flag for Numeric decimal places property"
- LPS-142133 Revert "LPS-141891 Mock feature flag in the test"
- LPS-142133 Revert "LPS-141891 Remove test related to decimal places for now, since it is under feature flag"

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @alinedoleron, can you please check if these failures are related to your changes? Thanks

**Review by miltonmc — APPROVED** [review]
@alinedoleron, the frontend looks great!

@carolmariaabb can you review the backend side, please?

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:reevaluate:1327401_1037

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @alinedoleron, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @alinedoleron, can you please check if these failures are related to your changes? Thanks

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @alinedoleron, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @alinedoleron, can you please check if these failures are related to your changes? Thanks

**Comment by marcelabc** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @alinedoleron, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by liferay-forms** [comment]
ci:test:relevant

**Pull request closed without merging**
