### PR TITLE
LPS-153881

### PR DESCRIPTION
**Pull request by alinedoleron**
Related ticket:

- https://issues.liferay.com/browse/LPS-153881
- https://issues.liferay.com/browse/LPS-154214

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
Hi @guilhermedcamacho, please, do you know how to solve this failures?

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
> Hi @guilhermedcamacho, please, could you take a look on this failures?

It was a semantic versioning problem, please rebase from upstream and run baseline command on object-api module. Thanks!

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Re-sending in #1725

**Comment by guilhermedcamacho** [comment]
ci:close

**Pull request closed without merging**
