### PR TITLE
LPS-128444

### PR DESCRIPTION
**Pull request by cleydyr**
This is a revert for LPS-114936. LPS-114936 was supposed to fix a double request, but I couldn't reproduce the double request after all after reverting LPS-114936 by putting a breakpoint in com.liferay.dynamic.data.mapping.data.provider.internal.DDMDataProviderInvokerImpl#156

Also, limiting the maximum number of threads to 1 will cause any concurrent additional requests to be rejected, which is undesirable.

### CODE REVIEW

**Comment by natocesarrego** [comment]
Hi @cleydyr,

Your fix makes sense to me, although I'm afraid that this pull can reintroduce the issue reported on LPS-114936. :grimacing: Do you mind to talk to Lino in order to find out the steps he has performed to reproduce the LPS-114936?

Thanks in advance.

**Comment by cleydyr** [comment]
Sure, Renatonho. I'd already talked to @linolaoj via Slack. He said it was no problem to revert his commit.

**Comment by cleydyr** [comment]
@natocesarrego, I couldn't reproduce it at all, as I stated in the initial comment for this issue. So maybe it was just a delay in the logs that presented two messages within a short period of time, but not due to two different requests. Or something changed on the frontend logic that made the source of double requests to disappear.

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
