### PR TITLE
LPS-121444 Allow set alphabetical order in SelectDDMFormField #5

### PR DESCRIPTION
**Pull request by robertoDiaz**
Related Issue: https://issues.liferay.com/browse/LPS-121444

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hey @robertoDiaz, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hi @robertoDiaz, since last week, we've added a bot on `liferay-forms` which already trigger CI commands, please see [here](https://github.com/liferay-forms/liferay-portal/pull/7#issuecomment-700754589), therefore you don't need to trigger them anymore. 😉 

Thanks.

**Comment by liferay-forms** [comment]
Hey @robertoDiaz, can you please check if these failures are related to your changes? Thanks

**Comment by robertoDiaz** [comment]
Hi @natocesarrego 

It seems that the form is taking a while to be loaded. I could not see how my changes could affect this (I'm just adding a new configuration to a field, nothing else)

**Comment by natocesarrego** [comment]
You're right, @robertoDiaz! Thanks for your analysis. 🙂 

@carolmariaabb, is taking care of this pull and will get in touch with you if needed.

Thanks for your contribution. 😄

**Comment by carolmariaabb** [comment]
Hi @robertoDiaz, 

I asked @cvanut to evaluate this PR and perform the necessary tests.

**Comment by carolmariaabb** [comment]
Hi @robertoDiaz,

We have the following updates regarding this PR:

@cvanut is working on creating test scenarios. When he's finished, he'll send it to me so I can perform the tests.

In addition, the team discussed and decided to treat this PR as a Story and not a Bug. Therefore, we will change the type of ticket or even create a new one, if necessary.

If you have any concerns, please let us know.

Thanks!

**Comment by robertoDiaz** [comment]
I'm ok with treating this as a story. 

BTW, I opened it as bug because i feel it as a UX error.

Anyway, it doesn't affect to the backport. Is it right?

The customer is waiting for this changes.

**Comment by carolmariaabb** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Hi @robertoDiaz,

Actually, because this is an improvement and not a bug, the backport cannot be executed.

I also finished the tests created by Cleyton and one failure was found in the following test: 
`Verify that when enabling the option "Order Options Alphabetically" in a Select from list filled from autofill, the items are shown from A to Z in Form view`. 

If the following rule is created:
`If Field Text is not empty, Autofill Select from List from Data Provider`, the options are not ordered alphabetically in Form view.

**Comment by robertoDiaz** [comment]
> Hi @robertoDiaz,
> 
> Actually, because this is an improvement and not a bug, the backport cannot be executed.
> 
> I also finished the tests created by Cleyton and one failure was found in the following test:
> `Verify that when enabling the option "Order Options Alphabetically" in a Select from list filled from autofill, the items are shown from A to Z in Form view`.
> 
> If the following rule is created:
> `If Field Text is not empty, Autofill Select from List from Data Provider`, the options are not ordered alphabetically in Form view.

Just to clarify, could you explain the second scenario a little bit? I'm not as familiar as you are with Forms and I'd like to fully understand it.

Thanks!

**Comment by carolmariaabb** [comment]
> > Hi @robertoDiaz,
> > Actually, because this is an improvement and not a bug, the backport cannot be executed.
> > I also finished the tests created by Cleyton and one failure was found in the following test:
> > `Verify that when enabling the option "Order Options Alphabetically" in a Select from list filled from autofill, the items are shown from A to Z in Form view`.
> > If the following rule is created:
> > `If Field Text is not empty, Autofill Select from List from Data Provider`, the options are not ordered alphabetically in Form view.
> 
> Just to clarify, could you explain the second scenario a little bit? I'm not as familiar as you are with Forms and I'd like to fully understand it.
> 
> Thanks!

Hi @robertoDiaz ,

I described the steps to reproduce the scenario on the [ticket](https://issues.liferay.com/browse/LPS-121444?focusedCommentId=2287977&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2287977).

Thanks!

**Comment by carolmariaabb** [comment]
Hi @robertoDiaz, I will close this PR for now. Could you resend the updates in a new one when you're finished and update the ticket [LPS-121444](https://issues.liferay.com/browse/LPS-121444)?

Thanks!

**Comment by carolmariaabb** [comment]
Closed [#7](https://github.com/liferay-forms/liferay-portal/pull/7).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
