### PR TITLE
[TS] LPS-148532

### PR DESCRIPTION
**Pull request by holatuwol**
Related Issue: https://issues.liferay.com/browse/LPS-148532

https://issues.liferay.com/browse/LPS-148532

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @holatuwol, can you please check if these failures are related to your changes? Thanks

**Comment by tototrinh** [comment]
> Hey @holatuwol, can you please check if these failures are related to your changes? Thanks

I don't think these failures are related to the changes. Thanks.

> Hi, @holatuwol. Thanks for your pull. Can this change create a vulnerability and open our application to formula injections?
The changes only affect form export to file (CSV, Xls, JSON..). Because of [this](https://github.com/holatuwol/liferay-portal/blob/LPS-148532/portal-impl/src/com/liferay/portal/util/HtmlImpl.java#L525), the break line will be removed. So I changed to unescape which will solve this issue. Thanks.

**Review by rodrigopaulino — APPROVED** [review]
Thanks for answering @tototrinh
I've resent this here due to rebase conflict: https://github.com/liferay-forms/liferay-portal/pull/1578

**Comment by rodrigopaulino** [comment]
ci:close

**Pull request closed without merging**
