### PR TITLE
LPS-191892

### PR DESCRIPTION
**Pull request by icgsbr**
https://liferay.atlassian.net/browse/LPS-191892

Follow up: https://github.com/brianchandotcom/liferay-portal/pull/140950#issuecomment-1726688323

### CODE REVIEW

**Comment by marcelabc** [comment]
Since @rebsilva was the one who reviewed https://github.com/liferay-forms/liferay-portal/pull/2328, so I'm assigning her in this follow-up.

@rebsilva could you help us and review this PR?

**Comment by rebsilva** [comment]
@marcelabc sure! I will take a look :cherry_blossom:

**Review by rebsilva — CHANGES_REQUESTED** [review]
I don't know exactly which part of the code he wanted us to sort and if he will be okay with the `min-height: 851px` being the first one but well, we can try and see what happens.

Also @icgsbr I think it would be better if you squash the commits into one, don't you think?

**Comment by icgsbr** [comment]
@rebsilva done.

**Comment by icgsbr** [comment]
Since he already merged the commit I just had to create another one.

**Comment by icgsbr** [comment]
@rebsilva could you please take a look at this PR again in order to see if everything is okay?

**Review by rebsilva — APPROVED** [review]
LGTM! :tada:

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward:force

**Pull request closed without merging**
