### PR TITLE
LPS-177029 Use ClayPanel instead of a div to create the FieldGroup collapsible structure

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-177029

### CODE REVIEW

**Comment by carolmariaabb** [comment]
I believe the failure in [LocalFile.FormsFieldsGroup#CanBeCollapsed](https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/401857//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FormsFieldsGroup_CanBeCollapsed_) is related to your changes @danvb112

**Review by alinedoleron — CHANGES_REQUESTED** [review]
Hi @danvb112! As Carol said, this test [LocalFile.FormsFieldsGroup#CanBeCollapsed](https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/401857//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FormsFieldsGroup_CanBeCollapsed_) seems to be related.

**Comment by danvb112** [comment]
Thanks @alinedoleron  and @carolmariaabb, I've fixed the test! :smile:

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:forms

**Review by alinedoleron — APPROVED** [review]
LGTM!
We have just to wait the tests to pass.

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
Sent to: https://github.com/brianchandotcom/liferay-portal/pull/131176

**Pull request closed without merging**
