### PR TITLE
LPS-123791 serviceContext's uuid may be null

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @IstvanD, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
@IstvanD, can you please check if the reported failures are related to your pull?

Thanks in advance.

**Comment by IstvanD** [comment]
Hi @natocesarrego they seem to be, however, since the customer issue is closed as won't fix, I suppose we don't need to implement this fix either.
Please let me know what you think.

Thank you and best regards,
István

**Comment by natocesarrego** [comment]
Ok. Makes sense to me. Therefore, I'll close it for now.

Thanks, @IstvanD. 🙂

**Pull request closed without merging**
