### PR TITLE
LPS-134230 Create tests

### PR DESCRIPTION
**Pull request by alinedoleron**
Ticket: [LPS-134226](https://issues.liferay.com/browse/LPS-134226)

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Review by miltonmc — CHANGES_REQUESTED** [review]
Great job!

You create some tests and it was a fantastic initiative! They helped me to identify some issues on previous implementation, related to the use of  `editingLanguageId` that is not been passed down to `ValidationDate`'s children components.

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Review by miltonmc — APPROVED** [review]
LGTM!

**Comment by miltonmc** [comment]
ci:forward

**Pull request closed without merging**
