### PR TITLE
LPS-129583

### PR DESCRIPTION
**Pull request by carolmariaabb**
**Related Issue**: https://issues.liferay.com/browse/LPS-129583

The second commit [108c5d49fd](https://github.com/liferay-forms/liferay-portal/pull/154/commits/108c5d49fdeaa5ddbaa70ab745ca3efe049354fa) was based on the solution made for this similar bug [LPS-127691](https://issues.liferay.com/browse/LPS-127691).

In addition, It was decided to use the **reduced** version instead.

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@carolmariaabb `SubmitFormWithAllFieldTypesAndThreePages` failed again, and an integration test batch is going to time out and abort. Please consider sending directly to Brian.

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
