### PR TITLE
LPD-39147

### PR DESCRIPTION
**Pull request by rijema**
Related fix: https://liferay.atlassian.net/browse/LPD-37921

### CODE REVIEW

**Comment by marcelabc** [comment]
Hey @rebsilva 
Could you review this PR, please? :smile:

**Comment by rebsilva** [comment]
taking a look! :cherry_blossom:

**Review by rebsilva — APPROVED** [review]
LGTM! :cherry_blossom:

**Comment by rebsilva** [comment]
ci:test:playwright

**Comment by rijema** [comment]
No relation between the failures and the fix.

**Comment by rijema** [comment]
ci:forward

**Pull request closed without merging**
