### PR TITLE
LPS-148561 Honor portlet ordering on export

### PR DESCRIPTION
**Pull request by manuelRives**
Related Issue: https://issues.liferay.com/browse/LPS-148561

Coming from pull #1485.

Hi @carolmariaabb, here is the new method.

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Review by carolmariaabb — APPROVED** [review]

**Comment by alinedoleron** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
