### PR TITLE
LPS-142337 Import directly from external module root path

### PR DESCRIPTION
**Pull request by miltonmc**
Related Issue: https://issues.liferay.com/browse/LPS-142337

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
@alinedoleron, since this PR is just changing the way we are importing some dependencies and all the poshi testes are green I'm going to forward it, ok?

**Comment by miltonmc** [comment]
ci:forward

**Pull request closed without merging**
