### PR TITLE
LPS-176503 IllegalArgumentException when adding a translation to a language with variant (ca_ES_VALENCIA or sr_RS_latin)

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-176503

This issue is produced when adding a webcontent translation but the root cause of the issue is produced in data engine code.

Root cause of the issue:

 - Java Locale code uses underscore character in the locale code to separate language, country and variant, for example: `ca_ES_VALENCIA`
 - But in the frontend side, we have to replace the underscore character with the dash, for example: `ca-ES-VALENCIA`
 - The problem here is we don't usually consider there could be two underscore characters, so only the first one is replaced: `ca_ES_VALENCIA` => `ca-ES_VALENCIA`, this language is considered invalid by Locale java class.

In my first commit b32ce8afe8557b90131b8afcfd32f8917d7e0d49  I have changed `replace('_', '-')` with `replaceAll('_', '-')` in all ocurrences inside data engine and dynamic data mapping.
In my second commit 2ee257395ba65626bf5616b505216a582b6a5fa3 I have applied the same change everywhere in the Liferay code.

Let me know if you prefer to only modify the code in data engine and dynamic data mapping.

Regards,
Jorge

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:data-engine

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:forms

**Comment by jorgediaz-lr** [comment]
ci:test:data-engine

**Comment by jorgediaz-lr** [comment]
Hi @rebsilva @carolmariaabb 

I have added commit 263c94ca6096e7acc46fbb08ad67c9ba8e5bc158 to fix "Uncaught TypeError: replaceAll must be called with a global RegExp" error when editing an structure

**Comment by rebsilva** [comment]
Just started reviewing! :cherry_blossom:

**Review by rebsilva — CHANGES_REQUESTED** [review]
Hello @jorgediaz-lr! Thanks for your patience on this PR, I appreciate a lot! I've reviewed the data-engine part and it seems okay to me; but for the second commit, since it envolves a lot of other components, I sugest to you send to each team responsible so they can review it instead.

If you do not wish to do this second commit anymore, you can remove it and i will aprove the PR, thanks! :cherry_blossom:

**Comment by jorgediaz-lr** [comment]
Hi @rebsilva 

No problem, I will remove that commit and I will send them to the other product team in a different PR.

**Comment by jorgediaz-lr** [comment]
Hi @rebsilva 

I have updated the PR, now it only contains the first commit, see: 43314c8a8f50f8fe3e746e3b5bad1a8eb10ccd14

So you can approve it

**Review by rebsilva — APPROVED** [review]
LGTM! :cherry_blossom:

**Comment by rebsilva** [comment]
Thanks @jorgediaz-lr! I will need to trigger the tests again since the PR changed

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:data-engine

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
