### PR TITLE
LPS-142018 Update options lists by language only for fields which have options

### PR DESCRIPTION
**Pull request by alinedoleron**
Related Issue: https://issues.liferay.com/browse/LPS-142018

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@alinedoleron I merged it manually.

**Comment by jpince** [comment]
https://github.com/brianchandotcom/liferay-portal/commit/f9b22fdf34c9ee0be496f3557fbfd124c1291e70

**Pull request closed without merging**
