### PR TITLE
LPD-19517 Add ddmStructureKey property when exporting a structure with fieldSet if it's null or blank

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://liferay.atlassian.net/browse/LPD-19517

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:report:2549620871

**Comment by marcelabc** [comment]
ci:forward:force

**Pull request closed without merging**
