### PR TITLE
LPD-33053

### PR DESCRIPTION
**Pull request by icgsbr**
https://liferay.atlassian.net/browse/LPD-33053

### CODE REVIEW

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by icgsbr** [comment]
Hi @marcelabc !

From what I've seen in the results from the test upgrade suite, looks like the errors are not related to the PR. I think we can forward this to Bchan; but before doing so, I'd like y our input in order to see if this is indeed the case.

Best regards.

**Comment by marcelabc** [comment]
ci:report:71689285

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
