### PR TITLE
LPS-125690 LPS-125689 Fixes the validation of the conditions and actions of a rule

### PR DESCRIPTION
**Pull request by matuzalemsteles**

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@matuzalemsteles, are the solutions of **LPS-125689** and **LPS-125690** dependent? If not, can you please clarify why did you decide to use a single pull to both fixes?

Thanks.

**Comment by matuzalemsteles** [comment]
Hey @natocesarrego, both are related to validation we could send separately but one part will break other things, so it only makes sense to keep both in the same PR and send.

**Comment by matuzalemsteles** [comment]
ci:forward

**Pull request closed without merging**
