### PR TITLE
LPS-155981 - Web content's field's reference doesn't start with alphabet

### PR DESCRIPTION
**Pull request by alberttgomes**
LPS: https://issues.liferay.com/browse/LPS-155981
Notice: This bug implies other problems related to those languages that use symbols, such as Arabic, Japanese and Chinese. In all form fields that use the normlizaFieldName function, due to another function that is called to validate the fieldName, which is checkValidFieldNameCharacter, where it returns a regular expression: (Regex)
where the solution updates the regex making it recognize the three symbol languages mentioned.
current:/[A-Za-z0-9_]/
solution:/[一-龠]+|[ぁ-ゔ]+|[ァ-ヴー]+|[A-Za-z0-9_]+|[々〆〤ヶ]+|[ا-ي_٩]+| [贼-阿]/
  However I do not know if it is a good solution due to other problems that could be created. So I removed the normalizeFieldName function from getDefaultFieldName, since the function just generates a random fieldReference that is created with a generateInstanceId function, concatenated to type.label.

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by alberttgomes** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
@alberttgomes, did you make sure any of the failures are not related to your fix before running tests again?

**Comment by alberttgomes** [comment]
> 
hi @rodrigopaulino, yes, failures are not related the my fix.

**Comment by alberttgomes** [comment]
Hi @rodrigopaulino the ci failed again, and apparently it's not something related to my pull request, it's integration failures in jdk modules, mysql... should i run it again or do you have any suggestions? thanks!

**Comment by rodrigopaulino** [comment]
Hey, @alberttgomes. Could you please run this [DEBooleanField#CanBeSubmittedAndCheckEntries](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/223294//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_DEBooleanField_CanBeSubmittedAndCheckEntries_) locally with your fix and assert it works properly. Thx

**Comment by alberttgomes** [comment]
hey, @rodrigopaulino . I run this test ([DEBooleanField#CanBeSubmittedAndCheckEntries](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/223294//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_DEBooleanField_CanBeSubmittedAndCheckEntries_)) in my branch where fix and in master, failed in both. Failures are in WebContent, are element is not present in a component checkbox. 
image (3)
image (2)

**Comment by alberttgomes** [comment]
hey @rodrigopaulino, i can run the ci:relevant again??

**Comment by rodrigopaulino** [comment]
Thanks, @alberttgomes.
@alinedoleron, this is free for reviewing. Thanks!

**Comment by alinedoleron** [comment]
Hello, @alberttgomes.
Sorry for the late response.
I've tested the solution but it changes a little what is expected when creating a field reference, which should follow the pattern: **label+InstanceId** for the field types (Ex: Text => `text12342370`; Select: `selectfromlist60042370`) 
**option+InstanceId** for the options of Selects, Radios and Checkboxes

The PR make every fieldType have fieldReference equals to **option+InstanceId**

So I think we could use what you've proposed here: 

> solution:/[一-龠]+|[ぁ-ゔ]+|[ァ-ヴー]+|[A-Za-z0-9_]+|[々〆〤ヶ]+|[ا-ي_٩]+| [贼-阿]/


I've tested for Japanese,Arabic, Chinese and it worked. I just wanted you to check if we can remove the part of the regex that test the numbers, since I think we can continue using the 0-9.

**Review by alinedoleron — CHANGES_REQUESTED** [review]
Hello, @alberttgomes.
Sorry for the late response.
I've tested the solution but it changes a little what is expected when creating a field reference, which should follow the pattern: **label+InstanceId** for the field types (Ex: Text => `text12342370`; Select: `selectfromlist60042370`) 
**option+InstanceId** for the options of Selects, Radios and Checkboxes

The PR make every fieldType have fieldReference equals to **option+InstanceId**

So I think we could use what you've proposed here: 

> solution:/[一-龠]+|[ぁ-ゔ]+|[ァ-ヴー]+|[A-Za-z0-9_]+|[々〆〤ヶ]+|[ا-ي_٩]+| [贼-阿]/


I've tested for Japanese,Arabic, Chinese and it worked. I just wanted you to check if we can remove the part of the regex that test the numbers, since I think we can continue using the 0-9.

**Comment by alberttgomes** [comment]
HI, @alinedoleron thanks by your analytics!!! I changed the regex remove the numbers of the arabic, the others not use numbers.

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
Hello @alberttgomes. Please, could  you run the `formatSource` on data-engine-js-components-web module?

**Comment by alberttgomes** [comment]
> Hello @alberttgomes. Please, could you run the `formatSource` on data-engine-js-components-web module?

hey @alinedoleron done!!

**Comment by alberttgomes** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by alinedoleron** [comment]
Hi @alberttgomes, we had misunderstood the expected result of this bug. The field reference doesn't need  to start with in field name transflated to the chosen language. It must always be the value in English, which is the field type value. For example, if it is a Text field, no matter what language is chosen, the value must be Text########. I'll close this PR and when you fix you'll need to open a new pull request.

**Comment by alberttgomes** [comment]
> Hi @alberttgomes, we had misunderstood the expected result of this bug. The field reference doesn't need  to start with the field name translated to the chosen language. It must always be the value in English, which is the field type value. For example, if it is a Text field, no matter what language is chosen, the value must be Text########. I'll close this PR and when you fix you'll need to open a new pull request.


Thanks,  @alinedoleron !!

**Pull request closed without merging**
