### PR TITLE
[TS] LPS-153129

### PR DESCRIPTION
**Pull request by jcampoy**
https://issues.liferay.com/browse/LPS-153129

the solution is a revert of the fix for https://issues.liferay.com/browse/LPS-72843 , I tried to reproduce the LPS-72843 without success reverting the fix, so, I tend to think the issue was a gmail issue and not something to fix in Liferay.

See my test:
Screen Shot 2022-05-10 at 11 43 55

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by jcampoy** [comment]
ci:test:sf

**Comment by jcampoy** [comment]
@carolmariaabb SF done! :)

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @jcampoy, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @jcampoy, can you please check if these failures are related to your changes? Thanks

**Comment by jcampoy** [comment]
Unique failure is not related with my changes.

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
