### PR TITLE
LPD-18623 LocalFile.FormsTranslations#CanBeCreatedInMultipleLanguages

### PR DESCRIPTION
**Pull request by diogomelo09**
[LPD-18623](https://liferay.atlassian.net/browse/LPD-18623)

### CODE REVIEW

**Review by p-albuquerque — APPROVED** [review]
LGTM

**Comment by marcelabc** [comment]
Hey @carolmariaabb 
Could you review this PR, please? :smile:

**Comment by julschong** [comment]
@diogomelo09 @carolmariaabb Hi Carol, Diogo,
Thanks for the big help on this. 
Would it be possible to have the test pass under both JRE and CLDR locale provider?
or this test would fail upstream before we switch to CLDR.
Thanks!

**Comment by carolmariaabb** [comment]
@diogomelo09 could you check this comment https://github.com/liferay-workflow/liferay-portal/pull/1086#issuecomment-1967204021 and do the same? Please talk to me or Camacho if you have any question.

**Comment by julschong** [comment]
@diogomelo09 Hi Diogo,
you should be able to just change it to 
```
FormViewBuilder.changeAppLanguageTo(changeAppLanguageTo = "السعودية");
```
this should pass both CLDR and JRE

**Comment by guilhermedcamacho** [comment]
Hey @diogomelo09 , which repository did you send the PR to test under both JRE and CLDR locale providers?
It would be nice to link these pull requests.

**Comment by p-albuquerque** [comment]
> Hey @diogomelo09 , which repository did you send the PR to test under both JRE and CLDR locale providers? It would be nice to link these pull requests.

https://github.com/p-albuquerque/liferay-portal/pull/120

**Comment by diogomelo09** [comment]
> Ei@diogomelo09, qual repositório você enviou o PR para testar nos provedores de localidade JRE e CLDR? Seria bom vincular essas solicitações pull.

https://github.com/p-albuquerque/liferay-portal/pull/120

**Comment by diogomelo09** [comment]
> @diogomelo09Olá Diogo, você deve conseguir simplesmente alterá-lo para
> 
> ```
> FormViewBuilder.changeAppLanguageTo(changeAppLanguageTo = "السعودية");
> ```
> 
> isso deve passar tanto no CLDR quanto no JRE

Resent here: https://github.com/liferay-forms/liferay-portal/pull/2487

**Pull request closed without merging**
