### PR TITLE
LPS-138120 Convert Checkbox to TypeScript

### PR DESCRIPTION
**Pull request by eli-rlima**
Related Issue: https://issues.liferay.com/browse/LPS-138120

Hi reviewer!

This PR is the rewrite of `Checkbox.es` in TypeScript. Here is the [related ticket](https://issues.liferay.com/browse/LPS-138120). 

I took advantage and do some refactoring in the original code. Because this, I needed adjust some FE tests.

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by eli-rlima** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hey @eli-rlima, can you please fix the source formatter issues and resend? Thanks

**Pull request closed without merging**
