### PR TITLE
LPS-176235 Files uploaded by guest are public

### PR DESCRIPTION
**Pull request by carolmariaabb**
Follow-up: https://github.com/liferay-forms/liferay-portal/pull/2145

Related Issue: https://issues.liferay.com/browse/LPS-176235

### CODE REVIEW

**Comment by robertoDiaz** [comment]
@carolmariaabb  lgtm!

I put my original upgrade to have the ddm services available.

👍

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
