### PR TITLE
LPS-189754 Cannot filter a date ddm field using Elasticsearch 'now' keyword because the information is stored as String instead of using the 'date' type 

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://liferay.atlassian.net/browse/LPS-189754

Similar PR than previous https://github.com/liferay-forms/liferay-portal/pull/2263 but I am using `_dateFormatFactory.getSimpleDateFormat(pattern)` instead of `DateUtil.parseDate` to avoid having to add the locale parameter to several methods. I have also modified the logic to avoid repeating some logic as requested here: https://github.com/liferay-forms/liferay-portal/pull/2263#discussion_r1253372583

----

Hi all,

Our customer is trying to filter the webcontent results using Custom Filters and the Elasticsearch special keyword `now` to display only the contents of today:
 - **Custom fields:** For more information about Custom Filters, see following documentation: https://help.liferay.com/hc/en-us/articles/4408343859341-Perform-a-date-range-query-using-Custom-Filter-Widgets-over-two-fields-of-a-structure
and https://learn.liferay.com/w/dxp/using-search/search-pages-and-widgets/search-results/custom-filter-examples#boosting-matches-to-nested-fields
 - **Date calculation in Elasticsearch:** For more infomation about the Elasticsearch special keyword 'now' see following documentation: https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#date-math

This is not working because now the Date and Date-Time fields are indexed in Elasticsearch as Strings.

For more information see the reproduction steps on ticket description https://liferay.atlassian.net/browse/LPS-189754

Other indexed web content fields such as 'createDate', 'displayDate', 'expirationDate', 'modified' or the field `nestedFieldArray.value_date` in Objects functionality are indexed as date and it is possible to apply the Custom Filters with the 'now' Elasticsearch keyword without any problem.

**Implemented solution**

To solve the customer problem, we have to parse the DDM field information and index them in Elasticsearch using the 'date' type, this will allow the customer to use Elasticsearch date calculations.

Instead of replacing current indexed field type, I am adding a new field with the "_date" suffix. Replacing current configuration would break all our customers installations until they execute a full reindex. Adding a separate _date field would save everybody to reindex after this LPS is commited.

The new "_date" field follows the similar approach of "_geolocation" fields, see https://github.com/liferay-forms/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/internal/util/DDMIndexerImpl.java#L688-L697

**Commits:**

- ac6ecee8021321d0c1a9e038a7219dbfad9c3418 => If the DDM field type is DATE or DATE_TIME, we parse and index them as an additional xxx_date field with date format.
- eb0a473d1c3124db3c564b91dfb2935dcb4c5dc6 => Add Elasticsearch mappings so all fields with *_date name will indexed with the 'date' format.
- 61877f94c7b75b8e92ee3281c184d3b1327d6770 and aec6bc68c13bacdb47dc1cf070ef51ec932cf207 => I am enabling some WARN traces as they weren't activated and I wasn't able to see why the JournalArticleSearchTest test was failing.
- 472c9579e153992e9a753adf6a886123ae2f44c0 => Fix TestOrderHelper date formats as they weren't correct (_20160417192501 instead of 2016-04-17 17:19_). That caused the new parse code to fail in test JournalArticleSearchTest.

Let me know if you have any question

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
cc @carolmariaabb

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Hi @carolmariaabb 

I have removed 54fd7fbd4e0e5dc8bfd7c611dbe07e130167831e commit  as it was an optional improvement. 
I though it was a good improvement to check `Validator.isNotNull` earlier but it seems it breaks some tests. So for now I have left the `Validator.isNotNull` check only for the DATE and DATE_TIME code.

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:forms

**Comment by jorgediaz-lr** [comment]
About failing integration tests:

> 4. [modules-integration-mysql57-jdk8/0/11](https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/632384//consoleText)
>       1 [com.liferay.headless.delivery.resource.v1_0.test.MessageBoardSectionResourceTest](https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/632384/testReport/com.liferay.headless.delivery.resource.v1_0.test/MessageBoardSectionResourceTest) - [Failed 1 of last 24](https://testray.liferay.com/home/-/testray/case_results/2371324869/history)
> 5. [modules-integration-mysql57-jdk8/0/17](https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/695628//consoleText)
>       2 [com.liferay.portal.search.indexer.clauses.test.IndexerClausesExpandoTest](https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/695628/testReport/com.liferay.portal.search.indexer.clauses.test/IndexerClausesExpandoTest) - [Failed 0 of last 24](https://testray.liferay.com/home/-/testray/case_results/2371325515/history)

I have executed them in my PC and I didn't reproduced them, so it seems they are false positives.

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
@jorgediaz-lr Could you please check if this [error](https://testray.liferay.com/home/-/testray/case_results/2374149208?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2374147236%26testrayRunId%3D2374147668%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) is related to your changes? Thanks!

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
@jorgediaz-lr the following tests are failing only in this PR. Could you please check if they are related to your changes?

1. [com.liferay.portal.odata.sort.InvalidSortException: Unable to sort by property: ratingValue  at com.liferay.portal.odata.internal.sort.SortParserImpl.getSortField(SortParserImpl.java:147)](https://testray.liferay.com/home/-/testray/case_results/2378008653?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2377999314%26testrayRunId%3D2378006940%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
2. [java.lang.NullPointerException  at com.liferay.dynamic.data.mapping.internal.util.DDMIndexerImpl._extractIndexableAttributes(DDMIndexerImpl.java:820)](https://testray.liferay.com/home/-/testray/case_results/2378008298?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2377999314%26testrayRunId%3D2378006940%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) 

Thanks!

**Comment by danielmijarra** [comment]
Hi @carolmariaabb,
the first error is reproducible in a clean bundle (_ratingValue_).

We're checking the second one.

**Comment by danielmijarra** [comment]
Hi @carolmariaabb, 
new pull request sent => https://github.com/liferay-forms/liferay-portal/pull/2271.

**Pull request closed without merging**
