### PR TITLE
LPS-149334

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issue: https://issues.liferay.com/browse/LPS-149334

Hello Reviewer!

This PR has new features related to the story:
**As a power user, I want to limit the number of characters of text and long text fields** ([LPS-146889](https://issues.liferay.com/browse/LPS-146889))

More details can be found [here](https://liferay.atlassian.net/wiki/spaces/ENGFORMS/pages/1994490142/LPS-146889+-+As+a+power+user+I+want+to+limit+the+number+of+characters+of+text+and+long+text+fields) on our Confluence page.

If you have any questions feel free to ask, thank you for your time!

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hey @rebsilva, can you please fix the source formatter issues and resend? Thanks

**Pull request closed without merging**
