### PR TITLE
LPS-179541 Add group role to fields and options

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Related Issue: https://issues.liferay.com/browse/LPS-179541

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
> ###  ci:test:stable - 26 out of 27 jobs passed
> ###  ci:test:relevant - 159 out of 171 jobs passed in 2 hours 19 minutes
> Click here for more details.
> ##### Test bundle downloads:
> * [liferay-portal-bundle-tomcat.tar.gz](https://files.liferay.com/private/bundles/test-1-39/jobs/test-portal-acceptance-pullrequest(master)/builds/3840/liferay-portal-bundle-tomcat.tar.gz) (mirrors: [dlc](http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-39/jobs/test-portal-acceptance-pullrequest(master)/builds/3840/liferay-portal-bundle-tomcat.tar.gz), [lax](http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-39/jobs/test-portal-acceptance-pullrequest(master)/builds/3840/liferay-portal-bundle-tomcat.tar.gz))

Hi @cgmonte,

I think the failing tests are related to the changes in select options DOM structure, I will have a look at them.

Regards.

**Comment by georgel-pop-lr** [comment]
ci:stop

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by cgmonte** [comment]
Hey @georgel-pop-lr, I am on it. Will give you a feedback soon.

**Comment by cgmonte** [comment]
Hey @georgel-pop-lr, I am on it. Will give you a feedback soon.

**Comment by cgmonte** [comment]
Hey @georgel-pop-lr, I am on it! Will bet back soon with a feedback.

**Comment by cgmonte** [comment]
ci:test:forms

**Comment by georgel-pop-lr** [comment]
> Hey @georgel-pop-lr I have approved the changes, but it looks like we still have three failing tests which are related to the changes:
> 
> https://testray.liferay.com/home/-/testray/case_results/2244781302?tab=history https://testray.liferay.com/home/-/testray/case_results/2244781222?tab=history https://testray.liferay.com/home/-/testray/case_results/2244781453?tab=history
> 
> Can you fix them? Let me know if you need help.

Hi @cgmonte,

I had a look, but I'm not sure how is best to change these tests.

Could someone from QA help me out?

Regards.

**Comment by carolmariaabb** [comment]
Hi @georgel-pop-lr,

> I had a look, but I'm not sure how is best to change these tests.

Is there any work in progress that you can share with the QA team to speed up the process?

**Comment by carolmariaabb** [comment]
The QA team will work to fix the tests later, but we can forward the PR now, as discussed in this [thread](https://liferay.slack.com/archives/C048YNC5GRK/p1680175253544079).

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
