### PR TITLE
LPS-123062 Migrate Calculator component to React

### PR DESCRIPTION
**Pull request by diegonvs**
# How to see my changes:

1. Go to Forms
2. Create a new Forms with a numeric field and then publish it
3. Go to Rules tab
4. Add a new rule clicking on the plus button
5. On the Actions section, click on the On select and select calculate
6. Then, choose calculator on the recently opened select

# What it does?

Migrates Calculator component from Metal to React and also:

* Migrate from 'dynamic-data-mapping-form-builder' module to 'data-engine-taglib' for compability to building React on this module
* Adjust Calculator Buttons markup and styling for another improving a11y: li elements are not adequated for using as a button and We cannot set a role="button" for this type of element
* Uses Field component for dynamic loading a Text form-field-type component on Calculator
* Creates an React adapter for rendering this component on RuleEditor
* Adds new Language Keys for Calculator buttons

# Considerations

## Calculator React Adapter ⚛️

It was necessary for rendering a React component(the newest Calculator) on the RuleEditor(currently written using Metal+Soy). It will be replaced sooner but for CI don't cry I used this approach and once the CI see it's okay I can remove and resent this PR again(while writing this description I notice that I could commit adapter things singly but I'll do it on monday.

## Rendering a Form Field on the Calculator component

If you take a look on the current Calculator.soy We're calling a text form field dynamically, I maintained this behaviour calling Field component.

## Calculator Buttons

Calculator buttons were written using li elements but this element isn't the best option for this type for interaction in terms of a11y and semantically. I decided to rewrite these ul > li elements to div > buttons to solve it.

I removed the button-padding-icons class since it was causing a positioning issue. It was easily replaced by a monospaced with ClayButton React component and it's working fine :)

## Where are the tests @diegonvs? 😢

While writing tests I found an error caused by a cyclical dependencies caused by adding a npmscripts.config.js file is contained on data-engine-taglib importing dynamic-data-mapping-form-builder things for making some imports from form-build run without (errors)[https://gist.github.com/diegonvs/40dc7de13f691c5c04bfb181a29c0b1f] on data-engine-taglib.

I decided to create another ticket for tackling it on the future.

Related Issue: https://issues.liferay.com/browse/LPS-123062

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by diegonvs** [comment]
@liferay-forms you almost killed me by heart attack when editing my PR description:

image

**Comment by liferay-forms** [comment]
Hey @diegonvs, can you please fix the source formatter issues and resend? Thanks

**Pull request closed without merging**
