### PR TITLE
LPS-122559 reseting value when visibility changes

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:test:forms

**Comment by natocesarrego** [comment]
@linolaoj, I remember that you did a [similar change](https://github.com/liferay/liferay-portal/commit/8d8e246384474d8ce0c3603b7e90fd08f8db30d6) on back-end a while ago, right? If so, why did you decide to replicate the action of erase the field value on front-end? Are you trying to perform an optimization?

Thanks in advance for your answers. 🙂

**Comment by linolaoj** [comment]
Hi @natocesarrego ,
Here we have the following context:
Rule1: if _Select1_ equals to _value1_ then show _Text1_
Rule2: if _Select2_ equals to _value2_ then show _Text2_ 
When we select _value2_ the condition of Rule1 is not satisfied and no action is done ([DDMFormEvaluatorHelper.java#L205](https://github.com/liferay/liferay-portal/blob/6e0d8f334f923d77ba3bc9959b589a189a00ade0/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-evaluator-impl/src/main/java/com/liferay/dynamic/data/mapping/form/evaluator/internal/helper/DDMFormEvaluatorHelper.java#L205)). Because no action was done, the [_ddmFormFieldsPropertyChanges](https://github.com/liferay/liferay-portal/blob/6e0d8f334f923d77ba3bc9959b589a189a00ade0/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-evaluator-impl/src/main/java/com/liferay/dynamic/data/mapping/form/evaluator/internal/helper/DDMFormEvaluatorHelper.java#L455) is not populated and I could not see a way to decide if the field became visible or not. When saving the form entry we are already filtering the fields that are not visible, so I went with this approach of updating at the frontend.
The changes from LPS-110839 worked because in that scenario the field present in the action of one rule was also present in the condition of another rule.

Please let me know if this makes sense to you.
Thanks!

**Comment by natocesarrego** [comment]
I see your point, @linolaoj, and I realized that the property which informs if the field is visible or not is on `DDMFormFieldRenderingContext`, e.g., a context not available on `DDMFormEvaluatorHelper`. I just have one more question to you, are both solutions redundant or complementary? Is the front-end solution enough to solve the both scenarios mentioned by you? If so, how about keep only it?

Thanks.

**Comment by linolaoj** [comment]
Hi @natocesarrego, I'll check if this fix will work for both cases.
Thanks!

**Comment by natocesarrego** [comment]
I'll close this pull for now. Thanks. 🙂

**Comment by linolaoj** [comment]
Hi @natocesarrego ,
both fixes are needed. I'm resending this rebased at https://github.com/liferay-forms/liferay-portal/pull/112
Thanks!

**Pull request closed without merging**
