### PR TITLE
[TS] LPS-162403 Dynamic Data List record with HTML Field definition cannot be opened for preview and error is shown in DevTools console

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

I'm re-adding the inclusion of 'liferay-portlet-dynamic-data-lists' that was removed by https://github.com/liferay/liferay-portal/commit/210101bda8515199ab7f48146a667d5eab51eac5 so that DDLUtil is reachable again.

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Dear Team,

Please let me know if there are any updates on the review.

Thank you and best regards,
István

**Review by rodrigopaulino — CHANGES_REQUESTED** [review]
Hey, @IstvanD. Thanks for your contribution.
Can you explain why this would be needed in this JSP? If it's another JSP that uses this, maybe it should go there. What do you think?

**Comment by IstvanD** [comment]
Hi @rodrigopaulino 

The inclusion of 'liferay-portlet-dynamic-data-lists' is needed in `view_records.jsp` because that will ultimately use `TextHTMLDDMFormFieldValueRenderer` when it lists a HTML field.
This will then refer to DDLUtil [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/internal/render/TextHTMLDDMFormFieldValueRenderer.java#L59).

I hope this explains it.

Please let me know if you have further questions.

Thank you and best regards,
István

**Review by rodrigopaulino — APPROVED** [review]
I see. That's great. Thanks for letting me know, @IstvanD.
This looks good to me. 🙂

**Comment by rodrigopaulino** [comment]
ci:forward

**Pull request closed without merging**
