### PR TITLE
LPS-198962

### PR DESCRIPTION
**Pull request by icgsbr**
# Jira Link
https://liferay.atlassian.net/browse/LPS-198962

# Old Pull Request
https://github.com/liferay-forms/liferay-portal/pull/2354

### CODE REVIEW

**Comment by icgsbr** [comment]
ci:test:stable

**Comment by icgsbr** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by icgsbr** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]
LGTM!!

**Comment by alinedoleron** [comment]
ci:forward

**Pull request closed without merging**
