### PR TITLE
LPS-132125 Call FieldSetModal.scss within respective component

### PR DESCRIPTION
**Pull request by interaminense**

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:sf

**Review by miltonmc — APPROVED** [review]
That is looking good. You did a great improve so far!

My concerns are:
- The class nesting. I know that the current style does not allow us to keep the style flat, but if you could clean it up a little more would be fantastic. 
- The use of `!import` is usually a bad smell. I saw the great job you did by reducing its usage, but If you could remove all of them would be terrific,. 

None of them are mandatory to be tackled.  We can go as it is, so I've already  approved this PR.

**Comment by interaminense** [comment]
> That is looking good. You did a great improve so far!
> 
> My concerns are:
> 
> * The class nesting. I know that the current style does not allow us to keep the style flat, but if you could clean it up a little more would be fantastic.
> * The use of `!import` is usually a bad smell. I saw the great job you did by reducing its usage, but If you could remove all of them would be terrific,.
> 
> None of them are mandatory to be tackled. We can go as it is, so I've already approved this PR.

Hello @miltonmc, I think we can dedicate a little more time when we are working on a technical debt to restructure the FormBuilder, what do you think? Can I forward this PR?

**Comment by miltonmc** [comment]
ci:forward

**Pull request closed without merging**
