### PR TITLE
LPS-150837 Display exclamation mark icon on error messages

### PR DESCRIPTION
**Pull request by miltonmc**
Related Issue: https://issues.liferay.com/browse/LPS-150837

### Before
Screenshot from 2022-04-01 00-38-12
### After
Screenshot from 2022-04-01 00-37-10

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:data-engine

**Comment by miltonmc** [comment]
ci:test:forms

**Comment by miltonmc** [comment]
ci:test:objects

**Comment by miltonmc** [comment]
ci:test:echo

**Comment by miltonmc** [comment]
ci:test:lima

**Comment by miltonmc** [comment]
ci:test:object

**Comment by miltonmc** [comment]
ci:forward

**Pull request closed without merging**
