### PR TITLE
LPD-34375 | LPD-35442 Handle undo/redo for repeatable fields | Fixing Image field onChange and Blur event order 

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,

**Tickets:**
[LPD-35442](https://liferay.atlassian.net/browse/LPD-35442) - Image field creates several steps in the history
[LPD-34375](https://liferay.atlassian.net/browse/LPD-34375) - Handle undo/redo for repeatable fields

**Changes:**
[LPD-35442](https://liferay.atlassian.net/browse/LPD-35442) - Image field creates several steps in the history
The onBlur event was handled sooner than the onChange event of the selectionModal. This caused an issue on our side creating a step in the historyReducer, as we only create that snapshot onBlur, when there was an edit registered before thru an onChange handler. I also had to make sure we only want to create a history step for the image field after the onBlur event.

[LPD-34375](https://liferay.atlassian.net/browse/LPD-34375) - Handle undo/redo for repeatable fields
I moved all our event Listeners related to the Undo/Redo feature from the Layout Component to the WebContentVariant Component. I also created a storeState event for every Repeatable field aciton, like add/remove/move.

Tests will be sent separately

Please review my changes,

Thanks,

/cc @rebsilva

### CODE REVIEW

**Comment by rebsilva** [comment]
i will review this later today, thanks @NemethNorbert! :cherry_blossom:

**Comment by rebsilva** [comment]
just started reviewing! :cherry_blossom:

**Review by rebsilva — APPROVED** [review]
LGTM! :cherry_blossom: great work here @NemethNorbert :tada: 
do you want to double check while the tests are running @danvb112?

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:forms

**Comment by rebsilva** [comment]
ci:test:data-engine

**Comment by rebsilva** [comment]
ci:test:journal

**Comment by rebsilva** [comment]
ci:test:content-management

**Comment by rebsilva** [comment]
taking a look at the test failures to see if they are related or not

**Comment by rebsilva** [comment]
ci:test:forms

**Comment by rebsilva** [comment]
ci:test:data-engine

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:data-engine

**Comment by NemethNorbert** [comment]
> the failing tests bellow seem to be related, could you run locally to see if they work or not please @NemethNorbert?
> 
> FormsMultipleSelectionField#CanBeSetToRepeatable DEMultipleSelectionField#CanInputDataOnDuplicatedField
> 
> i'll run the suites again just to make sure, but let me know your results if you have the chance to test it, thanks!

Hey @rebsilva ,

I run the tests locally, they fail there as well.


FormsMultipleSelectionField#CanBeSetToRepeatable

This one is strange as I see the test complete, but the test is closed without any usefull error msg. Doing the test manually passes, did not find any issue with the repeatable fields.

DEMultipleSelectionField#CanInputDataOnDuplicatedField

This also fails, however it seems like it fails with a locator error, when trying to change the display style.

**Comment by rebsilva** [comment]
i see @NemethNorbert, could you please fix them and send here? if you can't find a way to fix them let me know so i can help you, thanks a lot!

**Comment by rebsilva** [comment]
ci:test:playwright

**Comment by NemethNorbert** [comment]
Hey @rebsilva ,

I dont think my changes causing these issues, the tests also fails on master locally.
Can you check them as well please?

Thank you,

**Comment by rebsilva** [comment]
i will check and talk with the team about it, thanks!

**Comment by rebsilva** [comment]
hi @NemethNorbert, the tests are passing locally on the master and also on the ci when i saw on testray, but they are failing here; could you please take a look? thanks!

**Comment by danvb112** [comment]
LGMT as well! :tada:

**Comment by rebsilva** [comment]
@NemethNorbert i've tested locally with @danvb112 and the tests are passing! so i will forward the PR :blush:

but please notice that when the FF is removed some tests will fail because of different locators, but this is something to do in the future; thanks!

**Comment by rebsilva** [comment]
ci:forward:force

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Comment by NemethNorbert** [comment]
Manually forwaded to https://github.com/brianchandotcom/liferay-portal/pull/154445

**Pull request closed without merging**
