### PR TITLE
LPS-174219 Set masked value to be fixed with decimal places as parameter

### PR DESCRIPTION
**Pull request by MirnaGama**
**Scenario:**

1. Create a form with two numeric fields (cost and tax).
2. Set both fields to decimal, with an input mask of 2 decimal places, and a currency prefix (e.g. £).
3. Add a rule to calculate the value of the tax field as cost * 0.2 when cost is not empty.
4. Save and publish the form, and open the form URL.
5. Enter '1' in the cost field.

**Expected:** £1.00 displayed in cost and £0.20 displayed in tax.
**Actual:** £1 displayed in cost and £0.2 displayed in tax.

https://issues.liferay.com/browse/LPS-174219

### CODE REVIEW

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by carolmariaabb** [comment]
The Poshi test failures seem to be related to these changes.

/cc @alinedoleron

**Comment by alinedoleron** [comment]
> The Poshi test failures seem to be related to these changes.
> 
> /cc @alinedoleron
Thanks, @carolmariaabb!
I'll have a look!

**Review by alinedoleron — CHANGES_REQUESTED** [review]
Hello, @MirnaGama. Unfortunately this fix broke some tests because when the Number has thousands separator, the Number(masked) is NaN. 

I've tried another way but it is still not good. The `yarn test` passes but I saw another issue. It is forcing the number to have the given decimal places as soon as I type the number. Please, could you have another look on this issue to improve or change the solution? 

Thanks!

```
const splitNumbers = masked.split(symbols.decimalSymbol);

const decimalDigitsLength =
		splitNumbers.length > 1 ? splitNumbers.pop().length : 0;

	return {
		masked:
			dataType === 'double' && masked && decimalDigitsLength
				? masked + '0'.repeat(decimalPlaces - decimalDigitsLength)
				: masked,
		placeholder:
			dataType === 'double'
				? `0${symbols.decimalSymbol}${'0'.repeat(decimalPlaces)}`
				: inputMaskFormat.replace(/\d/g, '_'),
		raw: masked.replace(regex, ''),
	};
```

**Comment by MirnaGama** [comment]
Hi @alinedoleron 

I removed this check on the masked variable as it seems redundant and it is working as expected. 

```
return {
		masked:
                              dataType === 'double' &&  masked && decimalDigitsLength
				? masked + '0'.repeat(decimalPlaces - decimalDigitsLength)
```
				
Please check the following recording:
https://www.loom.com/share/041aa9d1781547cb9b7b7e5b5b16fa8b

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by MirnaGama** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
Hello, @MirnaGama. 
I created [this PR](https://github.com/alinedoleron/liferay-portal/pull/218) with another solution where I used the property `focused`. When the first field is edited (focused), the other (not focused) that will receive the value calculated by the rule will be completed with the zeroes needed.
Please, could you check if this solution passes the `ci:test:relevant`?

Thanks!

**Comment by carolmariaabb** [comment]
@MirnaGama Could you check Aline's comment and send us another PR with the necessary changes? I'll close this one for now. Thanks!

**Comment by carolmariaabb** [comment]
ci:close

**Comment by MirnaGama** [comment]
Hi @carolmariaabb , @alinedoleron 

Resent: https://github.com/liferay-forms/liferay-portal/pull/2133

**Pull request closed without merging**
