### PR TITLE
LRQA-71489

### PR DESCRIPTION
**Pull request by 91nilo**
Related Issue: https://issues.liferay.com/browse/LRQA-71489

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by 91nilo** [comment]
ci:test:relevant

**Comment by 91nilo** [comment]
ci:stop

**Comment by 91nilo** [comment]
ci:test:relevant

**Pull request closed without merging**
