### PR TITLE
LPS-152326 Setting the current Liferay context for CKEditor

### PR DESCRIPTION
**Pull request by rijema**
Hi Team,

Here is the link for the issue: https://issues.liferay.com/browse/LPS-152326

Thanks  in advance,
Richard.

### CODE REVIEW

**Comment by rijema** [comment]
ci:test:sf

**Comment by rijema** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Hi @rijema,

Thanks for sending this PR. However, you should ask the @liferay-frontend team to review it as the changes are related to the CKEditor component.

**Comment by carolmariaabb** [comment]
ci:close

**Comment by rijema** [comment]
Thanks for the info, @carolmariaabb!

**Pull request closed without merging**
