### PR TITLE
LPS 187743 - Avoid check default folder permissions in internal forms folders

### PR DESCRIPTION
**Pull request by robertoDiaz**
https://issues.liferay.com/browse/LPS-187743

As discussed this is the fix for the current error.

I've changed the permission check to the convenient one.

Best regards!

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Review by carolmariaabb — APPROVED** [review]
LGTM! 🎉

**Comment by robertoDiaz** [comment]
I have to check the failing tests

**Comment by robertoDiaz** [comment]
ci:test:forms

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
@robertoDiaz The `DocumentLibraryDDMFormFieldTemplateContextContributorTest` is failing in this PR. Could you please check? Thanks!

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by robertoDiaz** [comment]
ci:reevaluate:1397401_5423

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
Hi @robertoDiaz,

I just noticed that this solution won't work when using upload fields in Web Content for example, as you can see in the image below:

image

I'm not sure what permission we should check in this case. Could you please check this?

Thanks!

**Comment by robertoDiaz** [comment]
In this case I think that it makes sense to check the Article entry permission (I mean, if the user is able to add or update it)

I don't know if the architecture of the form field allows that. 

Maybe we could pass the className, classPK of the parent entity (as we do now with the formInstanceId) so we could get the Model Permission of this entity and check the right permissions in each case (anyway, maybe we'll have to create a new interface in DDM-Api to be implemented in each DDM-form-field client so they could check the right permissions in each case)

What do you think @carolmariaabb ?

**Comment by robertoDiaz** [comment]
I think I was able to find a solution, is similar as explained but we do not need to send nothing to the backend.

I'm testing it.

**Comment by carolmariaabb** [comment]
Hi @robertoDiaz,

I will try to find some time to think about the possible approaches we have to fix this issue. In the meantime, I see no problem with you trying to follow the described approach.

If you need help, feel free open a PTR, because in this case another team member can try to help you more quickly if I can't.

Thanks!

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:forms

**Comment by robertoDiaz** [comment]
@carolmariaabb done.

Now it seems to work.

I've created the described mechanism because this is convenient (since DDM is used by other Portlets).

By now I think that journal or DM do not have to implement it because the upload fields are rendered in FileEnty or Article creation and this edit views are not public (as Forms) and could use the Default option (allow render the field in all cases)

**Pull request closed without merging**
