### PR TITLE
LPS-153680 Break line when word is too big

### PR DESCRIPTION
**Pull request by alinedoleron**
Ticket: https://issues.liferay.com/browse/LPS-15368
wordbreak

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Review by miltonmc — COMMENTED** [review]
LGTM!

**Review by miltonmc — APPROVED** [review]

**Comment by miltonmc** [comment]
ci:forward

**Pull request closed without merging**
