### PR TITLE
[TECHNICAL SUPPORT] LPS-122906 Forms do not need to store the version of workflow definitions

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related Issue: https://issues.liferay.com/browse/LPS-122906

**Notes about this fix:**
Before implementing this, I've considered 3 different approaches. Here are they:
1. First I thought about creating a listener that would update all the forms linked to a workflow definition. This idea fell through, because it would cause an overhead on the update action of the workflow component. All those forms would have to be searched, deserialized and updated every time a workflow definition changed;
2. The second idea is a combination of the following approach and creating an upgrade process with the purpose of removing all the version related data from the forms' workflow setting (example: from ["Single Approver@1"] to ["Single Approver"]). I also thought this would cause and overhead during DXP upgrades, because, since this needs to be backported all the way to 7.1, this upgrade would have to be executed every time a customer upgrades their Liferay version up until 7.4;
3. Finally, the chosen approach is the same as the previous one, but I've decided to change this information on demand. What you can see in [this part](https://github.com/liferay-forms/liferay-portal/pull/62/commits/93f3eaf384c6bef8be61add8b282af8d75ed87eb#diff-6661dadc6f2d46e211d21fbae3624bcac98af84b52c62ebbf0820c298e8f6ee9R750-R767) is the removal of the version data from the workflow setting. It doesn't cause any stress on the database connection and customers won't have to wait for a heavy fix pack release to get this fixed. Also, now that [the workflow select field won't pair the keys and values containing version information](https://github.com/liferay-forms/liferay-portal/pull/62/commits/93f3eaf384c6bef8be61add8b282af8d75ed87eb#diff-48509e0457aafbdbc5fbead9b277f375c35cf16e8d426e751d44fb1055c4efdcR80), and it's mandatory to pass that data when updating the link, I had to make this [cheap search for the latest available version](https://github.com/liferay-forms/liferay-portal/pull/62/commits/93f3eaf384c6bef8be61add8b282af8d75ed87eb#diff-6661dadc6f2d46e211d21fbae3624bcac98af84b52c62ebbf0820c298e8f6ee9R686-R697) before finishing the form update. This last part will only happen when the user saves a form with a workflow defined in their form's settings.

_Extra notes:_
I chose to use the [KaleoDefinitionLocalService](https://github.com/liferay-forms/liferay-portal/pull/62/commits/93f3eaf384c6bef8be61add8b282af8d75ed87eb#diff-6661dadc6f2d46e211d21fbae3624bcac98af84b52c62ebbf0820c298e8f6ee9R791) instead of the [WorkflowDefinitionManager](https://github.com/liferay-forms/liferay-portal/blob/master/modules/apps/portal-workflow/portal-workflow-kaleo-runtime-integration-impl/src/main/java/com/liferay/portal/workflow/kaleo/runtime/integration/internal/WorkflowDefinitionManagerImpl.java), because basically the last one eventually uses the first one and we wouldn't need to use more memory to convert a KaleoDefinition object into a WorkflowDefinition one. It looks kinda wasteful for this use case IMO.

This is it. Please reach out if you need further details about this. I'll be happy to provide them.
Thanks in advance.

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Something tells me that tests will fail. 🤔😅

**Comment by rodrigopaulino** [comment]
Confirmed. They will fail. Sorry about that. I'll send a new one.

**Comment by rodrigopaulino** [comment]
ci:stop

**Pull request closed without merging**
