### PR TITLE
LPS-152899 Adds compatibility layer for color when we are rendering web content templates adding the # to color field type

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related Issue: https://issues.liferay.com/browse/LPS-152899

/cc @ealonso

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:reevaluate:1317401_3347

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by brianchandotcom** [comment]
@carolmariaabb I merged this manually.

**Comment by carolmariaabb** [comment]
ci:close

**Pull request closed without merging**
