### PR TITLE
LPS-129618 Fixes the error that prevents a field from having an empty value

### PR DESCRIPTION
**Pull request by matuzalemsteles**
This was brought in from the old Metal.js implementation but the conditional was different and I made an error when translating.

Previously on LayoutProvider: `propertyName !== 'name' || propertyValue !== ''`

This conditional was used to decide whether to update the state of the field, now just invert that to fail earlier. This is the type of conditional that should not be inside the reducer but in the field that handles `name`. Keeping here for now because it requires a lot of changes.

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:reevaluate:1147401_7945

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:forward

**Pull request closed without merging**
