### PR TITLE
LPS-131617 Do not close Forms Sidebar when the Product Menu sidebar is open

### PR DESCRIPTION
**Pull request by miltonmc**
**Ticket:** [LPS-131617](https://issues.liferay.com/browse/LPS-131617)

### CODE REVIEW

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:relevant

**Review by interaminense — COMMENTED** [review]
LGTM!

**Review by interaminense — APPROVED** [review]

**Comment by interaminense** [comment]
ci:forward

**Pull request closed without merging**
