### PR TITLE
[LPS-123964,LPS-124912] Migrate instances of AlloyEditor in Forms

### PR DESCRIPTION
**Pull request by julien**
**LPS-123964**
In [`edit_form_instance.jsp`](https://github.com/liferay/liferay-portal/blob/f1dbd869c1036f3bc6379585b4c2a0293877d389/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web/src/main/resources/META-INF/resources/admin/edit_form_instance.jsp), AlloyEditor instances
have been replaced with `<aui:input />`

**Test plan**
- Deploy the `dynamic-data-mapping-form-web` module
- Navigate to **Content & Data** > **Forms**
- Create a new form and save it

**Before**
LPS-123964-before

**After**
LPS-123964-after

**LPS-124912**
In [`edit_element_set.jsp`](https://github.com/liferay/liferay-portal/blob/f1dbd869c1036f3bc6379585b4c2a0293877d389/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web/src/main/resources/META-INF/resources/admin/edit_element_set.jsp), AlloyEditor instances
have also been replaced with `<aui:input />`

**Test plan**
- Deploy the `dynamic-data-mapping-form-web` module
- Navigate to **Content & Data** > **Forms**
- Select the **Element Sets** tab
- Create a new form and save it

**Before**
LPS-124912-before

**After**
LPS-124912-after

**Additional notes**
Initially reviewed by the @liferay-frontend team [here](https://github.com/liferay-frontend/liferay-portal/pull/624)

### CODE REVIEW

**Comment by natocesarrego** [comment]
Hey @julien, your pull looks good to me. 🙂

Can you please clarify to me why are you replacing Alloy Editor occurrences in Forms?

Thanks in advance for your explanation.

**Comment by jbalsas** [comment]
Hey @natocesarrego, picking up since @julien is on PTO.

> Can you please clarify to me why are you replacing Alloy Editor occurrences in Forms?

We're planning to remove AlloyEditor in `7.4` completely. We removed most of usages in `7.3` already but this one somehow went unnoticed. This is the last non-legitimate usage of AlloyEditor that we could find, so we're looking to get rid of it before the first GA so that UX remains consistent with the rest of DXP.

You can check similar cases in Blogs title and description fields which got replaced during the last version. In addition, this should make the forms app faster since it won't need to load AlloyEditor files to edit a simple input text, so that should be a win win! 😉

**Comment by natocesarrego** [comment]
Thanks for your clarification, @jbalsas. 😄 

I'll close this pull due to the conflicts, but feel free to forward it to Brian.

Thanks.

**Comment by jbalsas** [comment]
Thanks @natocesarrego, see https://github.com/liferay-frontend/liferay-portal/pull/659! Retesting there before forwarding!

**Pull request closed without merging**
