### PR TITLE
LPS-138700 Remove dead code

### PR DESCRIPTION
**Pull request by miltonmc**
Related Issue: https://issues.liferay.com/browse/LPS-138700

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @miltonmc, can you please check if these failures are related to your changes? Thanks

**Comment by miltonmc** [comment]
ci:reevaluate:1287401_119

**Comment by liferay-forms** [comment]
Hey @miltonmc, can you please check if these failures are related to your changes? Thanks

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @miltonmc, can you please check if these failures are related to your changes? Thanks

**Comment by miltonmc** [comment]
ci:reevaluate:1307401_189

**Comment by liferay-forms** [comment]
Hey @miltonmc, can you please check if these failures are related to your changes? Thanks

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @miltonmc, can you please check if these failures are related to your changes? Thanks

**Comment by miltonmc** [comment]
ci:reevaluate:1267401_123

**Comment by liferay-forms** [comment]
Hey @miltonmc, can you please check if these failures are related to your changes? Thanks

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @miltonmc, can you please check if these failures are related to your changes? Thanks

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:forward

**Pull request closed without merging**
