### PR TITLE
LPS-183803 - Select file pop-up window from upload field does not have any context when editing a form entry 

### PR DESCRIPTION
**Pull request by MirnaGama**
_**Steps to reproduce:**_
1. Log in as Admin
2. Create a new form with an upload field in it
3. Drag this form on any page
4. Fill the form with a dummy file and submit
5. Navigate to Site Menu > Content and Data > Forms > Options for the test form > View Entries > Options for the entry > Edit > Click on one of the Upload Field Select button
6. See the pop-up window without options

Expected Result: The user can choose and upload a new file successfully.

Actual Results: The pop-up window comes up but does not have nay options only the title is visible. 

_**Solution proposed:**_

I did some investigation and discovered that there is no request being made after we click the upload file selection button. This happened because the variable responsible for storing the request URL (itemSelectorURL) was null, so the request could not be made at all.

This variable is created in a back-end class, and depends on the field's context having a valid **groupId**. After debugging I found that the groupId was not being set correctly in the field context.

### CODE REVIEW

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:relevant

**Comment by MirnaGama** [comment]
ci:test:forms

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
