### PR TITLE
LPS-151126

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issue: https://issues.liferay.com/browse/LPS-151542

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
Im closing this PR to send everything of the story in [another one](https://github.com/liferay-forms/liferay-portal/pull/1615) already with the changes requested by @rodrigopaulino , thanks!

**Pull request closed without merging**
