### PR TITLE
LPS-137175, LPS-137176

### PR DESCRIPTION
**Pull request by mlan0**

### CODE REVIEW

**Comment by marcelabc** [comment]
Hi @natocesarrego,
I already talked with @mlan0 about this issue on Slack 👍 He will fix the test and resend the PR, thank you!

**Review by miltonmc — COMMENTED** [review]
That seems fine to me, but this code is essentially  backend so I will ask to @natocesarrego to review it.

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcelabc** [comment]
I'm just reviewing to get the code locally 😉

**Comment by mlan0** [comment]
ci:test:sf

**Comment by mlan0** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:forward

**Comment by miltonmc** [comment]
> @mlan0 can you resend, Not sure what this means: 'Only true value will be accepted.'
>
> Only a true value will be accepted?
>
> Only true will be accepted?
>
> What's "true value"?
>
> Thx.
https://github.com/brianchandotcom/liferay-portal/pull/105504#issuecomment-898016035

**Review by marcelabc — COMMENTED** [review]
test

**Comment by natocesarrego** [comment]
Hi Team, I'm closing this pull due to conflicts and the high amount of messages. @mlan0, please resend.

Thanks.

**Pull request closed without merging**
