### PR TITLE
LRQA-70004

### PR DESCRIPTION
**Pull request by rafaellajordao**
Related Issue: https://issues.liferay.com/browse/LRQA-70004

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Great job, @rafaellajordao! :tada: 

I won't forward your pull just because of this [comment](https://github.com/liferay-forms/liferay-portal/pull/930/commits/80e03ef2aa9eabca48677f93e2050d184ae7a21c#r711006138).

**Comment by natocesarrego** [comment]
@rafaellajordao, the pull request created by Leticia which has conflicted with yours was already merged, can you please revisit this pull, rebase and forward it to Brian?

Feel free to trigger the command `ci:forward` when you perform the rebase.

Thanks!

**Pull request closed without merging**
