### PR TITLE
LPS-189715 Do not call on change for default locale

### PR DESCRIPTION
**Pull request by alinedoleron**
Ticket: https://liferay.atlassian.net/browse/LPS-189715

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:forms

**Review by rebsilva — APPROVED** [review]
LGTM @alinedoleron!! :tada:

**Comment by davisaints** [comment]
The failures are not related. This PR is good to go!

**Comment by alinedoleron** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:test:stable

**Pull request closed without merging**
