### PR TITLE
LRQA-70031 fix data provider tests

### PR DESCRIPTION
**Pull request by leticiachiu**
Related Issue: https://issues.liferay.com/browse/LRQA-70031

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by leticiachiu** [comment]
Hey @natocesarrego, could you see and forward this PR asap? it's affecting 6 tests on CI :woman_facepalming:

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
