### PR TITLE
LPS-121532 accesibility forms

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Related Issue: https://issues.liferay.com/browse/LPS-121532

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @georgel-pop-lr, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@georgel-pop-lr, can you please double check if the reported failure is related? It was reported as related 2 times.

Thanks.

**Comment by georgel-pop-lr** [comment]
> @georgel-pop-lr, can you please double check if the reported failure is related? It was reported as related 2 times.
> 
> Thanks.

Hi @natocesarrego,

Don't think is related to my changes,
I rebase it with master and checked here https://github.com/georgel-pop-lr/liferay-portal/pull/9 and all looks fine to me,
I send it to you a new pr https://github.com/liferay-forms/liferay-portal/pull/50

Regards

**Pull request closed without merging**
