### PR TITLE
LPS-139170 The boolean field values are not counting as one in form entries (Summary) when form has translations

### PR DESCRIPTION
**Pull request by mateusgomes01**
Related Issue: https://issues.liferay.com/browse/LPS-139170

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by mateusgomes01** [comment]
Hey @carolmariaabb could you please review the backend from this PR? Thanks! :)

**Comment by liferay-forms** [comment]
Hey @mateusgomes01, can you please fix the source formatter issues and resend? Thanks

**Pull request closed without merging**
