### PR TITLE
LPS-188990 Create integration test for export/import with Forms with object storage type

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related ticket: [LPS-188990](https://liferay.atlassian.net/browse/LPS-188990)

Obs.: In addition to creating the integration test. I had to adapt the actual code. Because the ERC was not being included in the `settingsDDMFormValues` of the `ddmFormInstance` object, therefore it would not be present in the `ddmFormInstance` xml file generated on the export. 
That's why I added this [update](https://github.com/liferay-forms/liferay-portal/pull/2264/files#:~:text=_ddmFormInstanceLocalService.updateFormInstance). But, for this, the ERC needs to be in the `fieldValues` `JSONArray`, so that required more changes.

I discovered this because it was required to do the test.

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by devpedrotavares** [comment]
ci:test:sf

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:test:forms

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
Hey @devpedrotavares 

As discussed, we cannot change how we add the ERC now, it will break potential users. We need to create a test without changing the code. I will close this PR Thank you.

**Comment by murilostodolni** [comment]
ci:close

**Pull request closed without merging**
