### PR TITLE
LPS-130226 Forms data from site template is imported to sites after creation when it is referenced by a widget

### PR DESCRIPTION
**Pull request by larissacribeiro**
**Related Issue**: [LPS-130226](https://issues.liferay.com/browse/LPS-130226)

### CODE REVIEW

**Comment by larissacribeiro** [comment]
ci:test:sf

**Comment by larissacribeiro** [comment]
ci:test:relevant

**Comment by larissacribeiro** [comment]
ci:test:forms

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
