### PR TITLE
LPS-151677 Change _getResouceBundle to get the user portal language

### PR DESCRIPTION
**Pull request by leticia-maciel**
This PR intends to translate the Submit button for the language set by the User. 

The language set on User Settings has higher priority than the Site default language. So functional buttons like Submit have to be translated with the User language preferences. 

Thanks :)

### CODE REVIEW

**Comment by leticia-maciel** [comment]
ci:test:sf

**Comment by leticia-maciel** [comment]
ci:test:relevant

**Comment by leticia-maciel** [comment]
ci:test:sf

**Comment by leticia-maciel** [comment]
ci:test:sf

**Comment by leticia-maciel** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @leticia-maciel, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:reevaluate:1387401_159

**Comment by liferay-forms** [comment]
Hey @leticia-maciel, can you please check if these failures are related to your changes? Thanks

**Comment by leticia-maciel** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @leticia-maciel, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @leticia-maciel, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
Hey @leticia-maciel, can you please check if these failures are related to your changes? Thanks

**Comment by leticia-maciel** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @leticia-maciel, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
Hey @leticia-maciel, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by liferay-forms** [comment]
ci:test:relevant

**Pull request closed without merging**
