### PR TITLE
LPS-143113

### PR DESCRIPTION
**Pull request by rodrigopaulino**
I'm putting back the functionality with the necessary adaptations here.

Related Issue: https://issues.liferay.com/browse/LPS-143113

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by rodrigopaulino** [comment]
ci:stop

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:stop

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hey @rodrigopaulino, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
These failures are consistently happening, but are unrelated to this PR.

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
ci:forward

**Pull request closed without merging**
