### PR TITLE
LPS-160242

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Review by rodrigopaulino — APPROVED** [review]
Awesome find! This is way better. Thanks a lot for your contribution, @marianoalvarosaiz.
LGTM! 🎉

**Comment by marianoalvarosaiz** [comment]
Thanks @rodrigopaulino !

**Comment by marianoalvarosaiz** [comment]
Added baseline commit.

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by marianoalvarosaiz** [comment]
StringUtilTest failure unrelated. Opened LPS-151144, LPS-151221 for this issue in several branches.

**Comment by rodrigopaulino** [comment]
Hi, @marianoalvarosaiz. Since your code includes changes to petra, we will be running a lot of tests unrelated to forms. Therefore, we should keep trying until it passes.

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Hi, @marianoalvarosaiz. May I suggest you removing the char constant from petra and putting the literal right there in the number util? I believe this would have passed a long time if it wasn't these amount of tests. We'll see if Brian asks for that or if he makes this contribution himself. What do you think?

**Comment by rodrigopaulino** [comment]
I'm closing this PR due to inactivity. We'll reopen it if you still want to move forward. 🙂

**Comment by marianoalvarosaiz** [comment]
see https://github.com/liferay-forms/liferay-portal/pull/1939

**Comment by marianoalvarosaiz** [comment]
see https://github.com/liferay-forms/liferay-portal/pull/1940

**Pull request closed without merging**
