### PR TITLE
LPS-124603 Remove dataEngineSidebar feature flag

### PR DESCRIPTION
**Pull request by alinedoleron**
**Ticket**: [LPS-124603](https://issues.liferay.com/browse/LPS-124603)

### Related Issues
The following issues must be fixed prior to remove the feature flag:
- [x] [LPS-129810](https://issues.liferay.com/browse/LPS-129810) Enable data sources for Text Field Autocomplete #164 
- [x] [LPS 131380](https://issues.liferay.com/browse/LPS-131380) Sidebar items are cut off the screen on the bottom #199

### Notes
- Data Engine not supports field type changing [LPS-131379](https://issues.liferay.com/browse/LPS-131379)

### CODE REVIEW

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@miltonmc and @alinedoleron, I've just analyzed the CI results and there is a chance of a lot of failures be flaky, therefore I'll rerun the tests to make sure the results are valid.

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
Closed in favor of #204

**Pull request closed without merging**
