### PR TITLE
LPS-198962

### PR DESCRIPTION
**Pull request by icgsbr**
https://liferay.atlassian.net/browse/LPS-198962

### CODE REVIEW

**Comment by icgsbr** [comment]
ci:test:relevant

**Comment by icgsbr** [comment]
ci:test:stable

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by alinedoleron** [comment]
ci:test:forms

**Comment by alinedoleron** [comment]
ci:forward:force

**Comment by alinedoleron** [comment]
ci:forward:force

**Pull request closed without merging**
