### PR TITLE
LPS-135057

### PR DESCRIPTION
**Pull request by mateusgomes01**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by mateusgomes01** [comment]
ci:test:relevant
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by mateusgomes01** [comment]
ci:test:relevant
ci:test:sf

**Comment by carolmariaabb** [comment]
Resent https://github.com/liferay-forms/liferay-portal/pull/737

**Pull request closed without merging**
