### PR TITLE
[TS] LPS-190226 Success Page is not shown when form was not created in the default language

### PR DESCRIPTION
**Pull request by ricardocousolr**
Hi @liferay-forms team!

This is a solution for [LPS-190226](https://liferay.atlassian.net/browse/LPS-190226). 

The problem is that the success page is associated to the default language even when the form is created in a different language. 

The solution is to use the current page when initializing the state.

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by cgmonte** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:stable

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:stop

**Pull request closed without merging**
