### PR TITLE
LPS-161170 Forms not editable after upgrade

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

The "paginated" pagination mode was removed from the Forms editor in [LPS-135337](https://issues.liferay.com/browse/LPS-135337).
 "multi-pages" was introduced instead.

This fix makes the "multi-pages" mode load instead of the old "paginated" mode.

Best regards,
István

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Dear Team,

Please let me know if there are any updates on the review.

Thank you and best regards,
István

**Comment by IstvanD** [comment]
Dear Team,

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by rodrigopaulino** [comment]
Hi, @IstvanD.

Sorry for the wait. I'll be checking on your PR shortly.

Thanks for understanding.

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Review by rodrigopaulino — CHANGES_REQUESTED** [review]
Hey, @IstvanD. Thanks for contributing.

I believe it's better to simply create an upgrade process. This leaves a technical debt in our database.
Could you please send a new pull with it?
Thx!

**Comment by rodrigopaulino** [comment]
ci:stop

**Comment by rodrigopaulino** [comment]
ci:close

**Comment by IstvanD** [comment]
Hi @rodrigopaulino thank you for the feedback.
I have created a new upgrade process.
https://github.com/liferay-forms/liferay-portal/pull/1935

**Pull request closed without merging**
