### PR TITLE
[TS] LPS-197993 Sanitize Captcha HTML from Request

### PR DESCRIPTION
**Pull request by gergelyszalay**
Hi Team,

May I ask to review this PR?

issue is: [LPS-197993](https://liferay.atlassian.net/browse/LPS-197993), When enable captcha for forms, in the html request we are sending html data.

solution : html parameter is included in the page, before fetching we sanitize the data. : https://github.com/gergelyszalay/liferay-portal/blob/9167d952f7e0f551d7cc08f1cb22e03b56d6f605/modules/apps/data-engine/data-engine-js-components-web/src/main/resources/META-INF/resources/js/utils/evaluation.es.js#L42

Tested locally the solution.

BR,
Gege

### CODE REVIEW

**Comment by gergelyszalay** [comment]
ci:test:sf

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
