### PR TITLE
[IPT] LPS-199345 Form radio buttons do not adhere to best practise keyboard navigation

### PR DESCRIPTION
**Pull request by vngoliveira**
Based on this [thread](https://liferay.slack.com/archives/C04CPMRMXAL/p1697483915891529)
Related issue [LPS-199345](https://liferay.atlassian.net/browse/LPS-199345)
LPP ticket [LPP-51200](https://liferay.atlassian.net/browse/LPP-51200)

### CODE REVIEW

**Comment by vngoliveira** [comment]
ci:test:stable

**Comment by vngoliveira** [comment]
ci:test:relevant

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by cgmonte** [comment]
ci:reevaluate:1297401_8416

**Comment by cgmonte** [comment]
hi @vngoliveira! it looks like updating the snaps wasn't enough, but I am not sure. Some of the poshi test failures here may be related. Can you check or look for help from QA

**Comment by davisaints** [comment]
Hi @vngoliveira, some tests are failing because the radio options are inline:

testray-liferay-com-reports-production-logs-2023-10-test-1-37-test-portal-acceptance-pullrequest-master-15029-functional-tomcat90-mysql57-chrome100-jdk8-1-1-LocalFile-FormsFieldsets_PreserveTheAutoCompleteProperty-index-html-gz-authuser-0

Can you take a look at this?

**Comment by vngoliveira** [comment]
ci:test:sf

**Comment by vngoliveira** [comment]
ci:test:stable

**Comment by vngoliveira** [comment]
ci:test:relevant

**Comment by davisaints** [comment]
ci:stop

**Comment by davisaints** [comment]
ci:stop

**Comment by davisaints** [comment]
ci:test:relevant

**Comment by davisaints** [comment]
ci:test:forms

**Comment by davisaints** [comment]
ci:test:data-engine

**Comment by davisaints** [comment]
ci:test:data-engine

**Comment by davisaints** [comment]
ci:test:stable

**Comment by davisaints** [comment]
ci:test:data-engine

**Comment by davisaints** [comment]
ci:test:relevant

**Comment by vngoliveira** [comment]
ci:test:sf

**Comment by vngoliveira** [comment]
ci:test:relevant

**Comment by vngoliveira** [comment]
ci:test:data-engine

**Comment by vngoliveira** [comment]
ci:test:forms

**Comment by vngoliveira** [comment]
See https://github.com/liferay-forms/liferay-portal/pull/2381

**Pull request closed without merging**
