### PR TITLE
LPS-124000 not reseting fields unless it is explicitly not native

### PR DESCRIPTION
**Pull request by linolaoj**
Related Issue: https://issues.liferay.com/browse/LPS-124000

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:app-builder

**Comment by natocesarrego** [comment]
@linolaoj, once this issue is also affecting App Builder, I'll run its suite to see how it goes.

Thanks.

**Comment by natocesarrego** [comment]
According to @guipfreire, the test failures reported by App Builder suite aren't related to this pull, @linolaoj. 😉

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
