### PR TITLE
LPD-21428 Make possible the ObjectOutputStream serialization for DDMFormFieldValidationExpression

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPD-21428

### CODE REVIEW

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:test:stable

**Comment by p-albuquerque** [comment]
Hi @carolmariaabb if the _stable_ fails again, can I send it manually?

**Comment by carolmariaabb** [comment]
@p-albuquerque Let's wait for the results before making a decision.

**Pull request closed without merging**
