### PR TITLE
LPD-34101 Adding new property to custom form field type does not work if it is named 'options'

### PR DESCRIPTION
**Pull request by larissacribeiro**
Related Issue: [LPD-34101](https://liferay.atlassian.net/browse/LPD-34101)

### CODE REVIEW

**Comment by larissacribeiro** [comment]
@igor-franca I'll let you know when you can review this, since it's still missing the test. Thanks!

**Comment by larissacribeiro** [comment]
ci:test:playwright

**Comment by larissacribeiro** [comment]
ci:test:sf

**Comment by larissacribeiro** [comment]
ci:test:playwright

**Comment by larissacribeiro** [comment]
ci:test:sf

**Comment by larissacribeiro** [comment]
@igor-franca the playwright test has been replaced with a poshi one due to inconsistencies between local and ci results. You can review this now, thanks!

**Comment by igor-franca** [comment]
Hi @larissacribeiro, good job with the fix and poshi test!

**Review by igor-franca — CHANGES_REQUESTED** [review]
Hey @larissacribeiro, could you add information in your dependency addition commit message stating that the changes were auto generated?

After renaming the commit message, feel free to run the CI poshi routine.

**Comment by larissacribeiro** [comment]
ci:test:forms

**Comment by larissacribeiro** [comment]
ci:test:relevant

**Comment by larissacribeiro** [comment]
ci:test:data-engine

**Comment by larissacribeiro** [comment]
ci:test:forms

**Comment by larissacribeiro** [comment]
ci:test:sf

**Comment by larissacribeiro** [comment]
ci:test:relevant

**Comment by larissacribeiro** [comment]
ci:forward:force

**Comment by larissacribeiro** [comment]
ci failures are unrelated.

**Comment by larissacribeiro** [comment]
ci:test:stable

**Comment by larissacribeiro** [comment]
ci:forward:force

**Pull request closed without merging**
