### PR TITLE
LPS-203306 Allow users to configure fieldName/fieldValues for Web content Structures

### PR DESCRIPTION
**Pull request by devpedrotavares**
Follow up on: https://github.com/liferay-forms/liferay-portal/pull/2445

Related ticket: [LPS-203306](https://liferay.atlassian.net/browse/LPS-203306)

### CODE REVIEW

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:test:forms

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:stable

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:forms

**Comment by rebsilva** [comment]
ci:test:stable

**Comment by rebsilva** [comment]
after comparing the failures on the forms suite, all the failures are unrelated :tada: just waiting for the stable suite to finish

**Comment by rebsilva** [comment]
ci:test:data-engine

**Comment by rebsilva** [comment]
ci:test:echo

**Comment by rebsilva** [comment]
the tests that are failing on relevant and are related:

- WebContentStructures#ViewAndEditAsWellAsDeleteStructureWithAllFields
- LocalizedSimpleFieldsWebContent#DuplicateAndEditTranslatedFieldsWithOptions
- LocalizedSimpleFieldsWebContent#AddAndEditTranslatedFieldsWithOptions
- LocalizedSimpleFieldsStructure#TranslateStructureWithAllFields
- LocalizedNestedFieldsWebContent#AddAndEditTranslatedFieldsWithOptions

**Comment by rebsilva** [comment]
ci:stop

**Comment by rebsilva** [comment]
ci:test:data-engine

**Comment by rebsilva** [comment]
ci:test:echo

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:data-engine

**Comment by rebsilva** [comment]
these are only some of the tests failing of the echo suite, and they all seem related to the changes; i think on total there are more than 20 tests related failing

Screenshot from 2024-02-02 11-41-07

**Comment by guilhermedcamacho** [comment]
Hey @rebsilva and @marcelabc , I have a doubt here, has the code been approved and are we just in the phase of checking the CI results? If so, I would ask you to add the label "Dev Approved". Thanks! :)

**Review by rebsilva — APPROVED** [review]

**Comment by marcelabc** [comment]
Analyzing CI result

**Comment by marcelabc** [comment]
ci:report:2534061661

**Comment by marcelabc** [comment]
Talked to @cgmonte on Slack.
He will continue this PR :+1:

**Comment by cgmonte** [comment]
Thanks @rebsilva for following up with these test result analysis :heart:

**Comment by cgmonte** [comment]
Resent [here](https://github.com/liferay-forms/liferay-portal/pull/2488).

**Pull request closed without merging**
