### PR TITLE
LPS-151592 When upgrading from 6.2 to 7.4, the pollsQuestion table do…

### PR DESCRIPTION
**Pull request by SamZiemer**
Related Issue: https://issues.liferay.com/browse/LPS-151592

LPS-138675 removed the polls modules, and all related polls upgrades, however, when upgrading from Liferay 6.2, the polls tables do not have the lastPublishDate column so an exception is thrown when the PollsToDDMUpgradeProcess is run.

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
