### PR TITLE
LPD-19213 Change DDMFormRuleConverterImpl to consider the case where spiDDMFormRuleConditions is empty 

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related LPP: https://liferay.atlassian.net/browse/LPP-52934

Subtask: https://liferay.atlassian.net/browse/LPD-19213

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:forms

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
