### PR TITLE
LPS-139806 Add css styles for for checkbox and checkboxMultiple

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-139806

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
Hi @miltonmc, I will close this pull request because now this problem is related to a different[LPS](https://issues.liferay.com/browse/LPS-142127) Ticket

**Pull request closed without merging**
