### PR TITLE
LPS-137517

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related ticket: https://issues.liferay.com/browse/LPS-137517

### CODE REVIEW

**Review by carolmariaabb — APPROVED** [review]

**Comment by rodrigopaulino** [comment]
The frontend part was also reviewed by @miltonmc in a pair-reviewing session.

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
Looks like there's an error on ddm-form-web caused by these changes.

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
I'm attributing the "Good to Go" label since the additional changes were merely the same as [this one](https://github.com/liferay-forms/liferay-portal/pull/837/files#diff-2da13f96675911e11f430cb0e1e5a19f81572d9929a970563348ef3b2d35e219).

**Comment by rodrigopaulino** [comment]
ci:forward

**Pull request closed without merging**
