### PR TITLE
[TS] [Urgent] LPS-191314 Navigation does not work while embedding Documents and Media portlet via Widget Template

### PR DESCRIPTION
**Pull request by mbowerman**
Ticket: [LPS-191314](https://liferay.atlassian.net/browse/LPS-191314)
See also [PTR-4103](https://liferay.atlassian.net/browse/PTR-4103) for further discussion.

### CODE REVIEW

**Review by carolmariaabb — CHANGES_REQUESTED** [review]
Hey @mbowerman,

These changes were made in the `portlet-display-template` module, which is not the responsibility of the BPM team.

You would need to send this PR to the correct team (which appears to be the Echo team) or you can change to use the `themeDisplay.getRequest()` in this [file](https://github.com/liferay/liferay-portal/blob/379d5d45bc941efe624948991865b40fe63e5c14/modules/apps/dynamic-data-mapping/dynamic-data-mapping-taglib/src/main/resources/META-INF/resources/template_renderer/start.jsp#L24) instead (`DDM` Module).

**Comment by mbowerman** [comment]
Hi @carolmariaabb, Thanks, I re-sent the pull request to the Echo Team here: https://github.com/liferay-echo/liferay-portal/pull/12963

Do you know if there is an easy way to tell which Team owns a given module? I tried searching through the commit history of the `portlet-display-template-impl` module to see if I could see which team was making the most changes to it, but it seemed to have a very sparse history that largely just consisted of commits coming from the Core Infra Team or SF team when they were making sweeping changes that affected many modules.

**Comment by carolmariaabb** [comment]
Resent https://github.com/liferay-echo/liferay-portal/pull/12963

**Comment by jkappler** [comment]
Sorry to chime in :D. We also have this component list https://liferay.atlassian.net/jira/software/c/projects/LPS/components?filter=&orderDirection=DESC&orderField=NAME&page=1

Hope it helps. I already fw the PR. Thanks @mbowerman and @carolmariaabb!

**Pull request closed without merging**
