### PR TITLE
LPS-116665 Adjust tests to consider information that a field is required

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related Issue: https://issues.liferay.com/browse/LPS-116665

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
**/cc** @georgel-pop-lr

**Comment by natocesarrego** [comment]
Great job, @carolmariaabb! 😄 👏 

@georgel-pop-lr, we're very close to the 7.3 release, in light of this we'll hold a little bit to forward this pull to be merged on master to avoid instability on our product, if however you've some problem with this procedure please let me know.

Thanks!

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
