### PR TITLE
LPS-171686

### PR DESCRIPTION
**Pull request by alinedoleron**
Ticket: https://issues.liferay.com/browse/LPS-171686

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by alinedoleron** [comment]
Manually forwarded: https://github.com/brianchandotcom/liferay-portal/pull/128124

**Pull request closed without merging**
