### PR TITLE
LPS-162045 Should not parse value if the field type is text

### PR DESCRIPTION
**Pull request by binhtran92**
Hi team,
This is related to the ticket https://issues.liferay.com/browse/LPS-162045
Please review.
Thanks

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
SF failure not related to this PR.

**Comment by carolmariaabb** [comment]
@binhtran92, feel free to manually forward this PR to Brian. As I commented before, the SF failure is not related to this PR.

Thanks!

**Comment by binhtran92** [comment]
Thank you @carolmariaabb 
I forwarded it here: https://github.com/brianchandotcom/liferay-portal/pull/124577

**Pull request closed without merging**
