### PR TITLE
[TS] LPS-167438 - select fields need an accessible label explicitly associated to them

### PR DESCRIPTION
**Pull request by wanderlast**
Hi @liferay-forms team!

https://issues.liferay.com/browse/LPP-45746

This is a fix for an accessibility issue related to labels and input fields. Previously all labels fields were explicitly related to their input fields, but this was removed in LPS-116665 since technically the 3.3.2 success criterion would still be covered. However, without this relation we run into issues with success criterion 1.3.1. See https://www.w3.org/WAI/WCAG21/Techniques/html/H44 which notes that it should be explicitly related a swell as LPS-151194 where the issue was fixed for the Text and Numeric fields. This fix adds Select/Select from List fields as another field that should have a 'for' attribute to explicitly relate the label and form field.

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by alinedoleron** [comment]
ci:forward

**Pull request closed without merging**
