### PR TITLE
LPS-177235 Fix form submission

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related Issue: https://issues.liferay.com/browse/LPS-177235

### CODE REVIEW

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:reevaluate:1377401_9540

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
This issue is fixed by https://github.com/brianchandotcom/liferay-portal/pull/131134

**Pull request closed without merging**
