### PR TITLE
LPS-186560 Fix on some resolutions form fields panel covers some part…

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
…s of the page, for example the tree dots actions

### CODE REVIEW

**Comment by marcelabc** [comment]
Hey @rebsilva,
Could you review this PR please? :smile:

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
Sue @marcelabc! I will review it later today :blush:

**Review by rebsilva — APPROVED** [review]
LGTM! :tada:

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
> LGTM! tada

I rebased with master to see if all tests pass.

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:relevant

**Pull request closed without merging**
