### PR TITLE
LPD-31144 Save and restore state in rich text

### PR DESCRIPTION
**Pull request by DiegoHu97**
LPD-31144 Save and restore state in rich text

# What is this trying to solve?

In Content Management team we are implementing undo/redo component for Web Content (https://liferay.atlassian.net/browse/LPD-22301), in this PR we are sending the part that handles the rich text editor.

[Link to ticket](https://liferay.atlassian.net/browse/LPD-31144)

# How am I fixing it?

Now we have a historyReducer component that handles the changes that we make in the undo/redo for data engine components. We have added an event that fires the event when clicking on undo/redo buttons and change the value of the rich text editor.

Only these two commits needs to be reviewed, the other ones are already in [Brian's repo pending for submit](https://github.com/brianchandotcom/liferay-portal/pull/152716):
- [LPD-31144 Handle undo/redo events for rich text](https://github.com/liferay-forms/liferay-portal/pull/2576/commits/e7f52ed33aeaed1cfd029dfae07a1b9c8567e29f)
- [LPD-31144 Save initial state for ddm fields](https://github.com/liferay-forms/liferay-portal/pull/2576/commits/9b62554db4a5db2d414f1cba502eba1039f118ee)

# How can I test it?

**Steps of the test:**

- Enable FF 'LPD-11228': true
- Enable FF 'LPD-15596': true 
- Create a WC
- Fill the title 
- Fill the content field
- Click on undo button
- See content field gets empty
- Click on redo button
- See the content if filled

# Tests are not needed

We don't need tests for every data engine component, we already have this test that checks undo/redo buttons work for data engine components. **journalArticle.spec.ts > 'LPD-26863: Undo/Redo buttons work with content field'** (https://github.com/liferay/liferay-portal/blob/ab1686f25a5a3b47aaca2b02287fe377ef470e6c/modules/test/playwright/tests/journal-web/journalArticle.spec.ts#L219)

CC: @ambrinchaudhary

### CODE REVIEW

**Comment by rebsilva** [comment]
i will be reviewing this PR later today, as it is a follow-up if this PR: https://github.com/liferay-forms/liferay-portal/pull/2568

**Comment by rebsilva** [comment]
hi @DiegoHu97!
while testing i've found some behaviors:
- if we publish a web content, go back, change something inside the text, revert and publish again, the changes won't be persisted
- sometimes this warning/error triggers even with the web content having a valid title

am i doing something wrong here?


https://github.com/user-attachments/assets/8caaa058-313b-4767-984b-e98367a02d2c

**Comment by DiegoHu97** [comment]
Hey @rebsilva ,  this issue is controlled by us, we have a subtask to resolve it [https://liferay.atlassian.net/browse/LPD-32874,](https://liferay.atlassian.net/browse/LPD-32874,) for this PR we have to test only that undo/redo for rich text is working well :stuck\_out\_tongue:

**Comment by rebsilva** [comment]
nice, thanks for letting me know @DiegoHu97!

**Review by rebsilva — APPROVED** [review]
LGTM! :tada:

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:data-engine

**Comment by carolmariaabb** [comment]
ci:test:data-engine

**Comment by rebsilva** [comment]
ci:test:forms

**Comment by rebsilva** [comment]
hi @DiegoHu97 the PR has conflicts with the master, could you please update?

**Comment by DiegoHu97** [comment]
Hey @rebsilva I've just updated the pr, thanks!

**Comment by rebsilva** [comment]
great, thanks a lot!

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
