### PR TITLE
LPS-146979 Remove feature flag for date validations

### PR DESCRIPTION
**Pull request by miltonmc**
Related Issue: https://issues.liferay.com/browse/LPS-146979

This reverts commit 93ec0463cae99d879702a2d37fa9b07e181d86b4.

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
Hey @miltonmc, can you please fix the source formatter issues and resend? Thanks

**Comment by miltonmc** [comment]
ci:test:sf

**Review by carolmariaabb — APPROVED** [review]

**Comment by miltonmc** [comment]
ci:stop

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @miltonmc, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
Hey @miltonmc, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:forms

**Comment by miltonmc** [comment]
ci:test:data-engine

**Comment by carolmariaabb** [comment]
> ### ❌ ci:test:forms - 7 out of 11 jobs passed in 2 hours 35 minutes
> Click here for more details.

Unrelated failures

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
