### PR TITLE
LPS-155772

### PR DESCRIPTION
**Pull request by alinedoleron**
Ticket: https://issues.liferay.com/browse/LPS-155772

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Review by miltonmc — CHANGES_REQUESTED** [review]

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:relevant

**Review by miltonmc — APPROVED** [review]
LGTM!

**Pull request closed without merging**
