### PR TITLE
LPS-139709

### PR DESCRIPTION
**Pull request by natocesarrego**
Related issue: https://issues.liferay.com/browse/LPS-139709

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@rodrigopaulino, can you please review this pull?

It basically creates a new dedicated category to hold Maps Providers settings.

Thanks in advance

**Comment by rodrigopaulino** [comment]
Just started reviewing.

**Review by rodrigopaulino — APPROVED** [review]
LGTM! 🎉

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
@natocesarrego, I see the tests have failed for unrelated reasons. It leads me to believe this `portal-license-smoke-jdk8` is flaky. I'll report in the QA Slack channel.

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
@natocesarrego. Feel free to manually forward this to Brian: https://liferay.slack.com/archives/CL84ZPHAT/p1632492467110700

**Comment by natocesarrego** [comment]
ci:forward

**Comment by natocesarrego** [comment]
Thanks for the assistance, @rodrigopaulino. I didn't forward to Brian due to some changes discussed this morning with Victor Valle and Brian which were just applied to this pull. :wink:

**Pull request closed without merging**
