### PR TITLE
[TS] LPS-171400 NullPointerException is thrown during Upgrade 7.2 to 7.4 when using specifics fields in Forms caused by JSONFactory being null - REGRESSION BUG

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-171400

:warning: This is a regression caused by https://issues.liferay.com/browse/LPS-143631 :warning: 

During the upgrade, the DDMFormFieldTypeReportProcessor classes are created here calling the constructor:
 - https://github.com/liferay-forms/liferay-portal/blob/347d0d9e32ce975c2f9ac0cc6070b73ebb1a50c2/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/internal/upgrade/v3_7_3/DDMFormInstanceReportUpgradeProcess.java#L150-L175

So the JSONFactory object is not correctly populated in the DDMFormFieldTypeReportProcessor classes.

We cannot load them as OSGI components because the module is not ready yet, so I am adding a new constructor in order to be able to set the JSONFactory.

Let me know if you think there are better alternatives.

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:reevaluate:1387401_5883

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
Hey @jorgediaz-lr, 
I approved this PR, but now I noticed that you created the constructor and kept the @Reference in the variable declaration. I could not find an example of this scenario. I believe that we should refactor the usages only to use the constructor and remove the @Reference. What is your opinion?

**Review by marcelabc — CHANGES_REQUESTED** [review]
I approved this PR, but now I noticed that you created the constructor and kept the @Reference in the variable declaration. I could not find an example of this scenario. I believe that we should refactor the usages only to use the constructor and remove the @Reference. What is your opinion?

**Comment by jorgediaz-lr** [comment]
Hi @marcelabc 

We cannot remove the default constructor without parameters and the `@reference` because all DDMFormFieldTypeReportProcessor classes are registered in the DDMFormFieldTypeReportProcessorRegistry, see:

- https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/internal/report/DDMFormFieldTypeReportProcessorRegistryImpl.java#L30-L56

and they are used here:

- https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/service/impl/DDMFormInstanceReportLocalServiceImpl.java#L186-L221

If we remove the default constructor the components are not going to be created and registered there.

So my idea is:

- Constructor with JSONFactory parameter => used when the DDMFormFieldTypeReportProcessor classes are created during upgrade time, as they are instantiate using the "new" operator and adding the JSONFactory as a constructor parameter
- Constructor with no parameters => used when the DDMFormFieldTypeReportProcessor classes  are created as OSGI components and the JSONFactory is added using the `@reference`. There components are registered in the DDMFormFieldTypeReportProcessorRegistry

My first attempt was to use the `_ddmFormFieldTypeReportProcessorRegistry.getDDMFormFieldTypeReportProcessor(type)` method during the upgrade process but it doesn't work because the OSGI components belong to the same module that it is being upgraded.

Let me know if you have additional questions or ideas.

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
