### PR TITLE
[TS] LPS-170726 Accessibility fix for invalid language, use a hyphen in the language attribute

### PR DESCRIPTION
**Pull request by orsolyaDekany**
Hi @liferay-forms ,

Wave accessibility tool detected an invalid language on a non-admin site.
To meet the WCAG2.1 [3.1.1 criteria](https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=311#language-of-page), I replaced the dash with a hyphen. I have found one example on the Portal where the "lang" attribute is used, that is CKEditor in the Web Content for example, the language configs use hyphens as well.

https://issues.liferay.com/browse/LPS-170726

Could you please review it?
Thank you.

### CODE REVIEW

**Comment by orsolyaDekany** [comment]
ci:test:sf

**Comment by orsolyaDekany** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Hey @cgmonte, could you please review this PR?

**Comment by orsolyaDekany** [comment]
ci:test:relevant

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by cgmonte** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by cgmonte** [comment]
ci:test:forms

**Review by carolmariaabb — CHANGES_REQUESTED** [review]
Hi @orsolyaDekany,

There are many tests failing because of your changes. That said, can you simplify by only changing the `lang` attribute value ([here](https://github.com/liferay/liferay-portal/blob/f6e6884b8ac840634c0540b537655b588241b76b/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/src/main/resources/META-INF/resources/Text/Text.es.js#L167))? Something like:

`lang={editingLanguageId.replace('_', '-')}`

In addition, could you also run `yarn test -u` in the `modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/` folder to update the snapshots? Commit the changes as `LPS-170726 Update snapshots`.

Thanks!

**Pull request closed without merging**
