### PR TITLE
LPS-198962-reverts

### PR DESCRIPTION
**Pull request by icgsbr**
# Jira Link
- https://liferay.atlassian.net/browse/LPS-198962

# General Info
- All commits from [LPS-153738](https://liferay.atlassian.net/browse/LPS-153738) are being reverted since they cause the issue reported on the ticket above.

   - The issue lies on the attribution of onChange event functionality to onBlur, causing the onChange to be executed two times resulting in a double refresh, which caused the fields to vanish.
   
   - Fixes the collision of events.
   
- Some commits from [LPS-198962](https://liferay.atlassian.net/browse/LPS-198962) are being reverted since they are no longer needed to fix the issue.
   
   - We don't need to handle events collision anymore, therefore we need to get rid of the timeout.
   
   - The only commit which will stay is related to the conflict between the validation time and the field addition event, by making the validation faster we avoid and minimize the vanishing cases when we click the add button and the validation isn't completed.

### CODE REVIEW

**Comment by icgsbr** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
Hey @rebsilva 
Could you help me analyze if this revert would have any regressions (besides the original bug repairing) ?
Thank you

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
i will review this as soon as possible, thanks!

**Comment by rebsilva** [comment]
@icgsbr there are a lot of frontend tests failing, could you please take a look if they are related? thanks!

**Comment by rebsilva** [comment]
as discussed with @samuelromeiro and @gabrielwas, it is required to find a solution that fixes both the bug from the commit that is being reverted and the issues with the repeatable fields. for more info please talk to us about it, thanks!

**Pull request closed without merging**
