### PR TITLE
[TECHNICAL SUPPORT] LPS-116665 Revert "LPS-116665 Adjust tests to consider information that a field is required"

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related Issue: https://issues.liferay.com/browse/LPS-116665

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hey @rodrigopaulino, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @rodrigopaulino, can you please check if these failures are related to your changes? Thanks

**Comment by rodrigopaulino** [comment]
> Hey @rodrigopaulino, can you please check if these failures are related to your changes? Thanks

I sure can, robot. The only unique failure seems to be **unrelated** to the changes. Please let me know if there's some else you need me to check.

Best.

**Comment by natocesarrego** [comment]
Hi @rodrigopaulino, your pull makes sense to me. 🙂

@carolmariaabb, can you please review it too? Specially, the Poshi tests changes. If you approve it, please trigger `ci:forward`.

Thanks.

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
