### PR TITLE
LPS-199345 Fix forms radio buttons keyboard navigation

### PR DESCRIPTION
**Pull request by rebsilva**
Related issue: https://liferay.atlassian.net/browse/LPS-199345

Hello Reviewer! :cherry_blossom:

This PR fixes the keyboard navigation of radio buttons inside forms, by introducing the `<ClayRadioGroup>`  before `<ClayRadio>` and also putting the `onChange` on `<ClayRadioGroup>`. On the `onChange` I'm sending `{target: {value}}` because the function expects an event; you can see a similar approach on `Numeric.tsx line 294` on `dynamic-data-mapping`.

Let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by rebsilva** [comment]
ci:test:forms

**Comment by rebsilva** [comment]
ci:test:data-engine

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by davisaints** [comment]
ci:test:forms

**Comment by davisaints** [comment]
ci:test:relevant

**Comment by davisaints** [comment]
Hey   @rebsilva, I updated the last commit that I sent yesterday and added another one. Can you please cherry-pick them?

Commits: [2313b08](https://github.com/rebsilva/liferay-portal/pull/142/commits/2313b08509b986363d61e23e0b98cc953dac7129) and [beaa810](https://github.com/rebsilva/liferay-portal/pull/142/commits/beaa81033fd6bf4e6328243c58b994845970560f)

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:forms

**Comment by davisaints** [comment]
ci:forward:force

**Pull request closed without merging**
