### PR TITLE
LRQA 72440

### PR DESCRIPTION
**Pull request by guivilarim**
Related Issue: https://issues.liferay.com/browse/LRQA-72440

- LRQA-72440 change deleteField macro sikuli function
- LRQA-72440 change RobotType function in AddWCWithSecondComplexStructure test
- LRQA-72440 change SikuliUploadTempFile to UploadTempFile on addMultiplePG macro

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by guivilarim** [comment]
ci:foward

**Comment by guivilarim** [comment]
ci:forward

**Pull request closed without merging**
