### PR TITLE
LPS-156051

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://issues.liferay.com/browse/LPS-156051

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:forms

**Review by rodrigopaulino — COMMENTED** [review]
Hi, @carolmariaabb. Thanks for your pull.
Do you happen to know why is [DDMDataDefinitionConverterImpl.java](https://github.com/liferay-forms/liferay-portal/pull/1867/commits/83ec8c235f0838b4ac6782db5a6c665050a52ed5#diff-ecce0ede8890ad524549589a5a0517f1e2bdc5748038ba85694ab15663599714) being used inside the DDMStructure local service? Also, why is this replaceAll call being used in two different upgrade processes?

**Comment by rodrigopaulino** [comment]
Hey, @miltonmc. Could you please review the last commit of this pull? Thanks!

**Comment by carolmariaabb** [comment]
> Hi, @carolmariaabb. Thanks for your pull. Do you happen to know why is [DDMDataDefinitionConverterImpl.java](https://github.com/liferay-forms/liferay-portal/pull/1867/commits/83ec8c235f0838b4ac6782db5a6c665050a52ed5#diff-ecce0ede8890ad524549589a5a0517f1e2bdc5748038ba85694ab15663599714) being used inside the DDMStructure local service?

It's only used for web content structures and was added because of [LPS-128325](https://issues.liferay.com/browse/LPS-128325) (see this [commit](https://github.com/liferay-data-engine/liferay-portal/pull/281/commits/cd49ad93d4b6a4d9664ba572923a244735d60835) and this [commit](https://github.com/liferay-data-engine/liferay-portal/pull/281/commits/13df15c6003891a79ae69953716f597aaa89e236)).

>  Also, why is this replaceAll call being used in two different upgrade processes?

I actually didn't investigate deeply. Since it was added in the same PR (see this [commit](https://github.com/liferay-data-engine/liferay-portal/pull/317/commits/4407e49b99b0b039d86916e19dd7874db2876605) and this [commit](https://github.com/liferay-data-engine/liferay-portal/pull/317/commits/4b8bb451b9b3cac744c9bc2502ed5531cc5548b5)), I thought it was really needed in both places.

**Comment by rodrigopaulino** [comment]
> It's only used for web content structures and was added because of [LPS-128325](https://issues.liferay.com/browse/LPS-128325) (see this [commit](https://github.com/liferay-data-engine/liferay-portal/pull/281/commits/cd49ad93d4b6a4d9664ba572923a244735d60835) and this [commit](https://github.com/liferay-data-engine/liferay-portal/pull/281/commits/13df15c6003891a79ae69953716f597aaa89e236))

It's weird to have this logic embedded inside DDMStructure, but we won't touch it for now. Thanks for clarifying.

> I actually didn't investigate deeply. Since it was added in the same PR (see this [commit](https://github.com/liferay-data-engine/liferay-portal/pull/317/commits/4407e49b99b0b039d86916e19dd7874db2876605) and this [commit](https://github.com/liferay-data-engine/liferay-portal/pull/317/commits/4b8bb451b9b3cac744c9bc2502ed5531cc5548b5)), I thought it was really needed in both places.

As I could see, v3.9.1 upgrade process is just upgrading the options from both WC and Forms. After that, v4.0.0 upgraded structures from DE, which is correct, but I think the first one shouldn't be applied to WC structures anymore.

**Comment by carolmariaabb** [comment]
@rodrigopaulino 

> As I could see, v3.9.1 upgrade process is just upgrading the options from both WC and Forms. After that, v4.0.0 upgraded structures from DE, which is correct, but I think the first one shouldn't be applied to WC structures anymore.

Are you sure? Because this [commit](https://github.com/liferay/liferay-portal/commit/37ae3329e52f7d88755ec259d2ec0fe4fcfe81ee) was recently added to fix the bug described in [LPS-151628](https://issues.liferay.com/browse/LPS-151628).

If I revert this commit, the bug happens again, as you can see below:

[Gravação de tela de 14-07-2022 13:51:21.webm](https://user-images.githubusercontent.com/34186632/179036439-11415add-43ac-4e3c-a92c-8374c1c26659.webm)

Obs.: They didn't send the [PR](https://github.com/liferay-uniform/liferay-portal/pull/332) for us to review, not sure if this is expected.

**Comment by rodrigopaulino** [comment]
Perhaps this was needed to make into master for backporting purposes, since the other, where the options get their names fixed, is not available until 7.4. Could you please double check if my assumption is true, also debug to see what's happening with v4.0.0 that isn't fixing the options' references of WC's structures accordingly? Thanks a lot for your effort.

**Comment by carolmariaabb** [comment]
> Perhaps this was needed to make into master for backporting purposes, since the other, where the options get their names fixed, is not available until 7.4.

When Eudaldo made this [change](https://github.com/liferay-data-engine/liferay-portal/pull/317/commits/4b8bb451b9b3cac744c9bc2502ed5531cc5548b5#) to `v3_9_1/DDMStructureUpgradeProcess`, it wasn't really necessary because, at that moment, it was only upgrading `DDMFormInstace` structures. The change that was really necessary was [this one](https://github.com/liferay-data-engine/liferay-portal/pull/317/commits/4407e49b99b0b039d86916e19dd7874db2876605), since the `v4_0_0/DDMStructureUpgradeProcess` was upgrading WC structures.

This recent [change](https://github.com/liferay/liferay-portal/commit/37ae3329e52f7d88755ec259d2ec0fe4fcfe81ee) caused the `v3_9_1/DDMStructureUpgradeProcess` to run for both `DDMFormInstance` and `JournalArticle`. So this [change](https://github.com/liferay-data-engine/liferay-portal/pull/317/commits/4b8bb451b9b3cac744c9bc2502ed5531cc5548b5#) started to make sense because `v3_9_1/DDMStructureUpgradeProcess` is now upgrading `JournalArticle` structures. 

`v3_9_1/DDMStructureUpgradeProcess` is necessary to add field references to all fields in the structure when upgrading from `7.2.x` or earlier versions. 
`v4_0_0/DDMStructureUpgradeProcess` is necessary to fix the options references when upgrading from `7.3.x`.

> debug to see what's happening with v4.0.0 that isn't fixing the options' references of WC's structures accordingly

I didn't understand this question.. as I said, v4.0.0 is fixing the options' references of WC's structures when upgrading from `7.3.x`.

**Comment by rodrigopaulino** [comment]
Thanks a lot for the investigation, @carolmariaabb.

> v3_9_1/DDMStructureUpgradeProcess is necessary to add field references to all fields in the structure when upgrading from 7.2.x or earlier versions.

Did you mean add field references to all option fields, right? Also, I believe this is also used for portals on 7.3, with service packs earlier to the one that introduced this upgrade.
Ok. So why [this](https://github.com/liferay/liferay-portal/commit/37ae3329e52f7d88755ec259d2ec0fe4fcfe81ee) is necessary then, if WC's structures from 7.3 were still using DDM?

> I didn't understand this question.. as I said, v4.0.0 is fixing the options' references of WC's structures when upgrading from 7.3.x.

If v4_0_0's is doing just that ("fixing the options' references"), why do we need v3_9_1's?

We can make a call if it's still unclear. :)
Thanks, Carol!

**Comment by carolmariaabb** [comment]
ci:close

**Pull request closed without merging**
