### PR TITLE
LPS-190599 Default locale should match to avoid inconsistencies (having a default that is not in the available locales)

### PR DESCRIPTION
**Pull request by robertoDiaz**
Related issue: https://liferay.atlassian.net/browse/LPS-190599

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hi @liferay-forms 

Any update about this?? 

A customer is waiting for a fix.

Regards!

**Comment by samuelromeiro** [comment]
Hi @robertoDiaz, 
Someone fromt he team will review this PR as soon as possible.

**Comment by marcelabc** [comment]
Just started reviewing :)

**Comment by marcelabc** [comment]
Hey @robertoDiaz 
This test seems to be related and is failing with this solution. Could you try to run it locally?
Test: https://testray.liferay.com/home/-/testray/case_results/2390496390/history?tab=result&hideFilterPin=true

Thank you!

**Comment by marcelabc** [comment]
Hey @robertoDiaz 
Did you have time to check this failing test?

**Comment by manuelRives** [comment]
Hi @marcelabc, Roberto is on PTO, I'm going to review the test and return with my findings.

Regards.

**Comment by manuelRives** [comment]
Hi @marcelabc, pull resent with test fixed.

**Pull request closed without merging**
