### PR TITLE
LPS-191509

### PR DESCRIPTION
**Pull request by icgsbr**
# Description
Changed radio and checkbox button color in order to improve color contrast, resulting in a better accessibility on forms.

# Jira Link
[LPS-191509](https://liferay.atlassian.net/browse/LPS-191509)

### CODE REVIEW

**Comment by icgsbr** [comment]
ci:test:stable

**Comment by icgsbr** [comment]
ci:test:relevant

**Comment by icgsbr** [comment]
ci:test:sf

**Comment by icgsbr** [comment]
ci:test:stable

**Comment by icgsbr** [comment]
ci:test:relevant

**Comment by icgsbr** [comment]
ci:test:relevant

**Review by rebsilva — APPROVED** [review]
LGTM! :tada:

**Comment by rebsilva** [comment]
waiting the relevant to be fixed so we can run the tests again :cherry_blossom:

**Comment by icgsbr** [comment]
ci:test:relevant

**Comment by icgsbr** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
