### PR TITLE
LPS-131738 Apply the mask while the user is typing

### PR DESCRIPTION
**Pull request by alinedoleron**
### Related Tickets
- [LPS-131737](https://issues.liferay.com/browse/LPS-131737) [FE] Show the mask as a placeholder if the field does not have a placeholder
- [LPS-131738](https://issues.liferay.com/browse/LPS-131738) [FE] Apply the mask while the user is typing
- [LPS-131739](https://issues.liferay.com/browse/LPS-131739) [FE] Apply the mask on the predefined value
- [LPS-131740](https://issues.liferay.com/browse/LPS-131740) [FE] Validate that the field value is in accordance with the mask
- [LPS-132350](https://issues.liferay.com/browse/LPS-132350) [FE] Create unit tests
- [LPS-133086](https://issues.liferay.com/browse/LPS-133086) [FE] Create remaining cases of masks
- [LPS-133179](https://issues.liferay.com/browse/LPS-133179) [FE] Remove mask before submit the Form

### CODE REVIEW

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:reevaluate:1087401_7494

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:forward

**Pull request closed without merging**
