### PR TITLE
LPS-121444 Allow set alphabetical order in SelectDDMFormField

### PR DESCRIPTION
**Pull request by robertoDiaz**
Related Issue: https://issues.liferay.com/browse/LPS-121444

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
@carolmariaabb, can you please review this one?

Thanks.

**Comment by carolmariaabb** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
> @carolmariaabb, can you please review this one?
> 
> Thanks.

@natocesarrego, all test scenarios have passed.

**Comment by carolmariaabb** [comment]
Hi @robertoDiaz, I implemented a new unit test for your solution. Resent [here](https://github.com/liferay-forms/liferay-portal/pull/42). Thanks!

**Comment by carolmariaabb** [comment]
Closed [#39](https://github.com/liferay-forms/liferay-portal/pull/39).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
