### PR TITLE
[TS] LPS-121532 | accessibility forms fields

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Related Issue: https://issues.liferay.com/browse/LPS-121532

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hey @georgel-pop-lr, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @georgel-pop-lr, can you please fix the source formatter issues and resend? Thanks

**Pull request closed without merging**
