### PR TITLE
LPS-145911

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related Issue: https://issues.liferay.com/browse/LPS-145911

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @carolmariaabb, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Review by rodrigopaulino — APPROVED** [review]
Refactoring looks gooood! 👏🏻

**Comment by rodrigopaulino** [comment]
ci:forward

**Pull request closed without merging**
