### PR TITLE
LPS-148909

### PR DESCRIPTION
**Pull request by HenriquePereiraa**
Related issue: https://issues.liferay.com/browse/LPS-148909

### CODE REVIEW

**Comment by HenriquePereiraa** [comment]
ci:test:st

**Comment by HenriquePereiraa** [comment]
ci:test:sf

**Comment by HenriquePereiraa** [comment]
ci:test:sf

**Comment by HenriquePereiraa** [comment]
ci:test:relevant

**Comment by HenriquePereiraa** [comment]
ci:forward

**Comment by marcelabc** [comment]
Hi @HenriquePereiraa @daiazius 
How are you doing? Thank you for contributing!

Just to let you know that I edited the description to include the "Related Issue" (with the Jira ticket). Please, if you could always add this information in your next reviews! Helps a lot :+1:

**Comment by marcelabc** [comment]
I saw that this PR came from this eviewed PR:https://github.com/liferay-forms/liferay-portal/pull/2009
Please, if you could add this info in a comment next time, it would help!

I'm adding Good to go because it has been reviewed :+1:

**Comment by alinedoleron** [comment]
ci:forward

**Pull request closed without merging**
