### PR TITLE
LPS-133951 Remove Data Engine's front end deprecated code

### PR DESCRIPTION
**Pull request by miltonmc**
**Ticket:** [ LPS-133951](https://issues.liferay.com/browse/LPS-133951) Remove Data Engine's front end deprecated code

### CODE REVIEW

**Comment by miltonmc** [comment]
@diegonvs and @matuzalemsteles feel free to point anything I may missed

**Comment by matuzalemsteles** [comment]
Hey, you are considering removing the code from the `dynamic-data-mapping-form-builder`, there's a lot there too that needs to be removed that in theory is no longer being used, `LayoutProvider`... (Metal.js code), some utils should be moved into the Data Engine too .

**Comment by miltonmc** [comment]
@matuzalemsteles, great!

Thank you for the insight, I will check for the uses of the `dynamic-data-mapping-form-builder` and I will remove that too. But if you don´t mind, I would prefer add those changes in other PR.

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
Just started reviewing :)

**Comment by miltonmc** [comment]
ci:reevaluate:1257401_1148

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:stop

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
closed in favor of #596

**Pull request closed without merging**
