### PR TITLE
LPS-154792

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related ticket: https://issues.liferay.com/browse/LPS-154792

cc @carolmariaabb

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
@carolmariaabb, is it possible to change the status of the action from the endpoint?

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
A [technical debt](https://issues.liferay.com/browse/LPS-155955) was created in order to solve the problem this PR was facing with d.ts regen.

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:reevaluate:1367401_1353

**Comment by carolmariaabb** [comment]
ci:reevaluate:1367401_1351

**Comment by carolmariaabb** [comment]
Hi @rodrigopaulino,

I resent (https://github.com/liferay-forms/liferay-portal/pull/1755) because I added this [commit](https://github.com/liferay-forms/liferay-portal/pull/1755/commits/301f4e9b734b269816d9dae926a1b40058b4681b).

The failure below was reported as a common failure, but is actually related to the changes in this PR. The other failures are happening in other PRs, I already checked.

image

Thanks!

**Pull request closed without merging**
