### PR TITLE
LPS-187024 Add AI-Creator button to web contents CKEditor when configuration is enabled

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-187024

Hi Team ✋ 

From the Echo Team, we are working on a story to [Provide a button to trigger AI in the web content editor.](https://issues.liferay.com/browse/LPS-181285) As part of that story, we need to add an attribute that indicates if the toolbar should be added or not. 

I needed to set the attribute in the point instead of determining it directly in the CKEditor configuration since it is necessary to know if it is JournalPortlet or not and the portlet information sometimes is missing in the editor configuration but in this point, we always have the portletNamespace so I decide to use it.

Could you please review it?

Thanks in advance! ❤️

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:forms

**Review by carolmariaabb — APPROVED** [review]
LGTM! 🎉

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
