### PR TITLE
LPS-188990 Integration test for export/import with Forms with object storage type

### PR DESCRIPTION
**Pull request by devpedrotavares**
Follow up: https://github.com/liferay-forms/liferay-portal/pull/2288

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
@marcelabc I just included this [commit](https://github.com/liferay-forms/liferay-portal/pull/2291/commits/32d0f2dfd19fe5493a0f8d4b160e990c6d169b6c) to fix a compilation error that occurred due to recent changes to master

**Comment by devpedrotavares** [comment]
ci:test:sf

**Comment by devpedrotavares** [comment]
ci:test:revelant

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
Reopened since the PR got minor conflicts with Brian's branch

**Comment by devpedrotavares** [comment]
Fixed minor conflicts in build.gradle

**Comment by devpedrotavares** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:forward:force

**Pull request closed without merging**
