### PR TITLE
LPS-146591 Fix multiple page forms navigation index

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issue: https://issues.liferay.com/browse/LPS-146591

Hello Reviewer!

This PR has a fix of the bug above. The multiple page forms navigation index wasn't working properly when we were using the top navigation bar; I've changed the logic to send the right `nextIndex` and `previousIndex` when using it. Notice that I left the `activePage` as the default value for both props, because this is the correct value when you do the same navigation through the `next` and `previous` buttons instead of the navigation bar.

If you have any questions feel free to ask, thank you for your time!

### CODE REVIEW

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]
Nice job!!

**Comment by alinedoleron** [comment]
ci:forward

**Pull request closed without merging**
