### PR TITLE
LPS-123065 LPS-123063 LPS-123066 LPS-123067 Migrate RuleEditor, RuleList and RuleBuilder to React

### PR DESCRIPTION
**Pull request by matuzalemsteles**
Related Issue: https://issues.liferay.com/browse/LPS-123065

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @matuzalemsteles, can you please check if these failures are related to your changes? Thanks

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by liferay-forms** [comment]
Hey @matuzalemsteles, can you please check if these failures are related to your changes? Thanks

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by diegonvs** [comment]
ci:test:app-builder

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @matuzalemsteles, can you please check if these failures are related to your changes? Thanks

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @matuzalemsteles, can you please check if these failures are related to your changes? Thanks

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @matuzalemsteles, can you please check if these failures are related to your changes? Thanks

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by liferay-forms** [comment]
Hey @matuzalemsteles, can you please check if these failures are related to your changes? Thanks

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by liferay-forms** [comment]
Hey @matuzalemsteles, can you please check if these failures are related to your changes? Thanks

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by matuzalemsteles** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @matuzalemsteles, can you please fix the source formatter issues and resend? Thanks

**Comment by matuzalemsteles** [comment]
Resent https://github.com/liferay-forms/liferay-portal/pull/63

**Pull request closed without merging**
