### PR TITLE
LPS-140215 update failing tests

### PR DESCRIPTION
**Pull request by kiwm**
Related issue: https://issues.liferay.com/browse/LPS-140215

### CODE REVIEW

**Comment by kiwm** [comment]
ci:test:sf

**Comment by kiwm** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by kiwm** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by alinedoleron** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
