### PR TITLE
LPS-164922 Make ck editor modal stay open while editing its options

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issue: https://issues.liferay.com/browse/LPS-164922

**The solution:** Insert the CK Editor class inside the function `detectClickOutside` in the validation using `isElementInnerSelector`.

**Steps to Reproduce:**

1. Navigate to Site Menu > Content & Data > Document and Media > Document Types
2. Create a new document type.
3. Add a "Rich Text" field to the document type.
4. Open the "Advanced" tab of the "Rich Text" field.
5. In the "Predefined Value" field click on the "Table" icon in the editor toolbar. 
6. In the modal that opens, attempt to change the values.

**Expected Result:**
You are able to change the values with the modal staying open.

**Actual Result:**
The modal closes on mousedown or click.

### CODE REVIEW

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]
Good job!

**Comment by alinedoleron** [comment]
Hi @rebsilva, this failure seems not to be related to your PR because I've seen this error in another PR.

**Comment by alinedoleron** [comment]
ci:forward

**Pull request closed without merging**
