### PR TITLE
LPS-194830 | Acessibility error 

### PR DESCRIPTION
**Pull request by rijema**
https://github.com/liferay-forms/liferay-portal/pull/2303

### CODE REVIEW

**Comment by rijema** [comment]
Hi @rebsilva , here it is the PR!

**Review by rebsilva — APPROVED** [review]
LGTM! I was already reviewed on the previous PR :blush:

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by rebsilva** [comment]
ci:test:echo

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
