### PR TITLE
[TS] LPS-197334 Post upgrade to DXP 7.4 from DXP 7.1 Form Rules with national characters are broken on save if the Form is modified

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Motivation
=======
On 7.4 special characters on form field options are no longer allowed, which could lead to problems when upgrading from a lower version.
For example, if there is an option that has the value `töst`
```
{
	"label" : {
		"en_US" : "töst"
	},
	"reference" : "töst",
	"value" : "töst"
}
```
when the form is edited, the value will be normalized by [this code](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/src/main/resources/META-INF/resources/Options/util.es.js#L136) and the special character `ö` will be removed from the value.

It will end up like this:
```
{
	"label" : {
		"en_US" : "töst"
	},
	"reference" : "töst",
	"value" : "tst"
}
```

If there is a form rule that references the option by its value, it will break.

`equals(getValue('Testtåst'), 'töst') OR equals(getValue('Testtåst'), 'tåst') OR equals(getValue('Testtåst'), 'täst')`

Proposed Solution
========
Normalization should be applied only for newly added options that are not referenced by a rule.

Steps to Verify
========
Please see the linked LPS for the reproduction steps.
https://liferay.atlassian.net/browse/LPS-197334

Thank you and best regards,
István

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Dear Team,

I have checked the test failures are they don't seem to be related to the solution.

Please let me know if there are any updates on the review.

Thank you and best regards,
István

**Comment by marcelabc** [comment]
Just started reviewing :)

**Comment by marcelabc** [comment]
ci:reevaluate:1407401_6344

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
@IstvanD 
Do you prefer to send directly to Brian or try to run CI again?
If you send directly, please share the PR here! Thank you.

**Comment by IstvanD** [comment]
Hi @marcelabc thank you for the review!
I would prefer you forward the pull request to Brian because my account is not entrusted to send the pull to him directly.
Thank you in advance!

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Hey @IstvanD 
I tried one more time with CI, but the stable failed.
I think you can create the pull request for Brian. The bot will close, but you can reopen with this comment `ci:reopen`.
You can explain that the failures are not related.
Like this example: https://github.com/brianchandotcom/liferay-portal/pull/141510
What do you think?

**Comment by IstvanD** [comment]
Hi @marcelabc,
I have sent the pull request to Brian: https://github.com/brianchandotcom/liferay-portal/pull/141530

**Comment by marcelabc** [comment]
Thank you :smile:

**Pull request closed without merging**
