### PR TITLE
LPS-144713,LPS-144714

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related Issues: 
https://issues.liferay.com/browse/LPS-144713
https://issues.liferay.com/browse/LPS-144714

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:stop

**Comment by liferay-forms** [comment]
Hey @rodrigopaulino, can you please check if these failures are related to your changes? Thanks

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Review by carolmariaabb — APPROVED** [review]

**Comment by liferay-forms** [comment]
Hey @rodrigopaulino, can you please check if these failures are related to your changes? Thanks

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @rodrigopaulino, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
Closing this to send all together https://github.com/liferay-forms/liferay-portal/pull/1322

**Comment by rodrigopaulino** [comment]
ci:stop

**Pull request closed without merging**
