### PR TITLE
LPS-135596 Revert "LPS-146591 Fix multiple page forms navigation index"

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issue: https://issues.liferay.com/browse/LPS-135596

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
