### PR TITLE
LPS-139170 The boolean field values are not counting as one in form entries (Summary) when form has translations

### PR DESCRIPTION
**Pull request by mateusgomes01**
Related Issue: https://issues.liferay.com/browse/LPS-139170

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @mateusgomes01, can you please check if these failures are related to your changes? Thanks

**Comment by mateusgomes01** [comment]
ci:reevaluate:1337401_481

**Comment by liferay-forms** [comment]
Hey @mateusgomes01, can you please check if these failures are related to your changes? Thanks

**Comment by mateusgomes01** [comment]
ci:reevaluate:1337401_481

**Comment by liferay-forms** [comment]
Hey @mateusgomes01, can you please check if these failures are related to your changes? Thanks

**Comment by mateusgomes01** [comment]
ci:reevaluate:1337401_481

**Comment by liferay-forms** [comment]
Hey @mateusgomes01, can you please check if these failures are related to your changes? Thanks

**Review by miltonmc — COMMENTED** [review]
@mateusgomes01 are anything are missing something here? This PR just removes 3 blank lines. Is that what you intended to do?

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by mateusgomes01** [comment]
> @mateusgomes01 are anything are missing something here? This PR just removes 3 blank lines. Is that what you intended to do?

Yes @miltonmc , Brian asked me to make these changes after sending this PR [#109512](https://github.com/brianchandotcom/liferay-portal/pull/109512#issuecomment-961910226)

**Comment by mateusgomes01** [comment]
ci:foward

**Comment by miltonmc** [comment]
@mateusgomes01, I got confused due to the title of this PR, sorry about that!

**Comment by mateusgomes01** [comment]
No problem @miltonmc ! I just didn't know what to put on the title. Do you have any other suggestion?

**Comment by mateusgomes01** [comment]
ci:foward

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by liferay-forms** [comment]
ci:test:relevant

**Pull request closed without merging**
