### PR TITLE
LPS-156017 buildLang

### PR DESCRIPTION
**Pull request by ruben-pulido**
Hi Team!

In order to properly map Objects Exceptions to Info Framework Exceptions when creating objects via Content Pages we had to expose some fields of the Objects Exceptions through public methods.

This PR contains both the changes in Info Framework and Objects sides.

We would need you to review the object related changes, mainly this commit range https://github.com/ruben-pulido/liferay-portal/compare/2058908207a93024bc5f4def92bc19ec009dba05..35580643a912e7d7f97d80bda6c0e8979baee4c6

Thank you very much!

//cc @ealonso

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
LGTM 😄

**Comment by gabrielwas** [comment]
ci:forward

**Pull request closed without merging**
