### PR TITLE
LPS-153675

### PR DESCRIPTION
**Pull request by alinedoleron**
Ticket: https://issues.liferay.com/browse/LPS-153675

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Review by rebsilva — APPROVED** [review]
LGTM! :purple_heart:

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
