### PR TITLE
LPS-174732 Improve accessibility entries page

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
previous https://github.com/brianchandotcom/liferay-portal/pull/130935

Fixed failed tests in ../modules/dxp/apps/portal-workflow/portal-workflow-metrics-web.

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:test:forms

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
Hi @rebsilva,

I detected some tests failing because of these changes on content-dashboard-web and looking into it.

Once I have all the changes, I will push them to this PR.

If you see any other related tests failing please let me know.

Regards.

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:stable

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
Hi @rebsilva,

Could someone from QA review if the failing tests are related to these changes?

Regards.

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by rebsilva** [comment]
Hello @georgel-pop-lr! Thanks for your work on this PR, I'll be reviewing this by tomorrow; and about the failing tests, I'll take a look once I've done the review, thanks! :cherry_blossom:

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by alinedoleron** [comment]
ci:forward

**Comment by georgel-pop-lr** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
I did a full rebase with latest master, I will retest

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
