### PR TITLE
LPS-160949 Exceptions are not been throwing when uploading an invalid file

### PR DESCRIPTION
**Pull request by daiazius**
Related issue: https://issues.liferay.com/browse/LPS-160949

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:relevant

**Review by rebsilva — CHANGES_REQUESTED** [review]
Hi @daiazius, thanks for your PR! I've tested it and some things are not working as expected; I suggest you to take another look into this. 
[ This bug ](https://issues.liferay.com/browse/LPS-144404)is similar to what you are facing now and Rodrigo Paulino already did some [work](https://github.com/rodrigopaulino/liferay-portal/tree/LPS-144404) but never sent it to master; you could take a look to see if this helps you in anything. Thanks!

**Comment by rebsilva** [comment]
I will be closing this PR since a different solution will be necessary. @daiazius please reach us if you have any doubts, thanks!

**Pull request closed without merging**
