### PR TITLE
[TS] LPS-131928 | master

### PR DESCRIPTION
**Pull request by samanzanedo**
Hi @natocesarrego 

As suggested in your comments https://github.com/liferay-forms/liferay-portal/pull/308#pullrequestreview-668944561 this new PR has the changes.

Regards.

### CODE REVIEW

**Comment by natocesarrego** [comment]
@samanzanedo, I just have one word to you ...

leonardo di caprio

**Comment by natocesarrego** [comment]
ci:forward

**Comment by samanzanedo** [comment]
@natocesarrego 
Muito obrigado, você é muito prestativo :-)

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
