### PR TITLE
LPS-131825 Fieldset is not grayed out as it is being used in the Structure

### PR DESCRIPTION
**Pull request by miltonmc**
**Ticket**: [LPS-131825](https://issues.liferay.com/browse/LPS-131825)

### CODE REVIEW

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:reevaluate:1027401_570

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:relevant

**Review by interaminense — APPROVED** [review]
LGTM 🔥

**Comment by interaminense** [comment]
ci:forward

**Pull request closed without merging**
