### PR TITLE
[TS] LPS-176089 Workflows associated with Dynamic Data Lists get lost during upgrade

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Motivation
=======
Workflows associated with Dynamic Data Lists get lost during upgrade (From 7.0 to 7.4/master).

Root Cause
========
[DDMFormInstanceUpgradeProcess](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/internal/upgrade/v2_0_0/DDMFormInstanceUpgradeProcess.java) moves the entries from `DDLRecordSet` that have `scope = SCOPE_FORMS`, into the `DDMFormInstance` table.
Then, it sets every `WorkflowDefinitionLink`'s `classNameId` where the `classNameId` is `DDLRecordSet`'s ID to `DDMFormInstance`'s ID.

Dynamic Data Lists are created with `SCOPE_DYNAMIC_DATA_LISTS`, and during the upgrade, the `WorkflowDefinitionLink`'s `classNameId` is updated regardless. When the user views the Dynamic Data List, its associated Workflow Definition won't be displayed, due to the mismatching `classNameId`.

Proposed Solution
========

1. The new upgrade process, `WorkflowDefinitionLinkUpgradeProcess`,  reverts the `classNameId`s if the `classPK` matches with the `recordSetId` of the `DDLRecordSet` 

2. fixing `DDMFormInstanceUpgradeProcess` to update the `WorkflowDefinitionLink`'s `classNameId` only if the `WorkflowDefinitionLink` `classPK` is equal to the `recordSetId` that has the `SCOPE_FORMS`.

Steps to Verify
========
Please consult the LPS for the reproduction steps:
https://issues.liferay.com/browse/LPS-176089

Thank you and best regards,
István

### CODE REVIEW

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by carolmariaabb** [comment]
@IstvanD please fix the SF failure:

> At least one commit message is missing a reference to a required JIRA project: BLADE, CLDSVCS, COMMERCE, FACES, IDE, ISSITES, LCD, LHC, LOOP, LPS, LRAC, LRCI, LRDOCS, LRIS, LRQA, OAUTH2, POSHI, RELEASE, SYNC, TR. Please verify that the JIRA project keys are specifiedin ci.properties in the liferay-portal repository.

**Comment by IstvanD** [comment]
Hi @carolmariaabb, fixed it!

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
