### PR TITLE
LPS-135957 FE Tests

### PR DESCRIPTION
**Pull request by eli-rlima**
Hi, reviewer!

This PR is tests for component created in #759, therefor, can be only merged after #759 is merged. Another thing, this should be send to Liferay Echo Team as the #759.

- I used the [ShareFormModal](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web/test/js/components/ShareFormModal.js) as example to develop this. 
- In someone cases I tried use the `container` method that is returned by `render` method, but don't worked for find elements, maybe don't work in this case, therefor, I used the `document` for search the elements.

Here is the [related ticket](https://issues.liferay.com/browse/LPS-135957).

Thanks.

### CODE REVIEW

**Comment by eli-rlima** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
@eli-rlima I suggest you to merge the commit in this PR with the one into the PR #759, since they are related. I see as a good approach commit the code and its tests together.

**Comment by eli-rlima** [comment]
Hi @miltonmc, I added the commit here!

**Review by miltonmc — CHANGES_REQUESTED** [review]
There are a lot of noise on old test cases that may lead you these comments below:

**Comment by eli-rlima** [comment]
Hi @miltonmc, I applied your suggests!

**Comment by eli-rlima** [comment]
ci:test:relevant

**Comment by eli-rlima** [comment]
I put the blocked label because I will send new changes.

**Comment by eli-rlima** [comment]
I will close because this feature will go together with the LPS-135959 in a single PR.

Thanks for your review time, @miltonmc!

**Pull request closed without merging**
