### PR TITLE
LPD-20786 Don't set value for transient fields

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related issue: [LPD-20786](https://liferay.atlassian.net/browse/LPD-20786)

### CODE REVIEW

**Review by G-Sa — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:test:sf

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:forms

**Pull request closed without merging**
