### PR TITLE
    LPS-142904 separate resources for each collection

### PR DESCRIPTION
**Pull request by antonio91dev**
Related Issue: https://issues.liferay.com/browse/LPS-142904

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Hi @antonio91dev, the issue is not related to the Forms team. I'm not sure which team is responsible for this ticket, but the change is in the `Fragments` module.

Therefore, I will have to close this PR.

Thanks!

**Comment by carolmariaabb** [comment]
ci:close

**Comment by carolmariaabb** [comment]
ci:stop

**Pull request closed without merging**
