### PR TITLE
LPD-26366 Web Content with Multi-Select List Fails to Save Values When Option value Contains a Comma

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPD-26366](https://liferay.atlassian.net/browse/LPD-26366)

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:forms

**Comment by pedro-oliveira446** [comment]
ci:test:data-engine

**Comment by pedro-oliveira446** [comment]
Hey @carolmariaabb  and @rebsilva ,

I needed to add this last commit to fix the CI failures. Could you please review it again?

**Review by carolmariaabb — APPROVED** [review]
The failures do not appear to be related. 

Let's wait for @rebsilva's review as the new commit is changing the FE code.

**Comment by rebsilva** [comment]
just started reviewing! :cherry_blossom:

**Review by rebsilva — APPROVED** [review]
LGTM! :cherry_blossom:

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
