### PR TITLE
LPD-37484 Error indexing large terms using Rich Text box within a repeatable Field Group

### PR DESCRIPTION
**Pull request by icgsbr**
## Jira Link
https://liferay.atlassian.net/browse/LPD-37484

## Delivery Format
EDH

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
Hi @icgsbr 

With your change, you are truncating both the value used for regular text search and the value used for sorting.

Following calls must be always called with the complete value, as it will index in Elasticsearch the field that is used for searching:
`document.addKeywordSortable(name, valuesString);`
and
`document.addTextSortable(name, valuesString);`

The truncated value should only be used in following calls:
`document.addKeyword(_getSortableFieldName(name), valuesString);`
and 
`document.addText(_getSortableFieldName(name), valuesString);`

With your changes, the search functionality will only be able to search text that is in the first 255 characters of the rich text field, and that is not ok.

**Comment by icgsbr** [comment]
Thanks for the heads up @jorgediaz-lr ! I'll be discussing with @marcelabc about my previous approach idea.

**Comment by marcelabc** [comment]
Hi @jorgediaz-lr,
Thank you for the review!
Current behavior: If we try to index a text bigger than 255 characters, the log will throw an error. 

This proposal is only for text with more than 255 characters when using Rich Text. This is an edge case. We validate this solution with the product team. We think that is not a common case for the users to search for this type of field.
What do you think?

**Comment by jorgediaz-lr** [comment]
Hi @marcelabc @icgsbr 

I don't think it is an edge case, having a web content with a rich text box with a text larger than 255 characters is very common.

It is true that sorting a rich text box may be a edge case, but searching the text of a rich text box isn't.

As I said in my previous comment, the truncated value should only be used in following calls:
`document.addKeyword(_getSortableFieldName(name), valuesString);`
and
`document.addText(_getSortableFieldName(name), valuesString);`

I have done some tests in my computer with that change and it:

- It will solve the reported issue as the '_sortable' field will be correctly truncated
- It will continue indexing the complete content in the regular field (_the non '_sortable' one_)

I have sent you a PR, see: https://github.com/liferay-forms/liferay-portal/pull/2624

See my added commit: https://github.com/liferay-forms/liferay-portal/pull/2624/commits/c8344e8045cc37478b7687fe417a0573cd8595b8

**Comment by marcelabc** [comment]
@jorgediaz-lr, Thank you again for your help!! We appreciate a lot :smiley:

**Pull request closed without merging**
