### PR TITLE
LPS-153934 Adapt rules to compare String type with special characters case

### PR DESCRIPTION
**Pull request by leticia-maciel**
Related ticket: https://issues.liferay.com/browse/LPS-153934

### CODE REVIEW

**Comment by leticia-maciel** [comment]
ci:test:relevant

**Review by rodrigopaulino — CHANGES_REQUESTED** [review]
Hey, @leticia-maciel.

Thanks a lot for your investigation here, but I believe your solution changes the expected behavior of the equals function. With your changes, a text like `the char &#39; is an apostrophe` would be equal to `the char ' is an apostrophe`.
To solve this bug, I think we wouldn't need to escape the options labels in the first place. So we can leave this function intact. Please take a look at both CheckboxMultipleDDMFormFieldValueAccessor's and SelectDDMFormFieldValueAccessor's and getOptionsLabels method. Also could you please add a unit test inside EqualsFunctionTest to cover this example I gave you just now (meaning the char &#39; is an apostrophe" **is not equal to** "the char ' is an apostrophe")?

Let me know if you have any questions.
Thanks for your contribution.

**Comment by leticia-maciel** [comment]
ci:test:sf

**Comment by leticia-maciel** [comment]
> @leticia-maciel, that's the idea! Did you check to see if these `getOptionsLabels` are used somewhere else that needs the escaping? Let me know if this change is safe. Also, thanks for creating that unit test. That's exactly what we need. I'd like to suggest you just to merge all the methods into just one `testApply`. I don't see benefit in having these 1, 2, 3 methods.
> 
> Great work. 👏🏻

Hi @rodrigopaulino , 
I only saw `getOptionsLabels` being used once inside `getValueForEvaluation` method for all our cases(Checkbox, Radio and Select). So I don't think we need to escape in another place. 
I also merged all tests into one testApply for both False and True cases. 

Please let me know if I need to change something else. 

Thanks :grinning:

**Review by rodrigopaulino — CHANGES_REQUESTED** [review]
Thanks for answering, @leticia-maciel. As discussed offline, there will be some other changes to this.

**Comment by leticia-maciel** [comment]
ci:test:sf

**Comment by leticia-maciel** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
@leticia-maciel, feel free to let me know the result of your local tests on this. I'll wait for them before forwarding this. Thanks!

**Comment by rodrigopaulino** [comment]
Hey, @leticia-maciel. I'm closing this for the moment. Feel free to reopen it and comment here in case you still intend to move forward with this fix. 
Thanks for understanding.

**Pull request closed without merging**
