### PR TITLE
Forms Automated Test - LPS-131744 | master

### PR DESCRIPTION
**Pull request by Jamersonze**

### CODE REVIEW

**Comment by Jamersonze** [comment]
Fixed

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
Hi @Jamersonze, please resolve conflicting files. Thank you!

**Comment by Jamersonze** [comment]
Fixed

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
ci:forward

**Pull request closed without merging**
