### PR TITLE
LRQA-71470

### PR DESCRIPTION
**Pull request by rafaellajordao**
Related Issue: https://issues.liferay.com/browse/LRQA-71470

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by rafaellajordao** [comment]
ci:forward

**Pull request closed without merging**
