### PR TITLE
LPS-123985 Closes the dropdown properly when adding a field to calculator

### PR DESCRIPTION
**Pull request by diegonvs**
Related Issue: https://issues.liferay.com/browse/LPS-123985

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:forward

**Pull request closed without merging**
