### PR TITLE
LPS-204575

### PR DESCRIPTION
**Pull request by icgsbr**
https://liferay.atlassian.net/browse/LPS-204575

### CODE REVIEW

**Review by rebsilva — APPROVED** [review]
LGTM! :tada:

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:forms

**Comment by rebsilva** [comment]
ci:test:data-engine

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
