### PR TITLE
LPS-151194 Accessibility fix, fields do not have an ID and label is u…

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Related Issue: https://issues.liferay.com/browse/LPS-151194

Accessibility fix, fields do not have an ID and label is using for attribute referring to the name of the input, which is not correct.

Our clients are public institutions that by law need to pass this accessibility OAW tool, could be accessed here if you have an account https://administracionelectronica.gob.es/comunidades/verPestanaMas.htm?idComunidad=accesibilidad#.Yl5_EXVBzmH

For more details, please see: https://issues.liferay.com/browse/LPS-151194

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @georgel-pop-lr, can you please check if these failures are related to your changes? Thanks

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @georgel-pop-lr, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
Hey @georgel-pop-lr, can you please check if these failures are related to your changes? Thanks

**Comment by georgel-pop-lr** [comment]
Hi @rodrigopaulino,

Any news regarding this pull?

Regards.

**Comment by georgel-pop-lr** [comment]
> 's necessary to use

Hi @rodrigopaulino,

Thanks for looking into this, I understand your team is really busy, but I thought as this is something easy to fix would take less time.

The correct way to work FOR attribute needs to point out to an ID input, and the name is not even being taken into account.

So we need this fix in order for the accessibility test to pass. Actually this is something we had before then was removed see [commit](https://github.com/liferay-forms/liferay-portal/commit/c75048c163ab62c78029c5a7dbcfcb67f5b2a86a) and not the client wants it back.

Hope it helps.

Regards.

**Review by carolmariaabb — CHANGES_REQUESTED** [review]
Hi, @georgel-pop-lr,

After discussing with the team, we came to the conclusion that the appropriate solution for this case would be to remove the `hmtlFor` from the [ReactFieldBase](https://github.com/liferay/liferay-portal/blob/bdcb90f66b794af972dd4c635ce812b98236fbd2/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/src/main/resources/META-INF/resources/FieldBase/ReactFieldBase.es.js#L339).

As mentionted in this [thread](https://liferay.slack.com/archives/CL8R04Z7X/p1649435842383199?thread_ts=1649177234.360879&cid=CL8R04Z7X), the `htmlFor` was wrongly added in this [commit](https://github.com/liferay/liferay-portal/commit/1066cd0499503953f59762541c1ae5aa4976f503).

When we fixed the accessibility of form fields, by adding the `aria-labelledby` in this [commit](https://github.com/liferay/liferay-portal/commit/c533e49cca8ac47d09ddbe12d4518d5ff93d7c22#diff-e24cee579291babd4621a3cc2f45c41f3ac90a1a8ebdf8fd0d3267195717812aR206-R209), the `htmlfor` should have been removed again as it was done in this previous [commit](https://github.com/liferay/liferay-portal/commit/c75048c163ab62c78029c5a7dbcfcb67f5b2a86a).

Could you please make this change and resend this PR?

Thanks!

**Comment by georgel-pop-lr** [comment]
> 

Hi @carolmariaabb,

The client is insisting that we are not covering https://www.w3.org/WAI/WCAG21/Techniques/html/H44 and this FOR and ID is needed.

If you check, H44 is not being covered only by G131 + G162 so https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships and https://www.w3.org/WAI/WCAG21/Understanding/name-role-value are failing, these both request H44 in order for them to be sufficient.

I think the client is right on this.

Let me know what you think.

Regards.

**Comment by carolmariaabb** [comment]
Hi @georgel-pop-lr,

> The client is insisting that we are not covering https://www.w3.org/WAI/WCAG21/Techniques/html/H44

As I understand it, the `H44` is actually a technique that may or may not be implemented by us.

If you check the **Techniques** section in [Understanding Success Criterion 1.3.1: Info and Relationships](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships) and [Understanding Success Criterion 4.1.2: Name, Role, Value](https://www.w3.org/WAI/WCAG21/Understanding/name-role-value), you will see that:
> Each numbered item in this section represents a technique or combination of techniques that the WCAG Working Group deems sufficient for meeting this Success Criterion. **However, it is not necessary to use these particular techniques.** 

In addition, if you check the [Understanding Techniques for WCAG Success Criteria
](https://www.w3.org/WAI/WCAG21/Understanding/understanding-techniques) you will see that:
> Techniques are informative—that means they are not required. The basis for determining conformance to WCAG 2.1 is the success criteria from the WCAG 2.1 standard—not the techniques.

> There may be other ways to meet success criteria besides the sufficient techniques 

What we need to know is whether or not we are meeting the Success Criterion, and for that we can check your **Intent** section.

That said, could you provide more details about this issue, i.e. why we are not meeting the Success Criterion? If you prefer, you can open a PTR so we can discuss this further.

**Comment by carolmariaabb** [comment]
This PR is blocked by [PTR-3032](https://issues.liferay.com/browse/PTR-3032). 

I'll close this one for now.

**Comment by carolmariaabb** [comment]
ci:close

**Pull request closed without merging**
