### PR TITLE
LPS-125451 - Form Entries Report displays incorrect count when draft entries are deleted.

### PR DESCRIPTION
**Pull request by ethib137**

### CODE REVIEW

**Comment by natocesarrego** [comment]
Great job, @ethib137! 😄 Your fix makes sense to me. What do you think, @marcosapmf?

Additionally, @ethib137, the reported failures aren't related to your fix.

Thanks.

**Comment by marcosapmf** [comment]
> Great job, @ethib137! 😄 Your fix makes sense to me. What do you think, @marcosapmf?
> 
> Additionally, @ethib137, the reported failures aren't related to your fix.
> 
> Thanks.

@natocesarrego, it makes sense to me too. Nicely done, @ethib137 😄!

Thanks a lot

**Comment by ethib137** [comment]
@natocesarrego & @marcosapmf Thanks! :)

**Comment by natocesarrego** [comment]
ci:forward

**Comment by natocesarrego** [comment]
ci:forward

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
