### PR TITLE
LPS-201229 Update the focused field only when all nested fields languages are updated after changing the editing language

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related Issue: https://liferay.atlassian.net/browse/LPS-201229

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by alinedoleron** [comment]
> ### ❌ ci:test:forms - 169 out of 177 jobs passed in 1 hour 43 minutes
> Click here for more details.
> #### Base Branch:
> Branch Name: [master](https://github.com/liferay/liferay-portal/tree/master)Branch GIT ID: [ee303dbf5d7a3c23dfc86c727bb4c78ed894e749](https://github.com/liferay/liferay-portal/commit/ee303dbf5d7a3c23dfc86c727bb4c78ed894e749)
> 
> #### Upstream Comparison:
> Branch GIT ID: [ee303dbf5d7a3c23dfc86c727bb4c78ed894e749](https://github.com/liferay/liferay-portal/commit/ee303dbf5d7a3c23dfc86c727bb4c78ed894e749)Jenkins Build URL: [EE Development Acceptance (master) - 140 - 2023-11-09[04:40:12]](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2455800447)
> 
> **ci:test:forms - 169 out of 177 jobs PASSED**
> ##### For more details click [here](https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8631/jenkins-report.html).
> #### Failures unique to this pull:
> 1. [functional-tomcat90-mysql57-jdk8/0/2](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/822835//consoleText)1. [LocalFile.FormsUploadField#AllowsFiveUploadsWhenRepeatableIsEnabled](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/822835//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FormsUploadField_AllowsFiveUploadsWhenRepeatableIsEnabled_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2023-11/test-1-29/test-portal-acceptance-pullrequest(master)/8631/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.FormsUploadField_AllowsFiveUploadsWhenRepeatableIsEnabled/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2023-11/test-1-29/test-portal-acceptance-pullrequest(master)/8631/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.FormsUploadField_AllowsFiveUploadsWhenRepeatableIsEnabled/summary.html.gz) - [Poshi Console](https://testray.liferay.com/reports/production/logs/2023-11/test-1-29/test-portal-acceptance-pullrequest(master)/8631/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.FormsUploadField_AllowsFiveUploadsWhenRepeatableIsEnabled/console.txt.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2023-11/test-1-29/test-portal-acceptance-pullrequest(master)/8631/functional-tomcat90-mysql57-jdk8/0/2/jenkins-console.txt.gz)
> 2. [functional-tomcat90-mysql57-jdk8/0/14](https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/716634//consoleText)1. [LocalFile.FormsSingleSelectionField#OptionsCanBeDisplayedInlineAndAsList](https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/716634//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FormsSingleSelectionField_OptionsCanBeDisplayedInlineAndAsList_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2023-11/test-1-29/test-portal-acceptance-pullrequest(master)/8631/functional-tomcat90-mysql57-jdk8/0/14/LocalFile.FormsSingleSelectionField_OptionsCanBeDisplayedInlineAndAsList/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2023-11/test-1-29/test-portal-acceptance-pullrequest(master)/8631/functional-tomcat90-mysql57-jdk8/0/14/LocalFile.FormsSingleSelectionField_OptionsCanBeDisplayedInlineAndAsList/summary.html.gz) - [Poshi Console](https://testray.liferay.com/reports/production/logs/2023-11/test-1-29/test-portal-acceptance-pullrequest(master)/8631/functional-tomcat90-mysql57-jdk8/0/14/LocalFile.FormsSingleSelectionField_OptionsCanBeDisplayedInlineAndAsList/console.txt.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2023-11/test-1-29/test-portal-acceptance-pullrequest(master)/8631/functional-tomcat90-mysql57-jdk8/0/14/jenkins-console.txt.gz)
> 3. [functional-tomcat90-mysql57-jdk8/1/16](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/818395//consoleText)1. [LocalFile.FormsFieldsets#PreserveTheInlineProperty](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/818395//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FormsFieldsets_PreserveTheInlineProperty_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2023-11/test-1-29/test-portal-acceptance-pullrequest(master)/8631/functional-tomcat90-mysql57-jdk8/1/16/LocalFile.FormsFieldsets_PreserveTheInlineProperty/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2023-11/test-1-29/test-portal-acceptance-pullrequest(master)/8631/functional-tomcat90-mysql57-jdk8/1/16/LocalFile.FormsFieldsets_PreserveTheInlineProperty/summary.html.gz) - [Poshi Console](https://testray.liferay.com/reports/production/logs/2023-11/test-1-29/test-portal-acceptance-pullrequest(master)/8631/functional-tomcat90-mysql57-jdk8/1/16/LocalFile.FormsFieldsets_PreserveTheInlineProperty/console.txt.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2023-11/test-1-29/test-portal-acceptance-pullrequest(master)/8631/functional-tomcat90-mysql57-jdk8/1/16/jenkins-console.txt.gz)
> 4. [functional-tomcat90-mysql57-jdk8/1/23](https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/324093//consoleText)1. [LocalFile.FormsImageField#NotPossibleSubmitLargeImage](https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/324093//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FormsImageField_NotPossibleSubmitLargeImage_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2023-11/test-1-29/test-portal-acceptance-pullrequest(master)/8631/functional-tomcat90-mysql57-jdk8/1/23/LocalFile.FormsImageField_NotPossibleSubmitLargeImage/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2023-11/test-1-29/test-portal-acceptance-pullrequest(master)/8631/functional-tomcat90-mysql57-jdk8/1/23/LocalFile.FormsImageField_NotPossibleSubmitLargeImage/summary.html.gz) - [Poshi Console](https://testray.liferay.com/reports/production/logs/2023-11/test-1-29/test-portal-acceptance-pullrequest(master)/8631/functional-tomcat90-mysql57-jdk8/1/23/LocalFile.FormsImageField_NotPossibleSubmitLargeImage/console.txt.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2023-11/test-1-29/test-portal-acceptance-pullrequest(master)/8631/functional-tomcat90-mysql57-jdk8/1/23/jenkins-console.txt.gz)
> 5. [functional-tomcat90-mysql57-jdk8/5/6](https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/305360//consoleText)1. [LocalFile.FormsSelectFromListField#CanSaveFormFieldEntryWithRestDataProvider](https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/305360//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FormsSelectFromListField_CanSaveFormFieldEntryWithRestDataProvider_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2023-11/test-1-29/test-portal-acceptance-pullrequest(master)/8631/functional-tomcat90-mysql57-jdk8/5/6/LocalFile.FormsSelectFromListField_CanSaveFormFieldEntryWithRestDataProvider/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2023-11/test-1-29/test-portal-acceptance-pullrequest(master)/8631/functional-tomcat90-mysql57-jdk8/5/6/LocalFile.FormsSelectFromListField_CanSaveFormFieldEntryWithRestDataProvider/summary.html.gz) - [Poshi Console](https://testray.liferay.com/reports/production/logs/2023-11/test-1-29/test-portal-acceptance-pullrequest(master)/8631/functional-tomcat90-mysql57-jdk8/5/6/LocalFile.FormsSelectFromListField_CanSaveFormFieldEntryWithRestDataProvider/console.txt.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2023-11/test-1-29/test-portal-acceptance-pullrequest(master)/8631/functional-tomcat90-mysql57-jdk8/5/6/jenkins-console.txt.gz)
> 
> ##### Test bundle downloads:
> * [liferay-portal-bundle-tomcat.tar.gz](https://files.liferay.com/private/bundles/test-1-29/jobs/test-portal-acceptance-pullrequest(master)/builds/8631/liferay-portal-bundle-tomcat.tar.gz) (mirrors: [dlc](http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-29/jobs/test-portal-acceptance-pullrequest(master)/builds/8631/liferay-portal-bundle-tomcat.tar.gz), [lax](http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-29/jobs/test-portal-acceptance-pullrequest(master)/builds/8631/liferay-portal-bundle-tomcat.tar.gz))

Not related.

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
