### PR TITLE
LPS-142042 Refactor createField signature

### PR DESCRIPTION
**Pull request by miltonmc**
Related Issue: https://issues.liferay.com/browse/LPS-142042

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]
Very beautiful code!! :star:

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
