### PR TITLE
LPS-194515 The result displayed in the Form entries is inconsistent

### PR DESCRIPTION
**Pull request by larissacribeiro**
**Related Issue**: [**LPS-194515**](https://liferay.atlassian.net/browse/LPS-194515)

### CODE REVIEW

**Comment by rebsilva** [comment]
just started reviewing! :cherry_blossom:

**Comment by rebsilva** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
@larissacribeiro related failure:

- [LocalFile.FormsEntries#NoMetricsIsDisplayed](https://testray.liferay.com/home/-/testray/case_results/2489030385?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2489028255%26testrayRunId%3D2489029841%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

**Comment by larissacribeiro** [comment]
Hey @carolmariaabb and @rebsilva! I've updated the fix to also work for the image field as requested in this [thread](https://liferay.slack.com/archives/C026UR5976G/p1705945997854539) and adjusted the poshi tests considering the new scenario when submitting an entry of those types of field. Could you take another look, please? Thanks!

**Comment by rebsilva** [comment]
just started reviewing! :cherry_blossom:

**Review by rebsilva — APPROVED** [review]
LGTM! :tada: :cherry_blossom:

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
