### PR TITLE
LPS-135419 The decimal separator is not aligned on the sidebar when using google chrome

### PR DESCRIPTION
**Pull request by eli-rlima**
Hi reviewer, the related issue [is here](https://issues.liferay.com/browse/LPS-135419).

I needed to revert [this commit](https://github.com/liferay-forms/liferay-portal/commit/e425fc4595eb1658868047361ff95607e18a6d16) for the feature to be visible.

### CODE REVIEW

**Comment by eli-rlima** [comment]
ci:test:relevant

**Review by miltonmc — APPROVED** [review]
LGTM!

**Comment by eli-rlima** [comment]
ci:test:relevant

**Comment by eli-rlima** [comment]
ci:test:relevant

**Comment by eli-rlima** [comment]
ci:test:relevant

**Comment by eli-rlima** [comment]
ci:forward

**Pull request closed without merging**
