### PR TITLE
LPS-135576 Keep the symbol of decimal value the same of what being displayed on the predefined value field

### PR DESCRIPTION
**Pull request by alinedoleron**
Ticket: https://issues.liferay.com/browse/LPS-135576

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Review by miltonmc — APPROVED** [review]
Great job!

Just a suggestion: Create a test case for this scenarios in order to prevent it to happen again.

**Comment by alinedoleron** [comment]
Thanks @miltonmc! 
I tried to create a poshi test but something strange happened as I told you guys on the daily meeting last week. I decided not to add this test for now but I'll try to talk to QA to see how I can handle the case I need to type a comma but it only works if I type more than one. Ex: It only works if I put the test line like: 		
`FormFields.editFieldPredefined(key_fieldReference = "1,,3");`

**Comment by miltonmc** [comment]
That's true! I've forgot your mention during the daily, sorry :sweat_smile: 
I'm forwarding this PR now and then we can see how handle a test for it.

**Comment by miltonmc** [comment]
ci:forward

**Pull request closed without merging**
