### PR TITLE
LPS-189715

### PR DESCRIPTION
**Pull request by alinedoleron**
Ticket: https://liferay.atlassian.net/browse/LPS-189715

Hi @georgel-pop-lr! Thanks for the details you've described on the ticket.
I recorded a video but it was too big to attach here. But if you want you can open it on on the [ticket](https://liferay.atlassian.net/browse/LPS-189715) (file name: **LPS-189715_.webm**)

Please let me know if there' s something missing.

Thanks!

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:forms

**Comment by alinedoleron** [comment]
ci:test:data-engine

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:data-engine

**Comment by davisaints** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
Hi @rebsilva! @davisaints made the QA analysis and the failures are not related. Please, could you review the PR when you have time? Thanks 💜

**Comment by georgel-pop-lr** [comment]
> Hi @rebsilva! @davisaints made the QA analysis and the failures are not related. Please, could you review the PR when you have time? Thanks 💜

Hi @alinedoleron,

Thanks for checking this, I had a look at the video, and it seems to cover all the cases.

@rebsilva! @davisaints The client needs this in order to go to live, so is good to have it as soon as possible.

Regards.

**Review by rebsilva — CHANGES_REQUESTED** [review]
Hi @alinedoleron! Really good job on this :tada: I just realised that this commit has an error on its writing:

> LPS-189715 Do not call onchange on geolocation defualt value

I think it should be default instead of defualt right? I recommend making a rename only of this commit and everything is ready to go!!

**Comment by alinedoleron** [comment]
ci:forward:force

**Comment by alinedoleron** [comment]
ci:stop

**Comment by alinedoleron** [comment]
PR manually forwarder to https://github.com/brianchandotcom/liferay-portal/pull/141814

**Pull request closed without merging**
