### PR TITLE
LPS-129520 Select and Clear from Image and File upload fields buttons are not being translated on Forms

### PR DESCRIPTION
**Pull request by mateusgomes01**

### CODE REVIEW

**Comment by mateusgomes01** [comment]
ci:test:sf

**Comment by mateusgomes01** [comment]
@carolmariaabb Carol, could you please review this pull request? Thanks!

**Comment by carolmariaabb** [comment]
Hi @mateusgomes01 , 

I don't know why, but when I run the `gw format source` command, it deletes the language keys you added. That's why the `ci:test:sf` has FAILED. 

Captura de Tela 2021-06-18 às 10 20 06

**Comment by mateusgomes01** [comment]
@carolmariaabb yeah, I also didn't understand why that's happening. Do you know with whom should we talk to about this issue?

**Pull request closed without merging**
