### PR TITLE
[TS] LPS-200200 Handling record creation and update separately

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

I made a small correction to [LPS-200200](https://liferay.atlassian.net/browse/LPS-200200).

It now separates the two cases:

- adding a new record, where the nested items are added to `fieldValue`'s inner `nestedFieldValues` array
- updating a record, where the nested items are added sequentially to the `normalized` array

Thank you and best regards,
István

### CODE REVIEW

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
I just started reviewing! :cherry_blossom:

**Review by rebsilva — COMMENTED** [review]
LGTM, but I'll ask @alinedoleron to take a look as well since she has worked with DDL before

**Comment by alinedoleron** [comment]
LGTM!

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
