### PR TITLE
LPS-147590

### PR DESCRIPTION
**Pull request by alinedoleron**
Ticket: https://issues.liferay.com/browse/LPS-147590

This PR fixes the bug of not updating the status on Default column.

https://user-images.githubusercontent.com/26491796/179073953-ff3d392b-c309-44d9-94d4-a2909cc163c0.mp4

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Review by rebsilva — APPROVED** [review]
LGTM! :purple_heart:

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
