### PR TITLE
LPS-165822 MultiPanelSidebar not accessible to screen readers

### PR DESCRIPTION
**Pull request by alinedoleron**
Ticket: https://issues.liferay.com/browse/LPS-165822

Solution: I've followed the suggestion made by Marcos Castro on his last comment.

> [Marcos Castro](https://issues.liferay.com/secure/ViewProfile.jspa?name=marcos.castro) added a comment - [3 days ago](https://issues.liferay.com/browse/LPS-165822?focusedCommentId=2914432&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2914432)
> We are not informing correctly to the screenreader that is a tablist with tabs.
> 
> The mechanisms is not well labelled, we need to use role="tablist" aria-orientation="vertical" insted of a simple nav.
> 
> Also menu buttons need role="tab".
> 
> I suggest to copy the component or all composition from the component in page editor.

### CODE REVIEW

**Comment by cgmonte** [comment]
Hey, @alinedoleron! I just checked your solution with JAWS screen reader. I have some observations regarding the expected behavior:

- **Using the screen reader it's easy to understand how the MultiPanelSidebar works and where you are within it**.
When we get into the form editing area, the written instruction is announced: "Drag fields from the sidebar to compose your form". The next tab takes to the vertical nav, which is part of the sidebar, this is never announced. It announces "Panel builder tab is selected, 1 of 4", but there is no mention of a sidebar. You are already in the sidebar, but there is no information about it. I think the best here is to change the instructional test. It should prompt the user to "Drag fields from the builder tab in the side panel". Why sometimes it refers to a sidebar and other times to a panel? Ins't the same thing? It is confusing. 

- **After opening a panel, pressing tab should move focus into the panel**.
Right now, it moves focus to the button for closing the "sidebar", not the panel content. I think it should move focus to the first element of the panel content. We should think a little about how to describe what is the tabbing path to get to the close button. Also, closing the panel is never announced. Closing and opening the panel should be announced, otherwise the interface state is not clear to the user. 

- **The user should know when they've entered the panel**. 
I think this wasn't fixed. We should have an announcement of this action, something like "you have entered the builder panel. select a field to add to the form"

Overall, I don't think this is a easy fix. We should put some thought in this, together with the design team. The fix for this bug is more of an interaction design activity. Lets talk to Julia!

**Review by cgmonte — COMMENTED** [review]
Hey, @alinedoleron! I just checked your solution with JAWS screen reader. I have some observations regarding the expected behavior:

- **Using the screen reader it's easy to understand how the MultiPanelSidebar works and where you are within it**.
When we get into the form editing area, the written instruction is announced: "Drag fields from the sidebar to compose your form". The next tab takes to the vertical nav, which is part of the sidebar, this is never announced. It announces "Panel builder tab is selected, 1 of 4", but there is no mention of a sidebar. You are already in the sidebar, but there is no information about it. I think the best here is to change the instructional test. It should prompt the user to "Drag fields from the builder tab in the side panel". Why sometimes it refers to a sidebar and other times to a panel? Ins't the same thing? It is confusing. 

- **After opening a panel, pressing tab should move focus into the panel**.
Right now, it moves focus to the button for closing the "sidebar", not the panel content. I think it should move focus to the first element of the panel content. We should think a little about how to describe what is the tabbing path to get to the close button. Also, closing the panel is never announced. Closing and opening the panel should be announced, otherwise the interface state is not clear to the user. 

- **The user should know when they've entered the panel**. 
I think this wasn't fixed. We should have an announcement of this action, something like "you have entered the builder panel. select a field to add to the form"

Overall, I don't think this is a easy fix. We should put some thought in this, together with the design team. The fix for this bug is more of an interaction design activity. Lets talk to Julia!

**Comment by alinedoleron** [comment]
Thank you for the analysis, @cgmonte! I'll wait for his answer on the ticket https://issues.liferay.com/browse/LPS-165822

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:forms

**Comment by cgmonte** [comment]
Sorry for the delay @alinedoleron I am downloading this now and will start reviewing.

**Review by cgmonte — CHANGES_REQUESTED** [review]
Hey! I just had a call with @alinedoleron and we agreed to make one last adjustment to behavior :pray:

**Comment by alinedoleron** [comment]
Hi @cgmonte. I've updated the PR with the changes we've agreed to make for now. Thanks!

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:data-engine

**Comment by alinedoleron** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
Resent to https://github.com/liferay-forms/liferay-portal/pull/2236

/cc @alinedoleron

**Pull request closed without merging**
