### PR TITLE
LPS-143602 Update ddm_form to take into account if the private layouts are enabled or not when we are rendering LinkToPageField

### PR DESCRIPTION
**Pull request by ealonso**
Hey @liferay-forms,

As part of https://issues.liferay.com/browse/LPS-143602 we are modifying the portal apps to take into account if the private pages are enabled or not. 

In this case we need to update ddm forms, since if we have a LinkToPageField we are showing a nav bar with two tabs, one for public pages and another one for private pages, then if the private pages are not enabled we are showing the nav bar with only one tab called pages.

Please let me know if you have any question.

Regards,
Eudaldo.

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hi @ealonso, your pull looks good to me. :slightly_smiling_face: 

I just have a simple question: if this change is a need from the Link to Page Field, shouldn't it be done on the Data Engine side instead since the Web Content Structures use it?

Thanks!

**Comment by ealonso** [comment]
Hey @natocesarrego,

Yes, it is also necessary for Data Engine. In data engine we have LayoutDDMFormFieldTemplateContextContributor which is in layout modules and we are using the Item Selector to get the layouts, since it is generic and it is part of Echo Team it is already merged on master as part of LPS-143422

Regards,
Eudaldo.

**Comment by natocesarrego** [comment]
Thanks for your clarification, @ealonso. :slightly_smiling_face:

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
