### PR TITLE
LPS-109667 See partial results

### PR DESCRIPTION
**Pull request by alinedoleron**
This PR is related to allow submitters (and guests) to see the responses summary of a Form.

Related tickets:

- https://issues.liferay.com/browse/LPS-142262
- https://issues.liferay.com/browse/LPS-142261
- https://issues.liferay.com/browse/LPS-142260
- https://issues.liferay.com/browse/LPS-142259

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hey @alinedoleron, can you please fix the source formatter issues and resend? Thanks

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @alinedoleron, can you please check if these failures are related to your changes? Thanks

**Comment by alinedoleron** [comment]
ci:test:sf

**Pull request closed without merging**
