### PR TITLE
LPS-110839 reset value if field is not visible in view mode

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
@linolaoj, I executed the steps described on the ticket using the latest master (from today) and I couldn't reproduce the issue, can you please check on your side to see if you get the same result? Or is there any missing step on the LPS?

Thanks in advance.

**Comment by linolaoj** [comment]
Hi @natocesarrego ,
I've commented on [LPS-110839](https://issues.liferay.com/browse/LPS-110839?focusedCommentId=2314119&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2314119) showing my test on master. 
Please let me know if you can still not reproduce the issue.
Thanks!

**Review by natocesarrego — CHANGES_REQUESTED** [review]

**Comment by linolaoj** [comment]
Updated at https://github.com/liferay-forms/liferay-portal/pull/38

**Pull request closed without merging**
