### PR TITLE
LPS-172222 When Javascript SPA is turned off, can't save form instance

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related Issue: https://issues.liferay.com/browse/LPS-172222

For more context, you can check: https://issues.liferay.com/browse/PTR-3620

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:stop

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by brianchandotcom** [comment]
@carolmariaabb merged to master

**Pull request closed without merging**
