### PR TITLE
LPD-39148 

### PR DESCRIPTION
**Pull request by rijema**
Related: https://liferay.atlassian.net/browse/LPD-37920

### CODE REVIEW

**Comment by larissacribeiro** [comment]
ci:test:playwright

**Comment by marcelabc** [comment]
Hey @rebsilva 
Could you review this PR, please? :smile:

**Comment by larissacribeiro** [comment]
hey @rebsilva, I've assigned Carlos here because He has already reviewed this commit on another pr, We only separated the one related to the test fix! Thankss 🌷

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by rijema** [comment]
ci:forward

**Comment by rijema** [comment]
None of the above failed tests has the FormsPage/deleteItems implementation.

**Pull request closed without merging**
