### PR TITLE
LPS-136630 Introduce a switch to personalise if DDM Image description field should be required

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

This is the latest version of the solution, incorporating the recommended changes made in #936

Thank you and best regards,
István

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Hey, @IstvanD. I've found a very edge bug. 😕 

Here are the steps:
1. Before installing the fix, create a web content structure with two image fields (one required and the other not required);
2. Install the fix;
3. Click to edit the structure and disable the required description from the required image field;
4. Save the structure;
5. Go back to edit the structure again, but now click on the required image to show its sidebar settings;
6. Now, click on the non-required image to show its sidebar settings and turn on the required switch.

Actual result: entire builder disappears.

Here's a video of the final steps of the steps above:

https://user-images.githubusercontent.com/11450348/135168389-22480661-65af-40c8-ab98-9d4bed83672b.mov

For that reason, I'll close this pull request and wait for the fix. Thanks a lot for your patience.

**Comment by IstvanD** [comment]
Hi @rodrigopaulino thank you for testing the fix.
I have gone through the steps provided but couldn't reproduce this issue.
Are you getting it consistently? Does any error message appear on the server or the javascript console?

**Comment by IstvanD** [comment]
Hi @rodrigopaulino in the structure you provided the value of `requiredErrorMessage` is `{			}` but it should look like this, even when it's empty: `{"en_US" : ""}`
The JS error message it get
```
TypeError: Cannot read properties of null (reading 'en_US')
at settingsContext.es.js:293
```
suggests that the value is invalid.

If you import that structure in an environment **before** the fix, and enable the second image field's required property you'll get the same error.

**Comment by rodrigopaulino** [comment]
I see. Thanks for your analysis, @IstvanD.

I'll reopen it and continue the review then.

**Comment by rodrigopaulino** [comment]
ci:reopen

**Comment by rodrigopaulino** [comment]
Hey, @IstvanD. Apparently, you have force pushed into your branch. I'm afraid you'll have to send a new PR.

**Comment by IstvanD** [comment]
Hi @rodrigopaulino the new pull request is https://github.com/liferay-forms/liferay-portal/pull/974

**Pull request closed without merging**
