### PR TITLE
LPS-165581 Changing the select drop-down menu to open downwards

### PR DESCRIPTION
**Pull request by kildarep**
Hello Reviewer!
Related Issue: https://issues.liferay.com/browse/LPS-165581

  For the solution I edited the alignmentPosition that was {0} as TopRight to {5} that is BottomLeft

### CODE REVIEW

**Comment by kildarep** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
Hello, @kildarep. The code seems to resolve the issue but this ticket has been reverted some times due to broken tests (See Brian's comment: https://github.com/brianchandotcom/liferay-portal/pull/128761#issuecomment-1382116562). I'll ask the QA team to verify them. 
Thanks!

**Comment by kildarep** [comment]
Ok @alinedoleron, I look forward to the analysis

**Comment by andreefarias** [comment]
QA CI approved.

There were no poshi tests that broke in this PR.

**Comment by alinedoleron** [comment]
Hi @kildarep, as no poshi has broken, please, could you run `yarn test` to check is there are snapshots to be updated? If so, you can run `yarn test -u`, to update them.
If you need any help please let me know.

Thanks!

**Comment by kildarep** [comment]
Hi @alinedoleron, `yarn test -u` executed and updated as requested. Thanks for your help!

**Comment by kildarep** [comment]
ci:test:sf

**Comment by kildarep** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:reevaluate:1397401_3313

**Comment by marcelabc** [comment]
Hi @kildarep,
I analyzed the unique failure and it is not related to your work. You can send it directly to Brian if you prefer :+1: 
Please, remember to update the ticket and here with the link to Brian's PR.

**Comment by kildarep** [comment]
Resend here: [#130957](https://github.com/brianchandotcom/liferay-portal/pull/130957)

**Pull request closed without merging**
