### PR TITLE
[TS] LPS-121695 Use scopeGroupId just like in DDMTemplateStagedModelDataHandler

### PR DESCRIPTION
**Pull request by vendeltoreki**
Related Issue: https://issues.liferay.com/browse/LPS-121695

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hey @vendeltoreki, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
See details on [LPS-121695](https://issues.liferay.com/browse/LPS-121695?focusedCommentId=2288956&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2288956).

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @vendeltoreki, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
Hi @vendeltoreki, I'm closing this pull, please see [this comment](https://issues.liferay.com/browse/LPS-121695?focusedCommentId=2289149&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2289149) for more details.

Thanks.

**Pull request closed without merging**
