### PR TITLE
LPS-188981 Use option reference in dropdown value attribute

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://liferay.atlassian.net/browse/LPS-188981

### CODE REVIEW

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by naraandrade** [comment]
ci:forward

**Comment by naraandrade** [comment]
ci:forward

**Comment by danvb112** [comment]
Sent to: https://github.com/brianchandotcom/liferay-portal/pull/137516

**Pull request closed without merging**
