### PR TITLE
LPS-154761 Combine the CodeMirror and the Sidebar

### PR DESCRIPTION
**Pull request by miltonmc**

### CODE REVIEW

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
@naraandrade I did some changes on the CodeMirror and the Sidebar that are related to the things we talked in the last meeting we had and may be interesting use this PR for further discussions.

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
> @naraandrade I did some changes on the CodeMirror and the Sidebar that are related to the things we talked in the last meeting we had and may be interesting use this PR for further discussions.

Thank you :) I'll take a look at it on Monday.

**Comment by miltonmc** [comment]
ci:forward

**Pull request closed without merging**
