### PR TITLE
LRQA-69879

### PR DESCRIPTION
**Pull request by natocesarrego**
Related Issue: https://issues.liferay.com/browse/LRQA-69879

The [LPS-30938](https://issues.liferay.com/browse/LPS-30938) has removed the default VIEW permission of the roles **Site Member** and **Guest**. Therefore, remove the VIEW permission from all roles in the following tests is no more necessary:

- com.liferay.dynamic.data.mapping.service.test.DDMStructureServiceTest.testSearchWithSiteMemberPermission
- com.liferay.dynamic.data.mapping.service.test.DDMStructureServiceTest.testSearchWithSiteAdminPermission
- com.liferay.dynamic.data.mapping.service.test.DDMStructureServiceTest.testGetStructuresWithSiteAdminPermission

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @natocesarrego, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
ci:reevaluate:1317401_300

**Comment by liferay-forms** [comment]
Hey @natocesarrego, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @natocesarrego, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @natocesarrego, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
