### PR TITLE
LPS-195265   Accessibility error in Select from List fields

### PR DESCRIPTION
**Pull request by alinedoleron**
[LPS-195265](https://liferay.atlassian.net/browse/LPS-195265) Accessibility error in Select from List fields

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:forms

**Comment by alinedoleron** [comment]
ci:test:forms

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:forms

**Comment by alinedoleron** [comment]
ci:test:data-engine

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
This PR is being analyzed by QA team. Some poshi tests need to be fixed.

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:forms

**Comment by alinedoleron** [comment]
> ### ❌ ci:test:sf - 0 out of 1 jobs passed in 6 minutes
> Click here for more details.
Hi @carolmariaabb, do you know how I can solve this error? I did not change the file mentioned in the sf failure. Thanks!

**Comment by carolmariaabb** [comment]
> > ### ❌ ci:test:sf - 0 out of 1 jobs passed in 6 minutes
> > Click here for more details.
> > Hi @carolmariaabb, do you know how I can solve this error? I did not change the file mentioned in the sf failure. Thanks!

@alinedoleron go to the `liferay-portal/portal-impl` folder and run `ant format-source-current-branch` to see what happens.

**Comment by alinedoleron** [comment]
ci:test:relevant

**Pull request closed without merging**
