### PR TITLE
LPS-147079 buildLang

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issue: https://issues.liferay.com/browse/LPS-147079

Hello Reviewer!

This PR has a fix of the bug above. The current help text of the email field is not clear to the users how to add an email properly on Forms sharing option, so I'm changing it to: 

- Type a comma or press enter to input emails.

If you have any questions feel free to ask, thank you for your time!

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @rebsilva, can you please check if these failures are related to your changes? Thanks

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:stop

Stopping and restarting due to ci-infrastructure bug

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @rebsilva, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
Hey @rebsilva, can you please check if these failures are related to your changes? Thanks

**Comment by alinedoleron** [comment]
ci:test:relevant

**Pull request closed without merging**
