### PR TITLE
LPS-198028

### PR DESCRIPTION
**Pull request by natocesarrego**
Hi guys,

This pull request fixes the issue reported in https://liferay.atlassian.net/browse/LPS-198028. Basically, if a Form has entries associated to a previous version of a Form then a `NullPointerException` is raised because all entries of a Form will try to be upgraded considering only the latest Form version. The fix associates the Form entries to the correct version of the Form.

If you have any questions, please let us know. :slightly_smiling_face: 

Cheers!

### CODE REVIEW

**Comment by marcelabc** [comment]
Just started reviewing :)

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:upgrade

**Comment by marcelabc** [comment]
ci:test:forms

**Comment by marcelabc** [comment]
Hey @natocesarrego 
I asked the QA team to help us to analyze the CI results :+1:

**Comment by natocesarrego** [comment]
Thanks, @marcelabc!

cc @alberttgomes

**Comment by davisaints** [comment]
The failures aren't related. This PR is good to go!

[Comparison with acceptance](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1697026992510&testrayRunIdA=2438648633&testrayRunIdB=2439610345). No regressions found in the upgrade suite.

**Comment by davisaints** [comment]
ci:forward

**Comment by natocesarrego** [comment]
Hey @davisaints and @marcelabc,

Considering this pull is approved from the code review and QA perspectives, do you guys mind if I manually forward this pull to Brian?

This way we can get rid of random unrelated test failures and also we save CI resources. :smile:

**Comment by marcelabc** [comment]
@natocesarrego You can send it directly to Brian :+1: 
Thank you!

**Comment by natocesarrego** [comment]
Rebased and manually forwarded to Brian: https://github.com/brianchandotcom/liferay-portal/pull/142209

**Pull request closed without merging**
