### PR TITLE
LPS-136630 Introduce a switch to personalise if DDM Image description field should be required

### PR DESCRIPTION
**Pull request by IstvanD**
Related Issue: https://issues.liferay.com/browse/LPS-136630

Dear Team,

I'm sending the solution with the updated package name.
We agreed with @brianchandotcom on Slack that he'll take a look at this, however, I cannot send pulls directly to him.

Best regards,
István

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:forward

**Pull request closed without merging**
