### PR TITLE
LPS-172991 master

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi Team,

could you please check my fix?

**Reproduction Steps**

1. Create a new structure
   add a Text field
   set Repeatable to Yes
   save the structure
2. Start creating a new web content with the structure
   assert that you can see the repeatable field with a ➕ sign
   click on the ➕ sign
3. A 2nd repeatable field will appear with ➖➕

**Expected Behavior**
The ➖ sign appears next to the ➕ sign at the 1st element too and we can remove the 1st element too

**Actual Behavior**
The :➖ sign never appears at the 1st element

Running the test ReactFieldBase fails on fE ReactFieldBase › renders the add button when repeatable is true

 TypeError: pages is not iterable

      82 |      setPages(pages) {
      83 |              console.log('pages', pages)
    > 84 |              this._pages = [...pages];
         |                                ^
      85 |      }
      86 |
      87 |      visitFields(evaluateField) {

      at PagesVisitor.setPages (../../data-engine/data-engine-js-components-web/src/main/resources/META-INF/resources/js/utils/visitors.es.js:84:21)
      at new PagesVisitor (../../data-engine/data-engine-js-components-web/src/main/resources/META-INF/resources/js/utils/visitors.es.js:19:8)
      at checkRepetitions (src/main/resources/META-INF/resources/FieldBase/ReactFieldBase.es.js:264:19)
      at FieldBase (src/main/resources/META-INF/resources/FieldBase/ReactFieldBase.es.js:295:7)
      at renderWithHooks (../../../node_modules/react-dom/cjs/react-dom.development.js:16260:18)
      at mountIndeterminateComponent (../../../node_modules/react-dom/cjs/react-dom.development.js:18794:13)

The new **checkRepetitions** function is referencing to the page here: const visitor = new PagesVisitor(pages);
I tried to change the PageProvider in the test file by adding the pages value, but still i have the error:
```
const FieldBaseWithProvider = (props) => (
   <PageProvider value={{editingLanguageId: 'en_US', pages: []}}>
      <FieldBase {...props} />
   </PageProvider>
);

```
Could you please check this error?

More details: https://issues.liferay.com/browse/PTR-3639
https://issues.liferay.com/browse/LPS-172991

### CODE REVIEW

**Comment by carolmariaabb** [comment]
@alinedoleron could you help @rolandpakai fix the unit test? Thanks!

**Comment by alinedoleron** [comment]
> @alinedoleron could you help @rolandpakai fix the unit test? Thanks!

Sure, I'll have a look now.

**Review by alinedoleron — CHANGES_REQUESTED** [review]
Hello, @rolandpakai!

The solution I found to fix the test fix was to import the FormProvider passing the pages and wrap the PageProvider. Like this:

```
import {FormProvider, PageProvider} from 'data-engine-js-components-web';
INF/resources/FieldBase/ReactFieldBase.es';

const spritemap = 'icons.svg';

const FieldBaseWithProvider = (props) => (
	<FormProvider initialState={{pages: []}}>
		<PageProvider value={{editingLanguageId: 'en_US'}}>
			<FieldBase {...props} />
		</PageProvider>
	</FormProvider>
```

Also, I found a little bug on Documents and Media component with repeatable field. So I'll propose as addition in the code.

**Comment by rolandpakai** [comment]
Hi @alinedoleron 

thanks for the solution. It works for me too. I added the change wiht a new commit.

Thanks, Roland

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by rolandpakai** [comment]
ci:test:forms

**Review by alinedoleron — CHANGES_REQUESTED** [review]

**Review by alinedoleron — APPROVED** [review]

**Pull request closed without merging**
