### PR TITLE
[IPT] LPS-196486 Add aria-required attribute in the fields that were without

### PR DESCRIPTION
**Pull request by vngoliveira**
Related issue: [LPS-196486](https://liferay.atlassian.net/browse/LPS-196486)
LPP ticket: [LPP-50777](https://liferay.atlassian.net/browse/LPP-50777)

### CODE REVIEW

**Comment by vngoliveira** [comment]
ci:relevant

**Comment by vngoliveira** [comment]
ci:stable

**Comment by vngoliveira** [comment]
ci:test:stable

**Comment by vngoliveira** [comment]
ci:test:relevant

**Review by alinedoleron — CHANGES_REQUESTED** [review]
Hi @vngoliveira! Thanks for working on that!
I have just one more place I think aria-required is missing.
On Checkbox.tsx, the toggle can be a **Switcher** or a **Checkbox**. You've added the `aria-required={required}` only for the Switcher. So, on line 80 of <ClayCheckbox> we should also have the property aria-required. Please, could you make this change?
Thanks!

**Comment by vngoliveira** [comment]
ci:test:sf

**Comment by vngoliveira** [comment]
ci:test:relevant

**Comment by vngoliveira** [comment]
ci:test:stable

**Comment by alinedoleron** [comment]
Hi @vngoliveira! Some snapshots tests have failed because we've added the new attribute on the html. To fix,  you can run:
**`yarn test`** 
After check that only snapshots have failed  you can run
**`yarn test -u`** 

If you need any help you can call me and I can see this with you, ok? 
Thanks!

**Comment by vngoliveira** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:forms

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by davisaints** [comment]
ci:test:stable

**Comment by davisaints** [comment]
Startup error [here](https://testray.liferay.com/home/-/testray/case_results/2434047027?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2434046955%26testrayRunId%3D2434047012%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc). Can you rebase your PR?

**Comment by alinedoleron** [comment]
Thanks, @davisaints!!

Hi @vngoliveira! According to @davisaints analysis, you'll need to make a rebase on the branch to see if stable error will be fixed. Thanks!

**Comment by vngoliveira** [comment]
ci:test:sf

**Comment by vngoliveira** [comment]
ci:test:stable

**Comment by vngoliveira** [comment]
ci:test:relevant

**Comment by davisaints** [comment]
Hi @vngoliveira, we don't need to trigger stable and relevant separately at the same time; it's a bad idea because relevant always includes stable

**Comment by alinedoleron** [comment]
According to QA team, the failures are not related.

**Comment by alinedoleron** [comment]
ci:forward:force

**Pull request closed without merging**
