### PR TITLE
LPS-197491 Removed tabindex for form field types.

### PR DESCRIPTION
**Pull request by SelenaAungst**
https://liferay.atlassian.net/browse/LPS-197491
Forwarded from https://github.com/liferay-peds/liferay-portal/pull/291

### CODE REVIEW

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
just started reviewing :cherry_blossom:

**Comment by rebsilva** [comment]
Hi @SelenaAungst! The tests failing seem related, because since you changed the properties of the FieldBase so some snapshots from the FE unit tests are outdated. Could you please fix them and send again? Thanks!

**Comment by SelenaAungst** [comment]
Hi @rebsilva,
I updated the snapshots and pushed my changes, please let me know if I missed any or if any other changes are needed. 
Thank you!

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
since the tests are still failing, i will take a look myself

**Comment by rebsilva** [comment]
@SelenaAungst I saw that some snapshots haven't being updated, so I can do this and send another PR with your first commit; but before you do this, can you please explain why it was decided to remove the tabindex? Because from what I saw, the labels on the Form Fields are not being read anymore. When the user is filling a Form how will they know the purpose of the field or what should they do? I appreciate your help on this!

**Comment by SelenaAungst** [comment]
Hi @rebsilva,
I removed the tabindex because it caused errors with accessibility test scans. I tested and can confirm that all of the form field types still can be focused with my changes (except for 2 but those were caused by a separate commit). I just did an additional test and the screen reader still reads all but a few form field type titles, so I will send a new commit with updated changes for this. Apologies for the inconvenience and many updates on this one!

**Comment by rebsilva** [comment]
Hi @SelenaAungst, thanks for your answer! So I will wait for your new commit with these changes. 

Also I suggest you, if possible, to remove the changes you made on the commit to update snapshots and do a new one to update all that are missing as well. You can go to `dynamic-data-mapping-form-field-type/test` and run the command `yarn test -u` that all the snapshots necessary will be updated for you :blush:

If you have any doubts you can reach me anytime, thanks!

**Review by rebsilva — CHANGES_REQUESTED** [review]
Still needs some changes as discussed above!

**Comment by rebsilva** [comment]
Sure @SelenaAungst! You can take your time on this, and if you prefer, you can open another PR okay? You can mention me and I will review it again. Thanks!

**Comment by SelenaAungst** [comment]
Thank you @rebsilva! I will open another PR for this.

**Pull request closed without merging**
