### PR TITLE
LPS-152305 - Difficult to resize elements in field group due to lack of spacing

### PR DESCRIPTION
**Pull request by alberttgomes**
I'm changed the margin of field Group 2rem how suggester video in ticket.
LPS - https://issues.liferay.com/browse/LPS-152305

### CODE REVIEW

**Comment by alberttgomes** [comment]
ci:test:sf

**Comment by alberttgomes** [comment]
ci:test:relevant

**Comment by alberttgomes** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
@cgmonte, could you please review this pull? Thx.

**Comment by alberttgomes** [comment]
ci:test:relevant

**Comment by alberttgomes** [comment]
ci:test:relevant

**Comment by cgmonte** [comment]
> @cgmonte, could you please review this pull? Thx.

Sure! Sorry, just saw your comment. Will start reviewing it now.

**Comment by cgmonte** [comment]
LGTM

**Comment by cgmonte** [comment]
ci:forward

**Pull request closed without merging**
