### PR TITLE
[TS] LPS-177122 | master

### PR DESCRIPTION
**Pull request by samanzanedo**
Hi team,

Some DXP compatible databases (i.e. Oracle) restrict columns type to be used in 'order by' clauses. In this case, Oracle does not allow to use a LOB type.
Entity 'DDMTemplate' defines column 'name' as LOB (for Oracle). Thus, DXP functionality to order by template name crashes when the system uses an Oracle database.

Proposed solution in this PR consists in doing a cast to 'varchar' (string) to avoid the ORA-00932 error.

Reference: https://issues.liferay.com/browse/LPS-177122

Regards

### CODE REVIEW

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:reevaluate:1297401_6522

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:reevaluate:1387401_6689

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by samanzanedo** [comment]
@carolmariaabb 
Added semantic versioning.

Regards

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
