### PR TITLE
LPS-165991 Change parameter order

### PR DESCRIPTION
**Pull request by TaiPhamLR**
Dear team,
This PR fixes the issue in ticket [LPS-165991](https://issues.liferay.com/browse/LPS-165991). Please help me to review it and leave your comments.
Thanks,
Tai.
cc @sontruongces

### CODE REVIEW

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by marcelabc** [comment]
Hi @TaiPhamLR,
Thanks for contributing! :smile: 
Could you fix the SF error, please?

**Comment by sontruongces** [comment]
> Hi @TaiPhamLR, Thanks for contributing! smile Could you fix the SF error, please?

Hi @marcelabc, I got the same format issue at https://github.com/liferay-objects/liferay-portal/pull/1144#issuecomment-1263891585. It's being caused by other files from another module and already submitted a PR (https://github.com/liferay-objects/liferay-portal/pull/1146) to fix this.

**Comment by carolmariaabb** [comment]
Hi @sontruongces,

It was actually a different format issue and it was related to your changes. But I already fixed it and I manually forwarded it to Brian https://github.com/brianchandotcom/liferay-portal/pull/125037.

Thanks!

**Comment by carolmariaabb** [comment]
ci:close

**Pull request closed without merging**
