### PR TITLE
LRQA 71823

### PR DESCRIPTION
**Pull request by guivilarim**
Related Issue: https://issues.liferay.com/browse/LRQA-71823

- LRQA-71823 Fix DDM_FIELD_REFERENCE path
- LRQA-71823 Fix getFieldReference macro
- LRQA-71823 Fix getOptionReference macro

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by guivilarim** [comment]
ci:forward

**Pull request closed without merging**
