### PR TITLE
LPS-154627 Improve Forms Accessibility

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-154627

This pr maps the form element's `<label>` to the visible input and other accessibility fixes. This provides a few benefits:

1) Clicking on the `label` will focus the input
2) Screen readers will announce the label text when an input is focused
3) We don't need an `sr-only` element to announce text

Edit: Currently rerunning tests, but it looks like the failures are related to changing `div` to `button` at https://github.com/liferay-forms/liferay-portal/blob/741c56c5fc1a0c058cc66ac172c992aafd43e50d/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/src/main/resources/META-INF/resources/Select/VisibleSelectInput.es.js#L96. Can we update the tests to account for this?

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
@alinedoleron could you please review this PR? Thanks!

**Comment by alinedoleron** [comment]
> https://issues.liferay.com/browse/LPS-154627
> 
> This pr maps the form element's `<label>` to the visible input and other accessibility fixes. This provides a few benefits:
> 
> 1. Clicking on the `label` will focus the input
> 2. Screen readers will announce the label text when an input is focused
> 3. We don't need an `sr-only` element to announce text
> 
> Edit: Currently rerunning tests, but it looks like the failures are related to changing `div` to `button` at
> 
> https://github.com/liferay-forms/liferay-portal/blob/741c56c5fc1a0c058cc66ac172c992aafd43e50d/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/src/main/resources/META-INF/resources/Select/VisibleSelectInput.es.js#L96
> 
> . Can we update the tests to account for this?

Hi @pat270. Yes, you can update the snapshot tests. They are related to this change you've mentioned.

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by alinedoleron** [comment]
I've sent a new PR with snapshots tests fixed: https://github.com/liferay-forms/liferay-portal/pull/2098

**Pull request closed without merging**
