### PR TITLE
LPS-197709 Remove localizationMode property from disable condition in accepted date select

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://liferay.atlassian.net/browse/LPS-197709

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:forms

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by davisaints** [comment]
ci:test:stable

**Comment by davisaints** [comment]
Comparison with [acceptance](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1697637271529&testrayRunIdA=2442628914&testrayRunIdB=2442953744) and [forms](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1697636299178&testrayRunIdA=2442511106&testrayRunIdB=2442404202) suite

No related failures!

**Comment by davisaints** [comment]
I'm just triggering stable again since we have a startup error [here](https://testray.liferay.com/home/-/testray/case_results/2442630325)

**Comment by alinedoleron** [comment]
ci:forward:force

**Pull request closed without merging**
