### PR TITLE
LPS-152377 Update polls id to forms id

### PR DESCRIPTION
**Pull request by rebsilva**

### CODE REVIEW

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:reevaluate:1387401_298

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
Please do not send this PR yet, new changes will be made soon.

**Pull request closed without merging**
