### PR TITLE
LPD-37074

### PR DESCRIPTION
**Pull request by vngoliveira**
https://github.com/liferay-forms/liferay-portal/pull/2617
https://github.com/liferay-forms/liferay-portal/pull/2629
[LPD-37074](https://liferay.atlassian.net/browse/LPD-37074)

### CODE REVIEW

**Comment by vngoliveira** [comment]
ci:test:playwright

**Comment by vngoliveira** [comment]
ci:test:relevant

**Comment by vngoliveira** [comment]
ci:test:sf

**Comment by samuelromeiro** [comment]
Resent https://github.com/liferay-forms/liferay-portal/pull/2632

**Pull request closed without merging**
