### PR TITLE
LPS-127421 Dynamic Data Lists Web Info Panel should extend to bottom …

### PR DESCRIPTION
**Pull request by pat270**
Related Issue: https://issues.liferay.com/browse/LPS-127421

…of window

https://issues.liferay.com/browse/LPS-127421
https://issues.liferay.com/browse/LPS-149662

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
