### PR TITLE
LPS-138055 | LPS-138489 

### PR DESCRIPTION
**Pull request by alinedoleron**
Related Issues: 
https://issues.liferay.com/browse/LPS-138055
https://issues.liferay.com/browse/LPS-138489

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
Hi @miltonmc, just in case you ask about the tests. I didn't find a way to test this scenario in JS. Currently the Reports  tests only test the Cards creation itself (for example, if a List card or a graphic card is being created correctly). The scenarios of receiving the pages fields and displaying on Entries are being manual or poshi, but there's none about Search Location yet.

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Review by miltonmc — CHANGES_REQUESTED** [review]
Just a few suggestions that may help to improve the code

**Comment by liferay-forms** [comment]
Hey @alinedoleron, can you please check if these failures are related to your changes? Thanks

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @alinedoleron, can you please check if these failures are related to your changes? Thanks

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @alinedoleron, can you please check if these failures are related to your changes? Thanks

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @alinedoleron, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
Hey @alinedoleron, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
Hey @alinedoleron, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:reevaluate:1327401_322

**Comment by liferay-forms** [comment]
Hey @alinedoleron, can you please check if these failures are related to your changes? Thanks

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @alinedoleron, can you please check if these failures are related to your changes? Thanks

**Comment by alinedoleron** [comment]
ci:test:relevant

**Review by miltonmc — APPROVED** [review]
LGTM!

**Comment by miltonmc** [comment]
ci:forward

**Pull request closed without merging**
