### PR TITLE
LPD-28443 Remove unnecessary scroll event when creating a form next or previous page

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://liferay.atlassian.net/browse/LPD-28443

### CODE REVIEW

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by cgmonte** [comment]
ci:test:data-engine

**Comment by cgmonte** [comment]
ci:test:forms

**Comment by cgmonte** [comment]
ci:test:echo

**Comment by cgmonte** [comment]
ci:test:relevant

**Comment by cgmonte** [comment]
ci:test:playwright

**Comment by danvb112** [comment]
CI Failures are not related!

**Comment by danvb112** [comment]
ci:forward:force

**Pull request closed without merging**
