### PR TITLE
LPS-135713 The rich text field has inconsistent behaviour on forms when typing the predefined field

### PR DESCRIPTION
**Pull request by eli-rlima**
Related Issue: https://issues.liferay.com/browse/LPS-135713

Hi, reviewer!

This PR adds `debounce` for `onChange` event in `RichText.es.js` to prevent many dispatches.

Thanks for your review time.

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @eli-rlima, can you please check if these failures are related to your changes? Thanks

**Comment by eli-rlima** [comment]
ci:test:relevant

**Comment by eli-rlima** [comment]
ci:reevaluate:1337401_76

**Comment by eli-rlima** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by eli-rlima** [comment]
ci:reevaluate:1267401_274

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant

**Review by miltonmc — APPROVED** [review]

**Comment by miltonmc** [comment]
ci:forward

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:stop

**Pull request closed without merging**
