### PR TITLE
LPS-151476 Allowing guests to upload files in multipage forms

### PR DESCRIPTION
**Pull request by rijema**
Related Issue: https://issues.liferay.com/browse/LPS-151476

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @rijema, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:reevaluate:1257401_2387

**Comment by liferay-forms** [comment]
Hey @rijema, can you please check if these failures are related to your changes? Thanks

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
