### PR TITLE
LPS-115860 Add translate untranslated label in DDM when the elements are not available in the DOM

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Previous pull: https://github.com/liferay-forms/liferay-portal/pull/2019

I needed to add an extra [commit](https://github.com/liferay-forms/liferay-portal/pull/2026/commits/9906fc43a85e101510672e2716e0adacc3e17b1b) as I did not take into account that if you press on another menu, the items are not available in the DOM and I need to update `triggerMenu.getData('menuListContainer');`.

Steps to reproduce this case on 7.3.x or 7.2.x web content, on master this is not reproducible as on DDL we don't have more language button to change:
1. Press on the menu to open the language selector for the fields, change to a different untranslated language then default
2. Translate any field on this language
3. Press on the menu to open the language selector for the title, change language from there
4. Open again the menu for language selector for the fields, and see that is not displayed translated

Any questions, please let me know.

Regards.

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:stop

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by cgmonte** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:reevaluate:1397401_2010

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by georgel-pop-lr** [comment]
ci:forward

**Comment by cgmonte** [comment]
Hey @georgel-pop-lr and @carolmariaabb let's wait for this last relevant to finish. I am not counting on it to pass, so I will ask QA to confirm errors are unrelated when (and if) it fails. It they are unrelated, which I think they are, we will manually forward to BChan.

**Comment by cgmonte** [comment]
Hi @georgel-pop-lr, our QA team confirmed that the failures in the CI tests are not related to your changes. Can you please send this directly to [BChan](https://github.com/brianchandotcom/liferay-portal)? If you need any help to do this, you can reach me on Slack and I will be happy to help you. Thank you very much!

**Comment by georgel-pop-lr** [comment]
Manually sent: https://github.com/brianchandotcom/liferay-portal/pull/127172

**Pull request closed without merging**
