### PR TITLE
LPS-204298 - escape user name to avoid issues when opening structure item selector

### PR DESCRIPTION
**Pull request by wanderlast**
Hi @liferay-forms team,

When investigating a supposedly USM related XSS issue, I discovered another separate issue that could potentially occur during the reproduction steps with a script tag being used in a user's name. Specifically, if you have a user with a first name of "<script>alert("firstname")</script>" and they create a structure, if you open the structure selector in the WC template editor the script will activate. I wrote a small fix here and wanted it to send it your guy's way.

Let me know if this should be sent elsewhere (e.g. Lima or Echo). Thanks!

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
