### PR TITLE
[TS] LPS-197919 Image Selector UI is empty when browser does not support the image file type

### PR DESCRIPTION
**Pull request by dcarrillolf**
Ticket: https://liferay.atlassian.net/browse/LPS-197919

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by alinedoleron** [comment]
ci:test:forms

**Comment by dcarrillolf** [comment]
Hello everyone, found issue when reopening the web content: always shows the error when should be displayed.

**Pull request closed without merging**
