### PR TITLE
LPS-151126

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issues: 

- https://issues.liferay.com/browse/LPS-151126
- https://issues.liferay.com/browse/LPS-151129

Previous PRs: 

- https://github.com/liferay-forms/liferay-portal/pull/1591 _(a revert was made on these commits to avoid release blockers)_
- https://github.com/liferay-forms/liferay-portal/pull/1608

Hello Reviewer!

This PR has new features related to the story:
**As an objects admin, I want to be able to allow my users to upload files to a specific folder in Doc and Media** ([LPS-148112](https://issues.liferay.com/browse/LPS-148112))

If you have any questions feel free to ask, thank you for your time!

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @rebsilva, can you please check if these failures are related to your changes? Thanks

**Comment by rebsilva** [comment]
ci:test:sf

**Review by rodrigopaulino — APPROVED** [review]
All good from the backend, @rebsilva. Good job! 👏🏻

**Review by miltonmc — APPROVED** [review]
LGTM!

**Comment by miltonmc** [comment]
ci:forward

**Pull request closed without merging**
