### PR TITLE
LPS-136630 Introduce a switch to personalise if DDM Image description field should be required

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

This is the latest version of the solution, incorporating the recommended changes made in https://github.com/liferay-forms/liferay-portal/pull/936

Thank you and best regards,
István

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Hi, @IstvanD, could you please fix the SF failures and send the PR again? Thanks.

**Comment by rodrigopaulino** [comment]
ci:stop

**Comment by IstvanD** [comment]
Hi @rodrigopaulino new pull request sent: https://github.com/liferay-forms/liferay-portal/pull/971

**Pull request closed without merging**
