### PR TITLE
LPS-144315 Set background color on DefaultPage

### PR DESCRIPTION
**Pull request by miltonmc**
Related Issue: https://issues.liferay.com/browse/LPS-144315

# Before
Screenshot from 2021-12-22 15-17-02
Screenshot from 2021-12-22 15-14-30

# After
Screenshot from 2021-12-22 15-13-37
Screenshot from 2021-12-22 15-14-50

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by miltonmc** [comment]
ci:stop

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hey @miltonmc, can you please fix the source formatter issues and resend? Thanks

**Comment by liferay-forms** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by miltonmc** [comment]
ci:forward

**Pull request closed without merging**
