### PR TITLE
LPS-124149 Migrate ShareFormModal to React

### PR DESCRIPTION
**Pull request by diegonvs**
This PR is on top of Matu's branch.

~commit for the reviewer: e24f8e1~

~view_form_instance.jsp part is missing~

**Description:**

We can have two possible ways to instantiate a ShareFormModal:

* Using openShareFormModal function
* Using directly ShareFormModalBody/Modal buttons React component

The first one was necessary for the use case of view_form_instance.jsp file and the second one is used for calling the ModalContext redux with correct values.

We're reusing the same ModalContext for avoiding have multiple ModalContexts around the application and it prevent duplicate errors.

### CODE REVIEW

**Comment by diegonvs** [comment]
@matuzalemsteles ready for cherry-pick!

**Comment by matuzalemsteles** [comment]
@diegonvs I sent it to #142

**Comment by diegonvs** [comment]
@matuzalemsteles, see 246ecf8...c670d15

**Comment by diegonvs** [comment]
Closing this PR because Matu already cherry-picked those commits on https://github.com/liferay-forms/liferay-portal/pull/142

**Pull request closed without merging**
