### PR TITLE
LPS-122393 Check permissions for bulk actions

### PR DESCRIPTION
**Pull request by robertoDiaz**
Related Issue: https://issues.liferay.com/browse/LPS-122393

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hey @robertoDiaz, can you please fix the source formatter issues and resend? Thanks

**Comment by robertoDiaz** [comment]
ci:reopen

**Pull request closed without merging**
