### PR TITLE
LPS-121007 copy form permissions

### PR DESCRIPTION
**Pull request by linolaoj**
Related Issue: https://issues.liferay.com/browse/LPS-121007

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @linolaoj, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @linolaoj, can you please check if these failures are related to your changes? Thanks

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
@linolaoj, we're very close to the 7.3 release, in light of this we'll hold a little bit to forward this pull to be merged on master to avoid instability on our product, if however you've some problem with this procedure please let me know.

Thanks!

**Comment by linolaoj** [comment]
Hi @natocesarrego, I understand. Thank you for letting me know.

**Comment by robertoDiaz** [comment]
Hi guys.

If I understand it well, this is going to be merged in master. Could we provide this solution to the customer?

**Comment by natocesarrego** [comment]
Hi @robertoDiaz, your understanding is correct. 🙂 This pull is ready to be forwarded to Brian merge and we're just waiting the 7.3 release to move on with it. Therefore, on behalf of Forms team, I can say this fix can be delivered as a hotfix.

Thanks.

**Comment by natocesarrego** [comment]
@linolaoj, I just got green light to forward your pull to be merged, can you please fix the conflicts and resend?

**Comment by linolaoj** [comment]
rebased at https://github.com/liferay-forms/liferay-portal/pull/8

**Pull request closed without merging**
