### PR TITLE
[TS] LPS-200189 - dragging&dropping a repeatable field after deleting a duplicate field causes exceptions

### PR DESCRIPTION
**Pull request by wanderlast**
Hi Forms Team!

Currently there can be an issue with dragging & dropping when fields have been duplicated. For example, if we have a structure with a repeatable field set and a repeatable field:

Screenshot 2023-11-07 122250

And we then duplicate this entire fieldset using the + button near the "Tab" title, we are given a second fieldset with one title field and three description fields. Deleting one of those description fields in our second fieldset and then returning to our original fieldset to drag and drop the last description fields causes an undefined name exception.

This is due to the fact that when we drag&drop we are:
1. only checking for the "fieldName" which is broadly shared between the two duplicated fieldSets rather than the more exact "name" which contains the instanceID for the exact field being dragged/dropped
2. blindly using the known indexes of the fields in the larger fieldSet

This means that both fieldSets will be checked initially for a reorder even though only one has the correct field and causes problems when we try to find the indexed version in the smaller fields map (since the index would exceed the indexes available). I've fixed this by checking specifically for the name rather than the fieldName since we only want to be dragging&dropping one specific field anyway. Please let me know if there's any questions or issues. Thanks!

### CODE REVIEW

**Comment by rebsilva** [comment]
just started reviewing :cherry_blossom:

**Comment by rebsilva** [comment]
this is a major change that could break the repeatable fields feature, so i'll take some time testing this, thanks!

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by rebsilva** [comment]
just a update, while testing i've found another bug so i'm trying to make a fix for this as well. i'll update again tomorrow if i could find a solution and what we should do next, thanks for your patience!

**Comment by rebsilva** [comment]
A new PR with new modifications to fix all the bugs is here https://github.com/liferay-forms/liferay-portal/pull/2387, so I will close this PR

**Pull request closed without merging**
