### PR TITLE
LPS-132811 As a form creator, I want to define validations to my date field type with other date fields in the form as parameter

### PR DESCRIPTION
**Pull request by mateusgomes01**
Related Issue: https://issues.liferay.com/browse/LPS-141065

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
Hey @mateusgomes01, can you please fix the source formatter issues and resend? Thanks

**Comment by mateusgomes01** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hey @mateusgomes01, can you please fix the source formatter issues and resend? Thanks

**Pull request closed without merging**
