### PR TITLE
LPS-137764

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related ticket: https://issues.liferay.com/browse/LPS-137764

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
The failure seems to be caused by a flaky macro or CI. If it was consistent, it should be happening in every test that add a form.

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Review by miltonmc — COMMENTED** [review]
The frontend looks great to me!

If I understood right, with this fix we got a bonus that is the removal of the `_getDataDefinitionFieldFormattedValue()` (a function that was doing on the frontend what the backend supposed to be doing). 

Well done @rodrigopaulino! :clap: :clap: :clap: 

@natocesarrego now, it's up to you!

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
