### PR TITLE
LPS-126754 Settings tab is gray out when adding new Data Definitions

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
https://issues.liferay.com/browse/LPS-126754

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:reevaluate:1387401_5295

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Hi @cgmonte, could you please review this PR? :smile:

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by cgmonte** [comment]
ci:forward

**Comment by cgmonte** [comment]
ci:reevaluate:137null_7493

**Comment by marcelabc** [comment]
Hey @pedro-oliveira446, 

I analyzed the unique failure in the Testray: https://testray.liferay.com/home/-/testray/case_results/2146714926/history?tab=result&hideFilterPin=true

Could you run locally this test? Let me know if you need help :+1:

**Comment by pedro-oliveira446** [comment]
Ok @marcelabc, I will analyze.

**Comment by pedro-oliveira446** [comment]
@marcelabc, I run this test FormsSelectFromListField#CanCreateListUsingAutofill locally, and it passed.

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
