### PR TITLE
LPS-188339 Confusing naming for duplicate form

### PR DESCRIPTION
**Pull request by larissacribeiro**
Related Issue: [LPS-188339](https://liferay.atlassian.net/browse/LPS-188339)

### CODE REVIEW

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
@larissacribeiro the following tests are failing in this PR:

> LocalFile.FormRules#AreDuplicatedWhenTheFormIsDuplicated
> LocalFile.Forms#CheckBackButtonViewEntries
> LocalFile.Forms#CanBeDuplicated

Could you please fix them?

You probably need to update this [macro](https://github.com/liferay/liferay-portal/blob/67f84a6df233cfe2569dc15f0f2229ef5311cf43/portal-web/test/functional/com/liferay/portalweb/macros/Form.macro#L311). 

Thanks!

**Comment by larissacribeiro** [comment]
Hi @carolmariaabb! yes, I will do that now, thank you!

**Comment by larissacribeiro** [comment]
ci:test:relevant

**Comment by larissacribeiro** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
