### PR TITLE
LPS-191014 Render the system site’s default language when creating a form

### PR DESCRIPTION
**Pull request by alinedoleron**
Ticket: 

https://liferay.atlassian.net/browse/LPS-191014

[bug-translation.webm](https://github.com/liferay-forms/liferay-portal/assets/26491796/cc21d7a1-76c9-4974-8ca9-89d32497d83e)

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:forms

**Review by carolmariaabb — APPROVED** [review]

**Comment by icgsbr** [comment]
Hi @alinedoleron, I noticed that when we set the url to something like "localhost:8080/es/..." the forms is translated to spanish and its default language is still in english as expected. Yet I noticed that, when we access the forms with a different language from the default, the success page comes empty like in the image.

image

**Comment by icgsbr** [comment]
> Collaborator

I suspect that this is something related with forms inconsistency when handling and getting value from themeDisplay and Default

**Comment by icgsbr** [comment]
> Hi @alinedoleron, I noticed that when we set the url to something like "localhost:8080/es/..." the forms is translated to spanish and its default language is still in english as expected. Yet I noticed that, when we access the forms with a different language from the default, the success page comes empty like in the image. I've tested with portuguese, arabic, french, etc; and in all of those cases this happened.
> 
> image

I suspect that this is something related with forms inconsistency when handling and getting value from themeDisplay and Default

**Comment by icgsbr** [comment]
I suspect that this is something related with forms inconsistency when handling and getting value from themeDisplay and Default

**Comment by alinedoleron** [comment]
> Hi @alinedoleron, I noticed that when we set the url to something like "localhost:8080/es/..." the forms is translated to spanish and its default language is still in english as expected. Yet I noticed that, when we access the forms with a different language from the default, the success page comes empty like in the image. I've tested with portuguese, arabic, french, etc; and in all of those cases this happened.
> 
> image

Thanks @icgsbr! I sent a fix for this now.

**Comment by icgsbr** [comment]
/home/igorcosta/Videos/LPS-191014-success-page-issue-2023-10-10_08.45.34.mp4

**Comment by icgsbr** [comment]
> > Hi @alinedoleron, I noticed that when we set the url to something like "localhost:8080/es/..." the forms is translated to spanish and its default language is still in english as expected. Yet I noticed that, when we access the forms with a different language from the default, the success page comes empty like in the image. I've tested with portuguese, arabic, french, etc; and in all of those cases this happened.
> > image
> 
> Thanks @icgsbr! I sent a fix for this now. ([fea869f](https://github.com/liferay-forms/liferay-portal/commit/fea869f197e5400966df48d2ade07d54092041f1))

Hi @alinedoleron, in what concerns this issue, I just tested your newest commit and found that it still persists. Please see the attached evidence video.

https://github.com/liferay-forms/liferay-portal/assets/91233780/91ff2a66-2f30-4533-b4b8-61496d411b36

**Comment by carolmariaabb** [comment]
@icgsbr I've already approved the code, but I don't know if we'll need a QA request here. Please confirm with @samuelromeiro or @alinedoleron.

**Comment by davisaints** [comment]
The failures aren't related to this PR.

[Comparison with acceptance](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1696957188602&testrayRunIdA=2438753903&testrayRunIdB=2438944747) and [comparison with form suite](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1696957261247&testrayRunIdA=2438756137&testrayRunIdB=2438748463).

**Comment by icgsbr** [comment]
Hi @alinedoleron @carolmariaabb, now I assume we have the thumbs up to send it to Bchan? 😄

**Comment by davisaints** [comment]
Give me a few minutes to finish testing

**Comment by davisaints** [comment]
I finished testing manually, you can forward it 😄

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:test:stable

**Comment by alinedoleron** [comment]
ci:forward:force

**Pull request closed without merging**
