### PR TITLE
LPS-141491 Apply the date of default language into other languages if its values are initially empty

### PR DESCRIPTION
**Pull request by alinedoleron**
Related Issues: 

- https://issues.liferay.com/browse/LPS-141491

- https://issues.liferay.com/browse/LPS-140281

Note: This PR has a dependency of this other one: https://github.com/liferay-forms/liferay-portal/pull/1115
Please, just forward it after #1115 be merged

Commit:
[LPS-141491 Apply the date of default language into other languages if its values are empty](https://github.com/liferay-forms/liferay-portal/pull/1116/commits/91311d3a330cd8f3b93dd6aa50487967e40ff723)

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @alinedoleron, can you please check if these failures are related to your changes? Thanks

**Review by miltonmc — COMMENTED** [review]
LGTM!

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @alinedoleron, can you please check if these failures are related to your changes? Thanks

**Comment by marcelabc** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @alinedoleron, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @alinedoleron, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:reevaluate:1267401_836

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @alinedoleron, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:reevaluate:1327401_1114

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
