### PR TITLE
LPS-138357

### PR DESCRIPTION
**Pull request by natocesarrego**
Related Issue: https://issues.liferay.com/browse/LPS-138357

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @natocesarrego, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
ci:reevaluate:1267401_264

**Comment by liferay-forms** [comment]
Hey @natocesarrego, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
ci:reevaluate:1267401_264

**Comment by liferay-forms** [comment]
Hey @natocesarrego, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @natocesarrego, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
ci:reevaluate:1337401_37

**Comment by kenjiheigel** [comment]
ci:reevaluate:1337401_37

**Comment by natocesarrego** [comment]
ci:reevaluate:1337401_37

**Comment by eli-rlima** [comment]
ci:reevaluate:1337401_37

**Comment by natocesarrego** [comment]
ci:forward

**Comment by eli-rlima** [comment]
ci:forward

**Comment by danvb112** [comment]
ci:forward

**Comment by danvb112** [comment]
ci:forward

**Pull request closed without merging**
