### PR TITLE
LPS-144405

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related Issue: https://issues.liferay.com/browse/LPS-144405

I only need to concatenate with the `portletId` [here](https://github.com/carolmariaabb/liferay-portal/blob/e5b6ac4a1dabc3a6bc2f9e8014a81ff91be187ce/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web/src/main/java/com/liferay/dynamic/data/mapping/form/web/internal/portlet/action/AddFormInstanceRecordMVCActionCommand.java#L135-L138) because the existing `hideDefaultSuccessMessage` method also concatenates [here](https://github.com/liferay/liferay-portal/blob/8d2e15d135ea6f96abb6a76380e71e1145f1ea52/portal-kernel/src/com/liferay/portal/kernel/portlet/bridges/mvc/BaseMVCActionCommand.java#L111-L115).

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @carolmariaabb, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:reevaluate:1277401_1322

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
