### PR TITLE
LPS-186579 Nothing happens after clicking "View Fields" from a field set

### PR DESCRIPTION
**Pull request by ericthmoritsuka**
Related Issue: https://issues.liferay.com/browse/LPS-186579

When creating a new Kaleo Workflow Forms, after adding a field set, it was not possible to access _View Fields_. 

I noticed that [there was a change in this component last year](https://github.com/ericthmoritsuka/liferay-portal/commit/aac7101da39a663b9be80d368bdc50d588660151) that added a message if someone was trying to add a Document and Media without the proper permission.

The problem was being caused because the code was trying to read _classList_ from _null_ (I think the function __handleAlertMessages_ was being called in other moments that were not the ones intended by the previous alteration).

So, I added a condition to check if _documentsAndMediaField_ was not  _null_ and, only then, we would proceed with the rest of the documents and media check from the previous alteration.

As requested by @alinedoleron, I also brought back the scroll bar to make all fields visible (we could only do that by resizing the modal as it was).

And, I added a margin top to the _select_ button in the _form-builder-field_ because it was right next to the field and it did not look nice.

### CODE REVIEW

**Comment by alinedoleron** [comment]
Hi @ericthmoritsuka, I've tested the PR and the modal opens. However, the modal content doesn't seem to be well stylized. Please, could you check on previous update (for example, U40), or o 7.3.x, how the modal content looks like and fix it?
For me it's being shown this:

[Kaleo_Form_admin_bug.webm](https://github.com/liferay-forms/liferay-portal/assets/26491796/bd9fb23b-f1fa-4195-b2fd-292cee5d4033)

Does this same behavior happens for you?
Thanks!

**Review by alinedoleron — COMMENTED** [review]
Hi @ericthmoritsuka , please, check my comment above. Thanks! :slightly_smiling_face:

**Comment by ericthmoritsuka** [comment]
I brought back the scroll bar to the body of the _View Fields_ modal and I added a margin top to the select button in the _form-builder-field_ because it was not looking nice.

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:forms

**Review by alinedoleron — APPROVED** [review]
Thanks, @ericthmoritsuka! LGTM!

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
QA approved: https://liferay.slack.com/archives/C048YNC5GRK/p1687206535421029?thread_ts=1687200972.175279&cid=C048YNC5GRK

**Comment by alinedoleron** [comment]
ci:forward:force

**Pull request closed without merging**
