### PR TITLE
LPS-156051

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related Issue: https://issues.liferay.com/browse/LPS-156051

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Please, apply additional code as discussed. :) 
Thanks

**Comment by carolmariaabb** [comment]
ci:stop

**Review by rodrigopaulino — APPROVED** [review]
LGTM! 🎉

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
