### PR TITLE
LPS-200189 Fix drag and drop of repeatable fields

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issue: https://liferay.atlassian.net/browse/LPS-200189

This PR has additional fixes for the drag and drop of repeatable fields, along the original solution of https://github.com/liferay-forms/liferay-portal/pull/2382

The QA team will take some time testing and making sure everything is working as expected, since these changes could break the product.

### CODE REVIEW

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:forms

**Comment by rebsilva** [comment]
i'll ask the QA team to verify the tests failing and also to test the PR

**Comment by davisaints** [comment]
ci:test:data-engine

**Comment by davisaints** [comment]
No regressions found in the forms suite and acceptance. However, I need to review the CI results for the data engine suite

**Comment by davisaints** [comment]
No regressions found!

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
