### PR TITLE
LRQA 69788

### PR DESCRIPTION
**Pull request by guivilarim**
Related Issue: https://issues.liferay.com/browse/LRQA-69788

- LRQA-69788 Fix EditBooleanFieldFieldLabel test
- LRQA-69788 Fix populateFieldBoolean macro
- LRQA-69788 Fix EditBooleanFieldName test
- LRQA-69788 Fix AddListRecordWithRequiredBooleanField test
- LRQA-69788 Fix AddListRecordWithBooleanField test
- LRQA-69788 Fix LRQA-69788 test
- LRQA-69788 Fix ImportLAR test

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:forward

**Comment by liferay-forms** [comment]
ci:test:relevant

**Pull request closed without merging**
