### PR TITLE
LRQA-68131 Fix FormsTextField#ConfirmationBoxCanBePlacedHorizontally

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
Hi, @JoMaAlves. Please, could you remove this test from quarantine?
Change this line
`property forms.functional = "quarantine";`
to 
`property forms.functional = "true";`

**Comment by JoMaAlves** [comment]
@alinedoleron Fixed!

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:forward

**Pull request closed without merging**
