### PR TITLE
LPS-137172 Add Booelan Field PieChart in Entries

### PR DESCRIPTION
**Pull request by danvb112**
This PR is related with Boolean Field story!
Here is the related ticket: https://issues.liferay.com/browse/LPS-137172

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Review by miltonmc — APPROVED** [review]
LGTM!

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:stop

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:forward

**Pull request closed without merging**
