### PR TITLE
LPS-145181 Unit tests list

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issues:
- https://issues.liferay.com/browse/LPS-144708
- https://issues.liferay.com/browse/LPS-144709
- https://issues.liferay.com/browse/LPS-144710
- https://issues.liferay.com/browse/LPS-144711
- https://issues.liferay.com/browse/LPS-145181

Hello Reviewer! 🌸

This PR has new features and tests related to the story:
**As a form admin, I want to be able to request datetime from my users** ([LPS-143050](https://issues.liferay.com/browse/LPS-143050))

Summary: Updates the date picker dependency, adjusts the DatePicker logic to support `date_time` field type, allows the display of `date_time` fields in the entries section and add unit tests.
More details can be found [here](https://liferay.atlassian.net/wiki/spaces/ENGFORMS/pages/1958839342/LPS-143050+As+a+form+admin+I+want+to+be+able+to+request+datetime+from+my+users) on our Confluence page.

If you have any questions feel free to ask, thank you for your time!

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by rebsilva** [comment]
I'm only requesting Milton's review because @alinedoleron already reviewed and approved [this PR](https://github.com/liferay-forms/liferay-portal/pull/1367) that has the same code. Thanks Aline!

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @rebsilva, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
