### PR TITLE
LPS-139170 The boolean field values are not counting as one in form entries (Summary) when form has translations

### PR DESCRIPTION
**Pull request by mateusgomes01**
Related Issue: https://issues.liferay.com/browse/LPS-139170

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by mateusgomes01** [comment]
@miltonmc Just sorting the switch case statements as requested by Brian

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @mateusgomes01, can you please check if these failures are related to your changes? Thanks

**Review by miltonmc — APPROVED** [review]
LGTM!

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by mateusgomes01** [comment]
ci:test:sf
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @mateusgomes01, can you please fix the source formatter issues and resend? Thanks

**Comment by mateusgomes01** [comment]
ci:reopen

**Comment by mateusgomes01** [comment]
resent #1124

**Pull request closed without merging**
