### PR TITLE
LPS-135713 The rich text field has inconsistent behaviour on forms when typing the predefined field

### PR DESCRIPTION
**Pull request by markocikos**
Related Issue: https://issues.liferay.com/browse/LPS-135713

Fixes: https://issues.liferay.com/browse/LPS-135713, as a part of https://issues.liferay.com/browse/PTR-2589

@diogosantos @natocesarrego 

This PR fixes one of the `RichText` bugs, the most severe one, where changing predefined value stops updating field (see [attached movie in JIRA](https://issues.liferay.com/secure/attachment/415564/richTextNotWorking.mp4))

The root cause is [this line](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/src/main/resources/META-INF/resources/RichText/RichText.es.js#L49) in RichText:
```js
const currentValue = value ?? predefinedValue;
```
After `value` is set for the first time, we ignore `predefinedValue` from then on.

In this PR we are fixing the value setting, `predefinedValue` now always overrides `value`. `previousPredefinedValue` is needed for the case when we delete predefined value. Without it, we would set content to the last `value`, which is incorrect. Content should be deleted.

After PR, there are still glitching bugs, but value updating no longer stops:
after

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @markocikos, can you please check if these failures are related to your changes? Thanks

**Comment by markocikos** [comment]
Looking at unique failures in https://github.com/liferay-forms/liferay-portal/pull/874#issuecomment-909480440:
1. The first one is clearly unrelated.
2. The second one is the same as in https://github.com/liferay-forms/liferay-portal/pull/871, so it's unrelated.

**Comment by alinedoleron** [comment]
Hi @markocikos, thank you for the effort! Since the fix is on Forms side, we'll handle this ticket. Having said that,  I'll close this PR. Thanks!

**Pull request closed without merging**
