### PR TITLE
LPS-131217 Set labels of every fieldset nested Field

### PR DESCRIPTION
**Pull request by alinedoleron**
Ticket: [LPS-131217](https://issues.liferay.com/browse/LPS-131217)

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Review by miltonmc — CHANGES_REQUESTED** [review]
Well done!

I have just some minor comments to do:

**Pull request closed without merging**
