### PR TITLE
LPS-179781 Single Selection field options are not properly laid out

### PR DESCRIPTION
**Pull request by AlmirFe**
LPS ticket link: [LPS-179781](https://issues.liferay.com/browse/LPS-179781)

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by AlmirFe** [comment]
ci:test

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by rebsilva** [comment]
Just started reviewing! cherry_blossom

**Review by rebsilva — APPROVED** [review]
LGTM! Great work! :cherry_blossom: :tada:

**Comment by rebsilva** [comment]
This is looking good again! :purple_heart: 

Screenshot from 2023-03-30 15-54-35

**Comment by rebsilva** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
