### PR TITLE
LPS-140715

### PR DESCRIPTION
**Pull request by holatuwol**
Related Issue: https://issues.liferay.com/browse/LPS-140715

Related Issue: https://issues.liferay.com/browse/LPS-140715

/cc @binhtran92

Resend of https://github.com/liferay-forms/liferay-portal/pull/1049
Redirected here from https://github.com/liferay-echo/liferay-portal/pull/6198 and https://github.com/liferay-data-engine/liferay-portal/pull/584

### Problem overview

Legacy Liferay code in `dynamic-data-mapping-service` does not sanitize field namespaces for DDM fields. While the vulnerability requires that you hijack the session of a content administrator, this is true of many XSS vulnerabilities, so it's better to be safe than sorry.

### Steps to reproduce

**Note**: This issue is only reproducible in branch. While we could update the Javascript to submit instanceId information in master as well, as a side-effect of [LPS-129530](https://issues.liferay.com/browse/LPS-129530) which makes it so the problematic code is no longer called. However, this change cannot be brought back to maintenance branches.

1. Sign in as test@liferay.com
2. Go to Web Content > Basic Web Content
3. Submit a form where the instanceId is `<script>alert(document.location)</script>` by running the following script in the browser console:
``` javascript
document.getElementById('_com_liferay_journal_web_portlet_JournalPortlet_ddmFormValues').value = JSON.stringify({
  availableLanguageIds: ['en_US'],
  defaultLanguageId: 'en_US',
  fieldValues: [{
    instanceId: '<script>alert(document.location)</script>',
    name: 'content',
    value: {
      'en_US': 'testxss'
    }
  }]
});

document.forms[0].submit();
```
4. Navigate to the Web Content, access the latest Web Content you have just created.

**Expected Result:**
The edit screen shows up as normal

**Actual Result:**
The script is executed and the page stops loading

### Solution notes

Based on discussion with @samuelkong, it made more sense to validate the instanceId on the backend so that even if the problematic code is called in master, we don't experience any issues.

To introduce an invalid instanceId, you can use the following script in master on the screen where you create a new Basic Web Content:

```javascript
var prefix = '_com_liferay_journal_web_portlet_JournalPortlet_ddm$$content$';
var instanceId = '<script>alert(document.location)</script>';
document.querySelectorAll('input[name^="' + prefix + '"]').forEach(function(input) {
  var newName = prefix + instanceId + input.name.substring(input.name.indexOf('$', prefix.length));

  input.setAttribute('name', newName);
});

document.forms[0].submit();
```

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Review by carolmariaabb — APPROVED** [review]

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @holatuwol, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @holatuwol, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @holatuwol, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:reevaluate:1327401_1022

**Comment by liferay-forms** [comment]
Hey @holatuwol, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @holatuwol, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @holatuwol, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:reevaluate:1267401_799

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
