### PR TITLE
LPS-205559 Dynamic Data Lists Display portlet should not be visible if the feature flag is not enabled

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://liferay.atlassian.net/browse/LPS-205559

### CODE REVIEW

**Comment by carolmariaabb** [comment]
SF failure is not related. Also reported [here](https://liferay.slack.com/archives/C1SJ64S9X/p1704799263629319).

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
Sorry for the delay in reviewing it!

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by carolmariaabb** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/146212

**Pull request closed without merging**
