### PR TITLE
LPS-169759 Check the value from calculation result first so that the numeric field can be overwritten

### PR DESCRIPTION
**Pull request by MirnaGama**
**Bug found:** https://issues.liferay.com/browse/LPS-169759

The customer reported that after creating a Form with 3 Numeric fields and one of them being only for calculation purposes (after applying the rule for this field to be only for calculation purposes), you are able to edit this calculation field and the system does not have any kind of overwriting that would prevent the result value of being modified. He/she said that this was not possible to do back on 7.2.

**Steps to reproduce**

1. Start by creating a new Form
2. Add 3 Numeric fields (Value 1, Value 2, Calculation)
3. Add a rule (If Field Value 1 is not empty Calculate [Value 1]+[Value 2] into Calculation)
4. Return to the Form tab
5. Save the form
6. Click the Preview button
7. Type any number into the Value 1 field
8. Change the value in the Calculated field
9. Update Value 1 or set a value in Value 2 (the calculation field isn't updated)

**Results of Testing:**
I'm able to populate the Calculation field and the result is not being calculated and displayed anymore.

**Expected Result:**
It is expected that the calculation rule would be overwriting the field with the result value as it was in 7.2 in that the field was essentially read-only and could not be updated by the user as the field is populated based on other field conditions.

### CODE REVIEW

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:relevant

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by cgmonte** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by cgmonte** [comment]
Hi @MirnaGama, our QA team confirmed that the failures in the CI tests are not related to your changes. Can you please send this directly to [BChan](https://github.com/brianchandotcom/liferay-portal)? If you need any help to do this, you can reach me on Slack and I will be happy to help you. Thank you very much!

**Comment by MirnaGama** [comment]
Hi @cgmonte 
Thanks, it was sent: https://github.com/brianchandotcom/liferay-portal/pull/127149

**Pull request closed without merging**
