### PR TITLE
LPD-37484 Error indexing large terms using Rich Text box within a repeatable Field Group

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
Same code than https://github.com/liferay-forms/liferay-portal/pull/2620 but adding a commit to avoid truncating the non-'_sortable' field.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
@marcelabc @icgsbr see my change in commit https://github.com/liferay-forms/liferay-portal/pull/2624/commits/c8344e8045cc37478b7687fe417a0573cd8595b8

BTW: about https://github.com/liferay-forms/liferay-portal/pull/2624/commits/2a6aba4f0e247fa7e23a323c38227ed7fa5544ed commit that changes the test, I think it is not necessary to truncate the text, but I have no time to execute it.

**Comment by jorgediaz-lr** [comment]
I have added a SF commit

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
@jorgediaz-lr thank you for the spontaneous help here!! :smile: 
I will review and analyze the test :+1:

**Comment by jorgediaz-lr** [comment]
no problem @marcelabc !

**Comment by marcelabc** [comment]
Resend: https://github.com/liferay-forms/liferay-portal/pull/2627
cc: @icgsbr @jorgediaz-lr

**Pull request closed without merging**
