### PR TITLE
LPS-142264 | LPS-142266 | LPS-142267 | LPS-142268

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related Issues: 
https://issues.liferay.com/browse/LPS-142264
https://issues.liferay.com/browse/LPS-142266
https://issues.liferay.com/browse/LPS-142267
https://issues.liferay.com/browse/LPS-142268

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
