### PR TITLE
LPS-157856 Make SQL query more robust to prevent upgrade issues

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:relevant

**Review by rodrigopaulino — COMMENTED** [review]
Hey, @natocesarrego. Thanks a lot for your pull.
Have you considered simply using an [IN operator](https://www.w3schools.com/sql/sql_in.asp)?

**Comment by natocesarrego** [comment]
No problem, @rodrigopaulino. :slightly_smiling_face: 

Honestly, I didn't consider this option because I just followed the code pattern already being used in the class, .e.g., the `or` instead of `in`. Additionally, according to the link shared by you, the "The IN operator is a shorthand for multiple OR conditions." therefore it might be the reason for this alternative not come to my mind. Lastly, if you prefer, I can use the IN operator instead if you understand that it's worth. :slightly_smiling_face: 

Cheers!

**Comment by natocesarrego** [comment]
Done, @rodrigopaulino! :smile:

**Review by rodrigopaulino — APPROVED** [review]
Looks great. Thanks a lot, @natocesarrego!

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:reevaluate:1317401_4100

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
