### PR TITLE
LPS-153398 Break Action form into tabs

### PR DESCRIPTION
**Pull request by miltonmc**

### CODE REVIEW

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:relevant

**Review by alinedoleron — CHANGES_REQUESTED** [review]

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]

**Comment by miltonmc** [comment]
ci:forward

**Pull request closed without merging**
