### PR TITLE
LPS-175631 Use a local service to get the file entry so the permissions won't be checked

### PR DESCRIPTION
**Pull request by MirnaGama**
***Context:***
Approvers specified in the workflow cannot view or download attached file

***Solution Proposed:***
Workflow is using the remote service, DLAppService, and it checks permissions. We should use DLAppLocalService for fetch the files related to the workflow tasks instead.

https://issues.liferay.com/browse/LPS-175631

### CODE REVIEW

**Comment by marcelabc** [comment]
Related to this PTR: https://issues.liferay.com/browse/PTR-3667

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
@MirnaGama could you please fix the failed test: `/com.liferay.dynamic.data.mapping.form.field.type.internal.document.library/DocumentLibraryDDMFormFieldTemplateContextContributorTest`? Thanks!

You would have to change this [method](https://github.com/liferay/liferay-portal/blob/b0c8ccdb6126f54f16223bfeff3bc7bb5631d8e3/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/src/test/java/com/liferay/dynamic/data/mapping/form/field/type/internal/document/library/DocumentLibraryDDMFormFieldTemplateContextContributorTest.java#L567-L578) as follows:

```
@Before
@Override
public void setUp() throws Exception {
	super.setUp();

	_setUpCompanyLocalService();
        _setUpDLAppLocalService();
	_setUpDLAppService();
       ...
}

private void _setUpDLAppLocalService() throws Exception {
	ReflectionTestUtil.setFieldValue(
		_documentLibraryDDMFormFieldTemplateContextContributor,
		"_dlAppLocalService", _dlAppLocalService);

	Mockito.when(
		_dlAppLocalService.getFileEntryByUuidAndGroupId(
			_FILE_ENTRY_UUID, _GROUP_ID)
	).thenReturn(
		_fileEntry
	);
}

private void _setUpDLAppService() throws Exception {
	ReflectionTestUtil.setFieldValue(
		_documentLibraryDDMFormFieldTemplateContextContributor,
		"_dlAppService", _dlAppService);

	Folder folder = _mockFolder(_PRIVATE_FOLDER_ID);

	Mockito.when(
		_dlAppService.getFolder(_REPOSITORY_ID, _FORMS_FOLDER_ID, "Test")
	).thenReturn(
		folder
	);
}
```

**Comment by MirnaGama** [comment]
@carolmariaabb Done! :smiley:

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:relevant

**Comment by MirnaGama** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
