### PR TITLE
LPD-31144 Save and restore state in rich text

### PR DESCRIPTION
**Pull request by DiegoHu97**
LPD-31144 Save and restore state in rich text

# What is this trying to solve?

In Content Management team we are implementing undo/redo component for Web Content (https://liferay.atlassian.net/browse/LPD-22301), in this PR we are sending the part that handles the rich text editor.

[Link to ticket](https://liferay.atlassian.net/browse/LPD-31144)

# How am I fixing it?

Now we have a historyReducer component that handles the changes that we make in the undo/redo for data engine components. We have added an event that fires the event when clicking on undo/redo buttons and change the value of the rich text editor.

# How can I test it?

**Steps of the test:**

- Enable FF 'LPD-11228': true
- Enable FF 'LPD-15596': true 
- Create a WC
- Fill the title 
- Fill the content field
- Click on undo button
- See content field gets empty
- Click on redo button
- See the content if filled

# Tests are not needed

We don't need tests for every data engine component, we already have this test that checks undo/redo buttons work for data engine components. **journalArticle.spec.ts > 'LPD-26863: Undo/Redo buttons work with content field'** (https://github.com/liferay/liferay-portal/blob/ab1686f25a5a3b47aaca2b02287fe377ef470e6c/modules/test/playwright/tests/journal-web/journalArticle.spec.ts#L219)

CC: @NemethNorbert

### CODE REVIEW

**Comment by rebsilva** [comment]
hi @DiegoHu97! thanks for you PR :blush: it's expected for this to be reviewed on monday since part of the team is taking the liferay bootcamp this week. if you have any questions or concerns please let me know, thanks a lot! :tulip:

**Comment by rebsilva** [comment]
just started reviewing! :cherry_blossom:

**Comment by rebsilva** [comment]
hi @DiegoHu97! 

after testing i realized that if you try to save right after filling the fields the web content won't be saved. 
is this expected or will be addressed in another story?


https://github.com/user-attachments/assets/bdd0a923-8e5a-4b72-9669-1ceb3095f6ed

**Comment by rebsilva** [comment]
no problem! i will test with this FF too and see if it works :blush:

**Comment by rebsilva** [comment]
hi @DiegoHu97, are these behaviors expected as well? 

- when we fill first the field instead of the title, it will only revert the title and won't allow the rich to be reverted 
- also sometimes, the title is reverted at the same time as the text inside the rich text

please let me know if i'm doing something wrong!

https://github.com/user-attachments/assets/413110a0-1a24-411b-8ea3-0900196ef978

**Review by rebsilva — CHANGES_REQUESTED** [review]
the code seems fine to me, but i'm waiting for the confirmation that the behavior is expected or not

**Comment by DiegoHu97** [comment]
Hey @rebsilva I'm taking a look to it, sorry for the late response, yesterday was bank holiday in Spain.

**Comment by rebsilva** [comment]
no problem @DiegoHu97! let me know when the code is ready to be reviewed again, thanks! :cherry_blossom:

**Comment by rebsilva** [comment]
i'll be closing this PR since you are working on the solution again, you can open a new one and tag me so i can review it thanks!

**Pull request closed without merging**
