### PR TITLE
LPS-143863 If the item doesn't exist should return null instead of throwing an exception

### PR DESCRIPTION
**Pull request by lfbesada**
Related issue: https://issues.liferay.com/browse/LPS-143863

Hi team!

During the validations of the site navigation menus items for display pages, we have found a couple of bugs related to the info-framework implementation of Objects.

Could you please review the fix?

Thanks!!!

Regards

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @lfbesada, can you please check if these failures are related to your changes? Thanks

**Comment by lfbesada** [comment]
Hi Team!

The test failures don't seem to be related to my changes.

Thanks!

Regards

**Comment by natocesarrego** [comment]
Hi @lfbesada,

The team in charge of component Objects is @liferay-objects. Please, send your next pull requests affecting Objects to this team. :slightly_smiling_face: 

@liferay-objects, can you please review this one?

I'm not forwarding the pull to you to use the already reported CI results.

Thanks.

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Just started reviewing :)

**Comment by marcelabc** [comment]
ci:forward

**Comment by lfbesada** [comment]
Hi @natocesarrego, thanks a lot for your indications and your proactivity, I will keep it in mind for the next time ;-) Regards

**Pull request closed without merging**
