### PR TITLE
LPS-177877

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hey guys,

Can you review this pull request, please?

You can get more information in [LPS-177877](https://issues.liferay.com/browse/LPS-177877).

I've considered in this new solution the issues originally reported in [LPS-160435](https://issues.liferay.com/browse/LPS-160435) and [LPS-163762](https://issues.liferay.com/browse/LPS-163762). So I've tested them and I'd say they are fixed as well.

The solution initially provided for those two cases was fine if you consider in the page there is just one Form Widget, but as soon as you have more widgets, the behavior is not expected since the page is always scrolled and focus into the Form Widget, even in the first load, what might not be desirable, especially if your Form Widget is at the bottom of the page.

The second issue I saw analyzing the changes introduced by LPS-160435 and LPS-163762 is that management of Focus and Scroll is heavily tied to quite a few DOM elements and their CSS selectors. Apart from other problems, this makes inconsistent the behavior between using a regular Forms Widget, or rendering the form using liferay-ddm:ddm-form-renderer since they have a very different markup.

I hope this helps you to review this pull request.

Thanks.

Regards.

### CODE REVIEW

**Comment by antonio-ortega** [comment]
Hey guys,

Could you give some info about how to run format source on data-engine-js-component-web module?

I've run `gradlew formatSource` (from the module) and `ant format-source-current-branch` (from portal-impl) not getting any error or correction.

I also tried running `liferay-npm-scripts fix` from the module, but is failing, I guess because there is no .eslintrc file on this module.

Could you give me a hand, please?

**Comment by cgmonte** [comment]
Hey! You could try `yarn format` on the module, but I already did it and it didn't fix anything. I went trough the [console SF output](https://test-1-38.liferay.com/job/test-portal-source-format/4146/console) and could not find a specific test failure, it looks the execution failed, not a specific test. I recommend you to do a rebase with the latest master branch, force push it and run SF again.

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
`yarn format` didn't change anything for me either. I rebased, run check format again and forced pushed, but nothing. Any other ideas :\ ?

**Comment by cgmonte** [comment]
Can you check this [thread on slack](https://liferay.slack.com/archives/CNBG06JS3/p1678439723479579) and see if it has any useful information regarding this problem?

**Comment by cgmonte** [comment]
Also I will run relevant again, as I think its failures has nothing to do with SF's.

**Comment by cgmonte** [comment]
ci:test:relevant

**Comment by cgmonte** [comment]
ci:test:sf

**Comment by cgmonte** [comment]
> Can you check this [thread on slack](https://liferay.slack.com/archives/CNBG06JS3/p1678439723479579) and see if it has any useful information regarding this problem?

hey @antonio-ortega did check this? Thanks

**Comment by cgmonte** [comment]
Just checked and yes, as stated in linked Slack thread above, removing [this line of code](https://github.com/liferay/liferay-portal/blob/807987aff03221dedf0286618dcb13f93a2b5a9c/modules/npmscripts.config.js#L592) will fix `gradlew formatSource`. So remove the line, run format, revert the change in `npmscripts.config.js`, commit format changes in relevant files and force push it.

**Comment by antonio-ortega** [comment]
Hi @cgmonte ,

Since [LPS-178155](https://issues.liferay.com/browse/LPS-178155) was fixed yesterday solving the formatting issues in modules, I've rebased it, run formatSource (properly working now) and force push with new changes.

I hope everything goes well now.

Thanks for your help!

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
