### PR TITLE
LPS-152653

### PR DESCRIPTION
**Pull request by rafaellajordao**
492d12dd55d0de671735e453e0b2af048f1ada57 Automate Upgrade tests from 7.1.10: https://issues.liferay.com/browse/LPS-152653
74962265c8e2620408b2b2c0cebb8adc9702f2ee Automate Upgrade tests from 7.2.10: https://issues.liferay.com/browse/LPS-154060

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by rafaellajordao** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by rafaellajordao** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by rafaellajordao** [comment]
ci:forward

**Pull request closed without merging**
