### PR TITLE
LPS-166350 changed the width of the col-ddm class, in the main.scss folder

### PR DESCRIPTION
**Pull request by Valmir-unicap**

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
Hi @Valmir-unicap, I need to talk with Form's designer to align if this solution is acceptable. I come with an answer as soon as possible.

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
Hello, @Valmir-unicap. 

after talking to our designer, the best approach to solve this problem is the following:

- Reduce to a minimum size of 25% of the row
- Long Labels, Helptext and options break lines
- Input fields texts (text, selects and textarea) truncate with the width of the Input area (25%)
- For fields with truncated text, show tooltips on hover to complement truncated info

I put this info in the also in the [ticket](https://issues.liferay.com/browse/LPS-166350).

Please, if you have any questions contact us.

I'll close this PR, ok?

**Pull request closed without merging**
