### PR TITLE
LPS-203557 Use the correct location

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://liferay.atlassian.net/browse/LPS-203557

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:help

**Comment by mateussgn** [comment]
ci:test:forms

**Comment by marcelabc** [comment]
Hey @carolmariaabb 
Could you review this PR, please? :smile:

**Comment by carolmariaabb** [comment]
Hi @mateussgn,
Failures are related. Could you please take a look? Thanks!

**Comment by mateussgn** [comment]
Sure, I'm taking a look!
Thanks!

**Comment by mateussgn** [comment]
ci:test:forms

**Comment by mateussgn** [comment]
ci:test:forms

**Comment by mateussgn** [comment]
ci:close

**Pull request closed without merging**
