### PR TITLE
LRQA 71711

### PR DESCRIPTION
**Pull request by guivilarim**
Related Issue: https://issues.liferay.com/browse/LRQA-71711

- LRQA-71711 Add test stubs
- LRQA-71711 Add CanInputData test
- LRQA-71711 Add CanInputtedDataBeEdited test
- LRQA-71711 Add CanInputtedDataBeRemoved test
- LRQA-71711 Add CanInputDataOnDuplicatedField test
- LRQA-71711 Add CanRemoveDuplicatedField test
- LRQA-71711 Create collapsibleFieldsGroup macro
- LRQA-71711 Create clickCollapseFieldsGroup macro
- LRQA-71711 Add CanBeCollapsed test
- LRQA-71711 Add CanSelectGridOptionsInFieldsGroup test
- LRQA-71711 Add CanSelectOptionsInFieldsGroup test
- LRQA-71711 Add CanDataBeEditedInNewFieldsGroup test
- LRQA-71711 Made source format
- LRQA-71711 Fix test descriptions

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by guivilarim** [comment]
ci:foward

**Comment by guivilarim** [comment]
ci:forward

**Pull request closed without merging**
