### PR TITLE
[TS] LPP-46306 > LPS-161353 Accept Root Relative URL in Form redirect url on success

### PR DESCRIPTION
**Pull request by hongvo2308**
Hi @rodrigopaulino
This is the PR for the ticket https://issues.liferay.com/browse/LPS-161353. I have updated this based on your suggestion in the https://github.com/liferay-forms/liferay-portal/pull/1947. Could you please review this one again and leave your comments?
Thank you very much.

### CODE REVIEW

**Comment by hongvo2308** [comment]
ci:test:bundle

**Review by rodrigopaulino — APPROVED** [review]
LGTM! 🎉 
Thanks for working on this, @hongvo2308.

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
I believe these are related to your changes, @hongvo2308. Could you please address them? Thanks!

**Comment by hongvo2308** [comment]
ci:test:relevant

**Comment by hongvo2308** [comment]
Hi @rodrigopaulino 
I have updated with a commit for increasing bundle version and packageinfo. And then I run the relevant test. But the relevant tests still fail. I have checked the log and found that the issues are unrelated to my updates. So what should be the next steps for this one?
Thank you.

**Comment by rodrigopaulino** [comment]
ci:reevaluate:1287401_4333

**Comment by holatuwol** [comment]
ci:test:relevant:norebase

**Comment by hongvo2308** [comment]
@holatuwol @rodrigopaulino 
I have updated the PR with updating packageinfo only and it passed the relevant. I think it's fine now.
Thank you for your help.

**Comment by hongvo2308** [comment]
Hi @rodrigopaulino 
I would like to ask if there are any new updates or demands for this PR.
Thank you very much.

**Comment by rodrigopaulino** [comment]
Hi, @hongvo2308. This is good to go. Sorry for the delaying your answer.
Kind regards.

**Comment by rodrigopaulino** [comment]
ci:forward

**Pull request closed without merging**
