### PR TITLE
LPS-191395 Single selection options cannot be placed inline

### PR DESCRIPTION
**Pull request by larissacribeiro**
Related Issue: [LPS-191395](https://liferay.atlassian.net/browse/LPS-191395)

### CODE REVIEW

**Comment by kristinonias** [comment]
Hi @larissacribeiro @naraandrade 

Just wanted to update to say that I reviewed this PR and it doesn't look like the failures are related to the PR

**Comment by naraandrade** [comment]
> Hi @larissacribeiro @naraandrade
> 
> Just wanted to update to say that I reviewed this and it doesn't look like the failures are related to the PR

Thank you, Kristin!

**Review by alinedoleron — CHANGES_REQUESTED** [review]
Hi @larissacribeiro! 
When I deployed I realized the radio buttons are a little bit far from the beginning of the label. We can compare it with the Multiple selection field.
far

So I think we can change a little bit to make them closer.

I've tried doing this:

```
.ddm__radio {
    word-break: break-all;

    .custom-control-inline {
        margin-right: 1rem;
    }

    .custom-control-inline + .custom-control-inline {
        margin-left: 0;
    }
}
```

And I got this:


close

Please, could you test if this is really working? Also, I remade a scenario of a [previous fix on this file](https://liferay.atlassian.net/browse/LPS-179781) to see if it would impact. 
Thanks!

**Comment by larissacribeiro** [comment]
Hi @alinedoleron, thanks for your review! Yes, it does work, I've just updated it!

**Comment by larissacribeiro** [comment]
ci:test:sf

**Comment by larissacribeiro** [comment]
ci:test:forms

**Comment by larissacribeiro** [comment]
ci:test:relevant

**Comment by larissacribeiro** [comment]
ci:test:forms

**Comment by larissacribeiro** [comment]
ci:test:relevant

**Comment by larissacribeiro** [comment]
ci:stop

**Comment by larissacribeiro** [comment]
Test suites aren't working, it has already been fixed but we need to wait for the PR to be merged into master.
I'll monitor in order to retrigger the test suites when possible!

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:stop

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:stop

**Comment by alinedoleron** [comment]
ci:forward:force

**Pull request closed without merging**
