### PR TITLE
LPS-190904 Init editingLanguageId with defaultLanguageId of form

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
https://liferay.atlassian.net/browse/LPS-190904

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:test:forms

**Comment by alinedoleron** [comment]
Hello, @georgel-pop-lr ! I just wanted to confirm if it is working as expected. I'm not sure if I'm following the steps correctly. 

This is what we have on the [ticket](https://liferay.atlassian.net/browse/LPS-190904):

**Case A**: On a site with English as default language, I add a form browsing in English which will add English as default language, then I add a translation (Spanish, for example):

From the default language (English), I add a Single Selection field and save: it gives: 

Error: Setting (Options) of field Single Selection is invalid.
Note: If I do the same thing but from Spanish language, it works correctly.

Actual: There are various errors when trying to add fields from different language than default

**Expected: Fix all the cases described above and check if there are other fields affected by this behaviour.**

As the expected result is a little generic, I don't know what to expect.

Sorry if I'm mistaken. This is the video I recorded.

[Forms - Liferay DXP (1).webm](https://github.com/liferay-forms/liferay-portal/assets/26491796/d7642bf5-5d59-45a1-983f-441091300799)

**Comment by georgel-pop-lr** [comment]
Hi @alinedoleron,

I find out why is this happening as I forgot to add the changes from https://github.com/liferay-forms/liferay-portal/pull/2276 on the class modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web/src/main/java/com/liferay/dynamic/data/mapping/form/web/internal/portlet/action/util/DDMFormInstanceFieldSettingsValidator.java

Regards.

**Comment by alinedoleron** [comment]
Hi @carolmariaabb. Please, could you review the java file? 🌷

**Comment by georgel-pop-lr** [comment]
> Hi @carolmariaabb. Please, could you review the java file? Thanks! 🌷

I need help with the sf format fail, as I don't understand why is being thrown. 

Any help or suggestion?

Regards.

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
> Hi @alinedoleron,
> 
> I find out why is this happening as I forgot to add the changes from #2276 on the class modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web/src/main/java/com/liferay/dynamic/data/mapping/form/web/internal/portlet/action/util/DDMFormInstanceFieldSettingsValidator.java
> 
> Regards.

Great!! It tested now and it's working! ✨ 

Thanks!

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
> > > Hi @carolmariaabb. Please, could you review the java file? Thanks! 🌷
> > 
> > 
> > I need help with the sf format fail, as I don't understand why is being thrown.
> > Any help or suggestion?
> > Note: I think the SF fail is related to https://liferay.atlassian.net/browse/LPS-180838, https://liferay.slack.com/archives/C01FP01V5L0/p1683040080401029?thread_ts=1683039960.751409&cid=C01FP01V5L0
> > Regards.
> 
> Got it! @carolmariaabb will help you as soon as she can. 😊

Okay great, I think I solved the SF issue, I will retest again tomorrow to see is not breaking anything adding https://github.com/liferay-forms/liferay-portal/pull/2363/commits/32d67f93489fce4a92746e3ecdb3e564f3f77d5e

Regards.

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:test:forms

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by georgel-pop-lr** [comment]
ci:stop

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
The SF issue is related to this: https://liferay.slack.com/archives/C1SJ64S9X/p1697748694943069?thread_ts=1697743978.403029&cid=C1SJ64S9X

After doing this steps, https://liferay.slack.com/archives/C1SJ64S9X/p1697698253103789?thread_ts=1697636673.316089&cid=C1SJ64S9X it runs okay in my local environment

image

Let's hope CI runs now with the fix version of source formatter.

Regards.

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
> ### ❌ ci:test:forms - 171 out of 176 jobs passed in 1 hour 49 minutes
> Click here for more details.
> #### Base Branch:
> Branch Name: [master](https://github.com/liferay/liferay-portal/tree/master)Branch GIT ID: [b54c5ef4111265563c5fc24f93312f8f5c63095a](https://github.com/liferay/liferay-portal/commit/b54c5ef4111265563c5fc24f93312f8f5c63095a)
> 
> #### Upstream Comparison:
> Branch GIT ID: [de0de3137f8e3a749bcbb6d62dc186a4e734393e](https://github.com/liferay/liferay-portal/commit/de0de3137f8e3a749bcbb6d62dc186a4e734393e)Jenkins Build URL: [EE Development Acceptance (master) - 93 - 2023-10-20[00:42:16]](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2444330993)
> 
> **ci:test:forms - 171 out of 176 jobs PASSED**
> ##### For more details click [here](https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9354/jenkins-report.html).
> #### Failures unique to this pull:
> 1. [functional-tomcat90-mysql57-jdk8/1/23](https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/302462//consoleText)1. [LocalFile.FormsImageField#NotPossibleSubmitLargeImage](https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/302462//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FormsImageField_NotPossibleSubmitLargeImage_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2023-10/test-1-38/test-portal-acceptance-pullrequest(master)/9354/functional-tomcat90-mysql57-jdk8/1/23/LocalFile.FormsImageField_NotPossibleSubmitLargeImage/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2023-10/test-1-38/test-portal-acceptance-pullrequest(master)/9354/functional-tomcat90-mysql57-jdk8/1/23/LocalFile.FormsImageField_NotPossibleSubmitLargeImage/summary.html.gz) - [Poshi Console](https://testray.liferay.com/reports/production/logs/2023-10/test-1-38/test-portal-acceptance-pullrequest(master)/9354/functional-tomcat90-mysql57-jdk8/1/23/LocalFile.FormsImageField_NotPossibleSubmitLargeImage/console.txt.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2023-10/test-1-38/test-portal-acceptance-pullrequest(master)/9354/functional-tomcat90-mysql57-jdk8/1/23/jenkins-console.txt.gz)
> 2. [functional-tomcat90-mysql57-jdk8/5/6](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/771761//consoleText)1. [LocalFile.FormsSelectFromListField#CanSaveFormFieldEntryWithRestDataProvider](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/771761//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FormsSelectFromListField_CanSaveFormFieldEntryWithRestDataProvider_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2023-10/test-1-38/test-portal-acceptance-pullrequest(master)/9354/functional-tomcat90-mysql57-jdk8/5/6/LocalFile.FormsSelectFromListField_CanSaveFormFieldEntryWithRestDataProvider/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2023-10/test-1-38/test-portal-acceptance-pullrequest(master)/9354/functional-tomcat90-mysql57-jdk8/5/6/LocalFile.FormsSelectFromListField_CanSaveFormFieldEntryWithRestDataProvider/summary.html.gz) - [Poshi Console](https://testray.liferay.com/reports/production/logs/2023-10/test-1-38/test-portal-acceptance-pullrequest(master)/9354/functional-tomcat90-mysql57-jdk8/5/6/LocalFile.FormsSelectFromListField_CanSaveFormFieldEntryWithRestDataProvider/console.txt.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2023-10/test-1-38/test-portal-acceptance-pullrequest(master)/9354/functional-tomcat90-mysql57-jdk8/5/6/jenkins-console.txt.gz)
> 
> **Failures in common with [acceptance upstream results](https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)) at [de0de31](https://github.com/liferay-forms/liferay-portal/commit/de0de3137f8e3a749bcbb6d62dc186a4e734393e):**
> ##### Test bundle downloads:
> * [liferay-portal-bundle-tomcat.tar.gz](https://files.liferay.com/private/bundles/test-1-38/jobs/test-portal-acceptance-pullrequest(master)/builds/9354/liferay-portal-bundle-tomcat.tar.gz) (mirrors: [dlc](http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-38/jobs/test-portal-acceptance-pullrequest(master)/builds/9354/liferay-portal-bundle-tomcat.tar.gz), [lax](http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-38/jobs/test-portal-acceptance-pullrequest(master)/builds/9354/liferay-portal-bundle-tomcat.tar.gz))

These issues are not related to the PR.

**Comment by alinedoleron** [comment]
> ### ✔️ ci:test:stable - 30 out of 30 jobs passed
> ### ❌ ci:test:relevant - 177 out of 183 jobs passed in 1 hour 53 minutes
> Click here for more details.
> #### Base Branch:
> Branch Name: [master](https://github.com/liferay/liferay-portal/tree/master)Branch GIT ID: [b54c5ef4111265563c5fc24f93312f8f5c63095a](https://github.com/liferay/liferay-portal/commit/b54c5ef4111265563c5fc24f93312f8f5c63095a)
> 
> #### Upstream Comparison:
> Branch GIT ID: [de0de3137f8e3a749bcbb6d62dc186a4e734393e](https://github.com/liferay/liferay-portal/commit/de0de3137f8e3a749bcbb6d62dc186a4e734393e)Jenkins Build URL: [EE Development Acceptance (master) - 93 - 2023-10-20[00:42:16]](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2444330993)
> 
> **ci:test:stable - 30 out of 30 jobs PASSED**
> **ci:test:relevant - 177 out of 183 jobs PASSED**
> ##### For more details click [here](https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6778/jenkins-report.html).
> #### Failures unique to this pull:
> 1. [functional-upgrade-tomcat90-mysql57-jdk8/0/1](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/771728//consoleText)1. [LocalFile.PortalSmokeAutoUpgrade#ViewPortalSmokeArchiveAutoUpgrade7310](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/771728//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_PortalSmokeAutoUpgrade_ViewPortalSmokeArchiveAutoUpgrade7310_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2023-10/test-1-40/test-portal-acceptance-pullrequest(master)/6778/functional-upgrade-tomcat90-mysql57-jdk8/0/1/LocalFile.PortalSmokeAutoUpgrade_ViewPortalSmokeArchiveAutoUpgrade7310/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2023-10/test-1-40/test-portal-acceptance-pullrequest(master)/6778/functional-upgrade-tomcat90-mysql57-jdk8/0/1/LocalFile.PortalSmokeAutoUpgrade_ViewPortalSmokeArchiveAutoUpgrade7310/summary.html.gz) - [Poshi Console](https://testray.liferay.com/reports/production/logs/2023-10/test-1-40/test-portal-acceptance-pullrequest(master)/6778/functional-upgrade-tomcat90-mysql57-jdk8/0/1/LocalFile.PortalSmokeAutoUpgrade_ViewPortalSmokeArchiveAutoUpgrade7310/console.txt.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2023-10/test-1-40/test-portal-acceptance-pullrequest(master)/6778/functional-upgrade-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz) - [Failed 1 of last 17](https://testray.liferay.com/home/-/testray/case_results/2444340023/history)
> 
> **Failures in common with [acceptance upstream results](https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)) at [de0de31](https://github.com/liferay-forms/liferay-portal/commit/de0de3137f8e3a749bcbb6d62dc186a4e734393e):**
> ##### Test bundle downloads:
> * [liferay-portal-bundle-tomcat.tar.gz](https://files.liferay.com/private/bundles/test-1-40/jobs/test-portal-acceptance-pullrequest(master)/builds/6778/liferay-portal-bundle-tomcat.tar.gz) (mirrors: [dlc](http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-40/jobs/test-portal-acceptance-pullrequest(master)/builds/6778/liferay-portal-bundle-tomcat.tar.gz), [lax](http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-40/jobs/test-portal-acceptance-pullrequest(master)/builds/6778/liferay-portal-bundle-tomcat.tar.gz))

Not related.

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
