### PR TITLE
LPS-142453

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Please feel free to make any adjustments as I will be on PTO next week. Thanks!

Related Issue: https://issues.liferay.com/browse/LPS-142453

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Resent https://github.com/liferay-forms/liferay-portal/pull/1141

**Comment by carolmariaabb** [comment]
ci:close

**Pull request closed without merging**
