### PR TITLE
LPS-188971 remove tabindex attributes from ddm role group divs

### PR DESCRIPTION
**Pull request by pat270**
https://liferay.atlassian.net/browse/LPS-188971

Forwarding from https://github.com/liferay-peds/liferay-portal/pull/156.

I removed the `tabindex` attributes from

https://github.com/liferay/liferay-portal/blame/8a8ccf6182cddaa04da6992d2426014dea057cfb/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/src/main/resources/META-INF/resources/FieldBase/ReactFieldBase.es.js#L254

and 

https://github.com/liferay/liferay-portal/blame/master/modules/apps/data-engine/data-engine-js-components-web/src/main/resources/META-INF/resources/js/core/components/Pages.es.js#L70.

It includes the div that groups a set of form elements in the tab order. We only need to use `role="group"` for a screen readers. It will announce it properly when navigating with it.

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by cgmonte** [comment]
ci:test:relevant

**Review by cgmonte — CHANGES_REQUESTED** [review]
LGTM!, @pat270, but it looks like there are still some snaps left to update. Can you take a look at the latest results and update those too? Let me know if you need any help. 

Regarding the concerns raised in the [original PR](https://github.com/liferay-peds/liferay-portal/pull/156) about this change causing other accessibility issues, me and BPM qa have manually tested this and it looks like everything still works.

**Comment by pat270** [comment]
@cgmonte I think I need some help. When I run `yarn test -u` in `/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/`, it's failing with:

```
 FAIL  test/js/LocalizableText/LocalizableText.es.js
  ● Test suite failed to run

    TypeError: localeId.replaceAll is not a function

       95 | 	}
       96 | 
    >  97 | 	return localeId.replaceAll('_', '-').toLowerCase();
          | 	                ^
       98 | }
       99 | 
      100 | export function transformAvailableLocales(

      at normalizeLocaleId (src/main/resources/META-INF/resources/util/localizable/transform.es.js:97:18)
      at Object.<anonymous> (src/main/resources/META-INF/resources/LocalizableText/LocalizableText.es.js:36:8)
      at Object.<anonymous> (test/js/LocalizableText/LocalizableText.es.js:20:1)


Test Suites: 1 failed, 20 passed, 21 total
```

**Comment by cgmonte** [comment]
That is weird, it did not happen here. Downloaded this PR, rebased with latest master, deployed modules, run `yarn test -u` in `/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/` and did not get the error you reported.

See result [here](https://github.com/cgmonte/liferay-portal/pull/75).

**Comment by pat270** [comment]
@cgmonte I finally figured it out, I was on a different node version. Do you happen to know what the standard node version is now?

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
> @cgmonte I finally figured it out, I was on a different node version. Do you happen to know what the standard node version is now?

I think this is the official node version we use: https://learn.liferay.com/w/dxp/building-applications/tooling/reference/node-version-information#version-compatibility-matrix

**Review by cgmonte — APPROVED** [review]
LGMT! @pat270 Also, all failures are **not** related. Will forward this.

**Comment by cgmonte** [comment]
ci:forward

**Comment by cgmonte** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:forward:force

**Comment by marcelabc** [comment]
ci:forward:force

**Pull request closed without merging**
