### PR TITLE
LPS-152899 Adds compatibility layer for color when we are rendering web content templates adding the # to color field type

### PR DESCRIPTION
**Pull request by ealonso**
Related Issue: https://issues.liferay.com/browse/LPS-152899

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:relevant

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by liferay-forms** [comment]
Hey @ealonso, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by liferay-forms** [comment]
Hey @ealonso, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
Hey @ealonso, can you please check if these failures are related to your changes? Thanks

**Comment by ealonso** [comment]
It was already merged by Brian

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Resent https://github.com/liferay-forms/liferay-portal/pull/165

**Comment by carolmariaabb** [comment]
ci:close

**Pull request closed without merging**
