### PR TITLE
LPD-15082

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://liferay.atlassian.net/browse/LPD-15082

### CODE REVIEW

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by carolmariaabb** [comment]
I forced-pushed because I had to change the author [here](https://github.com/liferay-forms/liferay-portal/pull/2466/commits/be4bd928db4ad036ddd26d4474c6b124c5950a9a#diff-cc1d87ac7e04829a9a6f68c85e376556d173a18769efae60e7ef399c29b56be3R27) 😆

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
