### PR TITLE
LPS-170221 Add validation for duplicate field references

### PR DESCRIPTION
**Pull request by devpedrotavares**
[LPS-170221](https://issues.liferay.com/browse/LPS-170221) I'm re-sending this pull request since [this one](https://github.com/brianchandotcom/liferay-portal/pull/128237) got conflicted. Obs.: All I did was rerun `gw baseline`

### CODE REVIEW

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:reevaluate:1377401_8200

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by devpedrotavares** [comment]
forwarding manually: https://github.com/brianchandotcom/liferay-portal/pull/129132

**Comment by devpedrotavares** [comment]
ci:close

**Pull request closed without merging**
