### PR TITLE
LPS-124318

### PR DESCRIPTION
**Pull request by jgarcialr**
Related Issue: https://issues.liferay.com/browse/LPS-124318

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @jgarcialr, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
Hey @jgarcialr, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
Hi @jgarcialr, although the `DDMFormField` is being manipulated, this fix is changing the Workflow code, therefore it should be reviewed by @liferay-workflow. Please forward it to this GitHub user.

Thanks.

**Pull request closed without merging**
