### PR TITLE
LPS-136661 Add a padding at the bottom of field to make all dropdown options invisble

### PR DESCRIPTION
**Pull request by brunofariasdeo**
https://issues.liferay.com/browse/LPS-136661

### CODE REVIEW

**Comment by brunofariasdeo** [comment]
Hi @miltonmc,

After investigating the source of this issue, we (me and Renato) have identified that it is originated on a Clay component.
I have raised this [ticket](https://issues.liferay.com/browse/LPS-137439) with them and came up with this temporary solution once the Search Location field is the only one that does not have enough space left on sidebar to allow users to select all the available options.

Current state:

current-state

After my changes:

after-changes

Let me know what you think about this approach and if any changes would be required.
Tks! :)

**Comment by brunofariasdeo** [comment]
ci:test:relevant

**Comment by brunofariasdeo** [comment]
ci:test:relevant

**Review by miltonmc — APPROVED** [review]
LGTM!

**Comment by brunofariasdeo** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:reevaluate:1277401_960

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
