### PR TITLE
LPS-144404

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related Issue: https://issues.liferay.com/browse/LPS-144404

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Hey, @carolmariaabb. I'm changing reviewers this time, because I'm not entirely confident this won't cause a bug and I could use some of the FE team's insights.

@miltonmc, the reason I removed the `useEffect` above is because it isn't actually doing any logic on top of the latest render. It doesn't seem reasonable to render the component again just to set those values since other events already did that. Also, it was resetting to the initial values, which is weird and causing the reported bug.

**Comment by rodrigopaulino** [comment]
Yeah... found a bug already.

**Comment by rodrigopaulino** [comment]
ci:stop

**Comment by rodrigopaulino** [comment]
ci:close

**Pull request closed without merging**
