### PR TITLE
LPS-121532 Fix bugs: 1. Check each page for required fields individually; 2. Display required field icon legend only if portletNamespace is '_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormPortlet_'

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Related Issue: https://issues.liferay.com/browse/LPS-121532

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by georgel-pop-lr** [comment]
Tested https://github.com/georgel-pop-lr/liferay-portal/pull/9 and all looks fine

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Updated pull: https://github.com/liferay-forms/liferay-portal/pull/55.

**Pull request closed without merging**
