### PR TITLE
[TS] LPS-156368 Show alert message when adding a documents and media field

### PR DESCRIPTION
**Pull request by evibudai**
Hi Team,

**Issue**
The users don't know when they add an upload field to a DDL form that the uploaded document does not inherit the DDL's permission.

without-alert-message

**Solution**
When there is an upload field (Documents and media) added to the form, the system will show an info alert. (decided on [PTR-3206](https://issues.liferay.com/browse/PTR-3206)) 

image

I implemented/tested it including @alinedoleron 's solution (PTR-3272) and it worked as expected in my local environment.

Please review my PR!

Thank you and best regards,
Évi

### CODE REVIEW

**Comment by evibudai** [comment]
ci:test

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:forward

**Comment by alinedoleron** [comment]
Hello @evibudai. Please, could you run `gw formatSource` into` /dynamic-data-mapping-web/` module to fix this SF error?
Thanks :relaxed:

**Comment by evibudai** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
ci:forward

**Pull request closed without merging**
