### PR TITLE
LPD-15620

### PR DESCRIPTION
**Pull request by rijema**
https://liferay.atlassian.net/browse/LPD-15620

Upgrading version = This version is from 2018. Since then, Hystrix was descontinued by the Netflix team and the latest fixes related to maintenance are added on this version.

Thread Properties = Avoiding execution being stuck if some external, unpredicted action affects and block the process. According to the documentation "The general principle is keep the pool as small as possible", so I'm changing to a lower base value (default:10). The Maximum value still 10, so, if necessary, will reach all of them. In addition, we're not analyzing metrics, consequently, we don't need this information as much on the thread pool. that's the reason to change from 10000 to 1000.

Command Properties = We are also not treating the fallback cases on our current code. User must retry by themselves. Threads are better then Semaphore in our case to the isolation strategy, also it was noticed a good response through time compared to increasing the max concurrent size of multiple access.

InvokerImpl = Reducing consume that OSGI Classloader took over time after requesting some information to a Data Provider by cleaning the stored value and removing it from the running threads.

It’s safe to say, after a median of the tests, the value from the beginning was reduced at a rate of almost 30% after the changes. That means, the object from the Data Provider itself is not consuming as much during its allocation on the memory usage **during the execution**.  The tests on the *Test class were executed and the usage was tried on different network connections.

Best result on test: Almost 43% - from 325,028,952 (34.60%) to  196,072,392 (20.16%)
image 

All the results can be found here https://docs.google.com/spreadsheets/d/1xra2COzVTr1Ecvdmgyk7LCo_XCqOsk6lTMLO7SR88hA/edit#gid=0

No change of threshhold or change of timeout is indicated, since the field defining the value of this parameter is mandatory for each entry made on Liferay Data Provider, being treated by the class code if it is not in the range. Indication: A rule could be inserted in the numeric field and rendering the notification in the UI, removing validation in the backend. Tell me if it's necessary. Manipulating this attribute is NOT recommended as it may result in failure to load due to factors such as oscillation, speed and high demand.

After all the tests, there is no evident object pointing to the DDM module so far. 

Cheers,
Richard.

### CODE REVIEW

**Comment by rijema** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
Hi @rijema, I checked on MAT and the  ´com.netflix.config.DynamicProperty´ is not listed as a leak suspect whit the proposed changes, so those changes seem to be effective. Did you test it in a larger form with something like 20 fields or multiple pages to make sure the 'TimeoutInMilliseconds' will not affect negatively the data provider?

Leak suspect without changes:
no-changes-leak-suspect
Leak suspect with changes:
with-changes-leak-suspect

**Comment by rijema** [comment]
Hi @linolaoj , I tested on Forms with 3 different data providers and with different network speed. I did not change any time out property, as They would indeed impact the performance, so I maintained the value set by the user on the UI of a data provider creation.

**Comment by linolaoj** [comment]
As we talked on Slack, @rijema will perform a test to ensure the solution also works on forms with more fields (around 20 fields). I  would suggest keeping this pull request open until we have the results.

**Comment by linolaoj** [comment]
Thank you @rijema , it looks good to me.

**Review by linolaoj — APPROVED** [review]

**Comment by marcelabc** [comment]
Just started reviewing :)

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:forms

**Comment by rijema** [comment]
ci:reevaluate:1347401_5733

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by marcelabc** [comment]
Based on the CSV report generated by ci:test:relevant, there are no unique failures.

**Comment by marcelabc** [comment]
ci:report:2539459964

**Comment by marcelabc** [comment]
Based on the CSV report generated by ci:test:forms, there are no unique failures.

**Comment by marcelabc** [comment]
The unique failures are known issues:
[LocalFile.FormsRulesConditions#CanCreateMultipleConditionsUsingOR](https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/946897//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FormsRulesConditions_CanCreateMultipleConditionsUsingOR_)
[LocalFile.FormsRulesActions#CanIncludeNumericFieldsInCalculations](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/528692//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FormsRulesActions_CanIncludeNumericFieldsInCalculations_)

**Comment by marcelabc** [comment]
ci:forward:force

**Pull request closed without merging**
