### PR TITLE
LPS-171279 Add Locality and Street_Number variable

### PR DESCRIPTION
**Pull request by Marina-Gouveia**
https://issues.liferay.com/browse/LPS-171279

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:forward

**Comment by alinedoleron** [comment]
Hi @Marina-Gouveia. The failing tests are not related to the PR. Please, could you send it directly to Brian?Thanks!

**Comment by Marina-Gouveia** [comment]
ci:forward

**Comment by Marina-Gouveia** [comment]
Closed, sent manually for brianchandotcom

**Pull request closed without merging**
