### PR TITLE
LPS-131813 Delete app-builder and app-builder-workflow modules from Portal

### PR DESCRIPTION
**Pull request by interaminense**
Hi @brianchandotcom, this PR is about removing `app-builder` and `app-builder-worflow`. I got a lot of help from @rodrigopaulino to update some Data Engine integration tests. Let me know if you have any questions regarding anything about this PR.

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
@interaminense - Some of the builds were aborted in this pull request test. I will retest this now. Sorry for any inconvenience.

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
> @interaminense - Some of the builds were aborted in this pull request test. I will retest this now. Sorry for any inconvenience.

Thanks @michaelhashimoto !

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:stop

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
Hey @natocesarrego , someone can help me to investigate why these integration tests are failing?

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Hi, @interaminense. I'm checking to see what we can do about it. I'll let you know any findings.

**Comment by interaminense** [comment]
> Hi, @interaminense. I'm checking to see what we can do about it. I'll let you know any findings.

Thank you so much, @rodrigopaulino!! Let me know if you have a question about it.

**Comment by rodrigopaulino** [comment]
@interaminense, I was able to get rid of your failures, but I'm now activating again the tests that were ignored by @gabrielwas. I'll send you a pull request once this is done. Let me know if you need further details.

Thanks for your patience.

**Comment by interaminense** [comment]
> I was able to get rid of your failures, but I'm now activating again the tests that were ignored by @gabrielwas. I'll send you a pull request once this is done. Let me know if you need further details.
> 
> Thanks for your patience.

Wooow, that's a great news!! Thanks, @rodrigopaulino!! When you finish it, I'll solve these conflicts!

**Comment by rodrigopaulino** [comment]
@interaminense I've just sent you the changes concerning Data Engine's REST test module. See https://github.com/interaminense/liferay-portal/pull/270
Keep in mind that rebasing with master's liferay-portal is still needed.

Thanks for reaching out. Please let me know if there's anything else I can do to help. 😄

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
cc: @liferay-data-engine

**Comment by rodrigopaulino** [comment]
Hey, @interaminense. I checked the previous CI failures and they appear to be related to app builder poshi tests. :)

**Comment by interaminense** [comment]
> Hey, @interaminense. I checked the previous CI failures and they appear to be related to app builder poshi tests. :)

Yes, @rodrigopaulino. The DE needs some macros from the app-builder and I moved those macros to the data-engine-tests module. It was missing to get some updates made on FormViewBuilder.macro in this commit https://github.com/liferay-forms/liferay-portal/pull/221/commits/5bd4650bb690e9eff61e68da9dbcd665cda318cd

**Comment by rodrigopaulino** [comment]
I see. Thanks for letting us know @interaminense.

Good work! 👍🏻

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Hey, @interaminense. I see there's a failure related to the removal of an exception, but since we're in fact deleting code, we can push that removal, right? I guess it would be the case of simply committing the baseline changes so the tests stop failing. Please correct me if I'm wrong. 

Also, just want to let you know that I'll be on PTO next Monday, so, if need help with this asap, please contact the rest of the DE team. Thanks!

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
> Hey, @interaminense. I see there's a breaking change related to the removal of an exception, but since we're in fact deleting code, we can push that removal, right? I guess it would be the case of simply committing the baseline changes so the tests stop failing. Please correct me if I'm wrong.
> 
> Also, just want to let you know that I'll be on PTO next Monday, so, if you need help with this asap, please contact the rest of the DE team. Thanks!

@rodrigopaulino, In addition to code removal, I removed components that were only used by **app-builder** and **app-builder-workflow**. A component within the **workflow-metrics-web** module made a call to those components that were removed. I made the adjustment on [this commit](https://github.com/liferay-forms/liferay-portal/pull/221/commits/5cfd213123c75e2e93fc5e1e36fe4eed8f690023) to resolve this last fail of the relevant.

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Hey, @interaminense. Probably, Brian won't accept this breaking change. I will deprecate the exception instead which will cause only a minor change. I'll do that right now and send you the (hopefully) the final change.

**Comment by interaminense** [comment]
> Hey, @interaminense. Probably, Brian won't accept this breaking change. I will deprecate the exception instead which will cause only a minor change. I'll do that right now and send you the (hopefully) the final change.

Thanks, @rodrigopaulino

**Comment by rodrigopaulino** [comment]
@interaminense you can find the new commit here: https://github.com/interaminense/liferay-portal/pull/271
Let me know if there's anything else I can do to help.

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
> @interaminense you can find the new commit here: [interaminense#271](https://github.com/interaminense/liferay-portal/pull/271)
> Let me know if there's anything else I can do to help.

Thanks, @rodrigopaulino. I did a cherry-pick https://github.com/liferay-forms/liferay-portal/pull/221/commits/ba87fa612f4423f4128eea4f64fea67cd13e7cd8 and now I'll run relevant again

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:reevaluate:1257401_704

**Comment by interaminense** [comment]
ci:reevaluate:1257401_704

**Comment by interaminense** [comment]
ci:reevaluate:1257401_704

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:forward

**Pull request closed without merging**
