### PR TITLE
LPD-27759 Take into account ctCollectionId during DDMFormField upgrade proces

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://liferay.atlassian.net/browse/LPD-27759

### CODE REVIEW

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:upgrade

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
