### PR TITLE
LPS-160242

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
@rodrigopaulino I've fix the unrelated failing _StringUtilTest_ in https://issues.liferay.com/browse/LPS-151221. Besides that, it's the same pull, I've only added an additional test to test with our application server locale providers.

**Comment by rodrigopaulino** [comment]
> @rodrigopaulino I've fix the unrelated failing _StringUtilTest_ in https://issues.liferay.com/browse/LPS-151221. Besides that, it's the same pull, I've only added an additional test to test with our application server locale providers.

That's awesome. Thanks, @marianoalvarosaiz

**Review by rodrigopaulino — APPROVED** [review]
LGTM! 🎉

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by marianoalvarosaiz** [comment]
ci:stable

**Comment by rodrigopaulino** [comment]
@marianoalvarosaiz, feel free to send the pull directly to Brian if you don't want to wait for CI, which is having trouble at the moment. Just make sure to mention that tests already passed. 🙂

**Comment by marianoalvarosaiz** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122482

**Pull request closed without merging**
