### PR TITLE
LPS-137750 test

### PR DESCRIPTION
**Pull request by cleydyr**
Related Issue: https://issues.liferay.com/browse/LPS-137750

This is only a complementary commit to LPS-137750 adding a test. Please review and forward.

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by cleydyr** [comment]
Oops. Wrong user. :harold: Closing.

**Pull request closed without merging**
