### PR TITLE
LPS-168667

### PR DESCRIPTION
**Pull request by alinedoleron**
https://issues.liferay.com/browse/LPS-165822

### CODE REVIEW

**Comment by alinedoleron** [comment]
Waiting for Alana's check. https://github.com/liferay-forms/liferay-portal/pull/2236#issuecomment-1583542748

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:forms

**Comment by alinedoleron** [comment]
> Hey @alinedoleron I've checked the results and the tests that are failing are not related to the change. All right, send it! cc: @patriciajeanperez

Thank you, @alanafergs !!

**Comment by alinedoleron** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
