### PR TITLE
LPD-8497 / LPD-8498 / LPD-8499 / LPD-8501 /LPD-8502 / LPD-8503 / LPD-8504 / LPD-8505 Remove unused Reference variables

### PR DESCRIPTION
**Pull request by diogomelo09**
[LPD-8497](https://liferay.atlassian.net/browse/LPD-8497) [LPD-8498](https://liferay.atlassian.net/browse/LPD-8498) [LPD-8499](https://liferay.atlassian.net/browse/LPD-8499) [LPD-8501](https://liferay.atlassian.net/browse/LPD-8501) [LPD-8502](https://liferay.atlassian.net/browse/LPD-8502) [LPD-8503](https://liferay.atlassian.net/browse/LPD-8503) [LPD-8504](https://liferay.atlassian.net/browse/LPD-8504) [LPD-8505](https://liferay.atlassian.net/browse/LPD-8505)

### CODE REVIEW

**Comment by diogomelo09** [comment]
ci:test:sf

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
@diogomelo09 please fix the SF failure:

```
format-source-files:
     [java] java.lang.Exception: Found formatting issue in SHA 85ac525159e95b71156f35ff36511a92b63a7741
     [java] The commit message should not start with whitespace
```

**Comment by diogomelo09** [comment]
ci:test:sf

**Comment by diogomelo09** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
