### PR TITLE
Forms Automated Test - LPS-132266 | master

### PR DESCRIPTION
**Pull request by wesleyroberts**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
@wesleyroberts I think Brian already merged this (https://github.com/brianchandotcom/liferay-portal/pull/102782)?

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
@wesleyroberts can you please resolve the conflicts so we can send the test without the `ignore` annotation? Thanks!

**Comment by wesleyroberts** [comment]
resolved conflicts and i submitted  the test without the ignore annotation.

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
Resent https://github.com/liferay-forms/liferay-portal/pull/557

**Pull request closed without merging**
