### PR TITLE
LPS-138365

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related Issue: https://issues.liferay.com/browse/LPS-138365

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hey @rodrigopaulino, can you please fix the source formatter issues and resend? Thanks

**Comment by rodrigopaulino** [comment]
ci:reopen

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hey @rodrigopaulino, can you please fix the source formatter issues and resend? Thanks

**Pull request closed without merging**
