### PR TITLE
LPS-145982 Adjust pipe mask format logic to work with hungarian language

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issues: 

- https://issues.liferay.com/browse/LPS-145986
- https://issues.liferay.com/browse/LPS-145982

Hello Reviewer!

This PR has a fix of the bugs above. The first commit is to avoid closing the Date Picker modal after selecting a date so the user can select an hour value without the need to open the modal again. 

The second one fixes an issue on the pipe mask that wasn't working for the Hungarian language. The correct format for this language is `'yyyy mm dd  HH:MM'` with two spaces between `dd` and `HH` but the mask was sending only one, so I changed the logic to cover this case as well.

If you have any questions feel free to ask, thank you for your time!

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @rebsilva, can you please check if these failures are related to your changes? Thanks

**Comment by rebsilva** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]
LGTM! :purple_heart:

**Comment by rebsilva** [comment]
ci:forward

**Pull request closed without merging**
