### PR TITLE
LPS-147917

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-147917

From @hongvo2308

> Hi,
> This is the PR for fixing https://issues.liferay.com/browse/LPS-147917. Basically, the solution is using the reference service call function for activating AOP. The original PR at https://github.com/hongvo2308/liferay-portal/pull/24 has passed my review. Please review it and leave your comments.
> 
> Thank you.

CC: @sontruongces

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:reevaluate:1327401_4365

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:reevaluate:1347401_2129

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
