### PR TITLE
LPS-147973

### PR DESCRIPTION
**Pull request by leticia-maciel**
Related Issue: https://issues.liferay.com/browse/LPS-147973

Hi! 

This PR is intended to improve the Paragraph field view when there's a table with a large number of columns.
By adding the attribute `overflow-x: auto` on the `liferay-ddm-form-field-paragraph` class an horizontal scrollbar will appear and the table will not overlap others div tags anymore.

Before:
image

Now:
image

Feel free to ask if you have any questions.

Thanks.

### CODE REVIEW

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]
Great job!!

**Comment by alinedoleron** [comment]
ci:forward

**Pull request closed without merging**
