### PR TITLE
LPS-161287 Only overwrite user input if value is not null or not empty

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://issues.liferay.com/browse/LPS-161287

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
Hi @carolmariaabb,
The unique failure seems to be unique, but I don't see how your changes could affect this test. 
https://testray.liferay.com/home/-/testray/case_results/2127981695/history?tab=result&hideFilterPin=true

**Comment by carolmariaabb** [comment]
> Hi @carolmariaabb, The failure seems unique, but I don't see how your changes could have affected this test. https://testray.liferay.com/home/-/testray/case_results/2127981695/history?tab=result&hideFilterPin=true

I'll run `ci:test:relevant` again to make sure it's not related

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/127686

**Pull request closed without merging**
