### PR TITLE
LPS-161287 Only overwrite user input if value is not null or not empty

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://issues.liferay.com/browse/LPS-161287

### CODE REVIEW

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by marcelabc** [comment]
Maybe it is worthy checking this failure because it has been successful in history: https://testray.liferay.com/home/-/testray/case_results/2148839138/history?tab=result&hideFilterPin=true

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
