### PR TITLE
LPS-147119 Remove Feature Flag for LPS-143065

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related Issue: https://issues.liferay.com/browse/LPS-147119

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by liferay-forms** [comment]
Hey @carolmariaabb, can you please check if these failures are related to your changes? Thanks

**Comment by michaelhashimoto** [comment]
ci:test:relevant

@carolmariaabb - I am re-running this, this had failed due to this issue:
https://liferay.slack.com/archives/C19PWQ74J/p1648484921625339?thread_ts=1648463797.215559&cid=C19PWQ74J

Thanks!

**Comment by carolmariaabb** [comment]
Thanks @michaelhashimoto!

**Comment by carolmariaabb** [comment]
> @carolmariaabb, is it safe to forward this or should we run the objects suite again?

It's safe, thanks for asking!

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
