### PR TITLE
LPS-161287

### PR DESCRIPTION
**Pull request by titokenzo**
Related issue: https://issues.liferay.com/browse/LPS-161287

### CODE REVIEW

**Comment by titokenzo** [comment]
Updated/push force for SF

**Comment by marcelabc** [comment]
Hi @titokenzo 
I just wanted to let you know that I edited the description to include the "Related Issue" (with the Jira ticket). Please always add this information in your following reviews if you can!

**Comment by marcelabc** [comment]
Follow-up review: https://github.com/liferay-forms/liferay-portal/pull/1928

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
Resent https://github.com/liferay-forms/liferay-portal/pull/2040

**Pull request closed without merging**
