### PR TITLE
LPS-203404 Include fieldReference in the default form field settings

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related Issue: https://liferay.atlassian.net/browse/LPS-203404

Created because https://liferay.atlassian.net/browse/PTR-4568

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
