### PR TITLE
LPS-195265 Set chooseAnOption as empty value

### PR DESCRIPTION
**Pull request by alinedoleron**
Ticket: https://liferay.atlassian.net/browse/LPS-195265

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:forms

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:forms

**Comment by davisaints** [comment]
ci:test:relevant

**Comment by davisaints** [comment]
Hi @alinedoleron, the stable build failed with this unit test as failure:
 ```
 [exec] > Task :apps:data-engine:data-engine-taglib:packageRunTest
     [exec] FAIL test/js/data-layout-builder/components/rules/editor/Editor.es.js (98.526s)
```

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:data-engine

**Comment by alinedoleron** [comment]
ci:test:forms

**Comment by davisaints** [comment]
ci:test:stable

**Comment by alinedoleron** [comment]
resent here: https://github.com/liferay-forms/liferay-portal/pull/2399

**Pull request closed without merging**
