### PR TITLE
LPS-173582 When publishing web content folder, Link to Page fields are not be processed correctly

### PR DESCRIPTION
**Pull request by jvelalr**
**Notes:**

- Forwarding from: liferay-staging/liferay-portal#220 .

- Made some optimization

- The change looks ok from staging perspective

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:reevaluate:1327401_8059

**Comment by jgarcialr** [comment]
ci:reevaluate:1297401_6273

**Comment by jvelalr** [comment]
ci:reevaluate:1327401_8059

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
