### PR TITLE
LPD-34714 Add aria-label attribute for ClassicEditor component

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://liferay.atlassian.net/browse/LPD-34714

### CODE REVIEW

**Comment by danvb112** [comment]
Hey @rebsilva, this PR will require Frontend infra review as well, so I'll open a new PR for them in parallel

**Comment by danvb112** [comment]
Frontend-infra PR: https://github.com/liferay-frontend/liferay-portal/pull/4388

**Review by rebsilva — APPROVED** [review]
hey @danvb112! the code looks good to me, but maybe the frontend-infra team will ask to put the 'for' attribute instead of the 'aria-label', so let's wait for their review on this

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:forms

**Comment by danvb112** [comment]
ci:test:data-engine

**Comment by danvb112** [comment]
PR [accepted](https://github.com/liferay-frontend/liferay-portal/pull/4388#pullrequestreview-2266163299) by frontend-infra :tada:

**Comment by danvb112** [comment]
ci:test:forms

**Comment by danvb112** [comment]
ci:test:forms

**Comment by danvb112** [comment]
ci:test:data-engine

**Comment by danvb112** [comment]
ci:forward:force

**Comment by danvb112** [comment]
ci:forward:force

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:forms

**Comment by danvb112** [comment]
ci:test:data-engine

**Pull request closed without merging**
