### PR TITLE
LPS-156302 Make sure that the value of a required field is not empty

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://issues.liferay.com/browse/LPS-156302

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:sf

**Review by rodrigopaulino — APPROVED** [review]
LGTM! 🎉

**Comment by brianchandotcom** [comment]
@carolmariaabb @rodrigopaulino merged to master and the temp branch.

**Comment by carolmariaabb** [comment]
ci:close

**Pull request closed without merging**
