### PR TITLE
LPS-157358 - allowing admin to edit non-updated forms

### PR DESCRIPTION
**Pull request by lazhcsilva**
The [bug](https://issues.liferay.com/browse/LPS-157358) occurs when trying to edit a form that has some entry, when editing the form it generates a block in the form fields.
The solution in this PR is to make a check between the last version of the form and the current version, adding what is missing to the last version, thus allowing you to edit it.

### CODE REVIEW

**Comment by lazhcsilva** [comment]
ci:test:sf

**Comment by lazhcsilva** [comment]
ci:test:sf

**Comment by lazhcsilva** [comment]
ci:test:relevant

**Comment by lazhcsilva** [comment]
ci:test:relevant

**Review by rodrigopaulino — CHANGES_REQUESTED** [review]
Hi, @lazhcsilva. Thanks for working on this issue.
I believe the expected behavior is not the one implemented. For editing an entry, the user should render just the form's latest version.
I've commented on the ticket letting the reporter know.

I'll close this and we look forward for your other solution.
Thx.

**Comment by rodrigopaulino** [comment]
ci:close

**Pull request closed without merging**
