### PR TITLE
[TS] LPS-189059 Structure considered modified even if its not after every restart

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Motivation
=======
A web content is published the portal [checks](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/java/com/liferay/dynamic/data/mapping/web/internal/exportimport/data/handler/DDMStructureStagedModelDataHandler.java#L426) its referenced structure and determines if the structure has been modified or not. If it has been modified, all of the DDMFields are updated that are referencing this structure.
The issue is that after every server restart, the structure is deemed as modified even if it's not. This is because when the code [compares](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/java/com/liferay/dynamic/data/mapping/web/internal/exportimport/data/handler/DDMStructureStagedModelDataHandler.java#L772) the existing structure to the one that is being imported, the field order in their definition JSON is different.
This is because the JSON structure is written and then read from the exported file and the field order is altered during the serialization/deserialization process.

Proposed Solution
========
When comparing the structure definitions, the comparison should be made on the structural level ignoring the field order.

Steps to Verify
========
Please see the linked LPS for the reproduction steps.
https://liferay.atlassian.net/browse/LPS-189059

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
Dear Team,

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by IstvanD** [comment]
@carolmariaabb thanks for forwarding!

**Pull request closed without merging**
