### PR TITLE
LPD-27756

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://liferay.atlassian.net/browse/LPD-27756

### CODE REVIEW

**Comment by carolmariaabb** [comment]
I did some research and discovered that we just need to extend `BaseCTUpgradeProcessTestCase`, overriding the necessary methods.

The test fails if I revert the first commit 😄

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
