### PR TITLE
LPS-129340 Serialize the form builder context in-depth to avoid JSONArray and JSONObject in the structure

### PR DESCRIPTION
**Pull request by matuzalemsteles**
It seems that just getting `getContext` does not bring the context fully serialized and when we try to create a new `JSONObject` from it, some properties of some Fields that use `jsonFactory` end up being added as part of the structure, as an example `rows: {JSONArray: []}` instead of `rows: []`.

The solution here was to serialize the context in-depth and then create a JSONObject, this seems to have removed the use cases known above. This also removes the palliative from the Frontend side 🙌

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
I see no issues on this pull, @matuzalemsteles. :slightly_smiling_face: Feel free to move on with it.

**Comment by matuzalemsteles** [comment]
Thanks @natocesarrego, triggering a forward now.

**Comment by matuzalemsteles** [comment]
ci:forward

**Comment by matuzalemsteles** [comment]
ci:forward

**Pull request closed without merging**
