### PR TITLE
LRQA 70110.2

### PR DESCRIPTION
**Pull request by guivilarim**
Related Issue: https://issues.liferay.com/browse/LRQA-70110

- LRQA-70110 Create test stubs
- LRQA-70110 Create inputDataInLinkToPageField, assertLinktoPageIsClear, assertContentInLinktoPageField and assertContent macros
- LRQA-70110 Add CanInputLink test
- LRQA-70110 Add CanNotPublishBlankRequiredField test
- LRQA-70110 Add CanRemoveDuplicatedField test
- LRQA-70110 Add CanClearInput test
- LRQA-70110 Add CanInputDataOnDuplicatedField test

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Already merged https://github.com/brianchandotcom/liferay-portal/pull/109978

**Comment by carolmariaabb** [comment]
ci:close

**Comment by carolmariaabb** [comment]
ci:stop

**Pull request closed without merging**
