### PR TITLE
Forms Automated Test - LPS-131239 | master

### PR DESCRIPTION
**Pull request by piresdm**

### CODE REVIEW

**Comment by diogocordeiro** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
Hi @piresdm, could you also assert Test B and Test C are present as well? Thank you!

**Comment by piresdm** [comment]
> Hi @piresdm, could you also assert Test B and Test C are present as well? Thank you!

@brittneyq fixed!

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by diogocordeiro** [comment]
ci:forward

**Pull request closed without merging**
