### PR TITLE
LPS-160435 Focusing and scrolling to the first form input field on a page

### PR DESCRIPTION
**Pull request by rijema**
Click [here](https://issues.liferay.com/browse/LPS-160435) to see the LPS.

Let me know if you have any questions.

Regards,
Richard.

### CODE REVIEW

**Comment by rijema** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Review by rebsilva — CHANGES_REQUESTED** [review]
Hi @rijema, thanks for your PR! I made the cherry-pick to test it and I realized that some side effects are happening; like the page title on the Form Builder is being focused and some fields are not loading correctly (you need to keep trying to add a field until a error happens, not sure what is the exact cause but it involves the autoFocus):

New Form - Liferay

Could you please take a look at this and send it again after fixing it? Thanks a lot!

**Comment by rijema** [comment]
Hi @rebsilva , thanks for your findings. I will work on it tomorrow afternoon. Regards.

**Comment by rijema** [comment]
ci:test:relevant

**Comment by rijema** [comment]
ci:test:sf

**Comment by rijema** [comment]
I believe it's done!

**Comment by rebsilva** [comment]
Thanks @rijema! I will take a look today :blush:

**Review by rebsilva — APPROVED** [review]
LGTM! :cherry_blossom:

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
Hi @rijema! The same test failed two times already, could you take a look if it needs some fixing? Thanks!

**Comment by rijema** [comment]
Hi @rebsilva , After running the command `gw testIntegration --tests com.liferay.company.service.test.CompanyLocalServiceTest ` inside the module, all the tests inside CompanyLocalServiceTest has passed. So, I believe it's not related to my changes. 

Let me know if I have to do further tests.

Regards,
Richard.

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
From what I see this `CompanyLocalServiceTest` has been failing sometimes on [Testray reports](https://testray.liferay.com/home/-/testray/case_results/1950654214/history?tab=result&hideFilterPin=true). Should I report this to the QA team @rodrigopaulino?

**Comment by jorgediaz-lr** [comment]
Hi @rijema @rebsilva 

The failing test of CompanyLocalServiceTest is already reported here: https://issues.liferay.com/browse/LPS-157568

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:forward

**Pull request closed without merging**
