### PR TITLE
LPS-136630 Introduce a switch to personalise if DDM Image description field should be required

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

It enables the user to set the Image field's description as required individually.

Please note that this is the solution only for the Data Engine part. I have yet to figure it how to implement it on the DDM side.

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Hi, @IstvanD. Many thanks for sending us your contribution to be reviewed.

I took a quick look and it seems your pull is missing the introduction of this new property in DDM too.
DDM must also have the new property on master, since customer might be using the taglib with an image field.

Hope you understand. Please check the PTR related to this issue for more details.

Kind regards.

**Comment by natocesarrego** [comment]
@rodrigopaulino, do you prefer to assign this review to you once it's related to the PTR you and Mateus Melo are working on?

Thanks.

**Comment by rodrigopaulino** [comment]
Sounds good, @natocesarrego.

@IstvanD, I'll start the review after you push the requested additions.
Thanks for contributing.

**Comment by rodrigopaulino** [comment]
@IstvanD, I'll close this pull request. Please resend it when you include the additional changes requested here: https://github.com/liferay-forms/liferay-portal/pull/815#issuecomment-898765178

Thanks for working on this.

**Comment by rodrigopaulino** [comment]
ci:close

**Pull request closed without merging**
