### PR TITLE
LPS-157113

### PR DESCRIPTION
**Pull request by alinedoleron**
Hi @rebsilva! This PR contains the suggestions you've made on this [PR](https://github.com/liferay-forms/liferay-portal/pull/1816). Thank you very much, and feel free to suggest more if needed. :purple_heart:

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Review by rebsilva — APPROVED** [review]
LGTM!! :cherry_blossom: Thank you for making the changes! :purple_heart:

**Comment by rebsilva** [comment]
ci:forward

**Pull request closed without merging**
