### PR TITLE
[TS] LPS-164911 Creating web content from a fieldset from global structure with select from list field is not possible when Global langauge is different from Site language

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Review by carolmariaabb — CHANGES_REQUESTED** [review]

**Comment by IstvanD** [comment]
HI @carolmariaabb that you for the feedback! I have force-pushed the requested changes.

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
