### PR TITLE
LPS-180711 Duplicate key value violates unique constraint "ix_272bbc86" when editing and publishing a form from staging to live

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-180711

If you remove a field from a form and you re-publish the form and its form entries from staging to live, a database error is thrown:
```
2023-04-04 10:51:45.262 ERROR [liferay/background_task-10][SqlExceptionHelper:142] Batch entry 0 UPDATE DDMFormInstanceRecordVersion SET mvccVersion = 2, version = '1.0' WHERE formInstanceRecordVersionId = 47741 AND mvccVersion = 1 AND DDMFormInstanceRecordVersion.ctCollectionId = 0 was aborted: ERROR: duplicate key value violates unique constraint "ix_272bbc86"
 ```

The complete explanation of the root cause of this issue is explained in the description of https://issues.liferay.com/browse/LPS-180711, in a few words:

1. In some situations, when publishing the 1.0 version of a DDMFormInstanceRecord, a new 1.1 version is added by the DDMFormInstanceRecordLocalServiceImpl.updateFormInstanceRecord
2. The DDMFormInstanceRecord staging code has a code that updates the version from 1.1 to 1.0, but it fails because there is an existing 1.0 record.

To solve this issue, I am doing following changes:

- be610edd772d1102c99587322da0fdf0cc7d9d22 - New code that delete previous DDMFormInstanceRecordVersion entry to avoid 'ix_272bbc86' index unique constraint violation using the `ddmFormInstanceRecordVersionLocalService.deleteDDMFormInstanceRecordVersion` method.
- aee4b9befa5ca345c19b5d1ee2e1648e284bc75f - Here I am fixing the `ddmFormInstanceRecordVersionLocalService.deleteDDMFormInstanceRecordVersion` method because it doesn't delete the data from other tables (DDMFieldAttribute (storage), DDMStorageLinkLocalService, WorkflowInstanceLink). After this method is fixed, we can remove some duplicate code from DDMFormInstanceRecordLocalServiceImpl.java
- cea964cd72853dcbd798fbad127d7e16f1414562 - Add throws PortalException in the API module of DDMFormInstanceRecordVersionLocalService

Let me know if you have any question

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Semantic versioning errors belongs to other java classes unrelated to this PR

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
@jorgediaz-lr Please see https://github.com/liferay-forms/liferay-portal/pull/2196

Thanks!

**Pull request closed without merging**
