### PR TITLE
LPS-174628 | LPS-170823

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related Issues:
https://issues.liferay.com/browse/LPS-174628
https://issues.liferay.com/browse/LPS-170823

### CODE REVIEW

**Comment by xbrianlee** [comment]
Passed manual testing following the steps in [LPS-170823](https://issues.liferay.com/browse/LPS-170823) and [LPS-174628](https://issues.liferay.com/browse/LPS-174628)

**Comment by epark18** [comment]
Hi @carolmariaabb, there is one new test failure that is introduced with these changes. Would you be able to take a look? [
com.liferay.dynamic.data.mapping.internal.util.DDMIndexerImplTest - testFormWithTwoAvailableLocalesAndFieldWithTwoLocales](https://testray.liferay.com/home/-/testray/case_results/2198389870)
[Full Console Logs](https://testray.liferay.com/reports/production/logs/2023-02/test-1-36/test-portal-acceptance-pullrequest(master)/3026/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

```
     [exec] com.liferay.dynamic.data.mapping.internal.util.DDMIndexerImplTest > testFormWithTwoAvailableLocalesAndFieldWithTwoLocales FAILED
     [exec]     org.junit.ComparisonFailure: ������������->{ddmFieldArray.ddmFieldValueText_ja_JP=[null, ������������], ddmFieldArray.ddmFieldValueText_ja_JP_String_sortable=null, ddmFieldArray.ddmFieldValueText_en_US_String_sortable=create new, ddmFieldArray.ddmFieldValueText_en_US=[Create New, ������������]} expected:<...ieldValueText_en_US=[Create New, ddmFieldArray.ddmFieldValueText_en_US_String_sortable=create new, ddmFieldArray.ddmFieldValueText_ja_JP=������������, ddmFieldArray.ddmFieldValueText_ja_JP_String_sortable=������������]]> but was:<...ieldValueText_en_US=[[Create New, ������������], ddmFieldArray.ddmFieldValueText_en_US_String_sortable=create new, ddmFieldArray.ddmFieldValueText_ja_JP=[null, ������������], ddmFieldArray.ddmFieldValueText_ja_JP_String_sortable=null]]>
     [exec]         at org.junit.Assert.assertEquals(Assert.java:115)
     [exec]         at com.liferay.portal.search.test.util.AssertUtils.assertEquals(AssertUtils.java:100)
```

**Review by marcelabc — APPROVED** [review]
LGTM 🎉
Good work in refactoring (simplify) that class :smile:

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/130447

**Pull request closed without merging**
