### PR TITLE
LPS-202999 Wait until form has been rendered

### PR DESCRIPTION
**Pull request by p2kmgcl**
> Needs feature.flag.LPS-114700 to test

Since we now are rendering our form content inside a clay:panel taglib, the content form element might not be available on first render. We need to wait for this element.

To solve this, I've added a simple MutationObserver that watches the DOM until the element is found.

### CODE REVIEW

**Comment by rebsilva** [comment]
i'll be reviewing this later today, thanks! :cherry_blossom:

**Review by rebsilva — APPROVED** [review]
LGTM! :tada:

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:test:data-engine

**Comment by rebsilva** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
