### PR TITLE
[TS] LPS-121532 | Accessibility forms fields

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Related Issue: https://issues.liferay.com/browse/LPS-121532

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hey @georgel-pop-lr, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
> Related Issue: https://issues.liferay.com/browse/LPS-121532

1. Add icon required legend description for users who can read screen when the form has at least one required field.
2. Create relationship between fields and messages when being read by assistive tools
3. Fix some markup errors on the code I touch

To check why Select.es.js the li element when selecting an option has always the attribute area-selected="false", this creates problems when read by assistive tools, I could not identify from where is this attribute set up. `<li aria-selected="false">`
image

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @georgel-pop-lr, can you please fix the source formatter issues and resend? Thanks

**Pull request closed without merging**
