### PR TITLE
[LPS-166814, LPS-166815] FE of story "I want to be able to have my single selection entries display as tables"

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issues:

- https://issues.liferay.com/browse/LPS-166815
- https://issues.liferay.com/browse/LPS-164999

Hello Reviewer!

This has new features related to the story: **LPS-164999 As a form admin, I want to be able to have my single selection entries display as tables**

If you have any doubts you can always ask me, thanks a lot!

### CODE REVIEW

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:forward

**Pull request closed without merging**
