### PR TITLE
LPS-151862 New way to deal with feature flags on front-end

### PR DESCRIPTION
**Pull request by miltonmc**
Related Issue: https://issues.liferay.com/browse/LPS-151862

This PR code is an attempt to simplify the way we deal with feature flags on front-end side.

It creates a custom hook that should be directly imported by the React component where the flag is needed in order to avoid [prop drilling](https://kentcdodds.com/blog/prop-drilling), minimizing changes (possibly reducing conflicts between PRs) and ease the use, addition and deletion of a feature flag.

This hook captures all the feature flags existent in the `bundles/portal-ext.properties` and provides a type check in order to identify misuses once the flag is removed.

### Step-by-step:

1.  Go to `bundles/portal-ext.properties` and add the feature flag property

```properties
feature.flag.LPS-xxxxxx=true
```
2. Add the flag to the `data-engine-js-components-web` type definition:
```ts
declare module 'data-engine-js-components-web' {
	function useFlag(): {
		[key in Flags]: boolean;
	};
} 

type Flags = 'LPS-xxxxxx;
```
**Note**: Since the `data-engine-js-components-web` is not being imported by the `tsconfig.json` (due to a build performance issue) it will be necessary to create a type definition file like this into the module using the feature flag, in order to provide the type check for the available flags: 
`modules/apps/<project>/<project>-web/src/main/resources/META-INF/resources/type-declarations/data-engine-js-components-web.d.ts`

3. Go to the React component where the flag is needed and use it
```jsx
import {useFlag} from 'data-engine-js-components-web';
...

function MyComponent() {
	const flags = useFlag();
	...

	return (
		<div>
			{flags['LPS-xxxxxx'] && (
				<input />
			)}
		</div>
	);
}
```

### Console error (TypeScript code only)
By remove a flag from the type definition file is expected errors coming from every files using this flag. It will help the developer to identify all the flag's usages
```console
src/main/resources/META-INF/resources/js/components/ObjectFieldFormBase.tsx:443:5 - error TS7053: Element implicitly has an 'any' type because expression of type '"LPS-148112"' can't be used to index type '{ "LPS-xxxxxx": boolean; }'.
  Property 'LPS-148112' does not exist on type '{ "LPS-xxxxxx": boolean; }'.

443    {flags['LPS-148112'] && settings.fileSource === 'userComputer' && (
        ~~~~~~~~~~~~~~~~~~~
``` 

### Co-author: @rodrigopaulino

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
> @danvb112, @naraandrade, @rebsilva can you please take a look on this and tell me any concern or doubt you may have related to this approach to deal with feature flags on front-end side.

I just analyzed the code, it's a very nice way to us to apply the FFs. Great job, Milton :)

**Comment by rebsilva** [comment]
> @danvb112, @naraandrade, @rebsilva can you please take a look on this and tell me any concern or doubt you may have related to this approach to deal with feature flags on front-end side.

This looks great to me, thanks for taking this initiative Milton! :cherry_blossom:

**Comment by danvb112** [comment]
> @danvb112, @naraandrade, @rebsilva can you please take a look on this and tell me any concern or doubt you may have related to this approach to deal with feature flags on front-end side.

This is a nice new way to make feature flags on the front end, it will be much easier to understand when we have more than one FF for the same code, Amazing idea and implementation @miltonmc! :smile:

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:forward

**Pull request closed without merging**
