### PR TITLE
LPS-130483 Adjust App Builder to use the compatibility layer

### PR DESCRIPTION
**Pull request by matuzalemsteles**
This is just an initial implementation that starts to use the compatibility layer on the App Builder side, it is still necessary to search the App Builder files in the `form-view` folder, some part here has been removed but we have to clean up more things, many of the changes are more cleaning and removing methods that don't make sense or changing to something equivalent.

For example:
- `dataLayoutBuilder.formBuilderWithLayoutProvider.refs.layoutProvider?.dispatch?` becomes just the `dispatch`
- `config` is consumed from `dataLayoutBuilder.current.config`

To finish this, it also depends on changes to the ticket https://issues.liferay.com/browse/LPS-128053 that will bring the reducers and some actions that are more used in App Builder.

This PR does not deal with all the changes that are necessary in the ticket but only a start to continue from here.

### Uncompleted
- The `fieldActions` API needs to be recreated to allow customizing the action according to the field and removing the use of `hoveredField`
- Add an action to save the Custom fields configuration
- ...It is necessary to take a closer look at the files

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
cc @interaminense you can probably get it afterward when we have all the parts inside the master once you know more about App Builder.

**Comment by matuzalemsteles** [comment]
ci:stop

**Comment by interaminense** [comment]
Just started reviewing :)

**Comment by interaminense** [comment]
This PR will be closed because we will no longer need it, since the appbuilder will be removed from the master.
cc: @matuzalemsteles

**Pull request closed without merging**
