### PR TITLE
LPS-159797	Remove front-end files from dynamic-data-mapping-form-renderer

### PR DESCRIPTION
**Pull request by miltonmc**
Related: https://issues.liferay.com/browse/LPS-159797

### CODE REVIEW

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:reevaluate:1307401_4046

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:reevaluate:1377401_3971

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:reevaluate:1307401_4090

**Comment by rodrigopaulino** [comment]
resent https://github.com/liferay-forms/liferay-portal/pull/1920

**Pull request closed without merging**
