### PR TITLE
LPS-128249 Use a collator

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
Hi @robertoDiaz,
It appears that your changes are related to the failure of   `SelectDDMFormFieldTemplateContextContributorTest.testGetOptionsAlphabeticallyOrdered`.

Can you please take a look?

Thanks!

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:stable

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
