### PR TITLE
LPS-196486 Change the place of the aria-required in DatePicker because it isn't working

### PR DESCRIPTION
**Pull request by vngoliveira**
Related issue: [LPS-196486](https://liferay.atlassian.net/browse/LPS-196486)

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:stop

**Comment by alinedoleron** [comment]
Hi @vngoliveira! Before running the forms and relevant tests suite, please, could you run the tests locally to check if some snapshot tests have failed?

You can run:
`yarn test`

And then `yarn test -u` to update the tests, if needed.

Thanks 🌷

**Comment by vngoliveira** [comment]
@alinedoleron All is okay, the test ran without errors.

**Comment by alinedoleron** [comment]
ci:forward:force

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
