### PR TITLE
Forms Automated Test - LPS-134374 | master

### PR DESCRIPTION
**Pull request by chaowang-123**
https://issues.liferay.com/browse/LPS-134374

### CODE REVIEW

**Comment by alinedoleron** [comment]
Hi, @chaowang-123! The review passed but there's a conflict here. When you fix it I can forward it to Brian, ok? Thanks!

**Comment by chaowang-123** [comment]
hi, @alinedoleron , The conflict has been resolved,thanks~

**Comment by alinedoleron** [comment]
Hi @chaowang-123, please, could you take a look on the sourceFormatter failures? Thanks!

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by chaowang-123** [comment]
hi, @alinedoleron ,  The source formatted failures has been resolved, thanks~

**Comment by alinedoleron** [comment]
ci:forward

**Pull request closed without merging**
