### PR TITLE
LPS-158814 - Fix JS errors when displaying in my workflow tasks a for…

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
…m containing a ddm-image field as some fields are not available

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Hi, @georgel-pop-lr. Please check my comment on the related LPS. I'll for that to continue this review.
Thanks for understanding.

**Comment by georgel-pop-lr** [comment]
> 

Hi @rodrigopaulino,

Thanks for checking this, I will wait for your updates.

Regards.

**Comment by rodrigopaulino** [comment]
No problem, @georgel-pop-lr.
I'll let you know shortly.
Thanks

**Comment by georgel-pop-lr** [comment]
> No problem, @georgel-pop-lr. I'll let you know shortly. Thanks

Hi @rodrigopaulino,

I have talked with Daniel Angotti by email, the PO of your team, and we agreed that the client might have used this ddm-image field adding it by hand and tho resulting into unwanted errors that we try to fix in this pull.

For the moment, I asked the client why they want to use this field as it is not available for kaleo forms and why not using documents and media field instead, which is available.

I will keep you updated on the client response.

Also, as a feature request, maybe in order to prevent this for happening again, would be great if we could have a validation of the fields added manually by the JSON object.

What do you think about it?

Regards.

**Comment by rodrigopaulino** [comment]
Thanks for the update, @georgel-pop-lr.
I think your idea is great. It's very important to have a validation like you said. Would you mind opening this feature request for us to keep track of?
In the meantime, I'll close this PR and please let us know of any updates on the LPS ticket. 😄

Once again, thank you for your contribution.

**Comment by rodrigopaulino** [comment]
ci:close

**Pull request closed without merging**
