### PR TITLE
LPS-136124 Make sure AUI module is loaded before calling Liferay.Form

### PR DESCRIPTION
**Pull request by victorg1991**
This is follow up from https://github.com/liferay-echo/liferay-portal/pull/7392 

I believe this is a better solution since this way we make sure that Liferay.Form is always accessible before trying to call it :)

Let me know what do you think

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
Hi, @miltonmc. Could you please review this PR? Also, see https://github.com/liferay-echo/liferay-portal/pull/7392#issuecomment-1058000435
Thanks in advance.

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Review by miltonmc — APPROVED** [review]
Hi @victorg1991,

Not change non related modules is a better approach, indeed!

My concern here is about the responsibility of the `FormView.es.js` that ideally should not have to handle that, but receive a callback from the module that is using it instead.

Anyway we can proceed with this change for now and do a refactoring moving the logic to the product that is relying on it, in the future.

**Comment by rodrigopaulino** [comment]
ci:forward

**Pull request closed without merging**
