### PR TITLE
LPD-25319

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
-----
Add External Reference Code to Widget Templates

[Link to the Story](https://liferay.atlassian.net/browse/LPD-22449)

Proposed Solution
-----
- Update service.xml to include support for ERC
- Adds upgrade process
- Update add method
- Creates new get and delete methods
- Update poshi add template macro

Also this pr includes some integration tests to cover new methods in DDMTemplateServiceImpl and in DDMTemplateLocalServiceImpl classes

Please let me know if you have any question.

### CODE REVIEW

**Comment by marcelabc** [comment]
Hi @ealonso,
Thank you for your contribution. I will review your PR tomorrow.
Thank you!

**Review by marcelabc — CHANGES_REQUESTED** [review]
Hey @ealonso,
I finished my review. Let me know if you have questions :smile:

I don't know if you know this, but I'm just double-checking with you that DDMTemplate has a property named `templateKey`. It is kinda of an ERC with another name. It is scoped by groupId and classNameId and has a validation method in *localservice to avoid duplicate keys.

Could you let me know if you considered this property to achieve the story that you are implementing? Why did it not work?

Thank you!

**Comment by ealonso** [comment]
Hey @marcelabc,

First of all I've just copied the same pattern that we have for LPD-25325, LPD-25303, LPD-25467, ... The names for tests are the same names that we have for other LPD and those were also reviewed by Brian. I just copied the logic from others and I only changed the names.

**Comment by ealonso** [comment]
@marcelabc 

Related with templateKey I know that we have it, as far as I know we need to have ERC in all entities in portal since batch engine need it to make it work, for that reason I'm adding it.

**Comment by ealonso** [comment]
@marcelabc 

Could you please evaluate your comments and let me know if the changes are needed? As I said before, I copied the ERC logic from other code already merged on master. But, if you prefer I can just do the changes, it is your code and you decided.

**Review by marcelabc — APPROVED** [review]
I understand your point, and we can continue the code as it is. Thank you for your contribution :smile: 
LGTM 🎉

**Comment by marcelabc** [comment]
If you need any help, please let us know!
I did not run the ci because of the rebase error.

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:report:22729465

**Comment by lfbesada** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/15839

**Pull request closed without merging**
