### PR TITLE
LPS-171211 Check of valuesObjectJSON is null before updating

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-171211

I was unable to reproduce this issue, however in both LPP-47232 and LPP-45816 the issue was resolved by this null check before updateData

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:reevaluate:1297401_5794

**Comment by carolmariaabb** [comment]
@SamZiemer feel free to send this PR directly to Brian. The failures are not related. Thanks!

**Comment by carolmariaabb** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/127737

**Pull request closed without merging**
