### PR TITLE
LPS-154893

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://issues.liferay.com/browse/LPS-154893

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by rodrigopaulino** [comment]
Hey, @carolmariaabb.
Which one of these Portlets was responsible for the DisplayContext that we were trying to use?

**Review by rodrigopaulino — APPROVED** [review]
LGTM!
Good job here. Please share later how did you find you needed to change these other portlets versions as well.

**Comment by carolmariaabb** [comment]
Hi @rodrigopaulino,

> Are these objects failures related to your fix?

No, these failures are also happening [here](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=1871652065&statuses=3%2C7).

> Which one of these Portlets was responsible for the DisplayContext that we were trying to use?

The `ObjectDefinitionsPortlet`. However, for some reason, we need to add `version=3.0` to all Portlets in this module.. I did several tests to confirm this. Unfortunately, I didn't have time to figure out why, as I needed to prioritize another task.

**Comment by rodrigopaulino** [comment]
Got it. What do you think of keeping this solution as a plan B for now and work just this week to find the cause of this issue? We can discuss with Mari how to prioritize it. I have already previously discussed this possibility with her. Do you think it's worth it?

**Comment by carolmariaabb** [comment]
Sounds good to me.

My guess is it might have something to do with the [init.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/object/object-web/src/main/resources/META-INF/resources/init.jsp) file. It's the same for all these Portlets.

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
@carolmariaabb, unfortunately. There wasn't any time to check this in depth. Therefore, I'm forwarding your solution. Thanks for working on this.

**Pull request closed without merging**
