### PR TITLE
LPS-149334,LPS-149336,LPS-149335

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issues: 

- https://issues.liferay.com/browse/LPS-149334
- https://issues.liferay.com/browse/LPS-149336
- https://issues.liferay.com/browse/LPS-149335

Previous PR: https://github.com/liferay-forms/liferay-portal/pull/1538

Hello Reviewer!

This PR has new features related to the story:
**As a power user, I want to limit the number of characters of text and long text fields** ([LPS-146889](https://issues.liferay.com/browse/LPS-146889))

More details can be found [here](https://liferay.atlassian.net/wiki/spaces/ENGFORMS/pages/1994490142/LPS-146889+-+As+a+power+user+I+want+to+limit+the+number+of+characters+of+text+and+long+text+fields) on our Confluence page.

If you have any questions feel free to ask, thank you for your time!

### CODE REVIEW

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @rebsilva, can you please check if these failures are related to your changes? Thanks

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @rebsilva, can you please check if these failures are related to your changes? Thanks

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hey @rebsilva, can you please fix the source formatter issues and resend? Thanks

**Comment by alinedoleron** [comment]
ci:open

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:stop

**Comment by liferay-forms** [comment]
Hey @rebsilva, can you please check if these failures are related to your changes? Thanks

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:stop

**Pull request closed without merging**
