### PR TITLE
LPS-124399 Do not use the containerId as the componentId to prevent issues with Liferay.component

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:app-builder

**Comment by jeyvison** [comment]
ci:test:echo-acceptance

**Comment by jeyvison** [comment]
@natocesarrego App builder and echo suites are fine :) Thanks a lot!

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
