### PR TITLE
[TECHNICAL SUPPORT] LPS-151237 Visiting any Locale creates a translation

### PR DESCRIPTION
**Pull request by NemethNorbert**
Related Issue: https://issues.liferay.com/browse/LPS-151237

Related Issue: https://issues.liferay.com/browse/LPS-151237
Related PR for 7.3.x: https://github.com/liferay-forms/liferay-portal-ee/pull/124
Hey,
As Data Lists still users ddm, I was asked to test and make the PR for master as well. The codebase is different on master, but the issue was still reproducible due to a logical issue in the if statement at updateLocalistionMap.

On 7.3.x the issue will still be resolved by removing addAvailableLanguageIds for upadteLocale
Please review my changes.

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @NemethNorbert, can you please check if these failures are related to your changes? Thanks

**Comment by orsolyaDekany** [comment]
Hi @liferay-forms ,
I am checking the PR until Norbert is out of office.
Looking at the failures, none of them are relevant to the changes in ddm_form.js, but backend test-related (for instance: [LPS-150379](https://issues.liferay.com/browse/LPS-150379)).
Could you please review the changes? Thank you.

**Comment by orsolyaDekany** [comment]
Hi @liferay-forms ,
could you please review this PR?
Thank you.

**Review by rodrigopaulino — APPROVED** [review]
Thanks for contributing, @NemethNorbert. Your changes LGTM.
Sorry for taking this time to review this, @orsolyaDekany. The team is under heavy load and we appreciate your patience at this.

Kind regards.

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @NemethNorbert, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
Hey @NemethNorbert, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
Hey @NemethNorbert, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
ci:reevaluate:1357401_1362

**Comment by NemethNorbert** [comment]
I had to combine this PR with another one, I close this and please review the next one.
Sorry for the inconvenience

new PR: https://github.com/liferay-forms/liferay-portal/pull/1619

**Pull request closed without merging**
