### PR TITLE
Forms Automated Test - LPS-133213 | master 

### PR DESCRIPTION
**Pull request by fmarcio**

### CODE REVIEW

**Comment by CalumR23** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
@CalumR23 I added the pending-sender label because this PR uses FormViewBuilder.macro and it seems that it does not belong to forms. I'll fix it soon and then update this PR. Thanks :-)

**Comment by fmarcio** [comment]
> @CalumR23 I added the pending-sender label because this PR uses `FormViewBuilder.macro` and it seems that it does not belong to forms. I'll fix it soon and then update this PR. Thanks :-)

Update June 10: I removed the "pending-sender" label since it will not necessary update this PR anymore (`FormViewBuilder.macro` will be avoided only on future PRs)

**Comment by CalumR23** [comment]
[Combined PR](https://github.com/CalumR23/liferay-portal/pull/5)

**Pull request closed without merging**
