### PR TITLE
LPS-165581 Modified alignmentPosition property

### PR DESCRIPTION
**Pull request by vngoliveira**
Related issue [LPS-165581](https://issues.liferay.com/browse/LPS-165581)

### CODE REVIEW

**Comment by marcelabc** [comment]
Hi @alinedoleron , could you review this PR please? :smile:

**Comment by vngoliveira** [comment]
ci:test:forms

**Comment by vngoliveira** [comment]
ci:test:forms

**Comment by vngoliveira** [comment]
ci:test:stable

**Comment by vngoliveira** [comment]
ci:test:relevant

**Comment by vngoliveira** [comment]
ci:test:forms

**Comment by vngoliveira** [comment]
ci:test:stable

**Comment by vngoliveira** [comment]
ci:test:relevant

**Comment by vngoliveira** [comment]
ci:test:stable

**Comment by vngoliveira** [comment]
ci:test:forms

**Comment by vngoliveira** [comment]
ci:test:stable

**Comment by vngoliveira** [comment]
ci:test:relevant

**Comment by vngoliveira** [comment]
ci:test:forms

**Comment by vngoliveira** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]
Hi @vngoliveira. I've tested here. I've seen that on[ Clay's DropDown.Menu documentation](https://clayui.com/docs/components/drop-down/api.html), the default value for alignment Position is 5, so you could also just remove this property.

**Comment by alinedoleron** [comment]
Hi @vngoliveira.
This failing tests are due to changes on snapshots files once you've changed the dropdown position. 
You can run this command: `yarn test Select` and you'll see that 3 snapshots have failed.
To solve this you'll need to run `yarn test Select -u` to update the files. Then you can do a `git push --force` on this PR.

If you need any help please let me know.

Thanks.

**Comment by alinedoleron** [comment]
ci:stop

**Review by alinedoleron — CHANGES_REQUESTED** [review]
Hi @vngoliveira. There are some snapshot tests to be updated. Please check my previous comments. Thanks!

**Comment by vngoliveira** [comment]
Ok, I'll make the change.

**Comment by vngoliveira** [comment]
Done!

**Comment by vngoliveira** [comment]
ci:test:forms

**Comment by vngoliveira** [comment]
ci:test:stable

**Comment by vngoliveira** [comment]
ci:test:relevant

**Comment by vngoliveira** [comment]
ci:test:forms

**Comment by vngoliveira** [comment]
ci:test:forms

**Comment by vngoliveira** [comment]
ci:test:forms

**Comment by alinedoleron** [comment]
ci:forward

**Pull request closed without merging**
