### PR TITLE
LPS-157432

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Hi @carolmariaabb, I've pushed https://github.com/liferay-forms/liferay-portal/pull/1818/commits/9bd994ca55f01b07541651aa603afe303a28e2bf.
Please let me know if any other change is needed.
Thanks

**Comment by linolaoj** [comment]
ci:test:relevant

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
