### PR TITLE
LPD-12824

### PR DESCRIPTION
**Pull request by icgsbr**
# Jira Ticket
- https://liferay.atlassian.net/browse/LPD-12824

# Follow up
- https://github.com/liferay-forms/liferay-portal/pull/2514

### CODE REVIEW

**Comment by icgsbr** [comment]
ci:test:forms

**Comment by icgsbr** [comment]
ci:test:data-engine

**Comment by icgsbr** [comment]
ci:test:relevant

**Comment by icgsbr** [comment]
ci:test:echo

**Review by marcelabc — APPROVED** [review]
LGTM 🎉
Java files approved :+1: :smile:

**Review by rebsilva — APPROVED** [review]
LGTM! :cherry_blossom:

**Comment by cgmonte** [comment]
Failures in `ci:test:forms` are not related.

**Comment by cgmonte** [comment]
ci:report:2561183510

**Comment by cgmonte** [comment]
ci:report:2561185091

**Comment by cgmonte** [comment]
failures in relevant are also unrelated, but I will run stable again.

**Comment by cgmonte** [comment]
ci:test:stable

**Comment by cgmonte** [comment]
ci:report:2561220560

**Comment by cgmonte** [comment]
Failures in stable, relevant and echo suites are not related as well, so this was [forwarded directly to Brian](https://github.com/brianchandotcom/liferay-portal/pull/149272).

**Pull request closed without merging**
