### PR TITLE
LPS-191691

### PR DESCRIPTION
**Pull request by jonathanmccann**
https://liferay.atlassian.net/browse/LPS-191691

Based on the feedback from https://github.com/liferay-echo/liferay-portal/pull/13014 and the discussion on https://liferay.atlassian.net/browse/PTR-4147 it was decided to not check for VIEW permission when utilizing the `DataLayoutRendererTag`.

There were two places this permission was being checked - during the fetch of the structure as well as during the render process. Both have been addressed in the changes here.

Please let me know your thoughts on the changes and if there would be a better way to implement this functionality. Thank you.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:forward:force

**Pull request closed without merging**
