### PR TITLE
[TS] LPS-145445 Implements extraction of repeatable rich text fields for index attributes

### PR DESCRIPTION
**Pull request by kristofloneck**
Related Issue: https://issues.liferay.com/browse/LPS-145445

Related Issue: https://issues.liferay.com/browse/LPS-145445

Hello team.
Please check my pull request.
https://issues.liferay.com/browse/LPS-145445
Thanks.
Kristóf Loneck

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @kristofloneck, can you please check if these failures are related to your changes? Thanks

**Comment by natocesarrego** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @kristofloneck, can you please check if these failures are related to your changes? Thanks

**Comment by kristofloneck** [comment]
No, it doesn't seems to be related to the changes.

**Comment by natocesarrego** [comment]
ci:forward

**Pull request closed without merging**
