### PR TITLE
[TECHNICAL SUPPORT] LPS-189593 Text in repeatable text field not mouse selectable

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,
Ticket: [LPS-189593](https://liferay.atlassian.net/browse/LPS-189593)

I wanted to cancel the drag event if it is fired from the children of FieldRepeatableDND wrapper. This way all the input fields will be selectable and the drag'n'drop feature will be activated just when the user is draging the very top part of the repeated field.

Please review my change,

Thanks

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
I'll review this by the end of the day, let me know if you have any concerns about it, thanks! :cherry_blossom:

**Review by rebsilva — CHANGES_REQUESTED** [review]
Hi @NemethNorbert, thanks for your contribution! 

From what I saw on the [PTR](https://liferay.atlassian.net/browse/PTR-4117) and the behavior we have now, the drag action is expected to be possible on anywhere of the field **except** the input. Your solution only works for the title of the field on the blue topbar, that's why I'm not accepting your solution.

I'm aware this input issue is somewhat a problem in ReactDND and there are some workarounds like the one you sent, but I think we could do something more fitting using the [canDrag](https://react-dnd.github.io/react-dnd/docs/api/use-drag#:~:text=canDrag(monitor)%3A%20Optional.%20Use%20it%20to%20specify%20whether%20the%20dragging%20is%20currently%20allowed.%20If%20you%20want%20to%20always%20allow%20it%2C%20just%20omit%20this%20method.%20Specifying%20it%20is%20handy%20if%20you%27d%20like%20to%20disable%20dragging%20based%20on%20some%20predicate%20over%20props.%20Note%3A%20You%20may%20not%20call%20monitor.canDrag()inside%20this%20method.) function inside the useDrag. 

If this is urgent or you require our help to solve this please reach our team through a PTR or Slack, thanks! :cherry_blossom: 

cc: @naraandrade

**Comment by NemethNorbert** [comment]
Hey @rebsilva,

I reworked the solution to use canDrag method. Please review it.

Thanks,

**Comment by rebsilva** [comment]
I'll start the review now :cherry_blossom:

**Review by rebsilva — APPROVED** [review]
Great work @NemethNorbert! :tada: Thanks for your patience on this :cherry_blossom:

**Comment by rebsilva** [comment]
I will run the tests again since the code changed

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:reevaluate:1377401_13502

**Comment by rebsilva** [comment]
ci:forward

**Pull request closed without merging**
