### PR TITLE
LPS-148561 Honor portlet ordering on export

### PR DESCRIPTION
**Pull request by robertoDiaz**
Related Issue: https://issues.liferay.com/browse/LPS-148561

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by manuelRives** [comment]
Hi @carolmariaabb,

Roberto is out this week and I'm continuing this pull. 

Where do you want to create the new method?, inside the same component (ExportFormInstanceMVCResourceCommand) or you want to move it inside SearchOrderByUtil?

Thanks in advance!

**Comment by carolmariaabb** [comment]
> Hi @carolmariaabb,
> 
> Roberto is out this week and I'm continuing this pull.
> 
> Where do you want to create the new method?, inside the same component (ExportFormInstanceMVCResourceCommand) or you want to move it inside SearchOrderByUtil?
> 
> Thanks in advance!

Hi @manuelRives,
Inside the same component please. Thanks!

**Comment by carolmariaabb** [comment]
Resent https://github.com/liferay-forms/liferay-portal/pull/1508

**Comment by carolmariaabb** [comment]
ci:close

**Pull request closed without merging**
