### PR TITLE
LPS-135604 | Master [TS]

### PR DESCRIPTION
**Pull request by rijema**
Click [here](https://issues.liferay.com/browse/LPS-135604) to see the LPS

Hello,

With this fix I wanna be able to reset properly the field value after passes through a rule. The [LPS-110839](https://issues.liferay.com/browse/LPS-110839) was happening again so I fixed again with new changes. 

The reason to revert some commits:

[LPS-122337 ](https://issues.liferay.com/browse/LPS-122337) was not considering empty values with LPS changes, so the field was not getting the correct value. 

[LPS-129665](https://issues.liferay.com/browse/LPS-129665) wasn't working with the predefined value as it should. The predefined value shouldn't be deleted from the field properties. The steps to reproduce of this LPS says that the expected result is that the predefined value should be displayed, but once the predefined value isn't seemed in the form while submitting, they shouldn't be displayed too.

Thank you.

### CODE REVIEW

**Comment by rijema** [comment]
ci:test:sf

**Comment by rijema** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:reevaluate:1157401_4649

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Hi @rijema, some of these failures seem to be related to your changes. Can you please check? Thanks

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:reevaluate:1297401_196

**Comment by carolmariaabb** [comment]
Hi @rijema, 
I'm going to close this PR because of the related failures, as you can see in the last CI run. Can you resend and let me know when these issues are fixed?

Thanks!

**Comment by carolmariaabb** [comment]
Please let me know if you need any help with this.

**Pull request closed without merging**
