### PR TITLE
[TS] LPS-200200 Nested fields are not saved in Dynamic Data List spreadsheet view

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Please note that the pull request includes the commits for [LPS-199526](https://liferay.atlassian.net/browse/LPS-199526) because that issue blocks the demonstration of the current one.
 
Motivation
=======
When a value of an embedded field is inserted or edited in the Dynamic Data List spreadsheet view, it won't be saved.
This is because the `_normalizeFieldData` [function](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-lists/dynamic-data-lists-web/src/main/resources/META-INF/resources/js/main.js#L509) collects the nested fields in a serial arrangement instead of embedding them.
This is fine if the record is being updated because `UpdateRecordMVCResourceCommand._toDDMFormFieldValues` [processes the ddmFormFieldValues serially](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-lists/dynamic-data-lists-web/src/main/java/com/liferay/dynamic/data/lists/web/internal/portlet/action/UpdateRecordMVCResourceCommand.java#L92-L160) but if it is being added, then the JSON data should reflect the structure of the DDMFormValues, see this [method](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-lists/dynamic-data-lists-web/src/main/java/com/liferay/dynamic/data/lists/web/internal/portlet/action/AddRecordMVCResourceCommand.java#L58-L77).

Proposed Solution
========
`_normalizeFieldData` should place the nested field data inside the `fieldValue` as well.

Steps to Verify
========
Please see the linked LPS for the reproduction steps.
https://liferay.atlassian.net/browse/LPS-200200

Thank you and best regards,
István

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
I will review the frontend of this PR later today :cherry_blossom:

**Review by rebsilva — APPROVED** [review]
LGTM! :tada:

**Comment by rebsilva** [comment]
ci:test:relevant

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
