### PR TITLE
[TS | Master] LPS-130718 Multiple line text field shown as one line in email notification

### PR DESCRIPTION
**Pull request by rijema**
Hello, you can see the LPS [clicking here](https://issues.liferay.com/browse/LPS-130718).

Thanks.

### CODE REVIEW

**Comment by rijema** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
You did this fix almost as a surgeon :man_health_worker:. :wink: Good job, @rijema! :tada:

**Comment by natocesarrego** [comment]
ci:forward

**Comment by rijema** [comment]
Thank you very much, @natocesarrego!! :D

**Pull request closed without merging**
