### PR TITLE
LPS-161242 Corrected spacing between icons and link titles.

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
FWD: https://github.com/fortunatomaldonado/liferay-portal/pull/43

Let me know if there are any questions or comments about this.
Thank you!

> [LPS-161242](https://issues.liferay.com/browse/LPS-161242) Corrected spacing between icons and link titles.

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Review by rodrigopaulino — APPROVED** [review]
LGTM! 🎉

**Comment by rodrigopaulino** [comment]
ci:forward

**Pull request closed without merging**
