### PR TITLE
LPD-36741 Forms with Data Provider doesn't maintain user manual input

### PR DESCRIPTION
**Pull request by larissacribeiro**
Related Issue: https://liferay.atlassian.net/browse/LPD-36741

### CODE REVIEW

**Comment by rijema** [comment]
Hi @marcelabc  and @rebsilva , after talking to you, I assigned your users as reviewers of this PR once it's related to front and backend evaluations. Thanks in advance for the review!

[image](https://github.com/user-attachments/assets/be94bcae-e092-4228-8001-5d5cb2d91610)

**Review by rebsilva — APPROVED** [review]
LGTM! :tada:

**Comment by rijema** [comment]
ci:test:playwright

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:forms

**Comment by rijema** [comment]
Hi @larissacribeiro , would you be so kind and please analyse the failing playwright tests the CI has reported and verify if it's related? I looks like a punctual error https://testray.liferay.com/#/project/35392/routines/45357/build/17715706/case-result/17761915/history?filter=%7B%22testrayRoutineIds%22%3A%5B45357%5D%7D&filterSchema=buildResultsHistory, Thankss!!

**Comment by larissacribeiro** [comment]
Hi @rijema, I was just doing that, if you go further down on this test history You'll see it has already failed other 2 times before with the same error, so it shouldn't be related! It's likely some intermittent failure.

**Comment by larissacribeiro** [comment]
The failures are unrelated 🎉

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
