### PR TITLE
LPD-30116

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://liferay.atlassian.net/browse/LPD-30116

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:data-engine

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by carolmariaabb** [comment]
ci:test:data-engine

**Comment by carolmariaabb** [comment]
The test is passing:
image

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
