### PR TITLE
LPS-120092 Select field has multiple predefined values when multiple option is "No"

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
https://issues.liferay.com/browse/LPS-120092

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Pull request closed without merging**
