### PR TITLE
[TS]LPS-167910 Unable to save the structure when there is a field set with Boolean field.

### PR DESCRIPTION
**Pull request by thienquach87**
Hi Team 
 Here is the PR for fixing https://issues.liferay.com/browse/LPS-167910. The original PR(https://github.com/thienquach87/liferay-portal/pull/20) was passed my review. Please help take a look on it and leave your comments
cc: @locpham97
Thanks,
Thien

### CODE REVIEW

**Review by marcelabc — CHANGES_REQUESTED** [review]
Hi @thienquach87 ! Sorry about the delay in reviewing
How are you doing? Thank you for contributing!
I finished my review. Let me know if you have questions :smile:

**Comment by locpham97** [comment]
Hi @marcelabc ,
I updated another solution. Could you recheck it?
Thanks, 
Loc

**Review by marcelabc — CHANGES_REQUESTED** [review]
Hey @locpham97,
Sorry for the delay, we had a local holiday yesterday.
I reviewed your solution, but the problem remains. I cannot approve this solution because it is changing the UI in other components. We should not change the field type "select" to "checkbox".

Let me know if you have questions :smile:

**Comment by locpham97** [comment]
Hi @marcelabc,
Sorry, I forget to remove the old code. I updated the code.
Could you recheck it? 
Thanks,
Loc <3

**Comment by marcelabc** [comment]
ci:test:sf

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:reevaluate:1357401_3075

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
