### PR TITLE
LPS-153168

### PR DESCRIPTION
**Pull request by alinedoleron**
Ticket: https://issues.liferay.com/browse/LPS-153168

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Review by miltonmc — COMMENTED** [review]
I'm not sure if that is the proper solution. Is that root cause? Why change event type to `mousedown` solves the problem?
We can schedule a meeting to discuss this issue if you like

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
