### PR TITLE
LPD-20194 Allow User to Drop a Fieldset Into a Single Field

### PR DESCRIPTION
**Pull request by igor-franca**
Related [Ticket](https://liferay.atlassian.net/browse/LPD-20194)

This pull request enhances field group organization by enabling drag-and-drop functionality. Users can now drag a group of fields within a single field, essentially creating a new field group. To achieve this, the `isDroppingFieldGroupIntoField` function, which previously restricted this behavior, has been removed. However, a new function called `isDroppingFieldsetIntoNestedField` has been implemented to prevent users from dropping groups into nested fields, thereby avoiding potential bugs.

https://github.com/liferay-forms/liferay-portal/assets/61854510/bf927f4c-f162-48b6-a5fb-473e47edf7bb

### CODE REVIEW

**Review by rebsilva — APPROVED** [review]
LGTM! :tada: amazing work @igor-franca :blush:

**Comment by igor-franca** [comment]
ci:test:forms

**Comment by igor-franca** [comment]
ci:test:data-engine

**Comment by igor-franca** [comment]
ci:test:echo

**Comment by igor-franca** [comment]
ci:test:forms

**Comment by igor-franca** [comment]
test:echo ✅
test:data-engine ✅
test:forms ✅

**Review by danvb112 — CHANGES_REQUESTED** [review]
Hey @igor-franca, Great job on this bug! I only saw that the LPD ticket in the commit name is different from the ticket you are working on, can you please fix this before we send the PR?

**Comment by igor-franca** [comment]
> Hey @igor-franca, Great job on this bug! I only saw that the LPD ticket in the commit name is different from the ticket you are working on, can you please fix this before we send the PR?

Great observation Daniel, I used the spike reference number in my commits 😿

**Comment by igor-franca** [comment]
ci:test:relevant

**Review by danvb112 — APPROVED** [review]
LGTM! :tada:  Great work @igor-franca!

**Comment by igor-franca** [comment]
ci:forward:force

**Comment by igor-franca** [comment]
ci:forward:force

**Pull request closed without merging**
