### PR TITLE
LPS-143865 Should return the object entry's title instead of the object definition's title

### PR DESCRIPTION
**Pull request by lfbesada**
Related issue: https://issues.liferay.com/browse/LPS-143865

Hi team!

During the validations of the site navigation menus items for display pages, we have found a couple of bugs related to the info-framework implementation of Objects.

Could you please review the fix?

Thanks!!!

Regards

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hi @lfbesada,

The team in charge of component Objects is @liferay-objects. Please, send your next pull requests affecting Objects to this team. :slightly_smiling_face: 

@liferay-objects, can you please review this one?

I'm not forwarding the pull to you to use the already reported CI results.

Thanks.

**Comment by marcelabc** [comment]
Just started reviewing :)

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
