### PR TITLE
LPS-147111 | LPS-147112

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related Issue: 
https://issues.liferay.com/browse/LPS-147111
https://issues.liferay.com/browse/LPS-147112

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:close

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by carolmariaabb** [comment]
resent https://github.com/liferay-forms/liferay-portal/pull/1440

**Pull request closed without merging**
