### PR TITLE
LPS-165388 limit char sequence in time to avoid high cpu utilization if regex results in too much backtraking

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Review by marcelabc — CHANGES_REQUESTED** [review]
Hi @linolaoj,
As I said in the ticket, we don't think that would be the best solution for handling this case. 
Could you explain why you chose the time (500) to throw the exception?
I noticed that is happening a discussion related to this in the LPP. Maybe we could ask for help from the security team :+1:

**Comment by carolmariaabb** [comment]
Resent https://github.com/liferay-forms/liferay-portal/pull/1986

**Comment by carolmariaabb** [comment]
ci:close

**Pull request closed without merging**
