### PR TITLE
LPD-27993 Render the ObjectField options only when the focusedField exists

### PR DESCRIPTION
**Pull request by rebsilva**
Related issue: https://liferay.atlassian.net/browse/LPD-27993

**:warning: this PR fixes a blocker so it has higher priority**

PS: there is already a test for this, it was a blocker discovered by a failing test

hi @cgmonte! on this PR me and @danvb112 tried to solve the blocker on forms related to LPD-27993. 
here is a brief explanation of what is happening from my investigations:

the fix needs to be on our side like bryce said [here](https://liferay.atlassian.net/browse/LPD-27993?focusedCommentId=2671973); the commits only exposed the error.

basically what is happening is that on the `ObjectField.js` (which is used on the forms sidebar) we need some info from `useFormState()` that is not updated yet, preventing the field to render properly. The flow right now is `ObjectField.js ->(sidebar) -> FormBuilder.es.js -> formBuilderReducer.es.js` (where it updates the info of `useFormState()`), so the `ObjectField.js` is trying to get data that isn't even there yet (the `focusedField`).

**considerations:**

this is the code we are afraid it will make the performance worse since it is now inside an **useEffect**:

```
const mappedFields = getFields(pages)
					.map((field) => {
						const objectFieldName = getObjectFieldName(field);

						return (
							objectFieldName &&
							getSelectedValue(objectFieldName.value)
						);
					})
					.filter(Boolean);
```

from what i've tested the performance is similar to what was before (inside **useMemo**) but i'm not 100% sure since i've created only a few fields to test and not at large scale.

also daniel sans suggested to do something similar to the image bellow, but he stated that sometimes it still didn't work properly:

image

if you think there is a better way to do this or ways to be improved we will be glad to hear! we have about a week to deliver this solution since it's a blocker. thanks a lot!! :cherry_blossom:

### CODE REVIEW

**Comment by cgmonte** [comment]
Hey, @rebsilva! I just took a quick look and the basic idea seems to be replacing an `useMemo` with a `useEffect` and a `useState`. Yes, it can degrade performance, so I will have to take a better look tomorrow. Will do this first thing in the morning tomorrow, but I don't think that the difference in performance will be relevant. The biggest performance bottleneck in Forms is the amount of calls it does to the back-end throughout the life-cycle of the application, usually validating things. It doesn't look like this will increase this kind of call to the back-end.

**Review by cgmonte — APPROVED** [review]
LGTM, @rebsilva! But I will add a Blocked tag until we get an answer from the product team about the behavior.

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:forms

**Comment by rebsilva** [comment]
ci:test:playwright

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:object

**Comment by rebsilva** [comment]
ci:forward

**Pull request closed without merging**
