### PR TITLE
LPS-203850 Avoid multiple submissions in a Form

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://liferay.atlassian.net/browse/LPS-203850

Goal: Avoid multiple submissions in a Form.

Proposed solution: Disable the Submit button while the Form is being evaluated. If the evaluation is successful, the Form will be sent and the button will remain disabled until the Success Page appears. If the evaluation fails, the button will be activated.

### CODE REVIEW

**Comment by marcelabc** [comment]
Hey @rebsilva 
Could you review this PR, please? :smile:

**Comment by marcelabc** [comment]
ci:test:forms

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Analyzing CI

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
