### PR TITLE
LPS-148909 Wrong message showing on Form Builder after enabling the see partial results settings

### PR DESCRIPTION
**Pull request by daiazius**
Related issue: https://issues.liferay.com/browse/LPS-148909

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:relevant

**Review by rodrigopaulino — COMMENTED** [review]
Hi, @daiazius. Thanks for your contribution.
If I may, why should we use the old message in case the info is dismissible?

**Comment by daiazius** [comment]
Hey @rodrigopaulino, I just used the dismissible because it also differentiates where the message is being displayed, when it's dismissible it will show the previous message. I can do this another way if you have a suggestion.

**Comment by rodrigopaulino** [comment]
Thanks for your answer, @daiazius. I understand.
If this now needs to be two different values, we should create a prop to parametrized the message displayed.
For the one place where the dismissible is true, pass one message than the other one for the other place.
I'm closing this so you can send the suggestion.
Thx

**Pull request closed without merging**
