### PR TITLE
LPS-155021 Add condition for fieldset label

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-155021

When a field is nested inside a fieldset and the user changes the language, the field's translation will be set to the translation of the fieldset, rather than its original translation.
This is occurring since the setLabel looks for instance.getLabelNode();. This will result in getting the field information when the instance is the fieldset. The field will then be translated into the fieldset information.

In order to resolve this, I included a condition that will check if the type is a fieldset and correctly translate it.

Let me know if there are any questions or comments about this.
Thank you!

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Review by rodrigopaulino — CHANGES_REQUESTED** [review]
Hi, @fortunatomaldonado.

Thanks for your contribution here. I've applied your solution and tried the same steps provided in the ticket, but the paragraphs are not getting translated when changing languages. Did you account for these cases in your solution?

Kind regards.

**Comment by fortunatomaldonado** [comment]
Hello @rodrigopaulino,

I did not account for the translation of the Paragraphs. Thinking about it now, I don't think the Paragraphs were ever being called by `_onLocaleChanged` throughout my debugging of this issue.

**Comment by rodrigopaulino** [comment]
Oh I see, @fortunatomaldonado. Could you please take care of adding it to your fix?
I'll close this PR for the moment, but feel free to send us another when you amend that other part.
Let us know in our Slack channel or through a PTR ticket if you have any questions related to the product.

Thanks for understanding.

**Pull request closed without merging**
