### PR TITLE
LPS-147337 Only allow valid entries inside email field

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issue: https://issues.liferay.com/browse/LPS-147337

Hello Reviewer!

This PR has a fix of the bug above. The email field was allowing invalid values (that aren't emails) to be inserted, so I changed the logic to filter the values before transforming them into labels inside the field.

If you have any questions feel free to ask, thank you for your time!

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Pull request closed without merging**
