### PR TITLE
LPS-118032 Fix accessibility errors pagination Lexicon

### PR DESCRIPTION
**Pull request by rijema**
https://liferay.atlassian.net/browse/LPS-118032

Hi team, I'm submitting this fix based in an old LPS as with the change from Clay to React the correction was missed. The request is to remove the icon information during the screenreader reading. As I can't  directly update the Clay Icon (see [markup element rendered here ](https://clayui.com/docs/components/icon/markup.html)), I'm adding in the parent tag the aria-hidden attribute. 

As in the past we're creating the tags in a jsp writer, older fixes removed the role="presentation" from the creation and overwrote with the aria-hidden. To overpass an external library update, I'm proposing this fix and intending to maintain both info.

The aria-hidden="true" will remove the entire element from the accessibility tool, so the existing role="presentation" won't impact the results.

Let me know if it is the best approach to this case and if I have to open a new LPS ticket.

Solution tested and results were satisfactory.

sd

### CODE REVIEW

**Review by rebsilva — APPROVED** [review]
Hi @rijema, thanks for your PR! I don't see a problem on this since the `aria-hidden` will only affect the `span` tag and its child (the `ClayIcon`), so I'm approving this PR :blush: 

But if the problem is the presentation on the `ClayIcon` and it's affecting the portal as a whole, maybe it's also good to talk to frontend infra team about it too for it to be changed. Thanks!

**Comment by rebsilva** [comment]
ci:stop

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
@rijema this test that is failing is related to your changes, can you please take a look?

 [dynamic-data-mapping.dynamic-data-mapping-form-field-type.test.js.FieldBase.ReactFieldBase renders the FieldBase with required](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/681123//testReport/dynamic-data-mapping.dynamic-data-mapping-form-field-type.test.js/FieldBase/ReactFieldBase_renders_the_FieldBase_with_required)

**Comment by rijema** [comment]
ci:test:relevant

**Comment by rijema** [comment]
ci:test:stable

**Comment by rijema** [comment]
ci:test:forms

**Review by rebsilva — APPROVED** [review]
LGTM! :tada:

**Comment by rebsilva** [comment]
Since the change was on ReactFieldBase, it involves all the places that use them (Forms, Journal, Web Content...) so is hard to say if the tests failing are related or not. I will ask the QA team to take a look and also @naraandrade to double-check your solution

**Comment by davisaints** [comment]
ci:test:forms

**Comment by davisaints** [comment]
ci:test:echo

**Comment by thaiscabrals** [comment]
ci:reopen

**Comment by thaiscabrals** [comment]
Just starting reviewing :)

**Comment by rebsilva** [comment]
Hey @rijema! There is one test failing that the fix is already on master, could you please rebase and send again so we can check? Thanks!

The bug that was fixed if you want to see https://liferay.atlassian.net/browse/LPS-191374

**Comment by rijema** [comment]
ci:test:forms

**Comment by rijema** [comment]
ci:test:echo

**Comment by rijema** [comment]
I'm going to run LocalFile.Forms#AddFormToUserSiteAndViewNoDuplicates locally to verify the situation, but I believe the relationship with Echo is ok, LocalFile.WebContentUpgradeWithWithFirstComplexStructure is no longer  being thrown.

**Comment by rijema** [comment]
Hi @rebsilva , after testing locally, the failing test isn't related to the submitted change.

image

Do you have any other concerns? Thanks!!

**Comment by rijema** [comment]
Hi @rebsilva , just one more thing, if no changes are more needed, the requester has asked for a new ticket to track this solution, instead of using the old fix id [LPS-118032](https://github.com/liferay-forms/liferay-portal/pull/2303#top), can I overwrite this PR or do you indicate for me to create another one? Thanks!

**Comment by rijema** [comment]
Hi @rebsilva , sorry to bother you, but did you have the opportunity to read my comments? Thanks in advance!

**Comment by rebsilva** [comment]
Hi @rijema! Sorry for the delay, I will take a look now

**Comment by rebsilva** [comment]
I think is better for you to send another PR with the new LPS @rijema, you can ping me here or on Slack so I can approve it as soon as you send it, thanks!

**Pull request closed without merging**
