### PR TITLE
LPS-141065 tests WIP

### PR DESCRIPTION
**Pull request by mateusgomes01**
Related Issue: https://issues.liferay.com/browse/LPS-141065

- LPS-143095 search-experiences-service: Index status field. Minor fixes
- LPS-143095 search-experiences-service: Minor SXPElementIndexer fixes
- LPS-143095 search-experiences-rest-impl: Add support for sorting and filtering SXPBlueprint and SXPElement search
- LPS-143095: gw buildRest
- LPS-143095 search-experiences-rest-impl: Entitymodels for odata support
- LPS-143095 search-experiences-rest-impl: SXPBlueprint search
- LPS-143095 search-experiences-rest-impl: SXPElement search
- LPS-143095 Sort
- LPS-143095 buy space
- LPS-143092 auto SF
- LPS-143095 Sort
- LPS-143095 Make a util
- LPS-143095 EntityModels have a slightly different sort order, see modules/apps/headless/headless-delivery/headless-delivery-impl/src/main/java/com/liferay/headless/delivery/internal/odata/entity/v1_0/ContentElementEntityModel.java
- LPS-112856 search-experiences-web: Set a greater pagesize to get all elements to show up
- LPS-141748 Use generic object value pair
- LPS-142251 Remove portletResource, because it causes not persisting portlet settings when saving a content in addcontent panel and returning to the widget page. Regression caused by LPS-116913.
- COMMERCE-6562 dispatch-web - add propsTransformer to clay management toolbar taglib to handle group actions
- COMMERCE-6562 dispatch-web - remove unused jsp
- COMMERCE-6562 dispatch-web - JS - add props transformer
- COMMERCE-6562 dispatch-web - update portletURL
- COMMERCE-6562 dispatch-web - package.json
- COMMERCE-6562 dispatch-web - fixing CONSTANTS.CMD value
- LPS-143122 BuildService
- LPS-143122 Build Rest
- LPS-143122 Add new column to store if deploy the portlet as a widget
- LPS-143122 Generate upgrade table
- LPS-143122 Add upgrade step
- LPS-143122 Change method signature to handle new parameter
- LPS-143122 Adapt tests
- LPS-143122 Deploy Widget in deployer
- LPS-143122 Expose new property from rest layer
- LPS-143122 Use new property in service call
- LPS-143122 Allow user with right permission to update the property
- LPS-143122 Add new gradle dependency
- LPS-143122 Add new language property
- LPS-143122 Increase schema version
- LPS-143122 Source formatter
- LPS-143122 Sort
- LPS-143122 Rename
- LPS-143122 Regen
- LPS-140277 Implement a DLStore that performs async antivirus scanning
- LPS-140401 Make queue size configurable and handle overflow rejections via persistent scheduling
- LPS-140324 Periodic batch scan on existing DLStore files
- LPS-140325 Track metrics related to antivirus scanning
- LPS-138796 buildLang
- LPS-138796 Not an empty folder, no need of this.
- LPS-138796 Clean up constants
- LPS-138796 Be strict on names.
- LPS-138796 Unused dependencies
- LPS-138796 Unused references
- LPS-138796 Avoid Optional
- LPS-138796 No need to be GREEDY
- LPS-138796 Reference Destination directly, so that we don't need the unused reference to AntivirusScanner
- LPS-138796 Remove unused service types
- LPS-138796 SF
- LPS-138796 Destination are destroyed by DefaultMessageBus upon unregistering the service
- LPS-138796 Not a modifiable component.
- LPS-138796 Put eventData inside Message
- LPS-138796 Put event type into Message too.
- LPS-138796 Fix SF complain about package
- LPS-138796 Simplify EventListener handling
- LPS-138796 Create a real listener type
- LPS-138796 SF
- LPS-138796 SF
- LPS-138796 Not possible to be null.
- LPS-138796 Undo changes to FileSystemStore and AdvancedFileSystemStore
- LPS-138796 Expose rootDir as a service property and grab it from AntivirusAsyncFileStoreInitializer, so that we don't have to inject anything to the StoreRegisters.
- LPS-138796 Simplify MockAntivirusScanner
- LPS-138796 Simplify MockEventListener
- LPS-138796 Use MapUtil
- LPS-138796 Not used
- LPS-138796 Cleanup all CountDownLatch usage.
- LPS-138796 Remove unused keys.
- LPS-138796 buildLang
- LPS-138796 Wordsmith
- LPS-138796 Regen
- LPS-138796 SF
- LPS-138796 Rename
- LPS-138796 Match modules/apps/segments/segments-service/src/main/java/com/liferay/segments/internal/constants/SegmentsDestinationNames.java
- LPS-138796 I thought it was a GroupModel at first
- LPS-138796 Good enough
- LPS-138796 auto SF
- LPS-138796 rename
- LPS-138796 Sort
- LPS-138796 Sort
- LPS-138796 Sort
- LPS-138796 Wordsmith
- LPS-138796 move package
- LPS-138796 rename
- LPS-138796 rename
- LPS-138796 Move
- LPS-138796 Wordsmith
- LPS-138796 Rename
- LPS-138796 Wordsmith
- LPS-138796 Sort
- LPS-138796 Inline
- LPS-138796 Rename
- LPS-138796 SF
- LPS-138796 SF
- LPS-138796 Rename
- LPS-138796 Buy space
- LPS-138796 Wordsmith
- LPS-138796 Not thrown
- LPS-138796 Buy space
- LPS-138796 Wordsmith
- LPS-138796 Move
- LPS-138796 Buy space
- LPS-138796 Wordsmith
- LPS-138796 Not much value
- LPS-138796 Rename
- LPS-138796 Rename
- LPS-138796 Inline
- LPS-138796 Rename
- LPS-138796 Consolidate tests
- LPS-138796 Inline
- LPS-138796 Rename
- LPS-138796 Clean up repetitive code
- LPS-138796 Sort registrations
- LPS-138796 Inline
- LPS-138796 Rename, match MetaInfoCacheServletResponse.java#called*
- LPS-138796 auto SF
- LPS-138796 Sort / move
- LPS-138796 Satisfy SF
- LPS-138796 Rename
- LPS-138796 Tie it together
- LPS-138796 If the string value doesn't matter, make it random
- LPS-138796 this doesn't even exist
- LPS-143087 Removes deprecated classes and methods
- LPS-143087 Update usages
- LPS-143087 packageinfo
- LPS-143087 Auto
- LPS-112856 search-experiences-rest-test: Add portal-search-test-util dependency
- LPS-77699 Update Translations
- LPS-141521 Add CannotAddRelationshipTabFirst Test
- LPS-141521 SF
- LPS-136183 add Masterclass macros
- LPS-136183 add Masterclass paths
- LPS-136183 add Masterclass testcases
- LRQA-71865 Investigate CI failure of FormsSubmissions#CanRedirectUserAfterFormSubmission
- Revert "LPS-135678 SF"
- Revert "LPS-135678 SF"
- Revert "LPS-135678 the first repository on the breadcrumb is always the scopeGroup"
- Revert "LPS-135678 add the selected repository to differentiate the root folders from differents groups to let the user select the folder"
- Revert "LPS-135678 add the repository id to the breadcrumb util to generate the portlets URL"
- Revert "LPS-135678 add the repository setting to the dL configuration settings"
- Revert "LPS-135678 update the get the settings of the repository id when selecting the folder"
- Revert "LPS-135678 clean repository id on portlet preferences"
- Revert "LPS-135678 add the repositoryId to the criteria of folder"
- Revert "LPS-135678 baseline"
- Revert "LPS-135678 add the repositoryId to the FolderSelector criterion"
- LPS-112856 search-experiences-rest-impl: Only use custom query if non blank keywords
- LPS-143118 Fix typos in SAML.testcase
- LPS-143118 Remove comments which are replaced by task definitions
- LPS-143118 More specific task names
- LPS-143118 Fix ImportEncryptionCertificateFromPKCS12KeystoreFile
- LPS-143118 Fix ViewSingleLogoutAndForceAuthWithMultipleSPs
- LPS-143118 Fix AssertSSOWithSignAuthnRequests
- LPS-143118 Fix AssertKeepAliveToKeepMySAMLSessionAlive
- LPS-143118 Fix AssertEmptyMappingCannotBeUsedForUserMatching
- LPS-143118 Fix AssertVerificationForDuplicatedUserAttributeMappingSAML
- LPS-143118 Fix AssertVerificationForEmptyUserAttributeMappingSAML
- LPS-112856 search-experiences-service: Allow deleting read-only SXPElements directly through local service
- LPS-112856 Slight optimization
- COMMERCE-7857 fix null pointer exception
- COMMERCE-7857 Like this
- COMMERCE-7887 Merge guest commerce orders
- COMMERCE-5539 - Don't take into account guest orders when matching  commerceAccountIds
- LPS-137429 Test Autom. Content recommendation disabled
- LPS-143089 Update translation title with experience
- LPS-142904 separate resources for each collection
- LPS-141045 - Skip tests for flakey CI errors
- LPS-142025 - Add cases and locators to Masterclass.testcase
- LPS-142025 - SF
- LPS-141789 Hide quick links on mobile to avoid chrome/safari bug
- LRQA-71942 - Quarantine Workflow tests
- COMMERCE-7966 Added permission check into commerce product content helper implementation
- COMMERCE-7966 TODO
- COMMERCE-7966 TODO
- LRQA-71946 - Quarantine UpdatingSLARecalculateTimeInProgressInstances test
- LRAC-9881 Fix closeAllSessions by adding osb-asah-project-id parameter to curl command
- LPS-138464 Apply SearchOrderByUtil pattern.
- LPS-138464 Spacing like this
- LRQA-71947 Extra line removed
- LRQA-71947 Put viewAssetNotPresentPG on one line
- LRAC-9879 Fix NewPropertiesGeneratedIDsAreNotIncremental testcase
- LRQA-70760 Add CanApproveTranslation testcase
- LRQA-70805 Add TranslationStatusIsPendingOnReject testcase
- LRQA-70763 Add TranslationStatusDoesNotChangeAfterReject
- LRQA-70762 Add NotificationIsSentOnReject testcase
- LRQA-70761 Add TranslationStatusChangesAfterApproval testcase
- LPS-143055 Remove CRACO dependencies
- LPS-143055 Remove unnecessary css files
- LPS-143055 Remove relative path imports
- LPS-143055 SF
- LPS-143055 Add CSS to Remote App Entries and use a provisory script to rename files from build
- LPS-143055 Configure Gradle copy task
- LPS-143055 Apply everywhere
- LPS-143055 upload
- LPS-142807 Show error message in form builder when validation fails
- LPS-142807 Sort, Hugo SF
- LPS-141065 Create CustomDate SelectDateType and StartEndDate components
- LPS-141065 fixes bug that was breaking validation
- LPS-141065 Adapt front end tests
- LPS-141065 Reformulate all DateValidation to support Date Fields
- LPS-141065 remove unnecessary test
- LPS-141065 Add condition when ddmFormValues is null
- LPS-141065 Create languages keys
- LPS-141065 Buildlang
- LPS-141065 Add back-end unit test
- LPS-141065 Create DDMSelect component
- LPS-141065 Tests WIP

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by mateusgomes01** [comment]
ci:stop

**Comment by mateusgomes01** [comment]
ci:stop

**Comment by liferay-forms** [comment]
Hey @mateusgomes01, can you please fix the source formatter issues and resend? Thanks

**Pull request closed without merging**
