### PR TITLE
LPS-142481 Forms widget doesn't export the displayed form

### PR DESCRIPTION
**Pull request by moltam89**
Related Issue: https://issues.liferay.com/browse/LPS-142481

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @moltam89, can you please check if these failures are related to your changes? Thanks

**Comment by moltam89** [comment]
Hi @liferay-forms ,

I don't think that the CI errors are related.
Anyways, I rebased the branch to current master and resent the PR here:
https://github.com/liferay-forms/liferay-portal/pull/1146

Best,
Tamas

**Pull request closed without merging**
