### PR TITLE
LPS-199345 Form radio buttons do not adhere to best practise keyboard navigation

### PR DESCRIPTION
**Pull request by vngoliveira**
Based on this [thread](https://liferay.slack.com/archives/C04CPMRMXAL/p1697483915891529)
Related issue [LPS-199345](https://liferay.atlassian.net/browse/LPS-199345)
LPP ticket [LPP-51200](https://liferay.atlassian.net/browse/LPP-51200)
Previous [PR](https://github.com/liferay-forms/liferay-portal/pull/2361)

### CODE REVIEW

**Comment by vngoliveira** [comment]
ci:test:relevant

**Comment by davisaints** [comment]
ci:test:forms

**Comment by davisaints** [comment]
ci:reevaluate:1397401_8256

**Comment by davisaints** [comment]
ci:test:data-engine

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by davisaints** [comment]
ci:test:forms

**Comment by marcelabc** [comment]
Hi @vngoliveira!
Sorry for the delay in reviewing this PR :confused: 
Could you fix the rebase errors, please?
Thank you!

**Comment by vngoliveira** [comment]
I am closing this PR since the fix is generating a regression and an FE is investigating the issue. I forgot it was open, sorry :grinning:

**Pull request closed without merging**
